### ISSUE TITLE
包大小太大了. 单独编译一个仅带有log功能的mars就有12.8MB. 

### ISSUE THREAD

**Issue by JasonWorking** [Tencent/mars#100]
如题.

**Comment by garryyan** [comment]
iOS因为是静态库的原因，而且编译了四个cpu架构 所以会显得比较大。 可以参考Android 的动态库大小，Android的单CPU架构动态库只编Xlog大概在100-120kb左右

**Comment by JasonWorking** [comment]
即使4个cpu架构也是偏大的, 去掉x86和i386也会超过有6.4MB. 还是偏大的. 
是把boost打进去了的原因？

**Comment by garryyan** [comment]
不是 是把符号信息打进去的原因，ios 是静态库。和动态库是有区别的。

**Comment by happysir** [comment]
stlport_shared 包比较大 就marsxlog能接受

**Comment by garryyan** [comment]
使用了stl很难避免掉，有想法把xlog不依赖stl
