### ISSUE TITLE
是否考虑支持CocoaPods和Carthage

### ISSUE THREAD

**Issue by Shunzi007** [Tencent/mars#102]
代表iOS开发者问几个问题：
1.我看到工程并没有打tag，是默认每次run Script的时候，Python脚本打包最新包么？可是每次Build时间好长。。。
2.比较流行的库管理工具CocoaPods和Carthage是否会支持？

**Comment by garryyan** [comment]
1. 每次是最新包，不过提醒了我 可以根据git记录去判断是否有必要每次都打包。
2. 后续会尝试支持cocoapods
