### ISSUE TITLE
start_server.py脚本有问题

### ISSUE THREAD

**Issue by zhzhh7378** [Tencent/mars#103]
![image](https://cloud.githubusercontent.com/assets/14539415/22012518/60b95d8a-dccf-11e6-8aef-818e181836c3.png)

**Comment by shockcao** [comment]
不支持python3  请使用python2.7

**Comment by zhzhh7378** [comment]
恩 找到解决方法了
![image](https://cloud.githubusercontent.com/assets/14539415/22012613/ee7270b2-dccf-11e6-85a3-8ea7d1270e6d.png)
