### ISSUE TITLE
xlog在iOS上测试频繁调用时cpu占用过高

### ISSUE THREAD

**Issue by wangyoucao577** [Tencent/mars#104]
如题, 在iOS上做了下测试, 每秒1000条日志, 异步模式, 大约要占用iphone 5s 21%的cpu.  

![516f8429-f1bf-47a2-832b-aa7b1183d13b](https://cloud.githubusercontent.com/assets/1905370/22012866/20729bea-dcd1-11e6-9455-700c714cb657.png)

### 测试环境:  
- iphone 5s  
- xcode version 8.2.1  
- mars_xlog version git-bb793a0  

### 测试代码:  
每秒写足日志条数则剩下的时间sleep.  
 <pre><code>
void init_xlog_test(const char* log_path)
{
    // init xlog
#if DEBUG
    xlogger_SetLevel(kLevelVerbose);
    appender_set_console_log(true);
#else
    xlogger_SetLevel(kLevelInfo);
    appender_set_console_log(false);
#endif
    
    appender_open(kAppednerAsync, log_path, "myxlogtest");

}

static void test_case_loop_xlog(int xlog_count_per_sec){
    
    int loop_index = 0;
    
    int curr_xlog_count = 0;
    
    uint64_t curr_interval_start_ms = timeMs();
    uint64_t curr_ms = 0;
    
    int interval_count = 0;
    
    
    while (1){
        
        curr_ms = timeMs();
        if (curr_ms >= curr_interval_start_ms + 1000){
            ++interval_count;
            
            curr_xlog_count = 0;
            curr_interval_start_ms = curr_ms;
            continue;
        }
        
        if (curr_xlog_count >= xlog_count_per_sec){
            int sleep_ms = (int)(curr_interval_start_ms + 1000 - curr_ms);
            xinfo2(TSF"sleep ms %_ ", sleep_ms);
            usleep(sleep_ms * 1000);
            
            continue;
        }
            
        xverbose2(TSF"%_ %_ curr_interval_index %_ interval %_", "verbose", loop_index++, curr_xlog_count++, interval_count);
        
    }
   }

void run_xlog_test_cases()
{    
    test_case_loop_xlog(1000);
}
</code></pre>  

### 其他说明  
1.  试过关闭xlog的compress功能, cpu占用没有明显下降, 可认为不是压缩引起  
2.  试过关闭console log, cpu占用没有明显下降,  可认为不是压缩引起  
3.  默认实现没有加密, 可以认为不是加密引起  

所以主要消耗可能在哪里?

**Comment by garryyan** [comment]
试着不要 调用 init_xlog_test 看看效果

**Comment by wangyoucao577** [comment]
@garryyan  不调用init_xlog_test, cpu 100%. 

请问下这个实验的意义是啥？

**Comment by garryyan** [comment]
不调用init_xlog_test  cpu为什么100%  不要改掉sleep， 其他代码都不要动，只去掉init_xlog_test，  你只是调用xinfo接口会立即返回，因为没有open log。  这个实验意义 有可能CPU都是被循环吃掉了

**Comment by wangyoucao577** [comment]
我的实验代码是这样, 在 `init_xlog_test`中直接加了句`return`,  起到不调用的效果. 其他完全不动.  
<pre><code>
void init_xlog_test(const char* log_path)
{
    return;
    
    // init xlog
#if DEBUG
    xlogger_SetLevel(kLevelVerbose);
    appender_set_console_log(true);
#else
    xlogger_SetLevel(kLevelInfo);
    appender_set_console_log(false);
#endif
    
    appender_open(kAppednerAsync, log_path, "myxlogtest");

}
</code></pre>

被循环吃掉除非`usleep`的地方算的有问题, 实际没有去sleep?

**Comment by wangyoucao577** [comment]
补充一下新的实验, 改造了下`xverbose`调用的代码如下:   

<pre><code>
        xverbose2(TSF"%_ %_ curr_interval_index %_ interval %_", "verbose", loop_index, curr_xlog_count, interval_count);
        loop_index++;
        curr_xlog_count++;

</code></pre>

此时不调用`init_xlog_test`, cpu表现如下, 占用仅0%   

![image](https://cloud.githubusercontent.com/assets/1905370/22048810/77acf0a6-dd6a-11e6-8e87-d2c4b231824e.png)

由此, 我认为cpu不能说被循环占了吧.   

而上个实验中的cpu 100%, 我理解该是由于`xverbose`的实现原因. 未初始化xlog导致xverbose中实际宏并未完全展开, 故未调用`++`.  虽然还没看明白是怎么展开的..

**Comment by garryyan** [comment]
方便把代码打包发给 1173828173@qq.com 吗

**Comment by wangyoucao577** [comment]
OK

**Comment by garryyan** [comment]
@wangyoucao577 没收到你的邮件 是否已经发送

**Comment by wangyoucao577** [comment]
一早就已经发了.. 请检查下在不在垃圾邮件箱, Gmail发送的.  
或者从下面的网盘链接下载:  
https://www.jianguoyun.com/p/DSOE5xYQqpfzBRj7jCU

**Comment by garryyan** [comment]
我改了一下你的测试案例：
* 把 xlog_test.cpp 改名为 xlog_test.mm 方便后面使用 NSLog
* 注释掉 test_case_each_xlog_interface，只调用一次 xlog，方便后面对比。

机器iPhone6s， 三种案例：
1. 在 init_xlog_test 函数中添加 return 不初始化 xlog， CPU 使用率0%。
2. 在 init_xlog_test 函数中添加 return 不初始化 xlog，并添加 NSLog 进行打日志，CPU使用率7%-8%左右。
3. 去掉 init_xlog_test 函数中的 return， xlog 不使用压缩，使用 xlog 打日志，CPU使用率 8%-9% 左右。
3. 去掉 init_xlog_test 函数中的 return， xlog 使用压缩，使用 xlog 打日志，CPU使用率 16%-17% 左右。

注：NSLog只是打控制台，并不会打文件，xlog即使不使用压缩也会写入到文件中。

可见， 在不压缩时 CPU主要用于时间处理线程进程信息处理字符串处理上了。

![](http://o9gsoxx4j.bkt.clouddn.com/17-1-18/98449861-file_1484728871901_9802.png)

**Comment by wangyoucao577** [comment]
更新下几个新的实验: 

- 代码修改(`ConsoleLog`的实现用`fprintf(stdout...)`替代当前实现中调用的`NSLog`)  
![21c7ef41-fc72-49f5-af30-f5a742748e7b](https://cloud.githubusercontent.com/assets/1905370/22099535/b0e946ce-de66-11e6-92e3-ff065e5ea995.png)

- 测试数据
![0c8f4a3d-d7b4-4145-ab5c-7a0ecd8b8832](https://cloud.githubusercontent.com/assets/1905370/22099571/df2e6c30-de66-11e6-9083-55c5f95ad209.png)
![5922176b-3ecf-4eea-8a7d-fa6cd3892bcc](https://cloud.githubusercontent.com/assets/1905370/22099679/4a26aee4-de67-11e6-9674-d6b3741b77f8.png)
![6361b54d-5d40-4140-a5aa-7e4c3fd3b9cc](https://cloud.githubusercontent.com/assets/1905370/22099580/eaf0e5f2-de66-11e6-8aa2-d999f37e9ef2.png)

- 结论  
  1. iOS上`NSLog`性能比`fprintf(stdout...)`标准调用差太多, 不适合在需要关注CPU的情况下使用    
  2. `mmap`不影响CPU性能  
  3. 压缩功能可看出明显的CPU占用, 但消耗明显比`NSLog`小很多.
