### ISSUE TITLE
是否考虑支持多实例？即不同类型的日志写入不同的文件夹

### ISSUE THREAD

**Issue by Yanyuxxxx** [Tencent/mars#1059]

**Comment by Rain-dew** [comment]
我也想得到这个问题的答案，我碰到了项目中引入的framework使用了Mars，这样导致我们各自做了自己的初始化配置，最后写入的文件是最后一个初始化的。我很希望他能够通过某种配置，写入不同的文件。

**Comment by Rain-dew** [comment]
提问者是否已有解决方案？可否分享
