### ISSUE TITLE
MarsServiceStub不是抽象的, 并且未覆盖ICallBack中的抽象方法trafficData(int,int)

### ISSUE THREAD

**Issue by cngkqy** [Tencent/mars#107]
想运行samples\android\marsSampleChat跑跑试试，结果报下边错误，这示例能跑通么？

Error:(44, 8) 错误: MarsServiceStub不是抽象的, 并且未覆盖ICallBack中的抽象方法trafficData(int,int)

**Comment by cngkqy** [comment]
![image](https://cloud.githubusercontent.com/assets/16894280/22057375/5b4b3456-dd9f-11e6-8d06-e04a13aaad69.png)
刷新过，不行，版本也没改过，1.1.4对么？

**Comment by cngkqy** [comment]
![image](https://cloud.githubusercontent.com/assets/16894280/22057452/abb495d6-dd9f-11e6-8f4e-5f767d2acc4c.png)
master分支不行么，我直接拉取编译的

**Comment by shockcao** [comment]
查到了  是我们的mars代码修改没有同步成功到github  稍等

**Comment by shockcao** [comment]
@cngkqy 拉一下最新master代码试一下

**Comment by cngkqy** [comment]
好了，可以编译通过了，谢谢~
