### ISSUE TITLE
一些不是很重要的问题

### ISSUE THREAD

**Issue by NathanTao** [Tencent/mars#108]
1.buildToolsVersion 23.0.1 下无法获取mars-core 改成24.0.2 就可以
2.在运行过程中的错误日志
01-18 17:02:24.709 21347-21347/com.tencent.mars.sample W/System.err: android.os.DeadObjectException
01-18 17:02:24.712 21347-21347/com.tencent.mars.sample W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
01-18 17:02:24.714 21347-21347/com.tencent.mars.sample W/System.err:     at android.os.BinderProxy.transact(Binder.java:506)
01-18 17:02:24.714 21347-21347/com.tencent.mars.sample W/System.err:     at com.tencent.mars.sample.wrapper.remote.MarsService$Stub$Proxy.unregisterPushMessageFilter(MarsService.java:185)
01-18 17:02:24.714 21347-21347/com.tencent.mars.sample W/System.err:     at com.tencent.mars.sample.wrapper.remote.MarsServiceProxy.onServiceDisconnected(MarsServiceProxy.java:149)
01-18 17:02:24.714 21347-21347/com.tencent.mars.sample W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1230)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1244)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at android.os.Looper.loop(Looper.java:154)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5462)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
01-18 17:02:24.715 21347-21347/com.tencent.mars.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by NathanTao** [comment]
01-18 17:02:38.394 21347-21418/com.tencent.mars.sample W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tencent.mars.sample.wrapper.remote.MarsService.send(com.tencent.mars.sample.wrapper.remote.MarsTaskWrapper, android.os.Bundle)' on a null object reference
01-18 17:02:38.394 21347-21418/com.tencent.mars.sample W/System.err:     at com.tencent.mars.sample.wrapper.remote.MarsServiceProxy.continueProcessTaskWrappers(MarsServiceProxy.java:212)
01-18 17:02:38.394 21347-21418/com.tencent.mars.sample W/System.err:     at com.tencent.mars.sample.wrapper.remote.MarsServiceProxy.access$200(MarsServiceProxy.java:37)
01-18 17:02:38.394 21347-21418/com.tencent.mars.sample W/System.err:     at com.tencent.mars.sample.wrapper.remote.MarsServiceProxy$Worker.run(MarsServiceProxy.java:228)
01-18 17:02:38.429 21347-21355/com.tencent.mars.sample W/art: Suspending all threads took: 18.620ms

**Comment by NathanTao** [comment]
测试的机器是Mi-Note-MIUI8 开发版

**Comment by xmudall** [comment]
是否是混淆的问题？Proguard 配置里把无法找到的类去掉试试？

**Comment by NathanTao** [comment]
哦  好的  我试试
