### ISSUE TITLE
XLog的decode跟解压缩有没有对应的c代码？

### ISSUE THREAD

**Issue by guoguo338** [Tencent/mars#109]
现在只看到了python的脚本，有没有c版本的？

**Comment by garryyan** [comment]
暂无

**Comment by wangjinyu** [comment]
有没有查看log相关的文档，这个python文件我直接运行了没有效果。把图中的文件都放在一起了

![2017-01-18 19 05 37](https://cloud.githubusercontent.com/assets/3033623/22061691/1dd3d0d0-ddb1-11e6-9b00-5dd7382d2285.png)

**Comment by garryyan** [comment]
运行提示什么

**Comment by wangjinyu** [comment]
没有提示，直接就结束了

**Comment by wangjinyu** [comment]
![2017-01-18 19 09 48](https://cloud.githubusercontent.com/assets/3033623/22061829/b3279068-ddb1-11e6-9d23-386eed012664.png)

这是我运行3遍的效果

**Comment by garryyan** [comment]
cd 到那个目录下再执行

**Comment by wangjinyu** [comment]
![2017-01-18 19 12 11](https://cloud.githubusercontent.com/assets/3033623/22061908/0c3dd6b2-ddb2-11e6-82cc-167c1f5318dd.png)

还是没有

**Comment by garryyan** [comment]
目录下也没有生成相应的文件？

**Comment by wangjinyu** [comment]
没有呢

**Comment by wangjinyu** [comment]
有了，谢~

**Comment by guoguo338** [comment]
请教下，那腾讯这边服务端如何解密/解压缩，也是用python脚本么？性能会不会是个问题？

**Comment by garryyan** [comment]
客户端的日志 为什么服务端会大量解密解压缩呢。

**Comment by guoguo338** [comment]
服务端可以对数据进行一些预处理，比如监听到关键问题进行报警等。

**Comment by guoguo338** [comment]
你们的压缩算法有没有比较详细的文档，看python脚本来反写C代码有点累啊。
