### ISSUE TITLE
垃圾 好好的xcode不用非要用cmake 还各种报错

### ISSUE THREAD

**Issue by DargonLee** [Tencent/mars#1094]
CMake Error at ios.toolchain.cmake:208 (message):
  PLATFORM argument not set.  Bailing configure since I don't know what
  target you want to build for!
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.25.1/share/cmake/Modules/CMakeDetermineSystem.cmake:121 (include)
  comm/CMakeLists.txt:6 (project)

**Comment by Abson** [comment]
这玩意 Python 脚本命令没写好，可能裁员到没人干活了，但是，会点 cmake 和 Python 可以自己手动解决

可以通过修改 build_ios.py 来解决

```
INSTALL_PATH = BUILD_OUT_PATH + '/iOS.out'

IOS_BUILD_SIMULATOR_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=SIMULATOR -DARCH="x86_64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 && make -j8 && make install'
IOS_BUILD_OS_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS -DARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 && make -j8 && make install'
```

改一下这三句，可以解决

**Comment by DargonLee** [comment]
> 这玩意 Python 脚本命令没写好，可能裁员到没人干活了，但是，会点 cmake 和 Python 可以自己手动解决
> 
> 可以通过修改 build_ios.py 来解决
> 
> ```
> INSTALL_PATH = BUILD_OUT_PATH + '/iOS.out'
> 
> IOS_BUILD_SIMULATOR_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=SIMULATOR -DARCH="x86_64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 && make -j8 && make install'
> IOS_BUILD_OS_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS -DARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 && make -j8 && make install'
> ```
> 
> 改一下这三句，可以解决

多谢 🙏

**Comment by agoodcoolman** [comment]
能直接提交PR么。

**Comment by tiemuhua** [comment]
> CMake Error at ios.toolchain.cmake:208 (message): PLATFORM argument not set. Bailing configure since I don't know what target you want to build for! Call Stack (most recent call first): /usr/local/Cellar/cmake/3.25.1/share/cmake/Modules/CMakeDetermineSystem.cmake:121 (include) comm/CMakeLists.txt:6 (project)

@DargonLee 修复已合入master
