### ISSUE TITLE
(docs) Maybe there is a translate mistake for "长连接" and "短连接"

### ISSUE THREAD

**Issue by simpleton** [Tencent/mars#11]
I've found the RFC document named "长连接" as persistent connection, and "短连接" as non-persistent connection.

I didn't find where longlink and shortlink come from.

**Comment by garryyan** [comment]
persistent connection  应该是HTTP1.1引入的术语，一般来说这个词主要用于HTTP连接，没有保护概念。
longlink 因为国内特殊的网络机制的原因，是有心跳保活逻辑的。  有点中国式英语， 是因为历史原因使用的。不过确实新造一个词没必要。

我们稍后会在README和Wiki里说明下这个事情。 谢谢提醒。

**Comment by code4ever** [comment]
确实 persistent connection翻译地道.

**Comment by zxedker** [comment]
#11
