### ISSUE TITLE
增加 longlink_packer.h 的文档

### ISSUE THREAD

**Issue by linjackson78** [Tencent/mars#110]
已经使用现有协议的应用，如果想要整合 Mars 的话，必须要做的是通过扩展 longlink_packer.cc 里的

```cpp
void longlink_pack(uint32_t _cmdid, uint32_t _seq, const void* _raw, size_t _raw_len, AutoBuffer& _packed);
int  longlink_unpack(const AutoBuffer& _packed, uint32_t& _cmdid, uint32_t& _seq, size_t& _package_len, AutoBuffer& _body);
```

这两个函数以适配旧有的协议，而这两个函数的参数、返回值都没有说明，无从扩展。

比如在 `longlink_unpack` 里的 seq 对应上层的 taskId，可是如果这是服务器主动推送的包，这里的 seq 值应该返回什么？

**Comment by shockcao** [comment]
主动推送请看longlink_packer.cc里的 is_push_data

**Comment by linjackson78** [comment]
@shockcao 所以流程是先 longlink_unpack，再 is_push_data，没错吧？

另外 longlink_unpack 的返回值又是作何用？

这两个比较重要的函数建议加上文档说明。

**Comment by shockcao** [comment]
嗯 对的

好的 我们加一下注释 说明下参数及返回值作用
