### ISSUE TITLE
日志丢失问题。

### ISSUE THREAD

**Issue by agoodcoolman** [Tencent/mars#1109]
MARS_URL: 
MARS_PATH: rb/2020-OCT
MARS_REVISION: 8fae6828
MARS_BUILD_TIME: 2020-10-14 14:55:07
MARS_BUILD_JOB: 

版本信息如上。

VIVO、OPPO 正常。
RedMi 红米   丢失日志。

代码逻辑：
 在Application中初始化之后，立刻输出日志。输出的目录为APP自带内部的目录，应该也不存在读写权限申请的问题。
 在别的手机中能正常的输出日志，红米无法在初始化输出初始化的日志。
`

       val SDCARD = AndroidSecurityFileUtils.getBigCacheFile(context);
        val logPath = "$SDCARD/log";
        val dd = File(logPath);

        if (dd.exists()) dd.mkdirs();

        // this is necessary, or may cash for SIGBUS
        val cachePath = context.getFilesDir().absolutePath + "/xlog";

        //init xlog
        var xlog : Xlog  = Xlog();

        com.tencent.mars.xlog.Log.setLogImp(xlog);

        if (BuildConfig.DEBUG) {

            com.tencent.mars.xlog.Log.setConsoleLogOpen(true);
            com.tencent.mars.xlog.Log.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, cachePath, logPath, "log", 0);
        } else {
            com.tencent.mars.xlog.Log.setConsoleLogOpen(false);
            com.tencent.mars.xlog.Log.appenderOpen(Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, cachePath, logPath, "log", 0);
        }
`

**Comment by zhanlan123** [comment]
你这代码写错了。

**Comment by agoodcoolman** [comment]
> 你这代码写错了。
@zhanlan123 
兄弟，哪错了？

**Comment by zhanlan123** [comment]
```java
                File externalFileDir = context.getExternalFilesDir("XLog");
                String logPath = null;
                if (externalFileDir != null) {
                    logPath = externalFileDir.getAbsolutePath();
                } else {
                    android.util.Log.i("LOG", "创建文件夹失败，可能需要重启设备。");
                }
                final String cachePath = context.getFilesDir() + "/XLog";
                android.util.Log.i("LOG", "logPath:" + logPath);
                //init xlog
                if (debugStatus) {
                    Xlog.open(false, Xlog.LEVEL_ALL, Xlog.AppednerModeAsync, cachePath, logPath, prefix, PUB_KEY);
                } else {
                    Xlog.open(false,  Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, cachePath, logPath, prefix, PUB_KEY);
                }
                //下面需要放到appenderOpen方法后面，即Xlog.open后面。
                Xlog xlog = new Xlog();
                xlog.setConsoleLogOpen(0, consoleLogOpen);
                if (logFileSaveDays != 0) {
                    long maxAliveTime = (long) logFileSaveDays * 24 * 60 * 60;
                    xlog.setMaxAliveTime(0, maxAliveTime);
                }
                if (logFileMaxSize != 0) {
                    xlog.setMaxFileSize(0, logFileMaxSize);
                }
                Log.setLogImp(xlog);

```
试试这个

**Comment by zhanlan123** [comment]
我这个是。1.2.6版本。

**Comment by agoodcoolman** [comment]
@zhanlan123  感谢 感谢。应给你的这个也是不行。你是自己编译的so库还是用的仓库里面的包？

**Comment by agoodcoolman** [comment]
![image](https://user-images.githubusercontent.com/11003275/225481923-a73c9717-15de-49d8-a5f2-be67e1f4e321.png)
初始化方法用的上面的方法，用的1.2.6的版本，不知道为啥这里返回是6，所以导致输出日志的方法进不去，一个日志都没有。

**Comment by agoodcoolman** [comment]
#940 #1035 
这两个问题跟我的问题一样，类似。

**Comment by agoodcoolman** [comment]
![image](https://user-images.githubusercontent.com/11003275/225489693-05e83aea-2a33-4820-8576-f6239fdaa5f5.png)
这里查询问题红米上获取，根据上面的两个文字解释，我本地getLevel按道理参数是 jlong _log_instance_ptr 这个参数我是传进去的，传的0.

**Comment by agoodcoolman** [comment]
@garryyan  朋友，能看看吗

**Comment by agoodcoolman** [comment]
我回退到1.0.7的版本，可以在Redmi上输出日志了。算了低版本更适合我。

**Comment by agoodcoolman** [comment]
尝试使用项目中的SampleXlog项目到项目中，结果可以在Redmi中输出日志。我再把代码复制到项目中，就gradle引用 1.2.6，然后下面这个地方可能我写错了，我引用的file，没有getPath导致里面输出的时候估计路径不对，导致不能输出日志。
>val SDCARD = AndroidSecurityFileUtils.getBigCacheFile(context);    后面应该getPath才行。
> val logPath = "$SDCARD/log";

**Comment by agoodcoolman** [comment]
找了两天，发现是写错了地址，应该是不同的手机可能默认会把File转地址，有的手机没的这个功能。上面的哥们代码是对的，Kotlin语言还是不完美。
