### ISSUE TITLE
react native support 

### ISSUE THREAD

**Issue by Caijiacheng** [Tencent/mars#111]
hello, 我们团队正在添加对react native的支持  [react native support](https://github.com/facebook/react-native) 

1.  [react-native-mars](https://github.com/Caijiacheng/react-native-mars) 
2. [react-native-xlog](https://github.com/EngsShi/react-native-xlog). 

请问,可以在你们的Readme.md上面加上相关的第三方库推荐吗?我们希望有更多的react native开发人员加入到我们的开源项目上来

**Comment by garryyan** [comment]
先赞一个。 后面我稍微有空看一下你们项目的质量，如果优秀的话，可以加到readme上的第三方库推荐。
