### ISSUE TITLE
关于XLOG中异步模式下的回写时机的问题

### ISSUE THREAD

**Issue by IamYuZhiqiang** [Tencent/mars#113]
非常感谢Mars团队的开源行为！
根据mars系列（一）文章中的：
> mmap 既不会丢日志，回写时机对我们来说又基本可控。 mmap 的回写时机：
> · 内存不足
> · 进程 crash
> · 调用 msync 或者 munmap
> · 不设置 MAP_NOSYNC 情况下 30s-60s(仅限FreeBSD)

可以介绍下“基本可控”的含义吗？在应用层需要做控制吗（比如主动调Flush接口）？或者说回写是由mmap或系统来控制的？
谢谢！

**Comment by garryyan** [comment]
如果想控制，可以直接在应用层调用 msync。 不过基本是不需要控制的，你只需要操作内存就行。

**Comment by garryyan** [comment]
系统保证把信息写到中间文件里。 xlog保证下次启动的时候 把中间文件里的日志写到日志文件里。

**Comment by buptlingfeng** [comment]
@garryyan 谢谢，系统怎么保证的中间文件的数据不会丢失？难道是和150K的中间文件大小有关？

**Comment by garryyan** [comment]
可以谷歌下 mmap

**Comment by fupSZ** [comment]
@garryyan  请问 系统保证把信息写到中间文件里，是怎样保证的？现在异步模式下写日志，都会先写到buf中，如果进程crash，是什么机制会保证buf中的数据会冲洗到mmap中呢

**Comment by fupSZ** [comment]
看了下源码，上面的担心是多余的，这个buf就是mmap映射的内存，写到这个buf里面，其实系统就会将其映射到mmap中。

**Comment by garryyan** [comment]
是的

**Comment by JunyiXie** [comment]
mmap 既不会丢日志，回写时机对我们来说又基本可控。 mmap 的回写时机：
· 内存不足
· 进程 crash
· 调用 msync 或者 munmap
· 不设置 MAP_NOSYNC 情况下 30s-60s(仅限FreeBSD)

内存不足,进程crash 的时机可以确定吗？
mmap 中源码有对其进行区分吗？
