### ISSUE TITLE
android targetSdk 30以上多实例情况下log无法输出控制台和文件问题

### ISSUE THREAD

**Issue by cuiqingchao2161** [Tencent/mars#1131]
targetSdk 30以上newXlogInstance返回的地址是负值，jni层打印log的接口对instance为负值做了过滤，代码如下：
#define CHECK_LOG_INSTANCE(log_instance) \
    if (log_instance < 0) return
注释掉CHECK_LOG_INSTANCE()函数的调用即可。

**Comment by yangsk94** [comment]
> targetSdk 30以上newXlogInstance返回的地址是负值，jni层打印日志的接口对实例为负值做了过滤，代码如下： #define CHECK_LOG_INSTANCE(log_instance) if (log_instance < 0) return 注释掉 CHECK_LOG_INSTANCE ()函数的调用即可。

请问该问题是在那个分支上解决的呢
