### ISSUE TITLE
请问日志里面[, , 0]是代表什么意思，能去掉吗

### ISSUE THREAD

**Issue by Super-Barry** [Tencent/mars#1132]
[I][2023-06-20 +80 20:34:08.830][4849, 1769][MainActivity][, , 0][MainActivity.kt,onClick,16]test...

```[tasklist]
### Tasks
```

**Comment by Super-Barry** [comment]
y

**Comment by ChenYangQi666** [comment]
> 已解决，传递栈信息：类名、方法名、行数

怎么解决的？

**Comment by evangerlions** [comment]
同问

> [I][2023-06-20 +80 20:34:08.830][4849, 1769][MainActivity][, , 0][MainActivity.kt,onClick,16]test...
> 
> ### Tasks
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> No tasks being tracked yet.
> 1. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2.



> 已解决，传递栈信息：类名、方法名、行数

同问
