### ISSUE TITLE
服务器又挂了？

### ISSUE THREAD

**Issue by LawrenceHan** [Tencent/mars#116]
@garryyan @shockcao 两个大兄弟，服务器又挂了？我还指望用这个测试我的开源库呢。。。
方便的话能否把server端消息转发的代码也共享一下，这样我可以自己用你们提供的java demo搭服务器了。目前已有的server demo只有echo功能。

**Comment by garryyan** [comment]
大兄弟 我们这个只是demo的server 不保证稳定性的，而且可能随时停止提供服务了，服务器代码也已经全部开源了。你可以试着本地搭建 然后两个用户连应该就有转发功能了。

**Comment by LawrenceHan** [comment]
是这样的，我找同事帮我看了，他说服务端demo只有echo，没有现在你们服务器的转发功能。就是发消息给某个conversation然后广播给所有在线的 这个功能。方便double check一下嘛。麻烦了

**Comment by shockcao** [comment]
mars/samples/Server/server/src/main/java/com/tencent/mars/logicserver/TopicChats.java
mars/samples/Server/server/src/main/java/com/tencent/mars/webserver/SendMessageCgi.java

**Comment by LawrenceHan** [comment]
哦了，我让他看一下。。。

**Comment by shockcao** [comment]
我们的server代码已经放在了mars sample里
引入到工程中   android studio/intelj都能打开  代码自己看就行了
这只是个demo 服务器，特殊要求的话 我们没办法满足  不会针对demo做特性更改
