### ISSUE TITLE
iOS  私有库pod引入,编译失败

### ISSUE THREAD

**Issue by ManOld** [Tencent/mars#1167]
<img width="928" alt="image" src="https://github.com/Tencent/mars/assets/19388025/fd4c7170-657b-4078-9fed-f10e4aed6a08">
怎么解决？

**Comment by ManOld** [comment]
s.source_files        = "code/src/**/*.{h,m,mm}"
  s.public_header_files = "code/src/**/*.h",'code/lib/mars.framework/Headers/.h'
  s.vendored_frameworks = 'code/lib/mars.framework',

  s.libraries = 'z' #依赖libz.tbd
  s.frameworks = 'SystemConfiguration'

**Comment by ManOld** [comment]
如上引入，已解决

**Comment by zhaodusheng** [comment]
这个是怎么去查看呢， 我再自己私有的SDK库 手动引入了Xlog. 在SDK中能编译成功。
但在使用SDK的Demo中却遇到了问题。
ld: Undefined symbols:
  mars::xlog::appender_open(mars::xlog::XLogConfig const&), referenced from:
      -[JRXlogManager initXlog:pathName:] in DotfSDK[19](JRXlogManager.o)
  mars::xlog::appender_close(), referenced from:
      -[JRXlogManager closeXlog] in DotfSDK[19](JRXlogManager.o)
  mars::xlog::appender_set_console_log(bool), referenced from:
      -[JRXlogManager initXlog:pathName:] in DotfSDK[19](JRXlogManager.o)
  _xlogger_SetLevel, referenced from:
      -[JRXlogManager initXlog:pathName:] in DotfSDK[19](JRXlogManager.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
