### ISSUE TITLE
windows编译报错，是啥原因了？

### ISSUE THREAD

**Issue by sunchun2zzf** [Tencent/mars#1188]
D:\GDC\mars\mars(master -> origin) λ python3 build_android.py
Enter menu:
1. Clean && build mars.
2. Build incrementally mars.
3. Clean && build xlog.
4. Exit
3
ndk path:C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\android-ndk-r20b
[[==BUILD_DESCRIPTION==]]Revision: 8dd8b01e &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;
 line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left">master</td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2023-11-30 15:43:05</td></tr><tr><td align="left">Revision</td><td align="left">8dd8b01e</td></tr></table></div>
build cmd:cmake "D:\GDC\mars\mars" -G "Unix Makefiles" -DANDROID_ABI="armeabi-v7a" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\android-ndk-r20b/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\android-ndk-r20b -DANDROID_PLATFORM=android-21 -DANDROID_STL="c++_shared" && cmake --build . --target libzstd_static marsxlog --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- Check for working C compiler: C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works -- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ==============config comm====================
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config mars-boost====================
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/android-ndk-r20b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config app====================
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config baseevent====================
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config xlog====================
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config sdt====================
-- CMAKE_INSTALL_PREFIX=D:/GDC/mars/mars/cmake_build/Android
-- ==============config stn====================
-- ==============config mars====================
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
log-lib
    linked by target "marsxlog" in directory D:/GDC/mars/mars
    linked by target "marsstn" in directory D:/GDC/mars/mars

-- Configuring incomplete, errors occurred!
See also "D:/GDC/mars/mars/cmake_build/Android/CMakeFiles/CMakeOutput.log".
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by chsmy** [comment]
我也遇到了 咋整呢

**Comment by yinyangwu** [comment]
可以试试，Mars project最外层的CMakeLists.txt文件中，将下面：

` find_library(log-lib xlog)`

修改为：

`find_library(log-lib log)`

@chsmy @sunchun2zzf

**Comment by tiemuhua** [comment]
> 可以试试，Mars project最外层的CMakeLists.txt文件中，将下面：
> 
> ` find_library(log-lib xlog)`
> 
> 修改为：
> 
> `find_library(log-lib log)`
> 
> @chsmy @sunchun2zzf

该问题已在master中修复
