### ISSUE TITLE
log_crypt.cc编译出错

### ISSUE THREAD

**Issue by tom510230** [Tencent/mars#123]
在我的项目中，如果引入xlog编译，会报错。报错的位置很奇怪，说是系统的库有问题
![image](https://cloud.githubusercontent.com/assets/5229148/22584429/49277c04-ea2d-11e6-9e58-b80819a9fcf4.png)
这种编译错误肯定不是系统的问题，而是人为造成的，分析一下是因为pch文件造成的。如果在pch里面import的头文件，他里面又有import语法的话就会导致这个问题。解决的方案也很简单，将log_crypt.cc文件改名为log_crypt.mm即可。建议一下是否能够简单将文件改名？

**Comment by garryyan** [comment]
如果在 pch 里面 import 的头文件，他里面又有 import 语法的话就会导致这个问题。  这句话的意思没太理解 可以举个例子吗

本身这个文件是直接放到上层编译的 可以把后缀名改为.mm

**Comment by tom510230** [comment]
譬如在pch文件里面，#import "test.h"，然后在test.h里面又#import "test2.h"，这样的话，会出现上述的编译错误

**Comment by minug** [comment]
直接将工程拖入ios项目中接入。同时，如果在整个ios工程的pch文件中有存在 "#import<Foundation/Foundation.h> " 等cocoa层代码的话，会出现这个.cc文件编译不通过的情况。这时将.cc后缀修改为.mm才能编译通过
