### ISSUE TITLE
xlog的zlib为什么压缩率这么高？

### ISSUE THREAD

**Issue by chengxumiaodaren** [Tencent/mars#1230]
没看明白xlog的zlib为什么压缩率这么高？我自己用zlib压缩同样的数据，100M->63M，但是Xlog100M->4M？
代码都是：
`
deflateInit2(&cstream_, Z_BEST_COMPRESSION, Z_DEFLATED, -MAX_WBITS, MAX_MEM_LEVEL,
                                     Z_DEFAULT_STRATEGY));
deflate(&cstream_, Z_SYNC_FLUSH);
`
为什么xlog的效率这么高呢？？？是在哪里做了特殊处理吗？

**Comment by flx413** [comment]
我也好奇，请问大佬找到原因了吗？ @chengxumiaodaren
