### ISSUE TITLE
android本地编译报错

### ISSUE THREAD

**Issue by TomYeb** [Tencent/mars#124]
步骤：
1，执行python build_android.py
2，选择3 编译静态库
3，选择1 armeabi架构
4，build失败。
错误日志：
Android NDK: WARNING:jni/Android.mk:crypto: LOCAL_LDFLAGS is always ignored for
static libraries
make: Entering directory `F:/BackUpPart2/mars/mars-master/mars/openssl'
[armeabi] "Compile thumb  ": "crypto <= cpt_err.c"
[armeabi] "Compile thumb  ": "crypto <= cryptlib.c"
[armeabi] "Compile thumb  ": "crypto <= cversion.c"
[armeabi] "Compile thumb  ": "crypto <= ex_data.c"
process_begin: CreateProcess(NULL, F:/Studio/s_sdk/ndk-bundle/build//../toolchai
ns/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF ./obj/local/armeabi/o
bjs/crypto/__/crypto/cpt_err.o.d -gcc-toolchain F:/Studio/s_sdk/ndk-bundle/build
//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -ffuncti
on-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-a
rgument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated
-as -g -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msof
t-float -mthumb -Os -DNDEBUG -Ijni/../../comm -Ijni/../../ -Ijni/../../../ -Ijni
/../../../../ -Ijni/../ -Ijni/../export_include -Ijni/../ -Ijni/../crypto -Ijni/
../crypto/asn1 -Ijni/../crypto/evp -Ijni/../include -Ijni/../include/openssl -IF
:/Studio/s_sdk/ndk-bundle/build//../sources/cxx-stl/stlport/stlport -IF:/Studio/
s_sdk/ndk-bundle/build//../sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLO
GGER_TAG=\"mars::crypto\" -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wc
lobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-erro
r=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-i
nt-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -W
no-unused-local-typedefs -DSHA1_ASM -fvisibility=hidden -Wa,--noexecstack -Wform
at -Werror=format-security -isystem F:/Studio/s_sdk/ndk-bundle/build//../platfor
ms/android-9/arch-arm/usr/include -c jni/../crypto/cpt_err.c -o ./obj/local/arme
abi/objs/crypto/__/crypto/cpt_err.o, ...) failed.
make (e=2):
make: *** [obj/local/armeabi/objs/crypto/__/crypto/cpt_err.o] Error 2
make: *** Waiting for unfinished jobs....

请问这是什么原因呢，用过r13和r11c的都是这个情况

**Comment by garryyan** [comment]
操作系统信息？ndk版本信息？

**Comment by TomYeb** [comment]
window7下的，ndk版本是r13b

**Comment by garryyan** [comment]
换用r11c试试 或者修改编译脚本 -j后面的数字4改小甚至直接删除-j 4。 看日志是创建进程失败

**Comment by TomYeb** [comment]
改了之后问题还是存在

**Comment by StevenBlakley77** [comment]
This is my source code programin as you can see thieves come quickly in the night as the 48 laws of power say

**Comment by garryyan** [comment]
@TomYeb 使用r11c也有问题？

**Comment by TomYeb** [comment]
是的，我换回r11c编译也出现了问题
Enter menu:
1. build mars shared libs.
2. build mars static libs.
3. build xlog static libs.
4. build xlog shared libs.
5. exit.
3
Enter the architecture which would like to build:
1. armeabi.
2. x86.
3. mips.
4. armeabi-v7a.
5. arm64-v8a.
6. x86_64.
7. mips64.
8. exit.
1
build armeabi
F:\BackUpPart2\mars-master\mars-master\mars\libraries
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&n
bsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="tex
t/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collap
se;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-si
ze: 11px;    line-height: 16px;    color: #737373;    background-color: white;
  margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padd
ing: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0
069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.descript
ion h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent<
/h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr><
/thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align=
"left">BuildTag</td><td align="left">mars_xlog_sdk/mars_libs</td></tr><tr><td al
ign="left">BuildTime</td><td align="left">2017-02-05 09:42:55</td></tr><tr><td a
lign="left">Revision</td><td align="left"></td></tr></table></div>
process_begin: CreateProcess(NULL, `D:/ndk/android-ndk-r11c-windows-x86/android-
ndk-r11c/build//../ndk-which gcc` -dumpversion, ...) failed.
'info MY_USED_GCC_VERSION_CODE = '
process_begin: CreateProcess(NULL, `D:/ndk/android-ndk-r11c-windows-x86/android-
ndk-r11c/build//../ndk-which gcc` -dumpversion, ...) failed.
'info LOCAL_SRC_FILES= ../crypto/cpt_err.c ../crypto/cryptlib.c ../crypto/cversi
on.c ../crypto/ex_data.c ../crypto/mem.c ../crypto/mem_clr.c ../crypto/mem_dbg.c
 ../crypto/o_init.c ../crypto/o_str.c ../crypto/o_time.c ../crypto/uid.c ../cryp
to/aes/aes_cbc.c ../crypto/aes/aes_cfb.c ../crypto/aes/aes_core.c ../crypto/aes/
aes_ctr.c ../crypto/aes/aes_ecb.c ../crypto/aes/aes_ige.c ../crypto/aes/aes_misc
.c ../crypto/aes/aes_ofb.c ../crypto/aes/aes_wrap.c ../crypto/aes/aes_x86core.c
../crypto/asn1/a_bitstr.c ../crypto/asn1/a_bool.c ../crypto/asn1/a_bytes.c ../cr
ypto/asn1/a_d2i_fp.c ../crypto/asn1/a_dup.c ../crypto/asn1/a_enum.c ../crypto/as
n1/a_gentm.c ../crypto/asn1/a_i2d_fp.c ../crypto/asn1/a_int.c ../crypto/asn1/a_m
bstr.c ../crypto/asn1/a_object.c ../crypto/asn1/a_octet.c ../crypto/asn1/a_print
.c ../crypto/asn1/a_set.c ../crypto/asn1/a_strnid.c ../crypto/asn1/a_time.c ../c
rypto/asn1/a_type.c ../crypto/asn1/a_utctm.c ../crypto/asn1/a_utf8.c ../crypto/a
sn1/ameth_lib.c ../crypto/asn1/asn1_err.c ../crypto/asn1/asn1_lib.c ../crypto/as
n1/asn1_par.c ../crypto/asn1/asn_pack.c ../crypto/asn1/bio_asn1.c ../crypto/asn1
/bio_ndef.c ../crypto/asn1/d2i_pr.c ../crypto/asn1/evp_asn1.c ../crypto/asn1/f_e
num.c ../crypto/asn1/f_int.c ../crypto/asn1/f_string.c ../crypto/asn1/p8_pkey.c
../crypto/asn1/t_pkey.c ../crypto/asn1/tasn_dec.c ../crypto/asn1/tasn_enc.c ../c
rypto/asn1/tasn_fre.c ../crypto/asn1/tasn_new.c ../crypto/asn1/tasn_typ.c ../cry
pto/asn1/tasn_utl.c ../crypto/asn1/x_algor.c ../crypto/asn1/x_attrib.c ../crypto
/asn1/x_bignum.c ../crypto/asn1/x_long.c ../crypto/asn1/x_pubkey.c ../crypto/asn
1/x_sig.c ../crypto/bio/b_dump.c ../crypto/bio/b_print.c ../crypto/bio/bf_buff.c
 ../crypto/bio/bf_lbuf.c ../crypto/bio/bf_nbio.c ../crypto/bio/bf_null.c ../cryp
to/bio/bio_cb.c ../crypto/bio/bio_err.c ../crypto/bio/bio_lib.c ../crypto/bio/bs
s_bio.c ../crypto/bio/bss_fd.c ../crypto/bio/bss_file.c ../crypto/bio/bss_log.c
../crypto/bio/bss_mem.c ../crypto/bio/bss_null.c ../crypto/bn/bn_add.c ../crypto
/bn/bn_asm.c ../crypto/bn/bn_blind.c ../crypto/bn/bn_const.c ../crypto/bn/bn_ctx
.c ../crypto/bn/bn_depr.c ../crypto/bn/bn_div.c ../crypto/bn/bn_err.c ../crypto/
bn/bn_exp.c ../crypto/bn/bn_exp2.c ../crypto/bn/bn_gcd.c ../crypto/bn/bn_gf2m.c
../crypto/bn/bn_kron.c ../crypto/bn/bn_lib.c ../crypto/bn/bn_mod.c ../crypto/bn/
bn_mont.c ../crypto/bn/bn_mpi.c ../crypto/bn/bn_mul.c ../crypto/bn/bn_nist.c ../
crypto/bn/bn_prime.c ../crypto/bn/bn_print.c ../crypto/bn/bn_rand.c ../crypto/bn
/bn_recp.c ../crypto/bn/bn_shift.c ../crypto/bn/bn_sqr.c ../crypto/bn/bn_sqrt.c
../crypto/bn/bn_word.c ../crypto/bn/vms-helper.c ../crypto/buffer/buf_err.c ../c
rypto/buffer/buffer.c ../crypto/ec/ec2_mult.c ../crypto/ec/ec2_smpl.c ../crypto/
ec/ec_ameth.c ../crypto/ec/ec_asn1.c ../crypto/ec/ec_check.c ../crypto/ec/ec_cur
ve.c ../crypto/ec/ec_cvt.c ../crypto/ec/ec_err.c ../crypto/ec/ec_key.c ../crypto
/ec/ec_lib.c ../crypto/ec/ec_mult.c ../crypto/ec/ec_pmeth.c ../crypto/ec/ec_prin
t.c ../crypto/ec/ecp_mont.c ../crypto/ec/ecp_nist.c ../crypto/ec/ecp_smpl.c ../c
rypto/ecdh/ech_err.c ../crypto/ecdh/ech_key.c ../crypto/ecdh/ech_lib.c ../crypto
/ecdh/ech_ossl.c ../crypto/ecdsa/ecs_asn1.c ../crypto/ecdsa/ecs_err.c ../crypto/
ecdsa/ecs_lib.c ../crypto/ecdsa/ecs_ossl.c ../crypto/ecdsa/ecs_sign.c ../crypto/
ecdsa/ecs_vrf.c ../crypto/err/err.c ../crypto/evp/bio_b64.c ../crypto/evp/bio_en
c.c ../crypto/evp/bio_md.c ../crypto/evp/bio_ok.c ../crypto/evp/c_all.c ../crypt
o/evp/c_allc.c ../crypto/evp/c_alld.c ../crypto/evp/digest.c ../crypto/evp/e_aes
.c ../crypto/evp/e_aes_cbc_hmac_sha1.c ../crypto/evp/e_bf.c ../crypto/evp/e_came
llia.c ../crypto/evp/e_cast.c ../crypto/evp/e_idea.c ../crypto/evp/e_null.c ../c
rypto/evp/e_old.c ../crypto/evp/e_rc2.c ../crypto/evp/e_rc4.c ../crypto/evp/e_rc
4_hmac_md5.c ../crypto/evp/e_rc5.c ../crypto/evp/e_seed.c ../crypto/evp/encode.c
 ../crypto/evp/evp_acnf.c ../crypto/evp/evp_enc.c ../crypto/evp/evp_err.c ../cry
pto/evp/evp_fips.c ../crypto/evp/evp_key.c ../crypto/evp/evp_lib.c ../crypto/evp
/evp_pbe.c ../crypto/evp/evp_pkey.c ../crypto/evp/m_dss.c ../crypto/evp/m_dss1.c
 ../crypto/evp/m_ecdsa.c ../crypto/evp/m_md2.c ../crypto/evp/m_md4.c ../crypto/e
vp/m_md5.c ../crypto/evp/m_mdc2.c ../crypto/evp/m_null.c ../crypto/evp/m_ripemd.
c ../crypto/evp/m_sha.c ../crypto/evp/m_sha1.c ../crypto/evp/m_sigver.c ../crypt
o/evp/m_wp.c ../crypto/evp/names.c ../crypto/evp/openbsd_hw.c ../crypto/evp/p5_c
rpt.c ../crypto/evp/p5_crpt2.c ../crypto/evp/p_dec.c ../crypto/evp/p_enc.c ../cr
ypto/evp/p_lib.c ../crypto/evp/p_open.c ../crypto/evp/p_seal.c ../crypto/evp/p_s
ign.c ../crypto/evp/p_verify.c ../crypto/evp/pmeth_fn.c ../crypto/evp/pmeth_gn.c
 ../crypto/evp/pmeth_lib.c ../crypto/hmac/hm_ameth.c ../crypto/hmac/hm_pmeth.c .
./crypto/hmac/hmac.c ../crypto/hmac/hmactest.c ../crypto/lhash/lh_stats.c ../cry
pto/lhash/lhash.c ../crypto/md5/md5_dgst.c ../crypto/md5/md5_one.c ../crypto/mod
es/cbc128.c ../crypto/modes/ccm128.c ../crypto/modes/cfb128.c ../crypto/modes/ct
r128.c ../crypto/modes/cts128.c ../crypto/modes/gcm128.c ../crypto/modes/ofb128.
c ../crypto/modes/xts128.c ../crypto/objects/o_names.c ../crypto/objects/obj_dat
.c ../crypto/objects/obj_err.c ../crypto/objects/obj_lib.c ../crypto/objects/obj
_xref.c ../crypto/pem/pem_all.c ../crypto/pem/pem_lib.c ../crypto/pem/pem_oth.c
../crypto/pem/pem_pkey.c ../crypto/pkcs12/p12_decr.c ../crypto/pkcs12/p12_p8d.c
../crypto/rand/md_rand.c ../crypto/rand/rand_egd.c ../crypto/rand/rand_err.c ../
crypto/rand/rand_lib.c ../crypto/rand/rand_nw.c ../crypto/rand/rand_os2.c ../cry
pto/rand/rand_unix.c ../crypto/rand/rand_vms.c ../crypto/rand/rand_win.c ../cryp
to/rand/randfile.c ../crypto/rsa/rsa_ameth.c ../crypto/rsa/rsa_asn1.c ../crypto/
rsa/rsa_chk.c ../crypto/rsa/rsa_depr.c ../crypto/rsa/rsa_eay.c ../crypto/rsa/rsa
_err.c ../crypto/rsa/rsa_gen.c ../crypto/rsa/rsa_lib.c ../crypto/rsa/rsa_none.c
../crypto/rsa/rsa_null.c ../crypto/rsa/rsa_oaep.c ../crypto/rsa/rsa_pk1.c ../cry
pto/rsa/rsa_pmeth.c ../crypto/rsa/rsa_prn.c ../crypto/rsa/rsa_pss.c ../crypto/rs
a/rsa_saos.c ../crypto/rsa/rsa_sign.c ../crypto/rsa/rsa_ssl.c ../crypto/rsa/rsa_
x931.c ../crypto/sha/sha1_one.c ../crypto/sha/sha1dgst.c ../crypto/sha/sha256.c
../crypto/sha/sha512.c ../crypto/sha/sha_dgst.c ../crypto/stack/stack.c ../crypt
o/x509/x509_att.c ../crypto/x509v3/v3_utl.c ../export/aes_crypt.c ../export/ecdh
_crypt.c ../export/ecdsa_verify.c ../export/md5_digest.c ../export/rsa_private_d
ecrypt.c ../export/crypto/gen_rsa_key_pair.cpp ../export/crypto/openssl_multi_th
read_support.cpp ../export/crypto/pay_openssl_crypto_util.cpp ../export/crypto/r
sa_crypt.cpp ../export/crypto/rsa_pss_sha256.cpp ../export/crypto/test_rsa_pss_s
ha256.cpp ../crypto/sha/asm/sha1-armv4-large.S '
'info SCR end----------------------------------'
Android NDK: WARNING:jni/Android.mk:crypto: LOCAL_LDFLAGS is always ignored for
static libraries
make: Entering directory `F:/BackUpPart2/mars-master/mars-master/mars/openssl'
[armeabi] "Compile thumb  ": "crypto <= cpt_err.c"
[armeabi] "Compile thumb  ": "crypto <= cryptlib.c"
[armeabi] "Compile thumb  ": "crypto <= cversion.c"
process_begin: CreateProcess(NULL, D:/ndk/android-ndk-r11c-windows-x86/android-n
dk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/b
in/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi/objs/crypto/__/cry
pto/cpt_err.o.d -fpic -ffunction-section[armeabi] "Compile thumb  ": "crypto <=
ex_data.c"
s -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te
 -mtune=xscale -msoft-float -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-st
rict-aliasing -finline-limit=64 -Ijni/../../comm -Ijni/../../ -Ijni/../../../ -I
jni/../../../../ -Ijni/../ -Ijni/../export_include -Ijni/../ -Ijni/../crypto -Ij
ni/../crypto/asn1 -Ijni/../crypto/evp -Ijni/../include -Ijni/../include/openssl
-ID:/ndk/android-ndk-r11c-windows-x86/android-ndk-r11c/build//../sources/cxx-stl
/stlport/stlport -ID:/ndk/android-ndk-r11c-windows-x86/android-ndk-r11c/build//.
./sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG=\"mars::crypto\"
 -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set
-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror
=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-param
eter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs
-DSHA1_ASM -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-securit
y -isystem D:/ndk/android-ndk-r11c-windows-x86/android-ndk-r11c/build//../platfo
rms/android-9/arch-arm/usr/include -c jni/../crypto/cpt_err.c -o ./obj/local/arm
eabi/objs/crypto/__/crypto/cpt_err.o, ...) failed.
make (e=2):
make: *** [obj/local/armeabi/objs/crypto/__/crypto/cpt_err.o] Error 2
make: *** Waiting for unfinished jobs....
process_begin: CreateProcess(NULL, D:/ndk/android-ndk-r11c-windows-x86/android-n
dk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/b
in/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi/objs/crypto/__/cry
pto/cryptlib.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-str
ong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os
 -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Ijni/.
./../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../exp
ort_include -Ijni/../ -Ijni/../crypto -Ijni/../crypto/asn1 -Ijni/../crypto/evp -
Ijni/../include -Ijni/../include/openssl -ID:/ndk/android-ndk-r11c-windows-x86/a
ndroid-ndk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/ndk/android-ndk-r
11c-windows-x86/android-ndk-r11c/build//../sources/cxx-stl//gabi++/include -Ijni
 -DANDROID -DXLOGGER_TAG=\"mars::crypto\" -Wall -Wsign-compare -Wtype-limits -Wu
ninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conv
ersion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-er
ror=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -f
data-sections -Wno-unused-local-typedefs -DSHA1_ASM -fvisibility=hidden -Wa,--no
execstack -Wformat -Werror=format-security -isystem D:/ndk/android-ndk-r11c-wind
ows-x86/android-ndk-r11c/build//../platforms/android-9/arch-arm/usr/include -c j
ni/../crypto/cryptlib.c -o ./obj/local/armeabi/objs/crypto/__/crypto/cryptlib.o,
 ...) failed.
make (e=2):
make: *** [obj/local/armeabi/objs/crypto/__/crypto/cryptlib.o] Error 2
process_begin: CreateProcess(NULL, D:/ndk/android-ndk-r11c-windows-x86/android-n
dk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/b
in/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi/objs/crypto/__/cry
pto/cversion.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-str
ong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os
 -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Ijni/.
./../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../exp
ort_include -Ijni/../ -Ijni/../crypto -Ijni/../crypto/asn1 -Ijni/../crypto/evp -
Ijni/../include -Ijni/../include/openssl -ID:/ndk/android-ndk-r11c-windows-x86/a
ndroid-ndk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/ndk/android-ndk-r
11c-windows-x86/android-ndk-r11c/build//../sources/cxx-stl//gabi++/include -Ijni
 -DANDROID -DXLOGGER_TAG=\"mars::crypto\" -Wall -Wsign-compare -Wtype-limits -Wu
ninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conv
ersion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-er
ror=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -f
data-sections -Wno-unused-local-typedefs -DSHA1_ASM -fvisibility=hidden -Wa,--no
execstack -Wformat -Werror=format-security -isystem D:/ndk/android-ndk-r11c-wind
ows-x86/android-ndk-r11c/build//../platforms/android-9/arch-arm/usr/include -c j
ni/../crypto/cversion.c -o ./obj/local/armeabi/objs/crypto/__/crypto/cversion.o,
 ...) failed.
make (e=2):
make: *** [obj/local/armeabi/objs/crypto/__/crypto/cversion.o] Error 2
process_begin: CreateProcess(NULL, D:/ndk/android-ndk-r11c-windows-x86/android-n
dk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/b
in/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi/objs/crypto/__/cry
pto/ex_data.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-stro
ng -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os
-g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Ijni/..
/../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../expo
rt_include -Ijni/../ -Ijni/../crypto -Ijni/../crypto/asn1 -Ijni/../crypto/evp -I
jni/../include -Ijni/../include/openssl -ID:/ndk/android-ndk-r11c-windows-x86/an
droid-ndk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/ndk/android-ndk-r1
1c-windows-x86/android-ndk-r11c/build//../sources/cxx-stl//gabi++/include -Ijni
-DANDROID -DXLOGGER_TAG=\"mars::crypto\" -Wall -Wsign-compare -Wtype-limits -Wun
initialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conve
rsion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-err
or=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fd
ata-sections -Wno-unused-local-typedefs -DSHA1_ASM -fvisibility=hidden -Wa,--noe
xecstack -Wformat -Werror=format-security -isystem D:/ndk/android-ndk-r11c-windo
ws-x86/android-ndk-r11c/build//../platforms/android-9/arch-arm/usr/include -c jn
i/../crypto/ex_data.c -o ./obj/local/armeabi/objs/crypto/__/crypto/ex_data.o, ..
.) failed.
make (e=2):
make: *** [obj/local/armeabi/objs/crypto/__/crypto/ex_data.o] Error 2
make: Leaving directory `F:/BackUpPart2/mars-master/mars-master/mars/openssl'

**Comment by garryyan** [comment]
process_begin: CreateProcess(NULL, D:/ndk/android-ndk-r11c-windows-x86/android- ndk-r11c/build//../ndk-which gcc -dumpversion, ...) failed.

创建进程失败，一般来说和编译环境有关。我看你用的是x86版本的ndk，你的电脑是32位的？ 还有看这一行'android- ndk-r11c' 这个名字有空格？

**Comment by TomYeb** [comment]
好的，的确版本用错了，谢谢
