### ISSUE TITLE
1.2.6版本的xlog中，setMaxFileSize应该怎么用？

### ISSUE THREAD

**Issue by Mckrgf** [Tencent/mars#1243]
一个参数变成两个参数了，sample也没有相关代码，第一个参数传0，第二个参数传1024*1024*2 （2mb），并没有分割

**Comment by Mckrgf** [comment]
解决了。需要先Log.appenderOpen，然后再用xlog进行设置。。。

**Comment by huzipiaopiao** [comment]
我也也到了setMaxAliveTime和setMaxFileSize，怎么设置都不生效，问下你是怎么调用啊
