### ISSUE TITLE
解析日志出错

### ISSUE THREAD

**Issue by TomYeb** [Tencent/mars#125]
用的是python 2.7.3, 打印log解析的时候出现这个

[F]decode_log_file.py decompress err, unpack_from() argument 1 must be string or read-only buffer, not bytearray

**Comment by garryyan** [comment]
修改过加密算法没

**Comment by TomYeb** [comment]
没有修改过，只是直接使用，logcat上能显示，就是不能把那个xlog文件解析出来

**Comment by garryyan** [comment]
第96行  single_log_len = struct.unpack_from("H", tmpbuffer[0:2])[0]  改为single_log_len = struct.unpack_from("H", buffer(tmpbuffer, 0, 2])[0]  试试

**Comment by TomYeb** [comment]
改了之后能显示了

**Comment by garryyan** [comment]
ok 应该和版本有关 我改成这种方式
