### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by bughoho** [Tencent/mars#126]
Undefined symbols for architecture arm64:
  "LogCrypt::CryptAsyncLog(char const*, unsigned long, char*, unsigned long&)", referenced from:
      LogBuffer::Write(void const*, unsigned long) in mars(log_buffer.o)
  "LogCrypt::UpdateLogLen(char*, unsigned int)", referenced from:
      LogBuffer::Write(void const*, unsigned long) in mars(log_buffer.o)
  "LogCrypt::SetTailerInfo(char*)", referenced from:
      LogBuffer::__Flush() in mars(log_buffer.o)
  "LogCrypt::SetHeaderInfo(char*, bool)", referenced from:
      LogBuffer::__Reset() in mars(log_buffer.o)
  "LogCrypt::GetTailerLen()", referenced from:
      LogBuffer::__Flush() in mars(log_buffer.o)
  "LogCrypt::GetLogLen(char const*, unsigned long)", referenced from:
      LogBuffer::Flush(AutoBuffer&) in mars(log_buffer.o)
  "LogCrypt::Fix(char*, unsigned long, bool&, unsigned int&)", referenced from:
      LogBuffer::__Fix() in mars(log_buffer.o)
  "LogCrypt::UpdateLogHour(char*)", referenced from:
      LogBuffer::__Flush() in mars(log_buffer.o)
  "LogCrypt::GetHeaderLen()", referenced from:
      LogBuffer::Write(void const*, unsigned long, void*, unsigned long&) in mars(log_buffer.o)
      LogBuffer::__Fix() in mars(log_buffer.o)
      LogBuffer::__Reset() in mars(log_buffer.o)
  "LogCrypt::CryptSyncLog(char const*, unsigned long, char*, unsigned long&)", referenced from:
      LogBuffer::Write(void const*, unsigned long, void*, unsigned long&) in mars(log_buffer.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请教一下这个是什么原因造成的？我是按照文档上的方式用python编译的，我看了下i386\x64\armv7\arm64所有构架都有，但是工程链接的时候却无法通过。
其实我只是想用xlogger，但是我用xlogger里的工程编译出来的也是报这个错。

**Comment by bughoho** [comment]
已解决，没仔细看文档

**Comment by bughoho** [comment]
已解决，没仔细看文档。
不过我集成进来后在这里异常，由于是在framework里，无法看到变量的值，不清楚怎么会造成这种错误？
![image](https://cloud.githubusercontent.com/assets/10548054/22630868/7bf8285c-ec3c-11e6-9203-faed397e1964.png)

**Comment by garryyan** [comment]
不要在static域中初始化xlog，因为xlog也有static变量。对于C++来说，不同文件中的static变量的初始化顺序是不保证的
