### ISSUE TITLE
开源这个意图为何？

### ISSUE THREAD

**Issue by sopaco** [Tencent/mars#127]
从功能上来看是好项目，但是太重了，很多功能部分都集成在一个项目里而不是开放出去组件化给大家灵活的选择，结果就是这样一个项目长期都是官方来维护，社区力量很难参与进来。
对于ip池、就近择址、性能采样、防黑那些，如果腾讯云能提供对应的服务产品与之对应深度集成倒是不错的

**Comment by garryyan** [comment]
有过考虑结合云做一些工作，但是目前mars需要做的工作还有不少，所以优先级没放那么高。

**Comment by kirozhao** [comment]
mars开源的出发点一个是为了分享微信在应对移动网络环境问题的经验，另一个想法是能够让新的app开发者通过mars快速搭建起网络相关的模块。

mars往极致组件化走目前还有一定难度，但相关同学已经在思考可以尝试的方法。开源出来的mars同时承载了微信目前的客户端版本，因此也会比较谨慎，但同时也可以保证官方一定会在这个项目上持续维护。通过开源，很重要一点就是吸取社区的意见和建议，在这个基础上，再来看如何调整完善。mars的参与会有一定的门槛，但相信广大的社区开发者还是能以各种不同的形式参与进来（比如提这个issue :p）。

之前设想的一个方案就是和云服务合作（不限于腾讯云），简化学习和使用成本。不过限于目前在mars的人力投入，这部分优先级放低了一些。
