### ISSUE TITLE
NDK版本android-ndk-r13，编译失败

### ISSUE THREAD

**Issue by xgy310** [Tencent/mars#130]
jni/../../comm/thread/../unix/thread/mutex.h:121:76: error: 'pthread_mutex_lock_timeout_np' was not declared in this scope
         ret = pthread_mutex_lock_timeout_np(&mutex_, (unsigned)_millisecond);
                                                                            ^
make: *** [obj/local/armeabi/objs/crypto/__/export/crypto/openssl_multi_thread_support.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/Users/xxx/Downloads/mars-master/mars/openssl'
build static libs fail!!!

**Comment by garryyan** [comment]
试试r11c。确保ndk的位数版本和操作系统的位数版本一致
