### ISSUE TITLE
【'mars/xlog/xlogger.h' file not found】

### ISSUE THREAD

**Issue by zBo1997** [Tencent/mars#1308]
环境：

- Mac M3芯片 
- CMake版本：cmake version 3.30.2

我已经按照示例编译出了库，请问大佬为什么我Link库，还是找不到Xloger.h ，我是按照教程配置。不知道哪里做的不对，
![WX20240826-000539@2x](https://github.com/user-attachments/assets/03c85443-8921-4c22-b959-0297b061aac4)
![WX20240826-000709@2x](https://github.com/user-attachments/assets/0a2991c9-d16e-4897-a16b-5d926f73f710)

**Comment by hayukleung** [comment]
同问
