### ISSUE TITLE
您好，麻烦咨询一下集成Xlog之后替换NSLog使用的问题

### ISSUE THREAD

**Issue by wdwblueiOS** [Tencent/mars#132]
我已经将mars.framework以及xlog相关的头文件等加入工程，为了兼容我的项目工程中已经存在的大量NSLog,做了宏替换，在mars自带的LogUtil.h中增加：

#if INFO_LOG_FLAG == 1
#define NSLog(format, ...) LOG_INFO("Info:", format, ##__VA_ARGS__)
#endif

我试图把LogUtil.h文件加入项目工程的预编译文件中，但是编译失败报错，对于这种：

NSLog(@"测试语句"); 编译器报错Called object type 'int' is not a function or function pointer

我在stackOverFlow上找到类似报错，It looks like that macro redefines NSLog, which is a foundation runtime function that we're depending on. 

而且诡异的是，我在app delegate.m中完成Xlog的初始化，在此文件中
NSLog(@"测试语句"); 明显是执行的LOG_INFO
而在其他编译报错的文件中，实际执行的仍然是Foundation框架的方法

小弟水平有限，还请大家帮忙可靠，问题出在哪儿呢？多谢！

**Comment by garryyan** [comment]
#if INFO_LOG_FLAG == 1
#ifdef NSLog 
#undef NSLog
#endif
#define NSLog(format, ...) LOG_INFO("Info:", format, ##VA_ARGS)
#endif
