### ISSUE TITLE
XLog  console输出的最大长度是多少？如果不设置文件（appenderOpen）输出，console不输出？

### ISSUE THREAD

**Issue by lzhang1007** [Tencent/mars#135]

**Comment by garryyan** [comment]
1024字节   如果不设置文件（appenderOpen）输出，console 不输出

**Comment by lzhang1007** [comment]
@garryyan 
sample中这这个判断条件就没有意义了，这两个为什么不能分开控制？
`if (ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            if (BuildConfig.DEBUG) {
                Xlog.setConsoleLogOpen(true);
            }
            else {
                Xlog.setConsoleLogOpen(false);
            }
            Log.setLogImp(new Xlog());
        }`

**Comment by garryyan** [comment]
这这个判断条件就没有意义了。-----说的是哪个if分支
这两个为什么不能分开控制。 -----有想法分离出来，还没动手做
