### ISSUE TITLE
stn是如何通过getAccountInfo来判断用户是否已登录的

### ISSUE THREAD

**Issue by MrIceFox** [Tencent/mars#136]
在android sample中发现这个回调方法只是随机提供了一个账号
```java
public static AppLogic.AccountInfo accountInfo = new AppLogic.AccountInfo(
            new Random(System.currentTimeMillis()/1000).nextInt(), "anonymous");
```
那么如果我要实现这个方法，需要提供怎样一个账号和用户名呢？stn是如何通过这个账号信息判断用户是否已登录的？

**Comment by garryyan** [comment]
不会通过账号信息判断是否登陆，是通过 makesureauth和 isLogon两个函数来判断的

**Comment by MrIceFox** [comment]
makesureauth和 isLogon这两个方法好像都是判断是否是登录状态的

**Comment by MrIceFox** [comment]
那么我们向getAccountInfo这个方法提供的账号信息是有什么用处呢？

**Comment by garryyan** [comment]
STN 会根据客户端是否有账号信息进行网络连接策略的动态调整，当用户没有账号信息时，网络会将连接的频率降低等，所以需要获取用户的帐号信息

**Comment by MrIceFox** [comment]
感谢答复，在**Mars-Android-接口详细说明**里面也有这段话，所以我只需要像sample一样随便提供一个账号信息就可以了?

**Comment by garryyan** [comment]
如果客户端没有账号信息 期望username uin都返回初始值

**Comment by VectorWen** [comment]
我是来手机信息的，因为相关的文档太少了。我只能一个一个issue 看。
