### ISSUE TITLE
FlowLimit的算法貌似有bug

### ISSUE THREAD

**Issue by gengxin** [Tencent/mars#139]
现状：
在FlowLimit::__FlashCurVol方法中，会执行cur_funnel_vol_ -= interval * funnel_speed_，
然后在FlowLimit::Check中判断 if (cur_funnel_vol_ + _len > kMaxVol)，

问题：
除非出现短时间的超大数据流量，否则cur_funnel_vol_ + _len > kMaxVol很难成立，所以貌似无法达到限制流量的作用

**Comment by garryyan** [comment]
这是一个漏斗模型。想想你往漏斗里倒水，防止的就是短时间的超大数据流量

**Comment by gengxin** [comment]
原来是这样，看代码的时候误以为kMaxVol是一个小时内允许使用的流量上限，抱歉 ：）
