### ISSUE TITLE
怎么把stn模块里的src文件夹下的其它文件暴露出来？

### ISSUE THREAD

**Issue by dacaiguoguo** [Tencent/mars#146]
# 怎么把stn模块里的src文件夹下的其它文件暴露出来？
比如`longlink_connect_monitor.h`

**Comment by garryyan** [comment]
涉及到编译方面的，请说明平台

**Comment by dacaiguoguo** [comment]
iOS

**Comment by garryyan** [comment]
简单说是把头文件copy出去就行了 但是会涉及到比较多的头文件  不建议去做
