### ISSUE TITLE
Android平台so文件架构类型支持不够

### ISSUE THREAD

**Issue by liveei** [Tencent/mars#147]
Android 平台想集成Xlog, 可是gradle依赖完一看, 只支持'armeabi',  'x86', 现在主流的'armeabi-v7a',,'arm64-v8a'缺失, 于是想自己生成一下so文件, 然后看了下C文件,在文件夹里面比较分散, 对C不擅长时间成本比较大,能不能麻烦加大so架构类型的支持?

**Comment by garryyan** [comment]
本地编译可以指定其他几种cpu。
之所以没在gradle依赖里把所有的都加上是考虑体积大小，而且如果上层做兼容的话，'armeabi-v7a',,'arm64-v8a' 平台都可以用armeabi的

**Comment by liveei** [comment]
@garryyan   不知道上层怎样兼容?   我们app现在是支持多个架构cpu的, 所以现在必须保证每个架构的so数量及类型保持一致， 在armeabi-v7a 里copy一份armeabi的so应该没问题，但是arm64-v8a因为是64位的就不能copy armeabi了,64位环境运行32位的会报错

**Comment by liveei** [comment]
@garryyan  另外不知道鹅厂的大App是如何应对native层报错的,  因为微信及内置X5内核的App只提供了基本的armeabi架构so , 想必以SIG开头的报错不在少数, 而这势必会影响bug率 :-(

**Comment by garryyan** [comment]
如果一定要所以cpu架构的so，参考wiki中的本地编译部分。 如果你其他的so都有多种架构，那么xlog的也要自己编。除非你所有的so都只有armeabi. 这方面的知识你可以谷歌下 我也只是了解大概

**Comment by garryyan** [comment]
为什么使用armeabi 就会报错， 现在基本所以的架构都会去兼容arm指令

**Comment by garryyan** [comment]
简单的原则：要嘛所有的so都提高不同CPU架构的，要嘛都不提供，之所以会crash是因为你没遵守这个原则。在安装的时候，会根据机器架构去找相应cpu架构的目录，如果找不到我退而求其次，去找次兼容的。

**Comment by liveei** [comment]
so这方面是了解的，之所以多架构支持，是为了尽量提高执行效率（apk大小目前还在可接受的范围），另外其他架构兼容 armeabi 应该也是会有潜在问题的，这也会反应在bug率上

**Comment by garryyan** [comment]
那需要你本地编译了。
