### ISSUE TITLE
XLog 能否自定义加密算法？

### ISSUE THREAD

**Issue by SheepYoung** [Tencent/mars#148]
XLog 能否自定义加密算法？  我使用了demo，然后用decode_mar_log_file.py就可以解密了，我研究了一下Api没有发现有对日志进行自定义加密算法的，或者说自定义log的加密Key之类的？

**Comment by garryyan** [comment]
看wiki

**Comment by SheepYoung** [comment]
多谢，想问相同问题的请看：
https://github.com/Tencent/mars/wiki/Mars-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95
