### ISSUE TITLE
wiki 建议

### ISSUE THREAD

**Issue by dodola** [Tencent/mars#15]
在 Android 指南那边
本地编译的部分
`python build_android.py` 
这个 `build_android.py` 放在 libraries 里可以说明一下
然后编译用的 ndk 我试了13b 是编译不通过的，降级到 `android-ndk-r11c`  可以

**Comment by dodola** [comment]
还有 在mars_xlog_sdk 里缺少bintray.gradle 文件

`apply from: "bintray.gradle"`

**Comment by zxedker** [comment]
#15

**Comment by shockcao** [comment]
@dodola   ndk r13b 有个别平台编译存在问题
目前r11c  r12均支持全平台编译

bintray.gradle被我加到了ignore里  所以遗漏了 已经修复提交 可以pull最新代码
