### ISSUE TITLE
网络诊断用到的ping是否有考虑到Android设备兼容性问题

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#151]
看到这里[pingquery.cc#L119](https://github.com/Tencent/mars/blob/master/mars/sdt/src/checkimpl/pingquery.cc#L119)直接使用系统的ping命令。
有没有考虑到万一设备上没有/system/bin/ping这个可执行文件的情况呢？

**Comment by garryyan** [comment]
如果没有这个命令会返回错误的。 之所以没显式的写出来，是因为没有的话 也没有更好的替代办法。

**Comment by FelixZhang00** [comment]
是否考虑过把AOSP中的[ping.c](https://android.googlesource.com/platform/external/iputils/+/master/ping.c)单独编出一个可执行文件来调用呢？这或许是一个替代方法。

**Comment by garryyan** [comment]
不行，raw socket 需要root权限
