### ISSUE TITLE
关于登录的问题

### ISSUE THREAD

**Issue by jingtai5** [Tencent/mars#154]
你好，我设置了need_authed = true、needAuthed = true、this.limitFlow = true、limitFrequency = true；getLongLinkIdentifyCheckBuffer的时候dentifyReqBuf.write用户标识，并且return StnLogic.ECHECK_NOW。

然后执行任务A、（断网）B（等待20秒）、（联网）C
服务端收到A、（等待了20秒，重新建立连接）B、（心跳包，body包含用户表示）C；

请问，如何让服务端在重新建立连接后直接收到包含用户信息的心跳包，而不是先接收到任务B啊？

谢谢

**Comment by garryyan** [comment]
目前无法保证发包顺序

**Comment by jingtai5** [comment]
那么此时服务端收到B包的时候，并不知道是谁发过来的，请问微信是如何解决这个问题的？

**Comment by garryyan** [comment]
带上用户id和登录后拿到的session信息

**Comment by jingtai5** [comment]
是每条消息，都带登录后拿到的session信息啊？

**Comment by garryyan** [comment]
据我所知是的。

**Comment by jingtai5** [comment]
好，非常感谢

**Comment by larrymeng** [comment]
应该是这样，后台有业务逻辑验证这个session是否正确、合法。
