### ISSUE TITLE
Android mars-wrapper 中使用单独进程来调用mars是出于什么考虑？

### ISSUE THREAD

**Issue by MrIceFox** [Tencent/mars#159]
正在做接入mars的工作, 参照android sample 发现wrappers代码中mas初始化和数据发送都是在单独进程中的service中进行
```java
<service
            android:name=".service.MarsServiceNative"
            android:process=":marsservice" />
```
而数据解码、编码还是在主进程上，报文数据需要跨进程传递，这样设计是出于什么考虑呢？是防止意外crash和解耦和，或者是内存占用问题？

**Comment by shockcao** [comment]
1. 首先假设编码数据放在service进程，例如登录操作，就需要将UI进程的相关uin、pwd全部跨进程传递给service才能编码；换成发消息操作，就需要将消息内容、接收uin传递给service。也就是说针对所有业务，必须设计一个通用的数据结构来传递数据到service，这显然是不能满足的，这个数据结构就会囊括所有的业务成员属性。
2. 但如果设计成数据序列化成二进制，直接传递给service，这就通用了，service无需关心业务内容，这实际是从代码设计和逻辑的角度出发。
3. 当然你也可以将已经编码好的数据，在启动task的时候一并传递给service进程，但如果sessionkey失效，那么已经编码好的数据其实是无效的，所以回调的方式也就更合理。

**Comment by MrIceFox** [comment]
感谢回答，我的意思是为什么需要额外建立一个进程来调用mars，如果都在主进程上调用，比如发送和编解码，会有什么问题？单独建立一个进程是出于什么考虑？

**Comment by garryyan** [comment]
单独没太大问题，但是放在后台的话 因为占用内存比较多 容易被系统杀死

**Comment by shockcao** [comment]
service进程的存活优先级高于前台UI进程，长连接需要维持，UI进程容易被杀，而service进程存活也有拉起UI进程接收通知的能力
进程优先级问题可以google

**Comment by MrIceFox** [comment]
确实这样，查看oom_adj发现后台进程优先级更高，而手动杀死前台进程之后后台进程依然存活

**Comment by kirozhao** [comment]
独立进程不是必须的，mars-wrapper 为了展示在跨进程模式下的一种设计应用方法，好处就是轻重分离，可以提高网络服务的稳定性

**Comment by qhzxz** [comment]
看了一下，mars-warpper这边的代码，在MarsServiceStub里的req2Buf，buf2Resp，onPush的所用到的缓冲区buffer都是临时生成的，用完了就扔。如果频繁的发消息就会生成大量的缓冲区，这会不会造成GC抖动？如果把这些操作放在UI进程里，UI会不会因为频繁的GC导致卡顿？
