### ISSUE TITLE
导入 xlog 的时候，编译出错了，找不到解决方法，对不起

### ISSUE THREAD

**Issue by michaelmou** [Tencent/mars#163]
"_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:

      objc-class-ref in mars(platform_comm.o)

  "_OBJC_CLASS_$_UIDevice", referenced from:

      objc-class-ref in mars(platform_comm.o)

**Comment by garryyan** [comment]
[根据这个图把那几个系统库引入](https://github.com/Tencent/mars/wiki/Mars-iOS%EF%BC%8FOS-X-%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#%E9%93%BE%E6%8E%A5)

**Comment by michaelmou** [comment]
导 mars.framework 进去，就编译不过了，clang: error: linker command failed with exit code 1 (use -v to see invocation)

，这个错误

**Comment by michaelmou** [comment]
引用的库冲突么？
