### ISSUE TITLE
集成百度地图和Xlog错误：UnsatisfiedLinkError & IncrementalClassLoader$DelegateClassLoader

### ISSUE THREAD

**Issue by xiaobailong24** [Tencent/mars#164]
Android Studio: 2.2.3
Gradle: 2.14.1
SDK: API 25: Android 7.1.1 (Nougat)
Instant Run: enable
Xlog: com.tencent.mars:mars-core:1.1.4

Error:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tjkcht.cloudbill, PID: 29474
                  java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-validation-api-1.1.0.Final_ee83c58deaaad5538d2d106bd9ccf14cdf7b965a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-systembartint-1.0.3_c1ad2724fc6f22390862812e0729ca6fabbb5521-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-support-annotations-25.2.0_30f64a62097eb8c494ea5c502ef2f487c2fe4581-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-rxjava-2.0.4_57620904ba6948d5fc6402f751071d44bb5b0c17-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-retrofit-2.1.0_761ea07161efabba8396bb9503c58f8118d79741-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-reactive-streams-1.0.0_d39795e19dc6e3c480f2f258bc459caf03db7f4a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-pbp_models-beta-0.0.4_dc874b0c5f5464cc09d62587a934fefe7e61879d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-parceler-api-1.1.6_c39d8bace1c5f1581371ab1f47394c5fdf5ffcbf-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-otto-1.3.8_2f44242d876f6b00f2230530f6d9b8712f25092d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-org.xutils-xutils-3.3.40_a420c766ff885c8766a221d9acfe25d04d5e2279-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okio-1.11.0_3cc24fb9737e5f00be03585f2b15ab1784c84769-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okhttp-3.5.0_285f0d5e3eaa30eec1b201a971915161e50e3bfd-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-mpermission-annotation-1.0.0_d792e166d7ae38e41075c5df5c8037e471b0bed2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.3.0_0dc69c0be6ddef612ccaa592cfff39024eee2373-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-locSDK_6.13_cd33b2526bcb0d61d8cb4ca2a775f373416fe523-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-httpmime-4.1.2_089ec693b826bf7ee93ac1304cbd962093afc0be-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-gson-2.6.2_c3cabd47718b37c51de2a72ca421e74429a0e1c9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-glide-3.7.0_bf6891284619c5beeec2e1adc5b418f83f730e8c-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-de.hdodenhof-circleimageview-2.1.0_22b1bf67b2fd23759c638a93baa73bdbf577bcb6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-com.zhy-mpermission-api-1.0.0_cfd65120ef5c61752c29be704bb0057d674b9e68-classes.dex", dex file "/data/data/com.tjkcht.c
D/Error: ERR: exClass=java.lang.UnsatisfiedLinkError
D/Error: ERR: exMsg=com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-validation-api-1.1.0.Final_ee83c58deaaad5538d2d106bd9ccf14cdf7b965a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-systembartint-1.0.3_c1ad2724fc6f22390862812e0729ca6fabbb5521-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-support-annotations-25.2.0_30f64a62097eb8c494ea5c502ef2f487c2fe4581-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-rxjava-2.0.4_57620904ba6948d5fc6402f751071d44bb5b0c17-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-retrofit-2.1.0_761ea07161efabba8396bb9503c58f8118d79741-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-reactive-streams-1.0.0_d39795e19dc6e3c480f2f258bc459caf03db7f4a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-pbp_models-beta-0.0.4_dc874b0c5f5464cc09d62587a934fefe7e61879d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-parceler-api-1.1.6_c39d8bace1c5f1581371ab1f47394c5fdf5ffcbf-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-otto-1.3.8_2f44242d876f6b00f2230530f6d9b8712f25092d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-org.xutils-xutils-3.3.40_a420c766ff885c8766a221d9acfe25d04d5e2279-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okio-1.11.0_3cc24fb9737e5f00be03585f2b15ab1784c84769-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okhttp-3.5.0_285f0d5e3eaa30eec1b201a971915161e50e3bfd-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-mpermission-annotation-1.0.0_d792e166d7ae38e41075c5df5c8037e471b0bed2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.3.0_0dc69c0be6ddef612ccaa592cfff39024eee2373-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-locSDK_6.13_cd33b2526bcb0d61d8cb4ca2a775f373416fe523-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-httpmime-4.1.2_089ec693b826bf7ee93ac1304cbd962093afc0be-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-gson-2.6.2_c3cabd47718b37c51de2a72ca421e74429a0e1c9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-glide-3.7.0_bf6891284619c5beeec2e1adc5b418f83f730e8c-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-de.hdodenhof-circleimageview-2.1.0_22b1bf67b2fd23759c638a93baa73bdbf577bcb6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-com.zhy-mpermission-api-1.0.0_cfd65120ef5c61752c29be704bb0057d674b9e68-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-com.zhy-base-rvadapter-3.0.3_d0bae27c792bad3036a557db31f0
D/Error: ERR: file=Runtime.java
D/Error: ERR: class=java.lang.Runtime
D/Error: ERR: method=loadLibrary line=367
D/Error: ERR: stack=java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-validation-api-1.1.0.Final_ee83c58deaaad5538d2d106bd9ccf14cdf7b965a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-systembartint-1.0.3_c1ad2724fc6f22390862812e0729ca6fabbb5521-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-support-annotations-25.2.0_30f64a62097eb8c494ea5c502ef2f487c2fe4581-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-rxjava-2.0.4_57620904ba6948d5fc6402f751071d44bb5b0c17-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-retrofit-2.1.0_761ea07161efabba8396bb9503c58f8118d79741-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-reactive-streams-1.0.0_d39795e19dc6e3c480f2f258bc459caf03db7f4a-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-pbp_models-beta-0.0.4_dc874b0c5f5464cc09d62587a934fefe7e61879d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-parceler-api-1.1.6_c39d8bace1c5f1581371ab1f47394c5fdf5ffcbf-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-otto-1.3.8_2f44242d876f6b00f2230530f6d9b8712f25092d-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-org.xutils-xutils-3.3.40_a420c766ff885c8766a221d9acfe25d04d5e2279-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okio-1.11.0_3cc24fb9737e5f00be03585f2b15ab1784c84769-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-okhttp-3.5.0_285f0d5e3eaa30eec1b201a971915161e50e3bfd-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-mpermission-annotation-1.0.0_d792e166d7ae38e41075c5df5c8037e471b0bed2-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.3.0_0dc69c0be6ddef612ccaa592cfff39024eee2373-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-locSDK_6.13_cd33b2526bcb0d61d8cb4ca2a775f373416fe523-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-httpmime-4.1.2_089ec693b826bf7ee93ac1304cbd962093afc0be-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-gson-2.6.2_c3cabd47718b37c51de2a72ca421e74429a0e1c9-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-glide-3.7.0_bf6891284619c5beeec2e1adc5b418f83f730e8c-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-de.hdodenhof-circleimageview-2.1.0_22b1bf67b2fd23759c638a93baa73bdbf577bcb6-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-com.zhy-mpermission-api-1.0.0_cfd65120ef5c61752c29be704bb0057d674b9e68-classes.dex", dex file "/data/data/com.tjkcht.cloudbill/files/instant-run/dex/slice-com.zhy-base-rvadapter-3.
D/Error: ERR: TOTAL BYTES WRITTEN: 49856

**Comment by garryyan** [comment]
确认一下是不是百度的也用了libstlport_shared.so

**Comment by xiaobailong24** [comment]
问题解决！
## 尝试1：
关闭 **Instant Run**，得到以下错误：
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xiaobailong24.baidumaptest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xiaobailong24.baidumaptest-1/lib/arm, /data/app/com.xiaobailong24.baidumaptest-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libstlport_shared.so"
                                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                                    at com.xiaobailong24.baidumaptest.MainApplication.initXlog(MainApplication.java:36)
                                                                                    at com.xiaobailong24.baidumaptest.MainApplication.onCreate(MainApplication.java:28)
                                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                                    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                                                    at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
## 尝试2
由尝试1的错误输出可以看到**couldn't find "libstlport_shared.so"**，于是放弃使用Gradle引用方式，根据文档采用本地编译so库。
NDK: r11c
编译完成后，将 **libmarsxlog.so**和**libstlport_shared.so**文件放在**app\src\main\jniLibs\armeabi**目录中。
然后配置Android的NDK：
gradle.properties 添加
```
android.useDeprecatedNdk=true
```
Module 的 build.gradle 添加
```
android {
    ......
    defaultConfig {
    ......
        ndk {
            abiFilters "armeabi"
        }
    }
}
```
再次编译调试，问题解决！
在手机**/data/app/com.xiaobailong24.baidumaptest-2/lib/arm/**文件夹下可以看到刚刚添加的两个文件。（**libmarsxlog.so**和**libstlport_shared.so**）

**Comment by xiaobailong24** [comment]
再次打开 **Instant Run**，没有错误！
