### ISSUE TITLE
bool appender_get_current_log_path(char* _log_path, unsigned int _len);这个方法的两个参数分别是什么

### ISSUE THREAD

**Issue by NSYaphetS** [Tencent/mars#165]

**Comment by garryyan** [comment]
第一个 日志路径 第二个哪天的(0表示今天  1表示昨天 2表示前天 以此类推)

**Comment by NSYaphetS** [comment]
我这边是iOS端接入XLog
请问有没有提供方法，可以判断某一天的日志文件是否存在。
比如我想看一下昨天的日志文件是否存在，今天日志文件是否存在，有没有提供这样的方法？
我还以为上面的方法是，然后看了下发现不是。。

**Comment by garryyan** [comment]
appender_getfilepath_from_timespan  拿到路径，然后判断路径所对应的文件是否存在

**Comment by WuKongCoo1** [comment]
> appender_getfilepath_from_timespan 拿到路径，然后判断路径所对应的文件是否存在
打扰了，不会c++，这个方法应该怎么用啊

**Comment by hnny09** [comment]
@garryyan  
iOS多XloggerInstance时，通过appender_getfilepath_from_timespan拿到的数据为空，请问这种情况下如何获取当前正在写入的文件？
