### ISSUE TITLE
导 mars.framework 进去，就编译不过了，clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by michaelmou** [Tencent/mars#166]

**Comment by garryyan** [comment]
请给出更详细的信息

**Comment by michaelmou** [comment]
<img width="389" alt="2017-03-02 11 28 59" src="https://cloud.githubusercontent.com/assets/5761759/23492032/09ab02d8-ff3d-11e6-88ee-f98df1416249.png">

**Comment by michaelmou** [comment]
<img width="827" alt="wx20170302-114217 2x" src="https://cloud.githubusercontent.com/assets/5761759/23494963/ffcae580-ff50-11e6-9ed3-1b5e03208887.png">

**Comment by michaelmou** [comment]
跟libcrypto.a这个库冲突？？ 但我在别的项目同样引入这个库，没事

**Comment by garryyan** [comment]
可以自己本地编译mars.framework 在编译前打开mars的项目 ，把openssl那个子项目删除掉

**Comment by michaelmou** [comment]
要改mars-open-mac这项目里面的脚本是吧

**Comment by michaelmou** [comment]
可以了

**Comment by michaelmou** [comment]
thank you very much
