### ISSUE TITLE
Can I use SDT alone?

### ISSUE THREAD

**Issue by johntaiii** [Tencent/mars#168]
Can I use SDT alone ? 

if YES, How ?

From the architecture in the README, SDT is build on top of the Comm component, means that Comm component is required even if I just need SDT?

will you separate SDT into different repo ?

**Comment by garryyan** [comment]
now, the interface of SDTis invisible to user, of course you can make it visible yourself.
we just use SDT when the network of STN is unreachable.

**Comment by johntaiii** [comment]
From the architecture in the README, SDT is build on top of the Comm component, means that Comm component is required even if I just need SDT?

**Comment by garryyan** [comment]
The log library of SDT is Xlog, so SDT also depends on xlog.

**Comment by johntaiii** [comment]
Why not recommended, can you describe in detail ?
Thanks in advance.

**Comment by garryyan** [comment]
SDT was designed to assist STN, so we did not make the interface of SDT visible.
If you just want to use SDT alone to detect network,  using SDT alone  costs a bit much because we have little documet about it

**Comment by johntaiii** [comment]
ok, thanks.
