### ISSUE TITLE
什么时候可以提供头包 自定义的功能。。。。

### ISSUE THREAD

**Issue by kamaelyoung** [Tencent/mars#169]
什么时候可以提供头包 自定义的功能。。。。
现在头包是写死的 无法自定义

**Comment by garryyan** [comment]
头包 自定义  是什么意思？ 是java 的 package 吗？

**Comment by easyfan** [comment]
我估计是定制TCP包头吧。有很多TCP通信过程使用自定义的包头信息。我遇到了这样的需求。
已经实现了一部分，争取最近提交。

**Comment by kamaelyoung** [comment]
是的 tcp 头包 自定义的 目前mars不能满足需求。。。
 android客户端想使用mars 但是无奈 不会c／c++

**Comment by garryyan** [comment]
[Mars-自定义扩展](https://github.com/Tencent/mars/wiki/Mars-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95) 这里不能满足需求吗

**Comment by easyfan** [comment]
有些行业和领域使用的TCP连接，其包头是需要定制的。比如没有cmd_id等等。

**Comment by kamaelyoung** [comment]
😂个人感觉 mars依赖太强 例如头部信息 个人觉得 假如头部信息和body信息都不关注内容是什么 而是直接写入byte数组 是否跟好

**Comment by astrozhou** [comment]
由于Mars还包含了Task超时管理等，如果长连接中不包含头部信息的话，没办法从长连的数据流中划分出每一个回包的分界，也就没办法进行Task的管理了。除非把Mars设计为纯socket的通道。但即使如此，也会带来长连上不能并发的问题

**Comment by yinqiu1** [comment]
@easyfan 你改得如何了？我这边也在改，不过好像改了之后，似乎会影响到心跳，这个是否有这个影响呢？

**Comment by easyfan** [comment]
我的修改已经应用在项目中，没有影响心跳；但是没有验证对shortlink以及对ios影响。最近比较忙，跳票了不好意思……

**Comment by yinqiu1** [comment]
@easyfan 你只修改了longlink_pack这个函数，并重新定了__STNetMsgXpHeader这个数据结构？没有改shortlink_pack吗？

**Comment by microelec** [comment]
Mars嵌入了__STNetMsgXpHeader这样的内部控制信息，而且要求server的推送也需要填写该控制信息，这样重要的信息需要在用户文档里写明吧？？

**Comment by garryyan** [comment]
@microelec  wiki里都用说明

**Comment by kamaelyoung** [comment]
自定义头包是修改 __STNetMsgXpHeader 就可以了嘛？
