### ISSUE TITLE
xlog Android最低版本限制是16吗  16以下会有问题吗

### ISSUE THREAD

**Issue by huangshengsen** [Tencent/mars#171]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.tencent.mars:mars-xlog:1.0.2] /Users/test/WorkSpace/yunxiao/haofenshu/HaoFenShu/app/build/intermediates/exploded-aar/com.tencent.mars/mars-xlog/1.0.2/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.tencent.mars" to force usage

**Comment by garryyan** [comment]
#144  提问之前先看下是否有人问过没
