### ISSUE TITLE
混淆后写入LogFC

### ISSUE THREAD

**Issue by liangyuteng0927** [Tencent/mars#173]
如题，未混淆没有问题，混淆后崩溃

日志：
`java.lang.UnsatisfiedLinkError: method:logWrite, sig:(Lcom/tencent/mars/xlog/Xlog$XLoggerInfo;Ljava/lang/String;)V`

仅使用了xlog模块1.0.2。`compile "com.tencent.mars:mars-xlog:1.0.2"`

**Comment by shockcao** [comment]
保持非混淆，接口是不能被混淆的

**Comment by liangyuteng0927** [comment]
@shockcao 哪些非混淆

**Comment by shockcao** [comment]
mars提供的接口都必须非混淆  直接按包名com.tencent.mars

**Comment by liangyuteng0927** [comment]
@shockcao 谢谢，我试一下

**Comment by liangyuteng0927** [comment]
这么写了还出问题：
```
-keep interface com.tencent.mars{ *; }
```
@shockcao

**Comment by liangyuteng0927** [comment]
@shockcao 这么写规则还出问题..
`-keep public class com.tencent.mars.**`

**Comment by liangyuteng0927** [comment]
`-keep class com.tencent.mars.*` 依旧出错
@shockcao

**Comment by liangyuteng0927** [comment]
解决了：
```
-keep class com.tencent.mars.** {
  public protected private *;
}
```
