### ISSUE TITLE
Android arm64-v8a 编译不能成功

### ISSUE THREAD

**Issue by jingtai5** [Tencent/mars#174]
你好，我在修改长连接协议后进行针对不同架构处理进行编译的时候，'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64'都能编译成功，唯独 'arm64-v8a'成功不了。

```
localhost:mars_android_sdk lvmeng$ ndk-build _ARCH_=armeabi
'info APP_MODULES = '
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STATIC_XLOG -DMARS_COMM'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC -DMARS_CRYPTO'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
[armeabi] Install        : libmarsstn.so => libs/armeabi/libmarsstn.so
[armeabi] Install        : libmarsxlog.so => libs/armeabi/libmarsxlog.so
[armeabi] Install        : libyixia.so => libs/armeabi/libyixia.so
[armeabi] Install        : libstlport_shared.so => libs/armeabi/libstlport_shared.so
### armeabi 编译成功了 #####

localhost:mars_android_sdk lvmeng$ ndk-build _ARCH_=armeabi-v7a
'info APP_MODULES = '
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STATIC_XLOG -DMARS_COMM'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC -DMARS_CRYPTO'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
[armeabi-v7a] Install        : libmarsstn.so => libs/armeabi-v7a/libmarsstn.so
[armeabi-v7a] Install        : libmarsxlog.so => libs/armeabi-v7a/libmarsxlog.so
[armeabi-v7a] Install        : libyixia.so => libs/armeabi-v7a/libyixia.so
[armeabi-v7a] Install        : libstlport_shared.so => libs/armeabi-v7a/libstlport_shared.so

### armeabi-v7a 编译成功了 #####

localhost:mars_android_sdk lvmeng$ ndk-build _ARCH_=arm64-v8a
'info APP_MODULES = '
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STATIC_XLOG -DMARS_COMM'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC'
'module macros: -DMARS_STN -DMARS_SDT -DMARS_APPCOMM -DMARS_BASEEVENT -DMARS_COMM -DMARS_CRYPTO -DMARS_MMJPEG -DMARS_JPEG_STATIC -DMARS_CRYPTO'
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
[arm64-v8a] Install        : libmarsstn.so => libs/arm64-v8a/libmarsstn.so
[arm64-v8a] Install        : libmarsxlog.so => libs/arm64-v8a/libmarsxlog.so
[arm64-v8a] SharedLibrary  : libyixia.so
/Users/lvmeng/Library/Android/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: anonymous version tag cannot be combined with other version tags
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/libyixia.so] Error 1

```

**Comment by garryyan** [comment]
ndk-build -B V=1 \_ARCH\_=arm64-v8a  看更详细的信息

**Comment by jingtai5** [comment]
/Users/lvmeng/Library/Android/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -Wl,-soname,libyixia.so -shared --sysroot=/Users/lvmeng/Library/Android/android-ndk-r13b/platforms/android-21/arch-arm64 ./obj/local/arm64-v8a/objs/yixia/rea_encrypt.o jni/../mars_libs/arm64-v8a/libmarsstn.a jni/../mars_libs/arm64-v8a/libmarssdt.a jni/../mars_libs/arm64-v8a/libmarsappcomm.a jni/../mars_libs/arm64-v8a/libmarsbaseevent.a jni/../mars_libs/arm64-v8a/libmarscomm.a jni/../mars_libs/arm64-v8a/libcrypto.a -lgcc ./obj/local/arm64-v8a/libmarsxlog.so ./obj/local/arm64-v8a/libstlport_shared.so  -gcc-toolchain /Users/lvmeng/Library/Android/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes  -Wl,--gc-sections -Wl,--gc-sections,--version-script=jni/export.exp -Wl,--gc-sections,--version-script=../../log/jni/export.exp -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -L/Users/lvmeng/Library/Android/android-ndk-r13b/platforms/android-21/arch-arm64/usr/lib -latomic -llog -lz -ljnigraphics -llog -lz -lc -lm -o ./obj/local/arm64-v8a/libyixia.so
/Users/lvmeng/Library/Android/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: anonymous version tag cannot be combined with other version tags
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/libyixia.so] Error 1

**Comment by garryyan** [comment]
看不出。我在自己机器上试了下没问题。  你换个版本的ndk试试 ndk-r11c
