### ISSUE TITLE
能出篇文章，介绍底层socket的封装吗；

### ISSUE THREAD

**Issue by kakukeme** [Tencent/mars#176]
能出篇文章，介绍底层socket的封装吗；

http://www.jianshu.com/p/f8e7c8dc79ac

**Comment by garryyan** [comment]
看了你的xlog迁移，很赞。

socket封装这里确实有点复杂，建议你先把IO复用模式的socket编程搞懂，然后再慢慢看，核心是socketselect. 这个其实就是异步IO复用的封装，什么时候应该监听什么事件。其他的几个类看懂socketselect之后就很好懂了
