### ISSUE TITLE
编译脚本不支持python3，报错'raw_input' is not defined

### ISSUE THREAD

**Issue by microelec** [Tencent/mars#178]
编译脚本不支持python3.x，报错'raw_input' is not defined.
https://docs.python.org/3/whatsnew/3.0.html
PEP 3111: raw_input() was renamed to input(). That is, the new input() function reads a line from sys.stdin and returns it with the trailing newline stripped. It raises EOFError if the input is terminated prematurely. To get the old behavior of input(), use eval(input()).

**Comment by garryyan** [comment]
请仔细阅读wiki 要求python环境2.7
