### ISSUE TITLE
android mars-wrapper MarsServiceProxy.cancel无效

### ISSUE THREAD

**Issue by MrIceFox** [Tencent/mars#179]
`MarsServiceProxy.cancel(MarsTaskWrapper marsTaskWrapper)`这个api是无效的

`MarsServiceProxy`通过维护一个`WRAPPER_TO_TASK_ID`来对应上层`MarsTaskWrapper`和`taskId`，但是app进程传递过来的`MarsTaskWrapper`经过aidl之后，每次都是不同实例，因此在mars这个进程已经无法和taskId对应了。
  
例如在app进程中使用MarsTaskWrapper的实例A发送，在mars进程变成实例B,与taskId=1对应；但是当取消这个请求时，app进程再次传递A过来，在mars进程变成实例C,无法找到相应taskId，也就无法使用`StnLogic.stopTask(taskID)`来停止

**Comment by kirozhao** [comment]
fixed in dev branch
