### ISSUE TITLE
请问 android 可以同时创建多个  Xlog 的对象吗?

### ISSUE THREAD

**Issue by LiHanGuang** [Tencent/mars#183]
Hello mars_android_dev:
    如题,   我目前有 ABC 3个模块,  想把他们各自的Log打印到 "A.xlog", "B.xlog", C.xlog" 这几个文件里面去, 谢谢

**Comment by garryyan** [comment]
目前xlog单进程不支持分文件  建议可以加上个tag 没必要分文件

**Comment by LiHanGuang** [comment]
我看了一下源码(java层),  发现有**setLogImp(new Xlog()); ** 这样的代码,   我还以为可以 **new 多个 XLog** 

```java
package com.tencent.mars.xlog;

/**
 * @author zhaoyuan orehzhang
 */
public class Log {
...
     setLogImp(new Xlog());   // <--------------------我在这里
...
}
```

**Comment by garryyan** [comment]
这里只是让你可以想把xlog替换掉的时候方便替换而已。

**Comment by LiHanGuang** [comment]
好, 谢谢.
