### ISSUE TITLE
android平台上Alarm:Start(int _after)的问题

### ISSUE THREAD

**Issue by songzhangzhang** [Tencent/mars#188]
在android平台上，为什么已经通过MessageQueue::BroadcastMessage设置了一个定时器，还要再调用::startAlarm((int64_t) seq, _after)设置一个android系统的定时器？ 这两个定时器不是功能重复了吗？

**Comment by garryyan** [comment]
alarm是因为和Android的系统有关，如果只有第一个 可能存在一种情况 一直休眠

**Comment by songzhangzhang** [comment]
@garryyan 你的意思是MessageQueue::BroadcastMessage有bug？

**Comment by garryyan** [comment]
不是啊 每个平台都有相应的 alarm

**Comment by songzhangzhang** [comment]
@garryyan 那调用MessageQueue::BroadcastMessage的目的是什么？

**Comment by garryyan** [comment]
我找相关的开发问了下，之前回答的有点问题，真正的原因是：
其实Android下面如果没有alarm对齐的话，不需要消息队列，直接用alarm来触发。但是假设一种场景，一个手机存在alarm对齐(假设为5min)，我一个任务需要在6min执行，我放到消息队列里也是6min后执行，同时起了个6min的alarm，结果可能5min后就触发，这个时候，我们发现没到6min会再次起个1min的alarm，但是因为本身被对齐了，可能这个alarm仍然需要到5min后触发，假设这中间我唤醒手机了，就不需要使用系统的alarm了，因为消息队列里发现到了时间 会直接执行

**Comment by songzhangzhang** [comment]
@garryyan 如果手机休眠了，用消息队列设置的定时器即使超时了也不会触发？是因为这个原因才要使用系统的alarm吗？

**Comment by garryyan** [comment]
是的
