### ISSUE TITLE
Execution failed for task ':server:generateProto'.

### ISSUE THREAD

**Issue by CZXBigBrother** [Tencent/mars#19]
> protoc: stdout: . stderr: /root/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/2.6.1/49565269d355231128f9689f0cc050725bcea6fd/protoc-2.6.1-linux-x86_64.exe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/2.6.1/49565269d355231128f9689f0cc050725bcea6fd/protoc-2.6.1-linux-x86_64.exe)

我linux的服务器GLIBC_2.14也升级了,但是还出现错误

**Comment by zxedker** [comment]
#19

**Comment by garryyan** [comment]
这种是因为机器环境的原因，先确认是否已经升到glibc2.14

**Comment by yixiaojichunqiu** [comment]
i have this question too!
