### ISSUE TITLE
Mac上执行python build_android.py 失败

### ISSUE THREAD

**Issue by marklogg** [Tencent/mars#190]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
make: *** Waiting for unfinished jobs....
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
make: Leaving directory `/Volumes/Logic/workspace/github/tools/mars/mars/comm'
build static libs fail!!!

**Comment by marklogg** [comment]
[armeabi] Compile++ thumb: comm <= http.cc
/Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/comm/__/http.o.d -gcc-toolchain /Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -DNDEBUG  -I./jni -I. -I.. -I../.. -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl/stlport/stlport -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG='"mars::comm"' -Werror -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs -fvisibility=hidden -Wno-error=strict-aliasing -DUSING_XLOG_WEAK_FUNC -Wa,--noexecstack -Wformat -Werror=format-security  -frtti   -std=gnu++11  --sysroot /Volumes/Logic/android/Android/sdk/ndk-bundle/platforms/android-9/arch-arm  -c  jni/../http.cc -o ./obj/local/armeabi/objs/comm/__/http.o
[armeabi] Compile thumb  : comm <= md5.c
/Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -MMD -MP -MF ./obj/local/armeabi/objs/comm/__/md5.o.d -gcc-toolchain /Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -mthumb -Os -DNDEBUG  -I./jni -I. -I.. -I../.. -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl/stlport/stlport -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG='"mars::comm"' -Werror -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs -fvisibility=hidden -Wno-error=strict-aliasing -DUSING_XLOG_WEAK_FUNC -Wa,--noexecstack -Wformat -Werror=format-security    --sysroot /Volumes/Logic/android/Android/sdk/ndk-bundle/platforms/android-9/arch-arm  -c  jni/../md5.c -o ./obj/local/armeabi/objs/comm/__/md5.o
[armeabi] Compile++ thumb: comm <= memdbg.cc
/Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/comm/__/memdbg.o.d -gcc-toolchain /Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -DNDEBUG  -I./jni -I. -I.. -I../.. -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl/stlport/stlport -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG='"mars::comm"' -Werror -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs -fvisibility=hidden -Wno-error=strict-aliasing -DUSING_XLOG_WEAK_FUNC -Wa,--noexecstack -Wformat -Werror=format-security  -frtti   -std=gnu++11  --sysroot /Volumes/Logic/android/Android/sdk/ndk-bundle/platforms/android-9/arch-arm  -c  jni/../memdbg.cc -o ./obj/local/armeabi/objs/comm/__/memdbg.o
[armeabi] Compile++ thumb: comm <= mmap_util.cc
/Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/comm/__/mmap_util.o.d -gcc-toolchain /Volumes/Logic/android/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -DNDEBUG  -I./jni -I. -I.. -I../.. -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl/stlport/stlport -I/Volumes/Logic/android/Android/sdk/ndk-bundle/sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG='"mars::comm"' -Werror -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs -fvisibility=hidden -Wno-error=strict-aliasing -DUSING_XLOG_WEAK_FUNC -Wa,--noexecstack -Wformat -Werror=format-security  -frtti   -std=gnu++11  --sysroot /Volumes/Logic/android/Android/sdk/ndk-bundle/platforms/android-9/arch-arm  -c  jni/../mmap_util.cc -o ./obj/local/armeabi/objs/comm/__/mmap_util.o
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
*** [obj/local/armeabi/objs/comm/__/http.o] Error 1
make: error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
*** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/mmap_util.o] Error 1
make: Leaving directory `/Volumes/Logic/workspace/github/tools/mars/mars/comm'

**Comment by shockcao** [comment]
仔细阅读wiki    看你的ndk版本，这里看到你是直接用的android sdk里的ndk-bundle里的
ndk版本可能过高   
目前仅支持r11c  到 r13b版本   再高的还没适配

**Comment by MMLoveMeMM** [comment]
@shockcao 你好,我也遇见android编译问题,NDK版本是r11c的,Windows7系统
C:\Python27\python.exe E:/qq/library/mars/mars-master/mars/libraries/build_android.py
Enter menu:
1. build mars shared libs.
2. build mars static libs.
3. build xlog static libs.
4. build xlog shared libs.
5. exit.
1
Enter the architecture which would like to build:
1. armeabi.
2. x86.
3. mips.
4. armeabi-v7a.
5. arm64-v8a.
6. x86_64.
7. mips64.
8. exit.
1
build armeabi
E:\qq\library\mars\mars-master\mars\libraries
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left">default</td></tr><tr><td align="left">BuildTime</td><td align="left">2017-04-19 19:51:28</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
'info MY_USED_GCC_VERSION_CODE = '
'info LOCAL_SRC_FILES= ../crypto/cpt_err.c ../crypto/cryptlib.c ../crypto/cversion.c ../crypto/ex_data.c ../crypto/mem.c ../crypto/mem_clr.c ../crypto/mem_dbg.c ../crypto/o_init.c ../crypto/o_str.c ../crypto/o_time.c ../crypto/uid.c ../crypto/aes/aes_cbc.c ../crypto/aes/aes_cfb.c ../crypto/aes/aes_core.c ../crypto/aes/aes_ctr.c ../crypto/aes/aes_ecb.c ../crypto/aes/aes_ige.c ../crypto/aes/aes_misc.c ../crypto/aes/aes_ofb.c ../crypto/aes/aes_wrap.c ../crypto/aes/aes_x86core.c ../crypto/asn1/a_bitstr.c ../crypto/asn1/a_bool.c ../crypto/asn1/a_bytes.c ../crypto/asn1/a_d2i_fp.c ../crypto/asn1/a_dup.c ../crypto/asn1/a_enum.c ../crypto/asn1/a_gentm.c ../crypto/asn1/a_i2d_fp.c ../crypto/asn1/a_int.c ../crypto/asn1/a_mbstr.c ../crypto/asn1/a_object.c ../crypto/asn1/a_octet.c ../crypto/asn1/a_print.c ../crypto/asn1/a_set.c ../crypto/asn1/a_strnid.c ../crypto/asn1/a_time.c ../crypto/asn1/a_type.c ../crypto/asn1/a_utctm.c ../crypto/asn1/a_utf8.c ../crypto/asn1/ameth_lib.c ../crypto/asn1/asn1_err.c ../crypto/asn1/asn1_lib.c ../crypto/asn1/asn1_par.c ../crypto/asn1/asn_pack.c ../crypto/asn1/bio_asn1.c ../crypto/asn1/bio_ndef.c ../crypto/asn1/d2i_pr.c ../crypto/asn1/evp_asn1.c ../crypto/asn1/f_enum.c ../crypto/asn1/f_int.c ../crypto/asn1/f_string.c ../crypto/asn1/p8_pkey.c ../crypto/asn1/t_pkey.c ../crypto/asn1/tasn_dec.c ../crypto/asn1/tasn_enc.c ../crypto/asn1/tasn_fre.c ../crypto/asn1/tasn_new.c ../crypto/asn1/tasn_typ.c ../crypto/asn1/tasn_utl.c ../crypto/asn1/x_algor.c ../crypto/asn1/x_attrib.c ../crypto/asn1/x_bignum.c ../crypto/asn1/x_long.c ../crypto/asn1/x_pubkey.c ../crypto/asn1/x_sig.c ../crypto/bio/b_dump.c ../crypto/bio/b_print.c ../crypto/bio/bf_buff.c ../crypto/bio/bf_lbuf.c ../crypto/bio/bf_nbio.c ../crypto/bio/bf_null.c ../crypto/bio/bio_cb.c ../crypto/bio/bio_err.c ../crypto/bio/bio_lib.c ../crypto/bio/bss_bio.c ../crypto/bio/bss_fd.c ../crypto/bio/bss_file.c ../crypto/bio/bss_log.c ../crypto/bio/bss_mem.c ../crypto/bio/bss_null.c ../crypto/bn/bn_add.c ../crypto/bn/bn_asm.c ../crypto/bn/bn_blind.c ../crypto/bn/bn_const.c ../crypto/bn/bn_ctx.c ../crypto/bn/bn_depr.c ../crypto/bn/bn_div.c ../crypto/bn/bn_err.c ../crypto/bn/bn_exp.c ../crypto/bn/bn_exp2.c ../crypto/bn/bn_gcd.c ../crypto/bn/bn_gf2m.c ../crypto/bn/bn_kron.c ../crypto/bn/bn_lib.c ../crypto/bn/bn_mod.c ../crypto/bn/bn_mont.c ../crypto/bn/bn_mpi.c ../crypto/bn/bn_mul.c ../crypto/bn/bn_nist.c ../crypto/bn/bn_prime.c ../crypto/bn/bn_print.c ../crypto/bn/bn_rand.c ../crypto/bn/bn_recp.c ../crypto/bn/bn_shift.c ../crypto/bn/bn_sqr.c ../crypto/bn/bn_sqrt.c ../crypto/bn/bn_word.c ../crypto/bn/vms-helper.c ../crypto/buffer/buf_err.c ../crypto/buffer/buffer.c ../crypto/ec/ec2_mult.c ../crypto/ec/ec2_smpl.c ../crypto/ec/ec_ameth.c ../crypto/ec/ec_asn1.c ../crypto/ec/ec_check.c ../crypto/ec/ec_curve.c ../crypto/ec/ec_cvt.c ../crypto/ec/ec_err.c ../crypto/ec/ec_key.c ../crypto/ec/ec_lib.c ../crypto/ec/ec_mult.c ../crypto/ec/ec_pmeth.c ../crypto/ec/ec_print.c ../crypto/ec/ecp_mont.c ../crypto/ec/ecp_nist.c ../crypto/ec/ecp_smpl.c ../crypto/ecdh/ech_err.c ../crypto/ecdh/ech_key.c ../crypto/ecdh/ech_lib.c ../crypto/ecdh/ech_ossl.c ../crypto/ecdsa/ecs_asn1.c ../crypto/ecdsa/ecs_err.c ../crypto/ecdsa/ecs_lib.c ../crypto/ecdsa/ecs_ossl.c ../crypto/ecdsa/ecs_sign.c ../crypto/ecdsa/ecs_vrf.c ../crypto/err/err.c ../crypto/evp/bio_b64.c ../crypto/evp/bio_enc.c ../crypto/evp/bio_md.c ../crypto/evp/bio_ok.c ../crypto/evp/c_all.c ../crypto/evp/c_allc.c ../crypto/evp/c_alld.c ../crypto/evp/digest.c ../crypto/evp/e_aes.c ../crypto/evp/e_aes_cbc_hmac_sha1.c ../crypto/evp/e_bf.c ../crypto/evp/e_camellia.c ../crypto/evp/e_cast.c ../crypto/evp/e_idea.c ../crypto/evp/e_null.c ../crypto/evp/e_old.c ../crypto/evp/e_rc2.c ../crypto/evp/e_rc4.c ../crypto/evp/e_rc4_hmac_md5.c ../crypto/evp/e_rc5.c ../crypto/evp/e_seed.c ../crypto/evp/encode.c ../crypto/evp/evp_acnf.c ../crypto/evp/evp_enc.c ../crypto/evp/evp_err.c ../crypto/evp/evp_fips.c ../crypto/evp/evp_key.c ../crypto/evp/evp_lib.c ../crypto/evp/evp_pbe.c ../crypto/evp/evp_pkey.c ../crypto/evp/m_dss.c ../crypto/evp/m_dss1.c ../crypto/evp/m_ecdsa.c ../crypto/evp/m_md2.c ../crypto/evp/m_md4.c ../crypto/evp/m_md5.c ../crypto/evp/m_mdc2.c ../crypto/evp/m_null.c ../crypto/evp/m_ripemd.c ../crypto/evp/m_sha.c ../crypto/evp/m_sha1.c ../crypto/evp/m_sigver.c ../crypto/evp/m_wp.c ../crypto/evp/names.c ../crypto/evp/openbsd_hw.c ../crypto/evp/p5_crpt.c ../crypto/evp/p5_crpt2.c ../crypto/evp/p_dec.c ../crypto/evp/p_enc.c ../crypto/evp/p_lib.c ../crypto/evp/p_open.c ../crypto/evp/p_seal.c ../crypto/evp/p_sign.c ../crypto/evp/p_verify.c ../crypto/evp/pmeth_fn.c ../crypto/evp/pmeth_gn.c ../crypto/evp/pmeth_lib.c ../crypto/hmac/hm_ameth.c ../crypto/hmac/hm_pmeth.c ../crypto/hmac/hmac.c ../crypto/hmac/hmactest.c ../crypto/lhash/lh_stats.c ../crypto/lhash/lhash.c ../crypto/md5/md5_dgst.c ../crypto/md5/md5_one.c ../crypto/modes/cbc128.c ../crypto/modes/ccm128.c ../crypto/modes/cfb128.c ../crypto/modes/ctr128.c ../crypto/modes/cts128.c ../crypto/modes/gcm128.c ../crypto/modes/ofb128.c ../crypto/modes/xts128.c ../crypto/objects/o_names.c ../crypto/objects/obj_dat.c ../crypto/objects/obj_err.c ../crypto/objects/obj_lib.c ../crypto/objects/obj_xref.c ../crypto/pem/pem_all.c ../crypto/pem/pem_lib.c ../crypto/pem/pem_oth.c ../crypto/pem/pem_pkey.c ../crypto/pkcs12/p12_decr.c ../crypto/pkcs12/p12_p8d.c ../crypto/rand/md_rand.c ../crypto/rand/rand_egd.c ../crypto/rand/rand_err.c ../crypto/rand/rand_lib.c ../crypto/rand/rand_nw.c ../crypto/rand/rand_os2.c ../crypto/rand/rand_unix.c ../crypto/rand/rand_vms.c ../crypto/rand/rand_win.c ../crypto/rand/randfile.c ../crypto/rsa/rsa_ameth.c ../crypto/rsa/rsa_asn1.c ../crypto/rsa/rsa_chk.c ../crypto/rsa/rsa_depr.c ../crypto/rsa/rsa_eay.c ../crypto/rsa/rsa_err.c ../crypto/rsa/rsa_gen.c ../crypto/rsa/rsa_lib.c ../crypto/rsa/rsa_none.c ../crypto/rsa/rsa_null.c ../crypto/rsa/rsa_oaep.c ../crypto/rsa/rsa_pk1.c ../crypto/rsa/rsa_pmeth.c ../crypto/rsa/rsa_prn.c ../crypto/rsa/rsa_pss.c ../crypto/rsa/rsa_saos.c ../crypto/rsa/rsa_sign.c ../crypto/rsa/rsa_ssl.c ../crypto/rsa/rsa_x931.c ../crypto/sha/sha1_one.c ../crypto/sha/sha1dgst.c ../crypto/sha/sha256.c ../crypto/sha/sha512.c ../crypto/sha/sha_dgst.c ../crypto/stack/stack.c ../crypto/x509/x509_att.c ../crypto/x509v3/v3_utl.c ../export/aes_crypt.c ../export/ecdh_crypt.c ../export/ecdsa_verify.c ../export/md5_digest.c ../export/rsa_private_decrypt.c ../export/crypto/gen_rsa_key_pair.cpp ../export/crypto/openssl_multi_thread_support.cpp ../export/crypto/pay_openssl_crypto_util.cpp ../export/crypto/rsa_crypt.cpp ../export/crypto/rsa_pss_sha256.cpp ../export/crypto/test_rsa_pss_sha256.cpp ../crypto/sha/asm/sha1-armv4-large.S '
'info SCR end----------------------------------'
Android NDK: WARNING:jni/Android.mk:crypto: LOCAL_LDFLAGS is always ignored for static libraries    
make: Entering directory `E:/qq/library/mars/mars-master/mars/openssl'
process_begin: CreateProcess(NULL, `D:/android-ndk-r11c/build//../ndk-which gcc` -dumpversion, ...) failed.
process_begin: CreateProcess(NULL, `D:/android-ndk-r11c/build//../ndk-which gcc` -dumpversion, ...) failed.
[armeabi] "Compile thumb  ": "crypto <= cpt_err.c"
make: Leaving directory `E:/qq/library/mars/mars-master/mars/openssl'
process_begin: CreateProcess(NULL, D:/android-ndk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi/objs/crypto/__/crypto/cpt_err.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Ijni/../../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../export_include -Ijni/../ -Ijni/../crypto -Ijni/../crypto/asn1 -Ijni/../crypto/evp -Ijni/../include -Ijni/../include/openssl -ID:/android-ndk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/android-ndk-r11c/build//../sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG=\"mars::crypto\" -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-local-typedefs -DSHA1_ASM -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-security -isystem D:/android-ndk-r11c/build//../platforms/android-9/arch-arm/usr/include -c jni/../crypto/cpt_err.c -o ./obj/local/armeabi/objs/crypto/__/crypto/cpt_err.o, ...) failed.
make (e=2): ϵͳ�Ҳ���ָ�����ļ���
make: *** [obj/local/armeabi/objs/crypto/__/crypto/cpt_err.o] Error 2
build static libs fail!!!

Process finished with exit code 0

**Comment by garryyan** [comment]
@MMLoveMeMM 在libraries目录中执行脚本
