### ISSUE TITLE
求ProGuard rules

### ISSUE THREAD

**Issue by Billchen28** [Tencent/mars#195]
正式编译混淆代码，运行后出现crash。
java.lang.UnsatisfiedLinkError: method:logWrite, sig:(Lcom/tencent/mars/xlog/Xlog$XLoggerInfo;Ljava/lang/String;)V
初步估计是jni引用的java代码被混淆，逐个自己查效率低并且不全，有无标准的keep表？

**Comment by garryyan** [comment]
有通配符的， 建议谷歌下proguard的语法。

**Comment by Billchen28** [comment]
-keep class com.tencent.mars.xlog.** { *; }
-keep class com.tencent.mars.comm.** { *; }
-keep class com.tencent.mars.app.** { *; }
-keep class com.tencent.mars.stn.** { *; }
初步折腾出来，没有细致优化，混淆后可用。

**Comment by shockcao** [comment]
mars/mars/libraries/mars_android_sdk/proguard-rules.pro
