### ISSUE TITLE
xlog打印很长的日志，发现被截断掉了，怎么办？

### ISSUE THREAD

**Issue by taoweiji** [Tencent/mars#198]
xlog打印很长的日志，发现被截断掉了，怎么办？

**Comment by garryyan** [comment]
目前限制单条1024字节，建议上层自己分割，而且把太长的内容打到一行日志里体验也并不好。

**Comment by buptlingfeng** [comment]
@garryyan 源码没看到截断成1K，只看到不能超过65535的长度
