### ISSUE TITLE
iOS 中生成的xlog文件解密报错

### ISSUE THREAD

**Issue by huadaogege** [Tencent/mars#199]
我使用默认的方式写的，用python脚本解密出错：生成的log文件里面是这样的：[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid stored block lengths
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid code lengths set
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid distance too far back
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid stored block lengths

**Comment by garryyan** [comment]
基本是因为文件损坏的原因。 文件损坏的话，不是必现的。如果是必现的把环境和你调用的方式列出来。

**Comment by huadaogege** [comment]
不是文件损坏的原因，之前没有按照流程走，没有用python build_apply.py生成需要的文件，直接拷贝进去，结果导致log写进去，但是文件无法解压解密，还是要感谢！

**Comment by huadaogege** [comment]
配置的时候中间出了很多问题，arm64的，设置混编之后文件无法使用设置log文件不备份方法，建议给新用户使用的时候还是要强调说明一下生成文件和依赖库的方式。
