### ISSUE TITLE
使用xlog一个进程写多份文件

### ISSUE THREAD

**Issue by windsad** [Tencent/mars#200]
我想使用xlog去记录，压缩日志，但是日志需要分类记录到不同文件中。在不修改代码的情况下有没有比较好的策略。或者应该修改哪部分代码

**Comment by garryyan** [comment]
暂不支持你说的功能

**Comment by azibug** [comment]
我看微信上是有写很多个文件的，难道它们都是每个进程一个文件？

**Comment by garryyan** [comment]
微信也是每个进程一个文件

**Comment by ZenonHuang** [comment]
目前有考虑支持吗？比如想接入 Matrix ，把里面的日志单独分出来一个文件。
