### ISSUE TITLE
xlog IOS link的时候报错如下

### ISSUE THREAD

**Issue by weixiaotian** [Tencent/mars#201]
Undefined symbols for architecture x86_64:
  "_CFNetworkCopyProxiesForAutoConfigurationScript", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_CFNetworkCopyProxiesForURL", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_CFNetworkCopySystemProxySettings", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_kCFProxyAutoConfigurationURLKey", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_kCFProxyHostNameKey", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_kCFProxyPortNumberKey", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_kCFProxyTypeAutoConfigurationURL", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
  "_kCFProxyTypeKey", referenced from:
      getProxyInfo(int&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mars(platform_comm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by garryyan** [comment]
右侧link lib  黄色框中的都加上
![](https://github.com/Tencent/mars/wiki/images/apple_linker.png)

**Comment by weixiaotian** [comment]
我追加引用了CFNetwork.framework，这个编译成功了，谢谢
