### ISSUE TITLE
解压缩失败

### ISSUE THREAD

**Issue by buptlingfeng** [Tencent/mars#202]
如果字符串长度较长的话，超过16K，那么会在压缩之前把字符串的长度截断成16K，如果这个时候把字符串压缩，并且压缩后的结果超过4K长度，这个时候会把压缩后的字符串给截断，从而加密保存到mmap中。后续写入到mmap中的字符串内容在解压缩的时候会出错，这是由于Deflate的压缩算法所致。

**Comment by garryyan** [comment]
有测试用例吗

**Comment by buptlingfeng** [comment]
@garryyan 我的测试用例是这样写的：
StringBuilder builder = new StringBuilder();
                while (i < 10000) {
                    builder.append(i);
                    builder.append("|");
                    i++;
                }
然后调用接口，将builder.toString()写入到xlog中，然后再随便输出一条日志调用xlog的接口，在解压缩的时候会发现，后一条日志是没办法解压缩的

**Comment by garryyan** [comment]
是解压出来没有那一条日志 还是报解压失败的错误，描述再详细点

**Comment by buptlingfeng** [comment]
@garryyan 前一条日志可以解压出来，不过是被截断的，后一条日志在解压的过程中就出错了

**Comment by garryyan** [comment]
是可重现的吧？ 截断是正常的 第二句出错 我后续会重现下。

**Comment by garryyan** [comment]
fixed mars-core v1.1.6 mars-xlog v1.0.3
