### ISSUE TITLE
请问下Xlog中解析出来的内容是什么意思？另外如何才能不压缩，想省下用py解压的步骤

### ISSUE THREAD

**Issue by chxchen** [Tencent/mars#203]
[D][2017-04-10 +8.0 17:44:32.726][13635, 1316][Xlog][, , 0][...........................]
以上是xlog中的部分内容，其中[, , 0]是什么意思？

**Comment by chxchen** [comment]
另外如何才能不压缩，想省下用py解压的步骤

**Comment by garryyan** [comment]
0 是行号，java代码没有传 所以是0.   不压缩要改xlog的源码 不建议这么做，如果要改的话可以仔细看下源码
