### ISSUE TITLE
Mars的android build系统不支持增量编译的问题

### ISSUE THREAD

**Issue by songzhangzhang** [Tencent/mars#205]
现在在android上，使用python build_android.py进行build，但是这种build方式不支持增量编译， 每次我修改了stn里的一个源文件，都会导致所有mars源码全部被重新编译一遍，非常耗时， 为什么不直接用ndk-build进行build呢？

**Comment by garryyan** [comment]
本身这个脚本是用来编发布包的，一般编发布包是尽量不要增量编译的

**Comment by songzhangzhang** [comment]
如果我要开发调试，应该怎么build呢？

**Comment by songzhangzhang** [comment]
mars团队内部开发的过程中是如何进行build的？

**Comment by garryyan** [comment]
建议简单看下build_android.py 里的编译所用的命令.
先用python build_android.py  build一次项目，后续改了哪个项目使用ndk-build编哪一个同时把依赖他的项目编一下。

**Comment by songzhangzhang** [comment]
我对mars的Android.mk进行了改进，支持直接用ndk-build进行build，支持增量编译，支持与Android Studio集成以及在Android Studio中进行断点调试，你们要不要merge进去？

**Comment by garryyan** [comment]
不改造也支持  ndk-build 进行 build，支持增量编译。
之所以脚本不支持，一是加了 -C 参数，二是每次build前都会删除上次build生成的文件

**Comment by songzhangzhang** [comment]
我试过了，在mars/libraries/mars_android_sdk下ndk-build失败

**Comment by garryyan** [comment]
那是因为没有先编依赖的项目

**Comment by songzhangzhang** [comment]
但是编译依赖项目又必需使用python build_android.py， 而python build_android.py现在又不支持增量编译。 我的方案可以只用一个ndk-build命令就能自动编译依赖的模块，而且是增量编译。

**Comment by garryyan** [comment]
可以提个pr或者给个git地址我们review下

**Comment by songzhangzhang** [comment]
提pr了
