### ISSUE TITLE
Mars的android build系统不支持与Android Studio进行集成调试的问题

### ISSUE THREAD

**Issue by songzhangzhang** [Tencent/mars#206]
现在这种使用python build_android.py进行build的方式无法在Android Studio里对Mars的native代码进行断点调试，为什么不基于Android.mk或CMakeLists.txt搭建build系统呢？

**Comment by garryyan** [comment]
这和最初的工具有关。最初做mars的时候还没有as，是在eclipse下做的，eclipse可以使用项目依赖进行编译。
即使as出来后 也是最近两个版本对C++支持的比较完善的。
现在也是基于Android.mk的 只不过每个项目都是独立的

**Comment by songzhangzhang** [comment]
那mars团队内部现在使用什么工具调试android版本？

**Comment by garryyan** [comment]
android下面不调试的，主要用xcode调试
