### ISSUE TITLE
请教一下log文件压缩方式

### ISSUE THREAD

**Issue by huadaogege** [Tencent/mars#211]
是每一条数据都进行压缩，还是整个文件进行压缩

**Comment by garryyan** [comment]
每一条数据压缩。

**Comment by chenxi141017** [comment]
@garryyan  每一条日志压缩的话，看源码压缩部分的cstream_这个对象只在__Reset()里面才初始化，我测试发现不是每调用一次日志接口，就初始化一次的。  
<img width="712" alt="2017-06-03 2 25 44" src="https://cloud.githubusercontent.com/assets/14297268/26751302/a5dc4918-4868-11e7-83aa-23cbc4ff0dde.png">

请教一下，是怎么控制在什么时候进行初始化的

**Comment by garryyan** [comment]
和反初始化相对应的，这一块你还是要仔细看代码
