### ISSUE TITLE
日志解压问题

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#215]
```sh
~~~~~ begin of mmap ~~~~~
[I][2017-04-17 +8.0 20:14:00.048][23788, 812][app][Thread-812, , 0][msg...
//...#1
~~~~~ end of mmap ~~~~~[5114,5114][2017-04-17 +0800 20:14:09]
[I][2017-04-17 +8.0 20:20:13.829][5114, 847][app][Thread-847, , 0][msg...
//...
~~~~~ begin of mmap ~~~~~
[F]decode_log_file.py log seq:74-230 is missing
[I][2017-04-17 +8.0 20:14:00.048][23788, 812][app][Thread-812, , 0][msg...
//...#2
~~~~~ end of mmap ~~~~~[28964,28964][2017-04-18 +0800 10:38:39]
```

解压的日志里有`[F]decode_log_file.py log seq:74-230 is missing`说明什么？
这里是`#2`的日志内容和`#1`的日志内容是完全一样的。

**Comment by garryyan** [comment]
一般说明因为某些原因 丢了一部分日志

**Comment by FelixZhang00** [comment]
有哪些原因导致丢失日志呢？
为什么两块的日志是一样的？

发自我的 iPhone

**Comment by garryyan** [comment]
方便把日志文件给我吗

**Comment by garryyan** [comment]
看了你发的日志文件，这里上面说错了，没丢日志，冗余了一部分日志。

这个问题 我们内部也遇到过一次，不过与此同时sqlite的数据库里的数据也回滚了。暂时怀疑由于某个原因mmap里的数据回滚到了某个时间点。

后续再有进度我会在这里说的、

**Comment by chunlongyuan** [comment]
@garryyan 在iOS上使用xlog，有些用户遇到在手机电池耗尽自动关机然后充电启动后发现NSUserDefaults里保存的数据会丢失的情况，然后我拿到他们当时的xlog日志，看到有xlog数据丢失的日志。不知你有没有收集到该问题，谢谢？
[E][][0, 0*][][, , 0][-------- flush -------
$$$$$$$$$$Dec 10 2017$$$13:45:01$$$$$$$$$$[6495,10778914624][2019-06-09 +0800 11:12:25]
^^^^^^^^^^Dec 10 2017^^^13:45:01^^^^^^^^^^[6495,10778914624][2019-06-09 +0800 11:12:25]
del time out files time: 1
get mmap time: 0
MARS_URL: 
MARS_PATH: master
MARS_REVISION: 1db39d5
MARS_BUILD_TIME: 2017-12-10 13:44:53
MARS_BUILD_JOB: samplexloglibs
log appender mode:0, use mmap:1
[F][ last log file:/var/mobile/Containers/Data/Application/D4537D31-4999-4265-AD81-FFEFD8700AFB/Documents/log/morse_20190609.xlog from 2019-06-09 +0800 14:11:24 to 2019-06-09 +0800 15:14:55, time_diff:3811, tick_diff:471927
[F]decode_log_file.py log seq:262-1 is missing
