### ISSUE TITLE
NDK_PROJECT_PATH在编译share库的时候,这个环境参数是如何设置?

### ISSUE THREAD

**Issue by MMLoveMeMM** [Tencent/mars#217]
NDK_PROJECT_PATH在编译share库的时候,这个环境参数是如何设置?非常感谢

**Comment by garryyan** [comment]
请把问题描述的尽量清楚

**Comment by MMLoveMeMM** [comment]
@garryyan :1 warning generated.
[armeabi-v7a] Prebuilt       : libstlport_shared.so <= <NDK>/sources/cxx-stl/stlport/libs/armeabi-v7a/
3 warnings generated.
[armeabi-v7a] Install        : libstlport_shared.so => libs/armeabi-v7a/libstlport_shared.so
[armeabi-v7a] StaticLibrary  : libmarsxlog.a
make: Leaving directory `E:/qq/library/mars/mars-master/mars/log'
build succeed!
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
make: Entering directory `E:/qq/library/mars/mars-master/mars/libraries/mars_xlog_sdk'
D:\ndkr13b\build\\..\build\core\build-local.mk:151: *** Android NDK: Aborting    .  Stop.
make: Leaving directory `E:/qq/library/mars/mars-master/mars/libraries/mars_xlog_sdk'
build fail!!!
编译的是android的,选项都是选择4,编译成共享so库的,另外是否有微信讨论组呀,能够直接沟通呀,还有更详细的文件目录说明吗,mk文件有点多,链接套路有点长,看起来有点费劲,非常感谢!

**Comment by garryyan** [comment]
所有的编译脚本都在 libraries 目录, 运行编译脚本之前也必须 cd 到此目录，在当前目录下运行。。

讨论组 wiki里有说

**Comment by MMLoveMeMM** [comment]
@garryyan : 这个我都是照着说明操作的,静态库是已经可以编译成功了,只是共享库还没有,我再看看源代码,已经加了讨论,非常感谢

**Comment by garryyan** [comment]
qq群中已解决，因为mars_xlog_sdk 缺少mk文件，无故消失的原因暂时不明

**Comment by xiaobeisrichang** [comment]
@garryyan 能否麻烦说一下这个报错的原因以及解决方式呀
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/Users/xiaoming/android/android-ndk-r14b/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.
虽然没有前面那么一大段，但是最后的报错应该差不多，作为一个刚入门的rn开发，配置一个正确的安卓环境真是头疼呢，囧，希望不吝赐教～～谢谢哇

**Comment by garryyan** [comment]
使用ndk-r11c 目前mars不支持这么高的ndk版本
