### ISSUE TITLE
文件存在乱码

### ISSUE THREAD

**Issue by lindexi** [Tencent/mars#218]
文件 ：https://github.com/Tencent/mars/blob/dev/mars/app/src/wp/platform_logic.cpp 

存在乱码

**Comment by garryyan** [comment]
wp和windows平台都在适配中，这里是因为编码的原因

**Comment by lindexi** [comment]
@garryyan 多谢你的回复，什么时候可以在windows可以编译

**Comment by lindexi** [comment]
是否有UWP相关平台的开发？
