### ISSUE TITLE
iOSDemo 编译会跑自定义脚本。

### ISSUE THREAD

**Issue by ynot16** [Tencent/mars#22]
iOSDemo Build Phase有一个build mars的script，导致每次编译都好长时间。那个是编译marks.framework的脚本么，手动编译出marks.framework并拉进项目，是不是可以删了那个脚本？

**Comment by garryyan** [comment]
是的  为了保证用的代码是最新代码这里做了即时编译。   手动编译出 marks.framework 并拉进项目或者build success一次之后，就可以删了那个脚本
