### ISSUE TITLE
Mars/XLog的文件名有文件日期，如果设备长期运行，隔了一天以后log文件是怎么安排？

### ISSUE THREAD

**Issue by chxchen** [Tencent/mars#220]
比如24日到27日，程序一直运行，这时候记录文件只会有一个XXX_20170424.Xlog吗？
所有的24到27日的记录都会写在这个文件吗？

**Comment by garryyan** [comment]
为什么不自己测试一下呢

**Comment by chxchen** [comment]
现在我的结论是  只会有这样一个文件，但是25-27日的记录都没有了。。。

**Comment by garryyan** [comment]
会自动更换文件的，你实测出来的 只有一个文件吗

**Comment by chxchen** [comment]
环境限制，设备不在身边，我之所以得出这样的结论，是因为拉取log是根据日期拉取，24日能拉取到，但是25、26拉取不到。
后来联系那边工作人员，了解到从未关机的情况后，让他们重启了设备，再次拉取今日的  就有log了

**Comment by garryyan** [comment]
可以用自己身边的设备测试一下，会自动更换文件的，相关代码在appender.cc里面

**Comment by chxchen** [comment]
更换文件的命名规则是和原本初始化的文件名规则一样吗？

**Comment by chxchen** [comment]
抱歉   内部交流出了点问题，本来一个分进程被另一个同事取消掉了，导致本来拉取log的两个文件少了一个。。。
