### ISSUE TITLE
发现一个xlog的耗时问题

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#221]
在某些设备（小米盒子3）上，日志模块造成了卡顿，
在开启mmap的情况下，定位到[这里](https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L509)对sg_log_buff 执行Flush时，发现[memset](https://github.com/Tencent/mars/blob/master/mars/log/src/log_buffer.cc#L172)耗时严重，默认的buffer大小，耗时1秒多，而同时[log2file](https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L512)只耗时3毫秒。
如果不开启mmap，直接读写内存，没有卡顿的问题。

有没有可能厂商对mmap的实现不同呢？造成memset调用直接写文件了？

是否能这样修改：
把[memset](https://github.com/Tencent/mars/blob/master/mars/log/src/log_buffer.cc#L172)的这行代码注释掉，清零操作只对buffer的游标做[初始化](https://github.com/Tencent/mars/blob/master/mars/log/src/log_buffer.cc#L173)呢？

```
void LogBuffer::__Clear() {
    //memset(buff_.Ptr(), 0, buff_.MaxLength());
    buff_.Length(0, 0);
}
```
既然有游标了就没必要对内存做清零操作了吧

**Comment by garryyan** [comment]
看了下代码逻辑 这样是可以的，因为头部会记长度。

你也可以仔细确认一下。

**Comment by buptlingfeng** [comment]
这样做有一个小问题，如果在__Clear
之后应用进程挂了，会导致在下次启动的时候把buffer的数据再一次刷新到日志文件中，因为每次启动的时候去mmap文件，这个文件是有长度的，不过感觉这个影响不大，也就是数据重复了一份而已

**Comment by garryyan** [comment]
@FelixZhang00  这里考虑不周 的确如 @buptlingfeng 所说的，小概率的日志会重复

**Comment by buptlingfeng** [comment]
不过也有一个解决办法，就是memset的内容少一些，只把头部标示长度的地方设置成0，这样下次启动的时候也不会刷新，而且时间消耗也比较小一点

2017-05-04 11:06 GMT+08:00 garryyan <notifications@github.com>:

**Comment by FelixZhang00** [comment]
头部标示长度如何获取？

**Comment by buptlingfeng** [comment]
你可以看下具体的代码 判断mmap里边是否有数据需要flush到文件中，是判断一个头的 只有一个字段（源码的逻辑），你把第一个位置设置成0就好了。

if (buffer.Ptr()) {
    __writetips2file("~~~~~ begin of mmap ~~~~~\n");
    __log2file(buffer.Ptr(), buffer.Length());
    __writetips2file("~~~~~ end of mmap ~~~~~%s\n", mark_info);
}


正是这段代码，你可以把指针的第一个位置的值设置成0就OK了

2017-05-04 19:22 GMT+08:00 Fei Zhang <notifications@github.com>:
