### ISSUE TITLE
xlog新一天的日志不是以begin of mmap开始

### ISSUE THREAD

**Issue by jacpy** [Tencent/mars#223]
您好，请问发生以下场景的日志记录情况是正常的吗？

新一天的xlog日志文件不是以`~~~~~ begin of mmap ~~~~~`这样开始，而是直接以日志内容开始，这样的内容到下一个`~~~~~ begin of mmap ~~~~~`之间有14894个字符且都是英文字符。

而前一天的日志也没有以`~~~~~ end of mmap ~~~~~`结尾。从前一天日志的文件末尾开始，至倒数第一个`~~~~~ end of mmap ~~~~~`之间有21906个字符且都是英文字符。

前一天的日志与当天的日志时间也对不上，前一天的日志是18:24，当天日志开始记录的时间是09:35，差不多是上下班时间。

请问是不是发生日志丢失？可能是什么原因导致的？

**Comment by garryyan** [comment]
文件开始结束和  begin of mmap  以及 end of mmap 并没有任何关系。

18:24是文件中日志的最后一条日志的时间还是第一条日志的时间

**Comment by jacpy** [comment]
是前一天日志的最后一条日志时间。

**Comment by garryyan** [comment]
前一天的日志与当天的日志时间也对不上？ 是怎么体现的？

**Comment by jacpy** [comment]
意思是说：前一天日志到18点左右结束，也没有发现end of mmap结尾，而第二天的日志没有以begin of mmap开始，以为前一天的日志没有全部打出来，还有缓存，然后在第二天的日志文件中输出或者说中间日志发生的丢失或截断。

因为日志还没有在项目中大面积使用，只在部分功能中使用，所以也没有办法判断究竟是否被丢失或截断，没有用日志记录应用运行轨迹。但是没有发现规律的以end of mmap或begin of mmap标识结尾或开头（因为大部分日志文件都是很有规律的这样开始和结尾），所以认为中间日志发生丢失。

**Comment by garryyan** [comment]
换日志文件时是没什么标志的，只有重启才有标志。

**Comment by jacpy** [comment]
也就是说出现这样的现象是正常的？

**Comment by garryyan** [comment]
难说 根据你使用的场景和逻辑来看，只能说没有这两块标识很正常

**Comment by jacpy** [comment]
OK，非常感谢。
