### ISSUE TITLE
mutex unlock操作造成crash

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#224]
在应用初始化的时候出现了一次crash
堆栈如下：
![](http://i4.buimg.com/567571/f888e6318211a0a9.jpg)

crash的地方是`mutex.h`的`unlock`方法[第90行](https://github.com/Tencent/mars/blob/master/mars/comm/unix/thread/mutex.h#L90).
```
        int ret = pthread_mutex_unlock(&mutex_);

        if (EINVAL == ret) ASSERT(0 == EINVAL);
        else if (EAGAIN == ret) ASSERT(0 == EAGAIN);
        else if (EPERM == ret) ASSERT(0 == EPERM);
```
因为EAGAIN=35，` ASSERT(0 == EAGAIN)`一定是会报错的，
这里的逻辑是pthread_mutex_unlock失败，就让应用crash吗？

**Comment by garryyan** [comment]
这里在release版本下只会打堆栈 并不会crash,crash有可能由其他原因引起的，可以看下上下文

**Comment by FelixZhang00** [comment]
用默认的`build_android.py `编译xlog`,生成的libmarsxlog.so就是release版本的吧。

**Comment by garryyan** [comment]
是的 所以用编译脚本编的都是release版本
