### ISSUE TITLE
comm模块能否独立使用？

### ISSUE THREAD

**Issue by shuaixitao** [Tencent/mars#225]
很想在我们自己的项目中使用comm模块，这个应该是可以独立使用的吧？
目前在IOS上编译出libcomm.a 库，但是对应的头文件应该怎么导出呢？
盼复！谢谢！

**Comment by garryyan** [comment]
ios平台上 直接把头文件复制出来就行了、

**Comment by shuaixitao** [comment]
需要的头文件的话应该就是../comm/ 这个目录下的所有头文件吗？

**Comment by garryyan** [comment]
你用到哪个复制哪一个就行了。不过相互之间可能有依赖

**Comment by gmtalang** [comment]
@garryyan  android 平台呢，也是这样吗
