### ISSUE TITLE
Android监听信号强度耗电问题

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#227]
下面代码中，初始化mars的时候，就去监听信号强度变化，中间没有停止监听的代码，这样不会很耗电吗？

![2017-05-10 21 47 41](https://cloud.githubusercontent.com/assets/10632522/25901864/942390e2-35ca-11e7-9137-9a88aa1f1132.png)

**Comment by garryyan** [comment]
只要在listener里不做大规模的操作，不做比较重的操作，不会有太大的影响的。
