### ISSUE TITLE
Xlog在Android通过release打包的APK启动时会崩溃

### ISSUE THREAD

**Issue by zwmmenghuan123** [Tencent/mars#228]
能不能提供一个混淆配置文件。如果release打包时不混淆，则一切正常，如果混淆，Xlog加载so的时候会崩溃。

**Comment by garryyan** [comment]
混淆的时候把native相关的接口keep一下

**Comment by halfhq** [comment]
@zwmmenghuan123 
从Issues中找到的
-keep class com.tencent.mars.xlog.** { *; }
-keep class com.tencent.mars.comm.** { *; }
-keep class com.tencent.mars.app.** { *; }
-keep class com.tencent.mars.stn.** { *; }
