### ISSUE TITLE
请教下xlog日志上报到服务器问题

### ISSUE THREAD

**Issue by Puppy-Love** [Tencent/mars#229]
现在服务器有一个【上报日志】接口是走socket通信，可是用xlog记录日志，java上没法解压日志 然后进行上报，请问是只能走http把xlog文件全部上传到服务器然后自己用py解压查看？

**Comment by garryyan** [comment]
xlog文件也只是一个普通的文件， 和上传其他文件没区别的。 为什么不能在java上上传？

**Comment by Puppy-Love** [comment]
直接上传xlog文件肯定可以，现在是想在程序解压xlog获取里面 日志打印类型 打印内容 和时间 这些参数 然后把这些信息通过接口上传到服务器！

**Comment by Puppy-Love** [comment]
@garryyan

**Comment by garryyan** [comment]
不建议在客户端去解日志。

**Comment by Puppy-Love** [comment]
@garryyan 好吧，要是想获取日志详细的信息 就得自己去另用其他方式存储起来咯？

**Comment by garryyan** [comment]
是 或者按照xlog的格式去解析

**Comment by guohuake** [comment]
请问上传日志时，存在主进程在上传，子进程在写的情况，操作是同一个文件。怎么处理？
