### ISSUE TITLE
Android集成xlog遇到一点问题，请教下

### ISSUE THREAD

**Issue by AaronHezq** [Tencent/mars#23]
在测试xlog模块的时候获得的日志没有logcat中的全面，并且看不到crash的信息，是不是哪里配置的不对。
现象：
第一次点击按钮闪退，没有生成.xlog文件，log目录下只生成了MarsTest.mmap2,再次运行app才出现MarsTest_20161229.xlog;
集成信息：
依赖  compile 'com.tencent.mars:mars-xlog:1.0.0'
Application中的代码 
@Override
    public void onCreate() {
        super.onCreate();
        System.loadLibrary("stlport_shared");
        System.loadLibrary("marsxlog");
        initXlog();
    }

    private void initXlog() {
        final String SDCARD = Environment.getExternalStorageDirectory().getAbsolutePath();
        final String logPath = SDCARD + "/marstest/log";
        //init xlog
        if (BuildConfig.DEBUG) {
            Xlog.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, "", logPath, "MarsTest");
            Xlog.setConsoleLogOpen(true);
        } else {
            Xlog.appenderOpen(Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, "", logPath, "MarsTest");
            Xlog.setConsoleLogOpen(false);
        }
        Log.setLogImp(new Xlog());
        Log.d(TAG, "已初始化xlog");
    }
    @Override
    public void onTerminate() {
        super.onTerminate();
        Log.appenderClose();
    }
测试时手动点击按钮抛出一个未捕获的空指针，logcat有输出
解密后的日志：$ python decode_mars_log_file.py MarsTest_20161229.xlog out.txt
~~~~~ begin of mmap ~~~~~
^^^^^^^^^^Dec 28 2016^^^17:29:33^^^^^^^^^^[27946,27946][2016-12-29 +0800 12:59:15]
del time out files time: 0
get mmap time: 7
MARS_URL: 
MARS_PATH: hotfix/1.x
MARS_REVISION: 10b8355
MARS_BUILD_TIME: 2016-12-28 17:29:12
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
[D][2016-12-29 +8.0 12:59:15.227][27946, 1*][App][, , 0][已初始化xlog
~~~~~ end of mmap ~~~~~[28549,28549][2016-12-29 +0800 13:00:04]

**Comment by shockcao** [comment]
mmap2 是中间文件   因为xlog是写mmap，mmap同步到文件中的时机由操作系统决定
进程crash时是一定会刷到文件

使用的android系统是什么版本？

**Comment by AaronHezq** [comment]
安卓版本 5.1.1  权限加了的，并且再次运行app会生成.xlog文件，但.xlog中的日志没包含logcat中的NullPointerException信息，是不是我哪里配置错了或者少加了东西，依赖只加了com.tencent.mars:mars-xlog:1.0.0

**Comment by AaronHezq** [comment]
理解了，谢谢

**Comment by congmf** [comment]
请教一下xlog怎么在windows上打开

**Comment by garryyan** [comment]
@congmf #16  1.2将会支持
