### ISSUE TITLE
App was on running then crash happened: open file error:4 Interrupted system call...

### ISSUE THREAD

**Issue by nadnaij** [Tencent/mars#230]
我使用自己编译so的xlog。在app运行的过程中，发生了崩溃。

控制台输出

`V         : [, , 0]:open file error:4 Interrupted system call, path:/storage/emulated/0/myLogPath/prefix_20170516.xlog`

之前是有log保存的。

**Comment by garryyan** [comment]
什么场景下出现的？ 是否必现？什么机型

**Comment by nadnaij** [comment]
待机的时候，今天随机出现2次。机型是我这里的开发机。

这里还有第二次崩溃的日志

`05-16 14:20:00.764  9111  9111 F DEBUG   : backtrace:
05-16 14:20:00.767  9111  9111 F DEBUG   :     #00 pc 0004f5d0  /system/lib/libc.so (_Z10__fseeko64P7__sFILExii+9)
05-16 14:20:00.768  9111  9111 F DEBUG   :     #01 pc 0004f767  /system/lib/libc.so (fseeko+14)
05-16 14:20:00.768  9111  9111 F DEBUG   :     #02 pc 000067a7  /system/lib/libmarsxlog.so
05-16 14:20:00.768  9111  9111 F DEBUG   :     #03 pc 00006a23  /system/lib/libmarsxlog.so
05-16 14:20:00.768  9111  9111 F DEBUG   :     #04 pc 00007301  /system/lib/libmarsxlog.so
05-16 14:20:00.768  9111  9111 F DEBUG   :     #05 pc 00004feb  /system/lib/libmarsxlog.so
05-16 14:20:00.768  9111  9111 F DEBUG   :     #06 pc 00006043  /system/lib/libmarsxlog.so
05-16 14:20:00.768  9111  9111 F DEBUG   :     #07 pc 00047343  /system/lib/libc.so (_ZL15__pthread_startPv+22)
05-16 14:20:00.768  9111  9111 F DEBUG   :     #08 pc 0001a0dd  /system/lib/libc.so (__start_thread+6)`

**Comment by garryyan** [comment]
待机的时间是否有插播sdcard，或者是否有连接数据线，导致sdcard unmout了

**Comment by nadnaij** [comment]
没拔出sdcard，也没有链接数据线。

**Comment by garryyan** [comment]
error:4 Interrupted system call 
一般是被其他打断导致的，查下有没有其他信号发出来

**Comment by nadnaij** [comment]
我们这边的工程师分析，是fopen的时候cpu忙，导致fopen失败，建议fopen可以多尝试几次

**Comment by garryyan** [comment]
cpu在做什么？会忙到这个程度
