### ISSUE TITLE
怎么触发断线重连

### ISSUE THREAD

**Issue by Puppy-Love** [Tencent/mars#231]
我是用 reportConnectInfo 返回的状态来控制重连，但是感觉还是不够稳定

**Comment by garryyan** [comment]
mars有一套自己的重连机制，目前不可以外部控制

**Comment by Puppy-Love** [comment]
@garryyan 嗯，现在我们一个智能设备跑的Android系统，然后上面app用mars，断开了之后经常没法快速自动连接，有时候就等心跳好几分钟才能自动登录上去，设备又不像手机app 用户也没法主动请求数据，所以就经常一直干等心跳 然后再重连

**Comment by garryyan** [comment]
[这里](https://github.com/Tencent/mars/blob/master/mars/stn/src/longlink_connect_monitor.cc#L66) 可以根据需要自己改下重连间隔

**Comment by Puppy-Love** [comment]
@garryyan 默认重连间隔是多久？

**Comment by garryyan** [comment]
上面的链接里有重连间隔

**Comment by Puppy-Love** [comment]
static unsigned long const sg_interval[][5]  = {
    {5,  10, 20,  30,  300},
    {15, 30, 240, 300, 600},
    {0,  0,  0,   0,   0},
};
这个参数吗，不过我没看懂他这样写的含义
