### ISSUE TITLE
如何限制压缩包的大小？

### ISSUE THREAD

**Issue by ggt2077** [Tencent/mars#232]
为了安全，服务端做了限制，每个上传的压缩包不能超过1M，使用XLOG有没有对应的策略？

**Comment by garryyan** [comment]
对文件分片

**Comment by garryyan** [comment]
上传时对文件分片 而且现在 dev分支上支持单个文件多大之后分文件。

**Comment by ggt2077** [comment]
@garryyan 上传时对文件分片相关的api具体是在哪里？没找到啊

**Comment by garryyan** [comment]
上传时对xlog文件分片就相当于你对一个普通文件分片, 并不需要mars这里提供接口

**Comment by dabing1022** [comment]
@garryyan  使用dev分支代码测试发现，比如`appender_set_max_file_size(3 * 1024)`我将最大文件大小设置为3k大小，使用`[[NSFileManager defaultManager] attributesOfItemAtPath]`方法获取到到文件属性中到文件大小超过了3k，有5k，6k还有10k这样，好像对单个文件设置最大存储量有问题。可否帮忙分析下？

**Comment by garryyan** [comment]
写入之后再判断大小，如果：日志文件大小<3kb  日志文件大小+缓存的日志大小>3kb 这里如何取舍，dev上选用的方案是写之前检测大小，已经到达阀值就换文件 但是不考虑缓存的大小

**Comment by dabing1022** [comment]
这个特性有一定的作用，可考虑合并到master上呢？

**Comment by garryyan** [comment]
已经在内部灰度了，后续会合并到master上

**Comment by dabing1022** [comment]
（dev分支）在`appender.cc`的`__get_next_fileindex`计算存储文件序号方法中，有这么一段代码：
```c++
    if (!sg_cache_logdir.empty()) {
        logfilepath = sg_cache_logdir + "/" + last_filename;
        if (boost::filesystem::exists(logfilepath)) {
            filesize += boost::filesystem::file_size(logfilepath);
        }
    }
```
有一个`sg_cache_logdir`，于是我尝试使用`appender_open_with_cache`方法使用缓存，使得在存储文件序号计算的时候将cache计算上，但遇到了[https://github.com/Tencent/mars/issues/236](https://github.com/Tencent/mars/issues/236)问题。

@garryyan 非常感谢:]

**Comment by liverloopfirst** [comment]
单个文件分片，文件大小是否有最小值一说？
