### ISSUE TITLE
profile.rtt > timeout bug caused by receive size 1024 in the function SendHttpQuery at  httpquery.cc

### ISSUE THREAD

**Issue by lianshengzhang001** [Tencent/mars#234]
profile.rtt > timeout

check it,I find 
int SendHttpQuery(const std::string& _url, int& _status_code, std::string& _errmsg, int _timeout) {

...
if ((ret = tcpquery.tcp_receive(recv_autobuf, 1024/*HTTP_DUMMY_RECV_DATA_SIZE*/, (int)(_timeout - timeSpan4))) < 0) {
....
}

这里如果服务器返回的头信息小于1024，服务发送完头信息后，不会再有信息过来，那么socket recv loop不断select直至timeout耗尽，我设置timeout 1000ms,5000ms等到的rtt值都大于timeout。

**Comment by lianshengzhang001** [comment]
由于socket发送请求头信息后，没有办法知道服务器会返回多少信息，这个size是硬伤

**Comment by elviswoo** [comment]
这里的很多写法是不太好，已经在重构中，让检测更加实用一点。另外，这里其实有三个终止条件:1.svr close socket 2.timeout 3. recv size  > =1024

**Comment by lianshengzhang001** [comment]
期待，good job
