### ISSUE TITLE
异常断开

### ISSUE THREAD

**Issue by Puppy-Love** [Tencent/mars#237]
`[D][2017-05-23 +8.0 06:52:53.062][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 700][noopresp span:260
[V][2017-05-23 +8.0 07:02:53.160][18790, 18814][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[I][2017-05-23 +8.0 07:07:22.838][18790, 18812][mars::comm][alarm.cc, OnAlarm, 132][OnAlarm id:2768360800, seq:107, elapsed:870002

, `socketselect.cc, Clear, 117 是什么情况下导致断开的，五分钟了 才重连上去 中间五分钟啥日志都没有

**Comment by garryyan** [comment]
日志过少 看上下文日志

**Comment by Puppy-Love** [comment]
`6:52:52.796][18790, 18812][mars::comm][alarm.cc, OnAlarm, 132][OnAlarm id:2768360800, seq:104, elapsed:870005, after:870000, miss:5, android alarm:false, runing
[V][2017-05-23 +8.0 06:52:52.799][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[V][2017-05-23 +8.0 06:52:52.800][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 06:52:52.801][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 3000
[I][2017-05-23 +8.0 06:52:52.806][18790, 1*][MicroMsg.Alarm][, , 0][onReceive id=104, curId=104
[V][2017-05-23 +8.0 06:52:52.806][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +5, 
[I][2017-05-23 +8.0 06:52:52.807][18790, 1*][MicroMsg.Alarm][, , 0][onReceive find alarm id:104, pid:18790, delta miss time:15
[D][2017-05-23 +8.0 06:52:52.808][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 105, after= 10000, ret= true
[V][2017-05-23 +8.0 06:52:52.809][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +9, 
[I][2017-05-23 +8.0 06:52:52.809][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360696, after:10000, seq:105, po.reg.q:18446744072509678048,po.reg.s:0,po.s:377
[V][2017-05-23 +8.0 06:52:52.809][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartbeatStart, 64][-> OnHeartbeatStart 
[V][2017-05-23 +8.0 06:52:52.810][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartbeatStart, 64][<- OnHeartbeatStart +0, 
[V][2017-05-23 +8.0 06:52:52.810][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[D][2017-05-23 +8.0 06:52:52.811][18790, 18790*][mars::comm][OnAlarm.inl, Java_com_tencent_mars_comm_Alarm_onAlarm, 13][BroadcastMessage seq:104
[D][2017-05-23 +8.0 06:52:52.825][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 106, after= 870000, ret= true
[V][2017-05-23 +8.0 06:52:52.826][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +15, 
[I][2017-05-23 +8.0 06:52:52.826][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360800, after:870000, seq:106, po.reg.q:18446744072509678048,po.reg.s:0,po.s:378
[I][2017-05-23 +8.0 06:52:52.826][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 505][start noop taskid:4294967295, cmdid:65535,  last:(870000,870005), next:870000
[V][2017-05-23 +8.0 06:52:52.828][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][-> stopAlarm 
[D][2017-05-23 +8.0 06:52:52.835][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 59][id= 106, ret= true
[V][2017-05-23 +8.0 06:52:52.836][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][<- stopAlarm +7, 
[I][2017-05-23 +8.0 06:52:52.836][18790, 18814][mars::comm][alarm.cc, Cancel, 91][alarm cancel id:2768360800, seq:106, after:870000
[V][2017-05-23 +8.0 06:52:52.836][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[D][2017-05-23 +8.0 06:52:52.841][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 107, after= 870000, ret= true
[V][2017-05-23 +8.0 06:52:52.842][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +5, 
[I][2017-05-23 +8.0 06:52:52.843][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360800, after:870000, seq:107, po.reg.q:18446744072509678048,po.reg.s:0,po.s:381
[I][2017-05-23 +8.0 06:52:52.844][18790, 440][MarsServiceStub][, , 0][trafficData...send = 20, recv = 0
[V][2017-05-23 +8.0 06:52:52.845][18790, 18813][mars::stn][longlink_task_manager.cc, __OnSend, 579][-> __OnSend 
[V][2017-05-23 +8.0 06:52:52.846][18790, 18813][mars::stn][longlink_task_manager.cc, __OnSend, 579][<- __OnSend +0, 
[I][2017-05-23 +8.0 06:52:52.846][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 583][task socket send sock:32, all send:20, count:1, sub send taskid:4294967295, cmdid:65535, , len(S:20, 20/20), 
[V][2017-05-23 +8.0 06:52:53.053][18790, 18814][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[I][2017-05-23 +8.0 06:52:53.054][18790, 440][MarsServiceStub][, , 0][trafficData...send = 0, recv = 63
[I][2017-05-23 +8.0 06:52:53.054][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 670][task socket recv sock:32, recv len:63, buff len:63
[I][2017-05-23 +8.0 06:52:53.055][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 687][task socket recv sock:32, pack recv finish taskid:4294967295, cmdid:65535, , packlen:(63/63)
[I][2017-05-23 +8.0 06:52:53.055][18790, 18814][mars::stn][longlink.cc, __NoopResp, 285][end noop
[V][2017-05-23 +8.0 06:52:53.055][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][-> stopAlarm 
[D][2017-05-23 +8.0 06:52:53.058][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 59][id= 105, ret= true
[V][2017-05-23 +8.0 06:52:53.058][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][<- stopAlarm +3, 
[I][2017-05-23 +8.0 06:52:53.058][18790, 18814][mars::comm][alarm.cc, Cancel, 91][alarm cancel id:2768360696, seq:105, after:10000
[D][2017-05-23 +8.0 06:52:53.059][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartResult, 106][heart result:true, false
[V][2017-05-23 +8.0 06:52:53.059][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 06:52:53.059][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 500
[V][2017-05-23 +8.0 06:52:53.061][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +2, 
[D][2017-05-23 +8.0 06:52:53.062][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 700][noopresp span:260
[V][2017-05-23 +8.0 07:02:53.160][18790, 18814][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[I][2017-05-23 +8.0 07:07:22.838][18790, 18812][mars::comm][alarm.cc, OnAlarm, 132][OnAlarm id:2768360800, seq:107, elapsed:870002, after:870000, miss:2, android alarm:false, runing
[V][2017-05-23 +8.0 07:07:22.841][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[V][2017-05-23 +8.0 07:07:22.846][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 07:07:22.847][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 3000
[D][2017-05-23 +8.0 07:07:22.853][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 108, after= 10000, ret= true
[V][2017-05-23 +8.0 07:07:22.854][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +12, 
[I][2017-05-23 +8.0 07:07:22.854][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360696, after:10000, seq:108, po.reg.q:18446744072509678048,po.reg.s:0,po.s:387
[V][2017-05-23 +8.0 07:07:22.854][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartbeatStart, 64][-> OnHeartbeatStart 
[V][2017-05-23 +8.0 07:07:22.855][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartbeatStart, 64][<- OnHeartbeatStart +0, 
[V][2017-05-23 +8.0 07:07:22.855][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[I][2017-05-23 +8.0 07:07:22.855][18790, 1*][MicroMsg.Alarm][, , 0][onReceive id=107, curId=107
[I][2017-05-23 +8.0 07:07:22.856][18790, 1*][MicroMsg.Alarm][, , 0][onReceive find alarm id:107, pid:18790, delta miss time:19
[V][2017-05-23 +8.0 07:07:22.857][18790, 18812][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +10, 
[D][2017-05-23 +8.0 07:07:22.859][18790, 18790*][mars::comm][OnAlarm.inl, Java_com_tencent_mars_comm_Alarm_onAlarm, 13][BroadcastMessage seq:107
[D][2017-05-23 +8.0 07:07:22.865][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 109, after= 870000, ret= true
[V][2017-05-23 +8.0 07:07:22.866][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +10, 
[I][2017-05-23 +8.0 07:07:22.866][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360800, after:870000, seq:109, po.reg.q:18446744072509678048,po.reg.s:0,po.s:388
[I][2017-05-23 +8.0 07:07:22.867][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 505][start noop taskid:4294967295, cmdid:65535,  last:(870000,870002), next:870000
[V][2017-05-23 +8.0 07:07:22.871][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][-> stopAlarm 
[D][2017-05-23 +8.0 07:07:22.878][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 59][id= 109, ret= true
[V][2017-05-23 +8.0 07:07:22.878][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][<- stopAlarm +6, 
[I][2017-05-23 +8.0 07:07:22.878][18790, 18814][mars::comm][alarm.cc, Cancel, 91][alarm cancel id:2768360800, seq:109, after:870000
[V][2017-05-23 +8.0 07:07:22.878][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[D][2017-05-23 +8.0 07:07:22.882][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 49][id= 110, after= 870000, ret= true
[V][2017-05-23 +8.0 07:07:22.882][18790, 18814][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +3, 
[I][2017-05-23 +8.0 07:07:22.883][18790, 18814][mars::comm][alarm.cc, Start, 68][alarm id:2768360800, after:870000, seq:110, po.reg.q:18446744072509678048,po.reg.s:0,po.s:391
[I][2017-05-23 +8.0 07:07:22.883][18790, 440][MarsServiceStub][, , 0][trafficData...send = 20, recv = 0
[I][2017-05-23 +8.0 07:07:22.884][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 583][task socket send sock:32, all send:20, count:1, sub send taskid:4294967295, cmdid:65535, , len(S:20, 20/20), 
[V][2017-05-23 +8.0 07:07:22.884][18790, 18813][mars::stn][longlink_task_manager.cc, __OnSend, 579][-> __OnSend 
[V][2017-05-23 +8.0 07:07:22.884][18790, 18813][mars::stn][longlink_task_manager.cc, __OnSend, 579][<- __OnSend +0, 
[V][2017-05-23 +8.0 07:07:23.165][18790, 18814][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[I][2017-05-23 +8.0 07:07:23.166][18790, 440][MarsServiceStub][, , 0][trafficData...send = 0, recv = 64
[I][2017-05-23 +8.0 07:07:23.166][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 670][task socket recv sock:32, recv len:64, buff len:64
[I][2017-05-23 +8.0 07:07:23.166][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 687][task socket recv sock:32, pack recv finish taskid:4294967295, cmdid:65535, , packlen:(64/64)
[I][2017-05-23 +8.0 07:07:23.167][18790, 18814][mars::stn][longlink.cc, __NoopResp, 285][end noop
[V][2017-05-23 +8.0 07:07:23.167][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][-> stopAlarm 
[D][2017-05-23 +8.0 07:07:23.170][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 59][id= 108, ret= true
[V][2017-05-23 +8.0 07:07:23.170][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][<- stopAlarm +3, 
[I][2017-05-23 +8.0 07:07:23.170][18790, 18814][mars::comm][alarm.cc, Cancel, 91][alarm cancel id:2768360696, seq:108, after:10000
[D][2017-05-23 +8.0 07:07:23.170][18790, 18814][mars::stn][smart_heartbeat.cc, OnHeartResult, 106][heart result:true, false
[V][2017-05-23 +8.0 07:07:23.171][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 07:07:23.171][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 500
[V][2017-05-23 +8.0 07:07:23.174][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +3, 
[D][2017-05-23 +8.0 07:07:23.174][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 700][noopresp span:329
[V][2017-05-23 +8.0 07:07:23.174][18790, 18814][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[V][2017-05-23 +8.0 07:07:23.175][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.175][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.175][18790, 18814][mars::comm][platform_comm.cc, getCurSIMInfo, 260][-> getCurSIMInfo 
[V][2017-05-23 +8.0 07:07:23.175][18790, 18814][mars::comm][platform_comm.cc, getCurSIMInfo, 260][<- getCurSIMInfo +0, 
[W][2017-05-23 +8.0 07:07:23.176][18790, 18814][mars::stn][longlink.cc, __RunReadWrite, 497][task socket close sock:32, remote disconnect, net_type:46003task socket close getsocktcpinfo:tcpi_state=0x8， tcpi_ca_state=0x0， tcpi_retransmits=0x0， tcpi_probes=0x0， tcpi_backoff=0x0， tcpi_options=0x7， tcpi_rto=0x88b80， tcpi_snd_mss=0x500， tcpi_rcv_mss=0x218， tcpi_unacked=0x0， tcpi_sacked=0x0， tcpi_lost=0x0， tcpi_retrans=0x0， tcpi_fackets=0x0， tcpi_last_data_sent=0x136， tcpi_last_ack_sent=0x0， tcpi_last_data_recv=0xa， tcpi_last_ack_recv=0xa， tcpi_pmtu=0x5dc， tcpi_rcv_ssthresh=0x15630， tcpi_rtt=0x414ec， tcpi_rttvar=0xf424， tcpi_snd_ssthresh=0x7fffffff， tcpi_snd_cwnd=0xa， tcpi_advmss=0x5a8， tcpi_reordering=0x3， tcpi_rcv_rtt=0x0， tcpi_rcv_space=0x15630， tcpi_total_retrans=0x
[V][2017-05-23 +8.0 07:07:23.176][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][-> stopAlarm 
[D][2017-05-23 +8.0 07:07:23.180][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 59][id= 110, ret= true
[V][2017-05-23 +8.0 07:07:23.180][18790, 18814][mars::comm][platform_comm.cc, stopAlarm, 55][<- stopAlarm +3, 
[I][2017-05-23 +8.0 07:07:23.181][18790, 18814][mars::comm][alarm.cc, Cancel, 91][alarm cancel id:2768360800, seq:110, after:870000
[V][2017-05-23 +8.0 07:07:23.182][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.182][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.182][18790, 18814][mars::comm][platform_comm.cc, getSignal, 356][-> getSignal 
[V][2017-05-23 +8.0 07:07:23.184][18790, 18814][mars::comm][platform_comm.cc, getSignal, 363][Signal Strength= 0, wifi:false
[V][2017-05-23 +8.0 07:07:23.185][18790, 18814][mars::comm][platform_comm.cc, getSignal, 356][<- getSignal +2, 
[V][2017-05-23 +8.0 07:07:23.185][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.185][18790, 18814][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[I][2017-05-23 +8.0 07:07:23.185][18790, 18814][mars::stn][longlink.cc, __ConnectStatus, 321][connect status from:2 to:3, nettype:2
[I][2017-05-23 +8.0 07:07:23.186][18790, 18814][mars::stn][smart_heartbeat.cc, OnLongLinkDisconnect, 81][-> OnLongLinkDisconnect 
[I][2017-05-23 +8.0 07:07:23.186][18790, 18814][mars::stn][smart_heartbeat.cc, OnLongLinkDisconnect, 81][<- OnLongLinkDisconnect +0, 
[V][2017-05-23 +8.0 07:07:23.187][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[V][2017-05-23 +8.0 07:07:23.188][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 07:07:23.189][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 1000
[D][2017-05-23 +8.0 07:07:23.191][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 49][id= 111, after= 500, ret= true
[V][2017-05-23 +8.0 07:07:23.192][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +5, 
[I][2017-05-23 +8.0 07:07:23.192][18790, 18813][mars::comm][alarm.cc, Start, 68][alarm id:3095109352, after:500, seq:111, po.reg.q:18446744072509678048,po.reg.s:0,po.s:394
[V][2017-05-23 +8.0 07:07:23.192][18790, 18814][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +4, 
[V][2017-05-23 +8.0 07:07:23.193][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.193][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.193][18790, 18813][mars::stn][timing_sync.cc, OnLongLinkStatuChanged, 96][-> OnLongLinkStatuChanged 
[V][2017-05-23 +8.0 07:07:23.194][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.194][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[I][2017-05-23 +8.0 07:07:23.193][18790, 18814][mars::stn][longlink.cc, __Run, 350][<- __Run +28492089, 
[V][2017-05-23 +8.0 07:07:23.196][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 44][-> startAlarm 
[D][2017-05-23 +8.0 07:07:23.199][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 49][id= 112, after= 1800000, ret= true
[V][2017-05-23 +8.0 07:07:23.199][18790, 18813][mars::comm][platform_comm.cc, startAlarm, 44][<- startAlarm +3, 
[I][2017-05-23 +8.0 07:07:23.200][18790, 18813][mars::comm][alarm.cc, Start, 68][alarm id:3095120232, after:1800000, seq:112, po.reg.q:18446744072509678048,po.reg.s:0,po.s:398
[V][2017-05-23 +8.0 07:07:23.200][18790, 18813][mars::stn][timing_sync.cc, OnLongLinkStatuChanged, 96][<- OnLongLinkStatuChanged +6, 
[W][2017-05-23 +8.0 07:07:23.201][18790, 18813][mars::stn][longlink_task_manager.cc, __OnResponse, 511][task error, taskid:0, cmdid:0, error_type:4, error_code:-10090
[I][2017-05-23 +8.0 07:07:23.202][18790, 18813][mars::stn][longlink.cc, Disconnect, 218][_scene:10007
[D][2017-05-23 +8.0 07:07:23.204][18790, 18813][mars::stn][net_check_logic.cc, UpdateLongLinkInfo, 118][shortlink:_continueFailCount=0, _isTaskSucc=0, records=0xfffffffe
[D][2017-05-23 +8.0 07:07:23.204][18790, 18813][mars::stn][net_source.cc, ReportLongIP, 270][_is_success=false, ip=120.76.223.161, port=20000
[V][2017-05-23 +8.0 07:07:23.204][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.205][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.205][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.205][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.205][18790, 18813][mars::comm][platform_comm.cc, getCurSIMInfo, 260][-> getCurSIMInfo 
[V][2017-05-23 +8.0 07:07:23.205][18790, 18813][mars::comm][platform_comm.cc, getCurSIMInfo, 260][<- getCurSIMInfo +0, 
[I][2017-05-23 +8.0 07:07:23.689][18790, 18813][mars::comm][alarm.cc, OnAlarm, 132][OnAlarm id:3095109352, seq:111, elapsed:502, after:500, miss:2, android alarm:false, runing
[V][2017-05-23 +8.0 07:07:23.691][18790, 18813][mars::appcomm][com_tencent_mars_app_AppLogic_C2Java.cc, GetAccountInfo, 70][-> GetAccountInfo 
[I][2017-05-23 +8.0 07:07:23.691][18790, 439][MarsServiceStub][, , 0][getAccountInfo...com.tencent.mars.app.AppLogic$AccountInfo@148f16f5
[V][2017-05-23 +8.0 07:07:23.694][18790, 18813][mars::appcomm][com_tencent_mars_app_AppLogic_C2Java.cc, GetAccountInfo, 70][<- GetAccountInfo +2, 
[V][2017-05-23 +8.0 07:07:23.694][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.694][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.695][18790, 18813][mars::appcomm][com_tencent_mars_app_AppLogic_C2Java.cc, GetAccountInfo, 70][-> GetAccountInfo 
[I][2017-05-23 +8.0 07:07:23.695][18790, 439][MarsServiceStub][, , 0][getAccountInfo...com.tencent.mars.app.AppLogic$AccountInfo@148f16f5
[V][2017-05-23 +8.0 07:07:23.695][18790, 18813][mars::appcomm][com_tencent_mars_app_AppLogic_C2Java.cc, GetAccountInfo, 70][<- GetAccountInfo +0, 
[V][2017-05-23 +8.0 07:07:23.696][18790, 18813][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[V][2017-05-23 +8.0 07:07:23.697][18790, 18813][mars::comm][socketselect.cc, Clear, 117][Ret=-1
[I][2017-05-23 +8.0 07:07:23.697][18790, 18813][mars::stn][longlink_connect_monitor.cc, __IntervalConnect, 179][made interval connect interval:30000, posttime:28492583, newone:true, connectstatus:0
[V][2017-05-23 +8.0 07:07:23.698][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.699][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[I][2017-05-23 +8.0 07:07:23.699][18790, 6192][mars::stn][longlink.cc, __Run, 350][-> __Run LongLink Rebuild span:0, net:2
[V][2017-05-23 +8.0 07:07:23.700][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.700][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.700][18790, 6192][mars::comm][platform_comm.cc, getCurSIMInfo, 260][-> getCurSIMInfo 
[V][2017-05-23 +8.0 07:07:23.700][18790, 6192][mars::comm][platform_comm.cc, getCurSIMInfo, 260][<- getCurSIMInfo +0, 
[V][2017-05-23 +8.0 07:07:23.701][18790, 6192][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][-> wakeupLock_Lock_Timeout 
[V][2017-05-23 +8.0 07:07:23.701][18790, 6192][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 432][_object= 0x1004AA, _timeout= 30000
[V][2017-05-23 +8.0 07:07:23.707][18790, 6192][mars::comm][platform_comm.cc, wakeupLock_Lock_Timeout, 429][<- wakeupLock_Lock_Timeout +6, 
[V][2017-05-23 +8.0 07:07:23.707][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.708][18790, 6192][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[I][2017-05-23 +8.0 07:07:23.708][18790, 6192][mars::stn][longlink.cc, __ConnectStatus, 321][connect status from:0 to:1, nettype:2
[V][2017-05-23 +8.0 07:07:23.708][18790, 6192][mars::comm][dns.cc, GetHostByName, 181][-> GetHostByName 
[V][2017-05-23 +8.0 07:07:23.709][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][-> getNetInfo 
[V][2017-05-23 +8.0 07:07:23.709][18790, 18813][mars::comm][platform_comm.cc, getNetInfo, 115][<- getNetInfo +0, 
[V][2017-05-23 +8.0 07:07:23.710][18790, 18813][mars::stn][timing_sync.cc, OnLongLinkStatuChanged, 96][-> OnLongLinkStatuChanged 
[V][2017-05-23 +8.0 07:07:23.710][18790, 18813][mars::stn][timing_sync.cc, OnLongLinkStatuChanged, 96][<- OnLongLinkStatuChanged +0, 
[I][2017-05-23 +8.0 07:07:23.710][18790, 18813][mars::stn][net_core.cc, __ConnStatusCallBack, 696][reportNetConnectInfo all_connstatus:3, longlink_connstatus:3`

**Comment by garryyan** [comment]
task socket close sock:32, remote disconnect   服务器主动关闭了连接

**Comment by Puppy-Love** [comment]
@garryyan 多谢，半天没看出来问题，同一个设备ID  另外一个设备登录了，把我这个挤掉了，所以服务器异常断开了
