### ISSUE TITLE
xlog 本地编译so 日志未压缩

### ISSUE THREAD

**Issue by liveei** [Tencent/mars#241]
本地编译步骤:
1. cd 工程libraries目录
2. 命令行 python build_android.py
3. 选择4. build xlog shared libs.
4. 选择1. armeabi
5. mars_xlog_sdk\libs\armeabi 及mars_xlog_sdk\src拷贝至自有工程 

![xlog1](https://cloud.githubusercontent.com/assets/14347633/26628165/92b5f220-462f-11e7-8e15-b67e3a1d70ba.png)

如图, 日志未压缩, 不知道是否是我漏了什么设置?

**Comment by garryyan** [comment]
你这里是显示的哪里的日志？控制台还是文件里的？ 如果是文件里的 检查下是否是同步了， 同步写不压缩

**Comment by liveei** [comment]
文件日志, 果然异步就压缩了,谢谢~
另外有个问题想请教一下appenderFlush(true) 之后立即读取文件 好像最后一次的日志读取不到,
但是appenderClose() 就可以   请问 appenderFlush(true) 、appenderFlush(false) 和 appenderClose() 有什么区别呢？

**Comment by liveei** [comment]
好的，谢谢，六一嗨皮~
