### ISSUE TITLE
x86平台编译失败

### ISSUE THREAD

**Issue by Billchen28** [Tencent/mars#243]
jni/../export/crypto/openssl_multi_thread_support.cpp:56: error: undefined reference to 'CRYPTO_set_locking_callback'
jni/../export/crypto/openssl_multi_thread_support.cpp:57: error: undefined reference to 'CRYPTO_num_locks'
jni/../export/crypto/openssl_multi_thread_support.cpp:64: error: undefined reference to 'CRYPTO_free'
jni/../export/crypto/openssl_multi_thread_support.cpp:66: error: undefined reference to 'CRYPTO_free'
jni/../export/crypto/openssl_multi_thread_support.cpp:36: error: undefined reference to 'CRYPTO_num_locks'
jni/../export/crypto/openssl_multi_thread_support.cpp:36: error: undefined reference to 'CRYPTO_malloc'
jni/../export/crypto/openssl_multi_thread_support.cpp:37: error: undefined reference to 'CRYPTO_num_locks'
jni/../export/crypto/openssl_multi_thread_support.cpp:37: error: undefined reference to 'CRYPTO_malloc'
jni/../export/crypto/openssl_multi_thread_support.cpp:39: error: undefined reference to 'CRYPTO_num_locks'
jni/../export/crypto/openssl_multi_thread_support.cpp:49: error: undefined reference to 'CRYPTO_set_locking_callback'
jni/../export/crypto/openssl_multi_thread_support.cpp:17: error: undefined reference to 'CRYPTO_thread_id'

**Comment by garryyan** [comment]
感谢提醒，openssl的x86库没有编译，我们解决一下

**Comment by garryyan** [comment]
71ad5b7dc425e8f09acd18037dc00d4559702cb3  已解决，下载master最新代码
