### ISSUE TITLE
建议：gradle依赖的so包，按不同的平台分开提供不同的gradle

### ISSUE THREAD

**Issue by wangrunxiang** [Tencent/mars#244]
比如 
compile 'com.wangrunxiang.xxx:xxx-java:0.8.0'
compile 'com.wangrunxiang.xxx:xxx-armeabi:0.8.0'
compile 'com.wangrunxiang.xxx:xxx-armv7a:0.8.0'
compile 'com.wangrunxiang.xxx:xxx-arm64:0.8.0'
compile 'com.wangrunxiang.xxx:xxx-x86:0.8.0'
compile 'com.wangrunxiang.xxx:xxx-x86_64:0.8.0'

**Comment by garryyan** [comment]
这是一种办法，但考虑到其实大部分人不会直接用jcenter上的库，而是自己定制编译。所以目前jcenter上的库的定位是测试和尝鲜。

**Comment by wangrunxiang** [comment]
@garryyan 不会的，大部分人是不会去改源码的，只是使用而已

**Comment by ZhanRu** [comment]
> @garryyan 不会的，大部分人是不会去改源码的，只是使用而已

是的 大部分人都是直接用..
