### ISSUE TITLE
单独编译xlog工程失败，打不出so包

### ISSUE THREAD

**Issue by HarrisonLin** [Tencent/mars#245]
单独编译xlog工程， ndk-build失败， 对ndk版本有特定要求吗？

![image](https://user-images.githubusercontent.com/10679283/26916768-2a1abfa4-4c5e-11e7-8b3a-bc1527a06ae5.png)

我用的是libraries中的python build_android.py 来打的。

**Comment by ifinver** [comment]
请问这个怎么解决的啊？我现在也是这个问题

**Comment by garryyan** [comment]
@ifinver  #289

**Comment by ifinver** [comment]
谢谢
