### ISSUE TITLE
xlog 组件如何写入自定义log 信息

### ISSUE THREAD

**Issue by misty-rain** [Tencent/mars#247]
请问，在Xlog 组件中 ，如何将自定义的log 信息写入到本地的xlog 文件中？ 如果有的话 ，方法名是什么？ 谢谢！

**Comment by garryyan** [comment]
自定义log信息是什么意思?意思是自定义格式吗？能否给一个例子

**Comment by misty-rain** [comment]
对的 ，现在默认生成xlog文件，不是有头部 尾部的生成的信息 如~~~~~ begin of mmap ~~~~~ del time out files time: 0  ~~~~~ end of mmap ~~~~~[28715,28715][2017-06-09 +0800 11:10:20] ， 我尝试着将mars\log\src 目录下的format.cc 文件中 定义格式的修改，移除掉默认生成的部分，重新生成so 后！ 发现，没有作用！  请问，这是什么问题导致的，是修改的不对 还是 需要执行其他命令，才能生效？

**Comment by garryyan** [comment]
~~~~~ begin of mmap ~~~~~ del time out files time: 0 ~~~~~ end of mmap ~~~~~[28715,28715][2017-06-09 +0800 11:10:20]   这一块是在appender.cc里面的。
format.cc 只是格式化单条日志的格式

**Comment by garryyan** [comment]
这些常量没太大必要修改

**Comment by MartinLi2015** [comment]
我这边也想把额外生成的信息剔除，不知需要修改哪块源码呢

**Comment by EthanCo** [comment]
可以看我的博客 https://blog.csdn.net/EthanCo/article/details/104378841
