### ISSUE TITLE
iOS的例子 notifyUIWithResponse 回调 没有在主线程更新 UI

### ISSUE THREAD

**Issue by BoydYang** [Tencent/mars#25]
修改后的
MessageItemsController

- (int)notifyUIWithResponse:(NSData*)responseData {
    
    ConversationListResponse *convlstResponse = [ConversationListResponse parseFromData:responseData];
    self->converSations = convlstResponse.list;
    LOG_INFO(kModuleViewController, @"recv conversation list, size: %lu", (unsigned long)[self->converSations count]);
    
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        
        [self.tableView reloadData];
        
    }];
    return [self->converSations count] > 0 ? 0 : -1;

}

TopicViewController

-(int)notifyUIWithResponse:(NSData*)responseData {
    SendMessageResponse *sendMsgResponse = [SendMessageResponse parseFromData:responseData];
    
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        
        if (sendMsgResponse.errCode == 0 ) {
            [_recvContentField setText:sendMsgResponse.text];
        }
        else{
            [_recvContentField setText:sendMsgResponse.errMsg];
        }
        
    }];
    
    
    return sendMsgResponse.errCode == 0 ? 0 : -1;
}

**Comment by shockcao** [comment]
thanks  这里遗漏了   我修改后提交一下

**Comment by BoydYang** [comment]
textField 的位置也建议往上调一下，被键盘挡住了

**Comment by shockcao** [comment]
@BoydYang 可以提pull request，demo目前我们是为了保证mars可用性提供的，demo UI我们这里适配会有时间上的困难 谢谢理解

**Comment by garryyan** [comment]
#48
