### ISSUE TITLE
Android XlogSamples  Android.mk error 

### ISSUE THREAD

**Issue by MerlinYu** [Tencent/mars#252]
![image](https://user-images.githubusercontent.com/16703169/27416441-2270f664-5740-11e7-9bbc-45503acdeda2.png)

**Comment by garryyan** [comment]
[请仔细阅读wiki](https://github.com/Tencent/mars/wiki/Mars-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%89%93%E5%BC%80-xlog-%E7%9A%84-sample-%E6%8A%A5libmarsxlogso-exists-or-that-its-paths-is-correct)
