### ISSUE TITLE
xlogSample 工程编译出错

### ISSUE THREAD

**Issue by lxz2014** [Tencent/mars#253]
1. 刚开始报下面截图错误
![image](https://user-images.githubusercontent.com/8327268/27476182-4b3813de-583a-11e7-9027-72dc4569bdf7.png)

最后看issues有类似错误，改了，注释掉 path "src/main/jni/Android.mk"

2. 发起之前错误不报了，但又出现下面错误
![image](https://user-images.githubusercontent.com/8327268/27476245-8eeb83ea-583a-11e7-9226-0d51489610ca.png)

最后百度查了下，在 gradle.properties 中添加
android.useDeprecatedNdk=true 屏蔽了之前的错误，

3. 再次编译后发现还是有错误，
![image](https://user-images.githubusercontent.com/8327268/27476309-d8b740a4-583a-11e7-90f7-de5727cac8b1.png)

最后实在是找不到原因了，求救大神了

**Comment by garryyan** [comment]
ndk路径没配置
