### ISSUE TITLE
mars限制传输字符串的长度是多少？？

### ISSUE THREAD

**Issue by fuzi4it** [Tencent/mars#255]
mars限制传输字符串的长度是多少？？

**Comment by garryyan** [comment]
mars不限制大小的，但是建议在64kb以内

**Comment by fuzi4it** [comment]
但是，我在实际测试过程中(Android版本的marsSampleChat，服务器是阿里云)，很长的字符串是发不出的(比如500个汉字)，这个是怎么回事？

**Comment by garryyan** [comment]
可能sample那里有限制，你查下日志，看失败在什么地方
