### ISSUE TITLE
我用 xlog 为什么只有app在第一次启动的时候才能打印

### ISSUE THREAD

**Issue by wangjinyu** [Tencent/mars#256]
使用异步模式，同步模式就没有这个问题

**Comment by garryyan** [comment]
异步模式有个刷新到文件的时机，你可以多等一段时间。或者打多一点日志再看效果

**Comment by wangjinyu** [comment]
<img width="990" alt="2017-06-27 11 18 08" src="https://user-images.githubusercontent.com/3033623/27569453-529b786c-5b2a-11e7-9517-0c27514db783.png">
![2017-06-27 11 17 24](https://user-images.githubusercontent.com/3033623/27569457-5975c84a-5b2a-11e7-9e26-fd6215929fbf.png)

这是我昨天运行的程序。到今天看还是，只有这么几行。我打印的是1000行的log

**Comment by garryyan** [comment]
1. 调用appender_open初始化了吗？ 
2. 看是否打到了别的日志文件里
3. 把控制台日志打开，看控制台是否输出了

**Comment by wangjinyu** [comment]
<img width="990" alt="2017-06-27 11 18 08" src="https://user-images.githubusercontent.com/3033623/27569584-e459501c-5b2a-11e7-9d1c-c2cc4bcfcddc.png">

**Comment by wangjinyu** [comment]
![2017-06-27 11 17 24](https://user-images.githubusercontent.com/3033623/27569595-f1bc736a-5b2a-11e7-801c-ebc3c4665331.png)

**Comment by wangjinyu** [comment]
这是log 文件解析出来的内容。控制台是有输出的

**Comment by wangjinyu** [comment]
<img width="1061" alt="2017-06-27 11 23 01" src="https://user-images.githubusercontent.com/3033623/27569623-13026430-5b2b-11e7-988b-ee9c0211cdb9.png">

这是 xlog的初始化方法

**Comment by garryyan** [comment]
看你贴的日志，不是打出来了么？

**Comment by wangjinyu** [comment]
是打出来了，但是只到 15, 我打印的是 0 - 999的log

**Comment by garryyan** [comment]
是你的demo吗 方便发给我么？

**Comment by wangjinyu** [comment]
可以 邮箱？？？

**Comment by garryyan** [comment]
1173828173@qq.com

**Comment by wangjinyu** [comment]
发给你了， 邮箱是 jinyu.wang@speedx.com

**Comment by wangjinyu** [comment]
需要我把 修改后的 mars源码也发给你吗

**Comment by garryyan** [comment]
我需要拿到可以直接运行的项目

**Comment by wangjinyu** [comment]
解压出来就能运行了啊

**Comment by wangjinyu** [comment]
发给你了，在查看下邮件

**Comment by garryyan** [comment]
修改后的xlog的源码也发给我

**Comment by garryyan** [comment]
start_witn_mmap 这个代码改的有问题，先验证代码改之前是否有问题

        if (buffer.Ptr()) {
            __writetips2file("~~~~~ begin of mmap ~~~~~\n");
            __log2file(buffer.Ptr(), buffer.Length());
            __writetips2file("~~~~~ end of mmap ~~~~~%s\n", mark_info);
        }
        
这一块是必须的，防止丢日志需要用的

**Comment by wangjinyu** [comment]
已经解决， 谢谢~~
