### ISSUE TITLE
本地编译时失败

### ISSUE THREAD

**Issue by chwnFlyPig** [Tencent/mars#260]
error: use of undeclared identifier 'pthread_mutex_lock_timeout_np'
        ret = pthread_mutex_lock_timeout_np(&mutex_, (unsigned)_millisecond);
怎么改？

**Comment by garryyan** [comment]
使用的ndk是什么版本，请仔细阅读wiki，使用ndk-r11c

**Comment by chwnFlyPig** [comment]
ndk 15的，通过studio下的，没得选，勾选了ndk，就下了。

**Comment by garryyan** [comment]
不要用studio编译，用我们提供的脚本。看wiki
