### ISSUE TITLE
初始化xlog时崩溃

### ISSUE THREAD

**Issue by Quincy-QC** [Tencent/mars#261]
在项目中集成xlog时，在如下位置崩溃了：
在调用`appender_open(kAppednerAsync, [logPath UTF8String], "demo")`的时候, 
```
void lock() {
    ASSET(!islocked_);
    if (!islocked_ && mutex_.lock()) {   // 在这里崩溃了
        islocked_ = true;
    }
    ASSERT(islocked_);
}
```

集成方式之前通过demo使用过，并没有问题，但是集成到正式项目就在 ::lock() 这里崩溃了，请问可能是什么原因导致的呢？

**Comment by garryyan** [comment]
什么平台

**Comment by Quincy-QC** [comment]
iOS

**Comment by garryyan** [comment]
贴详细信息。  应该是因为有同名的类导致的，看看项目中有没有同名的 Mutex

**Comment by sj1910** [comment]
<img width="1278" alt="f75c8c2e669a04e4a304b645c33a99d5" src="https://user-images.githubusercontent.com/19926316/27821054-77a3efb4-60d3-11e7-9141-3f0d90134169.png">

**Comment by Quincy-QC** [comment]
就上图的报错，我这边图片上传有问题，借我同事的传的，请问这个该怎么解决呢？

**Comment by garryyan** [comment]
不在现场很难看出来，看看项目中有没有同名的 Mutex。  还有看看demo和你们项目的区别

**Comment by Quincy-QC** [comment]
<img width="487" alt="1c48b477-a9cb-437e-ad54-149fecfb0175" src="https://user-images.githubusercontent.com/18659596/27821312-6bf3a794-60d4-11e7-8a28-dbf6e48b158c.png">

这边我引入了这些库 可能会有冲突的吗？

**Comment by garryyan** [comment]
是 猜测和其中一个sdk中的同名。可以试着移除一下 一个个的排除

**Comment by Quincy-QC** [comment]
恩好 我先试试吧 谢谢！

**Comment by Quincy-QC** [comment]
我这边排除了下，确实是和高德地图发生了冲突，那我该怎么解决这个冲突呢，还是只能选择使用其中之一？

**Comment by garryyan** [comment]
你暂时可以把我们的加上namespace或者改一个类名。

**Comment by Quincy-QC** [comment]
这边崩溃的文件是lock.h，但是我定位不到这个文件，那我应该怎么修改才好？

**Comment by garryyan** [comment]
在mars的源码里有这个文件的。
