### ISSUE TITLE
xlog打印文件会少一行日志，源码直接编译的没有改动

### ISSUE THREAD

**Issue by wangjinyu** [Tencent/mars#262]
我打印的日志是 从 0 ~ 9可是日志文件里边只打印到 8. qing请问下这是什么原因呢

<img width="1378" alt="2017-07-05 18 15 00" src="https://user-images.githubusercontent.com/3033623/27860159-e39eeb12-61ad-11e7-8d8c-eba89a6f951f.png">

这是xlog文件解析出来的日志
<img width="1096" alt="2017-07-05 18 14 41" src="https://user-images.githubusercontent.com/3033623/27860209-27e03ae2-61ae-11e7-9204-3f22fee94f1b.png">

这是 git log信息
![2017-07-05 18 16 25](https://user-images.githubusercontent.com/3033623/27860229-3a2c3034-61ae-11e7-9d64-6814e354c802.png)

**Comment by garryyan** [comment]
appender_open的时候模式同步还是异步？如果是异步，可能缓存在mmap文件里

**Comment by wangjinyu** [comment]
同步的

**Comment by garryyan** [comment]
打完日志 调用一下 appender_sync试试

**Comment by wangjinyu** [comment]
<img width="419" alt="2017-07-05 18 22 22" src="https://user-images.githubusercontent.com/3033623/27860369-e809a13c-61ae-11e7-83c5-eea32eaa1e1b.png">
还是不管用

**Comment by wangjinyu** [comment]
用二进制查看，mmap2文件中的所有数据都是0

**Comment by garryyan** [comment]
代码打包发 1173828173@qq.com

**Comment by wangjinyu** [comment]
我直接用的官方代码打的 framework

**Comment by garryyan** [comment]
上层demo代码我看看，如果方便的话

**Comment by wangjinyu** [comment]
已发送

**Comment by garryyan** [comment]
调用一下appender_close 。  文件还没关闭，最后的日志在系统缓存里并没有刷到磁盘上

**Comment by garryyan** [comment]
还有 你用XLoggerInfo的时候 memset成0 。 那是个结构体，没有构造函数

**Comment by wangjinyu** [comment]
好了。谢谢啦
