### ISSUE TITLE
shortlink 多端口问题 

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#265]
在短连接获取IP和端口后，如果是多端口，那么会将ip和端口进行混合产生多个ip-port，但是在进行复合建连的时候，却始终使用第一个ip-port中的port作为连接端口，如下图中的代码。这里应该改为当前item的port才对吧？

![dingtalk20170710112838](https://user-images.githubusercontent.com/10632522/28001902-092b7996-6563-11e7-89af-24248a9781eb.png)

**Comment by garryyan** [comment]
这里短连其实目前我们只用80的，因为是把短连当做http的。
