### ISSUE TITLE
xlog文件大小限制

### ISSUE THREAD

**Issue by Quincy-QC** [Tencent/mars#266]
你好，现在我需要对单个xlog文件进行大小限制；
然后，我调用了`appender_set_max_file_size(120 * 1024);`这个方法，文件是进行了分片处理，但是文件的具体代销并没有根据我写的进行大小处理。我试了几个参数，都是51k、102k、154k，差不多都是50k的倍数；
请问，这个限制文件大小的方法是不能精确的吗，或者我少调用了什么方法，还是和xlog的缓存机制有关系？

**Comment by garryyan** [comment]
写进文件之后才开始判断是否超过大小的。没那么精确的。

**Comment by Quincy-QC** [comment]
这边我开始设了几个参数，发现都是以50k的倍数为界限，比如我设置了5k和50k，但是文件分割大小都是以50k为大小分割，如果是50-100k，就是以100k为大小分割；以此类推；
这个是为什么？（这边我是直接打开文件保存的路径查看的文件同时写入文件，然后发现会自动生成50k倍数的限制文件；如果是一个文件的话，是不会生成文件的）

**Comment by garryyan** [comment]
因为本身我们是有个缓存的，满50kb才会写进文件

**Comment by Quincy-QC** [comment]
是的，如果那个缓存当时超过了50k，同时我设置的是`appender_set_max_file_size(5 * 1024)`，那么生成的文件就会是50k分片大小；
是不是说`appender_set_max_file_size `这个方法，需要xlog自动进行的文件写入，而不是文件缓存溢出时文件的写入，才能实现具体的分片大小？

**Comment by garryyan** [comment]
没明白你的意思，不过这个接口会有一个缓存大小的误差范围。

**Comment by Quincy-QC** [comment]
恩，好，谢谢！

**Comment by yylyingy** [comment]
文件大小限制很小时(比如50k以内)可以修改kBufferBlockLength的值为sg_max_file_size的3倍，这样会比较准；如果设置的文件大小限制比较大时(比如超过150k)，只设置sg_max_file_size的值的话误差最大应该不超过50k
