### ISSUE TITLE
有关xlogger的tag问题

### ISSUE THREAD

**Issue by kinglezhuang** [Tencent/mars#268]
您好，我最近也在熟读mars代码，我在看log的时候有一点不太明白，xlogger打印的时候有一个tag，能按名称空间打印（比如mars::stn, mars::comm），我调试的时候看不到从哪里传进来，但是我看XLOGGER_TAG只有定义一个空的，这个是怎么实现的

**Comment by kinglezhuang** [comment]
终于看到了，在工程定义了

**Comment by garryyan** [comment]
对的  ios在项目文件定义的，android 在mk文件中定义的
