### ISSUE TITLE
 SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by SmallerRui** [Tencent/mars#270]
#00 pc 0001755c /system/lib/libc.so (memcpy+84) [armeabi-v7a]
--
2 #01 pc 0001f717 /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
3 #02 pc 0002051d /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
4 #03 pc 00020849 /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
5 #04 pc 0001f325 /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
6 #05 pc 0001c32f /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
7 #06 pc 00047983 /system/lib/libc.so (__pthread_start(void*)+22) [armeabi-v7a]
8 #07 pc 00019efd /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

线上版本，只有华为P10出现过一次。

**Comment by garryyan** [comment]
麻烦提供ndk-stack或者addr2line出来的堆栈，最好提供当时的上下文xlog日志
