### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by SmallerRui** [Tencent/mars#271]
#00 pc 00049128 /system/lib/libc.so (__rt_sigprocmask+12) [armeabi-v7a]
--
2 #01 pc 0001e1c5 /system/lib/libc.so (sigprocmask+48) [armeabi-v7a]
3 #02 pc 0000217b /system/bin/app_process32 (sigprocmask+106) [armeabi-v7a]
4 #03 pc 0001949b /system/lib/libc.so (__libc_android_abort+28) [armeabi-v7a]
5 #04 pc 000170e4 /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 0005f2a9 /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
7 #06 pc 0005fccd /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
8 #07 pc 0004cca1 /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
9 #08 pc 0001c32f /data/app/com.xx.xx-1/lib/arm/libmarsstn.so [armeabi-v5te]
10 #09 pc 00047983 /system/lib/libc.so (__pthread_start(void*)+22) [armeabi-v7a]
11 #10 pc 00019efd /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

线上版本，出现次数较多

**Comment by garryyan** [comment]
麻烦提供 ndk-stack 或者 addr2line 出来的堆栈，最好提供当时的上下文 xlog 日志
