### ISSUE TITLE
接了mars后开启Log功能，碰到很多如下Native Crash

### ISSUE THREAD

**Issue by guoguo338** [Tencent/mars#273]
比较奇怪的native crash，由于都是系统的unicode库，未能找到symbols。接了mars做Log功能后，线上大面积native 崩溃，将XLog关掉后，crash全没了。不知道腾讯这边有没有碰到过？ Natvie Crash如下：

libc.so + 0x4a940
libart.so + 0x1f5555
libart.so + 0x2f892e
libart.so + 0x306a36
libicuuc.so + 0x7e3e9
libicuuc.so + 0x7e407
libicui18n.so + 0xe2189
libicui18n.so + 0x15a396
libicui18n.so + 0xe2443
libicui18n.so + 0x15a396
libicui18n.so + 0xe2463
libart.so + 0xa37b9
libc.so + 0x426f1
libc.so + 0x50095
libc.so + 0x4bd5b
libart.so + 0xa36b7
libart.so + 0x1e5b37
libc.so + 0x4bd5b
libart.so + 0x2205f5
libart.so + 0x21a551
libart.so + 0x252e59
libart.so + 0x294fd9
libart.so + 0x2384a5
libart.so + 0x307b3e
libart.so + 0x2ca9ae
libart.so + 0x2ca012
libart.so + 0x2ca9ae
libc.so + 0x1a5f3
libc.so + 0x1716f
libc.so + 0x1718f
libc.so + 0x1716f
libc.so + 0x1716f
libc.so + 0x1517f

**Comment by garryyan** [comment]
我们这边没有类似的问题

**Comment by MerlinYu** [comment]
@guoguo338 你们是怎么解决这种系统库挂掉的问题的？

**Comment by garryyan** [comment]
我们没遇到过这种问题。

**Comment by guoguo338** [comment]
还没时间看。打算不用mars了

**Comment by MerlinYu** [comment]
遇到两个系统 libicuuc.so ，libicui18n.so挂掉的问题
