### ISSUE TITLE
iOS9 省电模式在前台长连接不会断开，发包成功但是收回包超时

### ISSUE THREAD

**Issue by brucewangzhihua** [Tencent/mars#274]
task first-pkg timeout taskid:5,  nStartSendTime=1760286, nfirstpkgtimeout=12

**Comment by garryyan** [comment]
请详细描述场景：是一直在前台？还是后台切换到的前台？

**Comment by brucewangzhihua** [comment]
我获取问题的日志看是一直在前台。这个问题可以通过手动设置省电模式复现，我再确认一下。


原始邮件
发件人:garryyannotifications@github.com
收件人:Tencent/marsmars@noreply.github.com
抄送:brucewangzhihuabrucewang@vip.qq.com; Authorauthor@noreply.github.com
发送时间:2017年7月24日(周一) 11:27
主题:Re: [Tencent/mars] iOS9 省电模式在前台长连接不会断开，发包成功但是收回包超时 (#274)


请详细描述场景：是一直在前台？还是后台切换到的前台？
