### ISSUE TITLE
请教一个关于appender里面的细节技术问题

### ISSUE THREAD

**Issue by SatanWoo** [Tencent/mars#276]
在appender.cc 的`append_open`代码里面有这样一段代码：
```
if (NULL == sg_log_buff->GetData().Ptr()) {
        if (use_mmap && sg_mmmap_file.is_open())  CloseMmapFile(sg_mmmap_file);
        return;
}
```
从字面意思来看，就是说如果mmap成功了，但是映射到了`NULL`对应的地址上，所以就相当于初始化配置失败了，直接返回吗？

如果是这样的话，那后续`xlogger_appender`这个函数接口，一直往`append_async` -> `LogBuffer.write` -> `PtrBuffer.write`。

那这样的话，岂不是添加日志就会挂在`PtrBuffer.write`的assert断言里？

**Comment by garryyan** [comment]
看上面的 if else 分支，如果 mmap 失败则映射内存作为缓冲区。 
不管哪种方式，最终的 buffer 中没有可用的缓冲区，则直接返回。 这里返回并不会导致日志写到断言里，因为有sg_log_close 控制着，写不进去日志

**Comment by SatanWoo** [comment]
哈哈，抱歉，是看错了，一开始看成`sg_log_close`以为默认是`false`，结果是`true`。ok，那就没问题啦，谢谢。
