### ISSUE TITLE
请问下安卓下如何控制log回写到文件里？

### ISSUE THREAD

**Issue by chxchen** [Tencent/mars#277]
文章中指出
mmap 既不会丢日志，回写时机对我们来说又基本可控。 mmap 的回写时机：
· 内存不足
· 进程 crash
· 调用 msync 或者 munmap
· 不设置 MAP_NOSYNC 情况下 30s-60s(仅限FreeBSD)
对mmap不是很了解，能否指教下如何调用 msync 或者 munmap实现回写吗？
因为我们远程的客户端遇到问题后，我们是主动去拉取机器中的log，有时候拉取的时候发现出问题时的log并没有回写到文件中。（有时候等待很久很久才有相关记录）

**Comment by garryyan** [comment]
仔细阅读wiki中的接口说明。 可以调用 appenderSync 来刷到文件中

**Comment by chxchen** [comment]
是appenderFlush(boolean isSync) 这个方法吗？当初阅读说明的时候的确没有太仔细，抱歉。我测试下

**Comment by garryyan** [comment]
是的
