### ISSUE TITLE
dnsquery内部数组越界写

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#278]
在 mars/mars/sdt/src/checkimpl/dnsquery.cc 中，存在着数组越界写操作的问题。如下：

![dingtalk20170731164025](https://user-images.githubusercontent.com/10632522/28769673-0c71d3ea-760f-11e7-80d5-c540bf6eac40.png)

另外，这里面同一代码块调用 ntohs(_answers[i].resource->data_len) 过多，建议用临时变量暂存，避免频繁调用ntohs

**Comment by elviswoo** [comment]
这里确实是存在越界写操作，尽快修复

**Comment by wosshzhb** [comment]
怎么感觉这部分还没有修复？

**Comment by garryyan** [comment]
内部已经更改，但由于不算严重的问题，准备和其他特性一起合并

**Comment by wosshzhb** [comment]
好的，谢谢

**Comment by garryyan** [comment]
越界的问题 fixed in 66d669348b4cbd930818c60f8cba6715ce5073db.
至于你说的同一代码块调用 ntohs(_answers[i].resource->data_len) 过多，建议用临时变量暂存，避免频繁调用 ntohs，这里暂时不打算修改，因为后续可能对这一块进行比较大的重构

**Comment by wosshzhb** [comment]
好的，谢谢
