### ISSUE TITLE
android 环境下进行加密，加密未生效

### ISSUE THREAD

**Issue by huangdh2** [Tencent/mars#279]
在上层调用了jni方法appenderOpen，传入了publicKey，但是直接使用decode_mars_nocrypt_log_file.py脚本把文件解压出来了，也就是加密无效了。

**Comment by garryyan** [comment]
对，说明你的 key 是无效的 key。你的 key 怎么生成的？

**Comment by huangdh2** [comment]
异步加密是成功的，同步加密的话失败，使用同一套秘钥对。同步加密的文件可以直接用notepad打开，前一段内容为乱码，后面为明文。
类似下面这种情况
Q   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱚^^^^^^^^^Aug  3 2017^^^14:42:26^^^^^^^^^^[2715,2715][2017-08-04 +0800 10:24:30]
   

   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱠el time out files time: 0
   

   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱣et mmap time: 22
   

   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱉ARS_URL: mars-master/mars
   

   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱉ARS_PATH: E:/GLOG/mars_songqi
   

   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱉ARS_REVISION: 405388
   

%   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱉ARS_BUILD_TIME: 2017-08-03 14:41:52
   

(   坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱉ARS_BUILD_JOB: mars_xlog_sdk/mars_libs
   

    坎翀夅骂薫|碈>汼p_弄圶C廪^F掷顖?笿?.'哯桸}r篋u鶨nキ鱨og appender mode:1, use mmap:1

**Comment by garryyan** [comment]
是这样的，异步加密，同步考虑到效率不加密的。我更新下 wiki，忘了说这个事情了。

**Comment by huangdh2** [comment]
OK

**Comment by wangli135** [comment]
使用加密的情况，指定了目录，为什么看不到文件夹？难道生成文件失败了？
