### ISSUE TITLE
SampleChat

### ISSUE THREAD

**Issue by gmtalang** [Tencent/mars#281]
when  start mars-sample ,always display" topics load failed ,click to refresh",not such as that example "stn issue..."
server started successfully(window)
info:
08-10 14:25:39.830 29387-29399/com.tencent.mars.sample I/Mars.Sample.MarsServiceProxy: [, , 0]:processing push message, cmdid = 10004
08-10 14:25:39.844 29387-29387/com.tencent.mars.sample I/Mars.Sample.ConversationActivity: [, , 0]:getconvlist: empty response list

**Comment by garryyan** [comment]
we did not support the server of samplechat any more. please use your own server.

**Comment by gmtalang** [comment]
I used 127.0.0.1本地服务， 为什么还是那样的，我测试了一下，返回的响应的错误类型4 错误码-10087

**Comment by garryyan** [comment]
根据wiki的说明把访问的ip改成你的服务器ip。 确保你的手机能访问你的服务器。比如用127.0.0.1 确保手机和电脑用usb连上了。而且已经把网络请求转到了pc

**Comment by gmtalang** [comment]
我把 android 的代码按照wiki里面 IP替换成 localhost，一直不行 ，我在看发的请求，都是空的 。你能告诉我你的QQ吗 ，咱们及时聊

**Comment by garryyan** [comment]
看日志连的ip是不是你的ip。 task end callback 搜这个关键字 能看到用的哪个ip

**Comment by gmtalang** [comment]
08-11 11:17:30.141 9816-9827/com.tencent.mars.sample E/Mars.Sample.ConversationActivity: [, , 0]:REQ的类型2 请求的token 1
08-11 11:17:34.170 9816-9827/com.tencent.mars.sample I/Mars.Sample.MarsServiceProxy: [, , 0]:processing push message, cmdid = 10004
08-11 11:17:34.173 9816-9816/com.tencent.mars.sample E/Mars.Sample.ConversationActivity: [, , 0]:错误类型4 错误码-10087
08-11 11:17:34.173 9816-9816/com.tencent.mars.sample I/Mars.Sample.ConversationActivity: [, , 0]:getconvlist: empty response list

**Comment by garryyan** [comment]
看网络层的日志，选对进程。你这是ui进程的日志吧。

**Comment by gmtalang** [comment]
这个问题搞定
