### ISSUE TITLE
LogBuffer::Write(const void* _data, size_t _length) 问题

### ISSUE THREAD

**Issue by helloworldgnu** [Tencent/mars#283]
log_buffer.cc的 Write(const void* _data, size_t _length) 中，

`AutoBuffer out_buffer;
    size_t last_remain_len = remain_nocrypt_len_;
    log_crypt_->CryptAsyncLog((char*)buff_.Ptr() + before_len, write_len + remain_nocrypt_len_, out_buffer, remain_nocrypt_len_);
    
    buff_.Write(out_buffer.Ptr(), out_buffer.Length(), before_len);
    
    before_len += out_buffer.Length();
    buff_.Length(before_len, before_len);
   
    log_crypt_->UpdateLogLen((char*)buff_.Ptr(), (uint32_t)(out_buffer.Length() - last_remain_len));`

经过` log_crypt_->CryptAsyncLog` 后， out_buffer 里存储的未加密数据长度应该为 remain_nocrypt_len_，这里为什么 `log_crypt_->UpdateLogLen ` 最后传入的是 减去 last_remain_len ，而不是 remain_nocrypt_len_ 呢？ 能说明一下吗？

**Comment by garryyan** [comment]
看CryptAsyncLog的实现你会发现 out_buffer既包含已经加密的数据也包含未加密的数据，未加密的数据怎么处理呢？ 会等待下一部分数据过来的时候和下一部分数据拼到一块去处理。所以本次加密其实用了之前未加密的部分，之前未加密的部分已经计算过长度了。所以需要减去

**Comment by helloworldgnu** [comment]
谢谢解答。
但是，这样的话是否表明 __async_log_thread 线程写日志的时候，每次写出的都包含一部分未加密的，
因为 `log_crypt_->UpdateLogLen((char*)buff_.Ptr(), (uint32_t)(out_buffer.Length() - last_remain_len));`
这句已经把包含未加密的数据长度也写入了，我理解的有问题吗？

**Comment by garryyan** [comment]
对。 已经写入了。

**Comment by garryyan** [comment]
看日志的长度，因为是8字节8字节进行的加密，如果日志长度不是8的倍数，多余的未加密的是包含在里面

**Comment by garryyan** [comment]
但是只在日志块结尾处才有，而且是不到8个字节的长度。因为中间未加密的会和下一句日志凑在一起加密。 再加上本身这些数据是压缩后的数据，即使部分加密也不存在安全性问题。
