### ISSUE TITLE
数据发送线程问题

### ISSUE THREAD

**Issue by helloworldgnu** [Tencent/mars#284]
请教一个问题，长链接数据发送时，执行的是
`
bool LongLink::Send(const AutoBuffer& _body, const AutoBuffer& _extension, const Task& _task) {
    ......
    readwritebreak_.Break();
    ......
}
`

而，数据读取线程阻塞在
`
void LongLink::__RunReadWrite(SOCKET _sock, ErrCmdType& _errtype, int& _errcode, ConnectProfile& _profile) {
......
int retsel = sel.Select(10 * 60 * 1000);
......
}
`

sel.Select 实现在
`
int SocketPoll::Poll(int _msec) {
    ......
    ret_ = poll(&events_[0], (nfds_t)events_.size(), _msec);
    ......
    if (autoclear_) Breaker().Clear();
    return ret_;
}
`
有两个问题：
1. 读取线程已经在 poll 阻塞了，还没有执行后续的 pipe read 操作，而 send 的时候只是 往 pipe 里写入了数据，由于 pipe read 还没有执行，这里的 pipe write 是不是已经没有意义了，那到底是怎么实现立刻唤醒的呢？
2. Breaker 里的 pipe 是 O_NONBLOCK，不会阻塞，那么用这个 pipe 还有什么用处呢，读写都会立刻返回

**Comment by garryyan** [comment]
poll不仅在监听socket也在监听pipe,当pipe另一端有写入的时候，另一段所监听的就会触发事件

**Comment by helloworldgnu** [comment]
确实如你所说，遗漏了没有看到，谢谢！
