### ISSUE TITLE
Sample chat

### ISSUE THREAD

**Issue by gmtalang** [Tencent/mars#285]
in the example，how tcp longlink set?  android and server should how do?
i want to try to test it...可以吗

**Comment by garryyan** [comment]
使用问题请仔细阅读wiki。 实现问题可以仔细看下代码

**Comment by gmtalang** [comment]
那个是短连接，但是长连接不知道怎么弄

**Comment by garryyan** [comment]
长连 wiki和reademe里都有说，至于连你自己的服务器也是根据域名来解析的，按照你短连操作方式就行。

**Comment by gmtalang** [comment]
哪个readme里面？给我说说，域名那些都没问题，短连接wiki我知道，长连接wiki在哪里？找不到

**Comment by garryyan** [comment]
长连用的wiki也是域名来更换的。你最开始不是调用SetLonglinkSvrAddr 设置了长连域名和端口，而且还支持debugip。
