### ISSUE TITLE
python gen_key.py 报错 提示找不到OpenSSL lib，我都是按Xlog 加密使用指引来的。

### ISSUE THREAD

**Issue by horse5700** [Tencent/mars#286]
Traceback (most recent call last):
  File "gen_key.py", line 3, in <module>
    import pyelliptic
  File "build\bdist.win-amd64\egg\pyelliptic\__init__.py", line 43, in <module>
  File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 527, in <module>
Exception: Couldn't load OpenSSL lib ...

环境：win10 64bit

python-2.7.13.amd64
Win64OpenSSL-1_1_0f
其他三个也装了

**Comment by garryyan** [comment]
pyelliptic 用的哪个版本

**Comment by horse5700** [comment]
pyelliptic-1.5.7
pip-9.0.1
setuptools-36.0.1

**Comment by horse5700** [comment]
@garryyan 

pyelliptic-1.5.7
setuptools-36.0.1
pip-9.0.1

**Comment by garryyan** [comment]
参考 https://github.com/yann2192/pyelliptic/issues/44 这个issue看是否能解决

**Comment by horse5700** [comment]
@garryyan 
请问  pyelliptic folder 这个目录在什么位置？ 谢谢
To fix it, literally search the web, find and download file libeay32.dll Then just drop it in pyelliptic folder. It will work.

**Comment by horse5700** [comment]
@garryyan  解决了谢谢

**Comment by garryyan** [comment]
@horse5700 如何解决的 贴下方案 方便后来的人参考

**Comment by horse5700** [comment]
1.搜索并下载：  libeay32.dll  （分32位和64位，根据你系统选择）
2.放入 系统盘：system/system32 目录

**Comment by pengwei1024** [comment]
有些64位系统得把`libeay32.dll`放到 `SysWOW64` 文件夹下

**Comment by ouyangpeng** [comment]
出现了下面的错误：
![image](https://user-images.githubusercontent.com/5885735/47142659-fd1a9b80-d2f5-11e8-8b5b-c1a69de707ca.png)

报错  OpenSSL 相关的，但是  OpenSSL 我已经按照指南（https://github.com/Tencent/mars/wiki/Xlog-%E5%8A%A0%E5%AF%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%BC%95）安装了。

![image](https://user-images.githubusercontent.com/5885735/47142765-436ffa80-d2f6-11e8-99f9-709fc5e36a3b.png)




Win64 OpenSSL v1.1.1

![image](https://user-images.githubusercontent.com/5885735/47142821-5d114200-d2f6-11e8-8505-a6cdaa912a4c.png)

后面搜索到这个issue，发现@horse5700 解决了这个问题。

![image](https://user-images.githubusercontent.com/5885735/47142966-b2e5ea00-d2f6-11e8-9262-7fb2fb2dae71.png)

>1.搜索并下载： libeay32.dll （分32位和64位，根据你系统选择）
>2.放入 系统盘：system/system32 目录


![image](https://user-images.githubusercontent.com/5885735/47143044-e58fe280-d2f6-11e8-982e-aa34d4025ae9.png)


将libeay32.dll  放到  C:\Windows\System32目录下之后，在运行就成功了！

**Comment by aaadaaaada** [comment]
Exception: Couldn't load OpenSSL lib ...

**Comment by aaadaaaada** [comment]
Exception: Couldn't load OpenSSL lib ... 
window环境下接入XLog安装接入流程把所有软件都安装好了,解密日志时一直提示:
Exception: Couldn't load OpenSSL lib ...
后面参考了这个issues https://github.com/Tencent/mars/issues/286 
解决了问题,下载libeay32.dll 将libeay32.dll 放到 C:\Windows\System32目录下之后,就好了

**Comment by wzp09tjlg** [comment]
记录一下我这边出现的问题：
1.环境都是按照上述的步骤进行的操作，但是在执行的时候 出现这样的错误：
  File "C:\Users\hp\Desktop\log\20200210_164159\wecarnavi\decode_mars_crypt_log_file.py", line 9, in <module>
    import pyelliptic
  File "build\bdist.win-amd64\egg\pyelliptic\__init__.py", line 43, in <module>
  File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 528, in <module>
  File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 67, in __init__
  File "D:\Pro\python2.7\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

2.也是各种找办法，看到这个已经结了的帖子。下载了libeay32dll.zip（ouyangpeng 这个小伙伴）
然后解压，将libeay32.dll 放置到  C:\Windows\System32 下，我的电脑已经存在这个文件，我将之前的文件 修改了名字，备份起来 libeay32.dll.bak ,然后将新的文件 拷贝进来。 
3.再执行 上述的 解密 xlog文件，就可以了。

谢谢大神 和 各位爱分享的小伙伴。 给各位点赞。

**Comment by iankevinlee** [comment]
pip install pyelliptic 装上了pyelliptic-1.5.8版本不能用，提示openssl缺失。
后来下载pyelliptic-1.5.10版本安装，就可以了。

**Comment by stubhbw** [comment]
谢天谢帝看到了这个，折腾一天各种错误都遇到了[微笑]

**Comment by Perter89757** [comment]
Python环境配置有问题, 可以使用第三方解析xlog
 Tencent mars-xlog 解密的javaGUI版本
https://github.com/zhanlan123/YXlogDecode/tree/main
