### ISSUE TITLE
自定义封包、拆包等编译问题

### ISSUE THREAD

**Issue by helloworldgnu** [Tencent/mars#287]
请教一个问题。 以长链接封包为例，longlink.cc 中依赖的是 `#include "mars/stn/proto/longlink_packer.h"`,  实现文件对应的路径是 mars/stn/proto/longlink_packer.cc。在编译的时候生成了mars.framework。而iOSDemo依赖了 mars.framework，同时也提供了samples/iOS/iOSDemo/PublicComponentV2/longlink_packer.h，samples/iOS/iOSDemo/PublicComponentV2/longlink_packer.cc文件。android同样也是如此。 这两个文件的命名空间、函数声明、全局变量(函数)实现都是一样的

那么，iOS和android 分别是怎么处理的，不会出现库链接冲突？

**Comment by garryyan** [comment]
mars.framework 没有编longlink_packer.cc  也就是说在静态库里只有声明没有定义。

**Comment by helloworldgnu** [comment]
嗯，确认。谢谢
