### ISSUE TITLE
xlog编译不过

### ISSUE THREAD

**Issue by heiheiwanne** [Tencent/mars#289]
执行 python build_android.py之后一直报错，求大神指教
In file included from jni/../export/crypto/openssl_multi_thread_support.cpp:9:
In file included from jni/../../comm/thread/mutex.h:17:
jni/../../comm/thread/../unix/thread/mutex.h:121:15: error: use of undeclared
      identifier 'pthread_mutex_lock_timeout_np'
        ret = pthread_mutex_lock_timeout_np(&mutex_, (unsigned)_millisecond);
              ^
2 warnings and 1 error generated.
make: *** [obj/local/armeabi/objs/cryptowrapper/__/export/crypto/openssl_multi_thread_support.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by garryyan** [comment]
使用ndk-r11c版本编译

**Comment by heiheiwanne** [comment]
![image](https://user-images.githubusercontent.com/11434634/29613183-6ce71fd4-8837-11e7-8eee-94f2a67bbc24.png)
我已经是11了还是会报错

**Comment by garryyan** [comment]
是ndk的版本。看目录下的source.properties文件

**Comment by heiheiwanne** [comment]
Pkg.Desc = Android NDK
Pkg.Revision = 11.2.2725575

**Comment by heiheiwanne** [comment]
是不是不对啊，应该是多少？

**Comment by garryyan** [comment]
对的 你用的代码是什么时候的代码

**Comment by heiheiwanne** [comment]
今下午clone的代码，切换了不同的分支以及tag试过都不可以

**Comment by heiheiwanne** [comment]
jni/../../comm/thread/../unix/thread/mutex.h:121:15: error: use of undeclared
      identifier 'pthread_mutex_lock_timeout_np'
代码里是说类型转换失败，是不是代码有问题呢？

**Comment by garryyan** [comment]
编的哪个cpu架构，我刚试了下armeabi是没问题的。

**Comment by garryyan** [comment]
你的代码有问题，最新的编译脚本不是这样的。

**Comment by heiheiwanne** [comment]
这个我是切到了dev分支,还是报错
![image](https://user-images.githubusercontent.com/11434634/29613900-9c5a9252-883a-11e7-8992-5bc2019ba061.png)

![image](https://user-images.githubusercontent.com/11434634/29613963-d118964c-883a-11e7-8142-be3128e73fe0.png)

**Comment by garryyan** [comment]
切到master

**Comment by heiheiwanne** [comment]
master分支也是报错

error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/mmap_util.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
make: Leaving directory `/Users/xmq/demo/mars_/mars/comm'
build static libs fail!!!

**Comment by garryyan** [comment]
这个问题和你最初说的不一样。 这个一直是老大难的问题。在某些机器环境上会出现这个问题。你把你的代码挪个目录看能不能解决，不能解决的话 我们这边暂时也没有很好的解决办法

**Comment by heiheiwanne** [comment]
想知道是什么原因造成的～？

**Comment by garryyan** [comment]
如果把你代码换到别的目录可以解决。 不要同级别的目录。要更深或者更浅的目录。 比如  之前是 a/b/c   现在可以改成 d/e。 那么就可能include的问题。猜测的，目前我这边没环境验证

**Comment by heiheiwanne** [comment]
果然如你所说切换目录之后好了，很不理解为什么会出现这种情况，多谢了！

**Comment by 337240552** [comment]
把整个mars目录移到更浅层目录，还是不行

**Comment by MuZiLee** [comment]
我需要编译iOS版的framework，过程出现报错，我以为是我很久没用的python库的问题，我重装python还是同样的报错。请问哪位有遇到过这样的问题。

我是使用SourceTree摘取的git，是在master分支下的操作，结果有不同的报错，我感到很困惑。


以下操作是在mars最外层目录python mars/build_ios.py,出现的报错，提示找不到“comm”这个文件夹。
<img width="752" alt="qq20190114-013858 2x" src="https://user-images.githubusercontent.com/7467318/51088659-4ebfae80-179d-11e9-899e-a8219469a75d.png">


以下操作是在mars/mars层目录python build_ios.py,出现的报错，提示编译失败。
<img width="780" alt="qq20190114-013051 2x" src="https://user-images.githubusercontent.com/7467318/51088662-5bdc9d80-179d-11e9-9c38-662786ac8ffd.png">

**Comment by MuZiLee** [comment]
@heiheiwanne @garryyan @337240552 @rocklau @king6cong 

麻烦帮忙分析一下我以上遇到的问题，非常感谢
