### ISSUE TITLE
xlog Android解码后中文乱码

### ISSUE THREAD

**Issue by huangchen0** [Tencent/mars#292]
环境 mac
解码后中文乱码，控制台输入中文是正常的，类似如下

"name":"1ååååæ¢å¸","orderminamount":0,"realm":"1åä¹°æ´åæ°´å¯","realmdesc":"1åä¹°æ´åæ°´å¯","realmid":4,"reason":"ä¸éç¨äºè¯¥åå®¶"

**Comment by huangchen0** [comment]
补充一下：Android

**Comment by garryyan** [comment]
改为utf8编码

**Comment by Smart-shine** [comment]
麻烦请教下xlog有这样Java接口可以设置为UTF-8的方式吗？

**Comment by Smart-shine** [comment]
麻烦请教下xlog有这样Java接口可以设置为UTF-8的方式吗？

**Comment by EspoirX** [comment]
> 改为utf8编码

可以说下在哪改吗
