### ISSUE TITLE
xlog: logcat中debug级别的日志没有输出来

### ISSUE THREAD

**Issue by larrymeng** [Tencent/mars#293]
mars-core版本：1.2.0

xlog的初始化:
// init xlog
if (BuildConfig.DEBUG) {
  Xlog.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, cachePath, logPath, logFileName, PUB_KEY);
  Xlog.setConsoleLogOpen(true);
} else {
  Xlog.appenderOpen(Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, cachePath, logPath, logFileName, PUB_KEY);
  Xlog.setConsoleLogOpen(false);
}

日志使用：
Log.d("MainActivity", "haha123");
Log.i("MainActivity", "debug="+BuildConfig.DEBUG);

结果：
Log.d这句在logcat上没有输出，而Log.i这句在logcat上是有输出的。

**Comment by garryyan** [comment]
Log.d 打印的时候日志是否已经初始化了

**Comment by larrymeng** [comment]
为了问题简单化，代码如下：
public class MainActivity extends AppCompatActivity {

  // 日志的公钥, 空串表示不加密.
  private static final String PUB_KEY = "";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);

    // Used to load the 'mars-core' library on application startup.
    System.loadLibrary("stlport_shared");
    System.loadLibrary("marsxlog");
    // 初始化xlog
    openXlog();

    Log.d("MainActivity", "haha123");
    Log.i("MainActivity", "debug="+BuildConfig.DEBUG);
    Log.d("MainActivity", "xxx");
    Log.i("MainActivity", "yyy");
  }

  // 初始化xlog
  public  void openXlog() {
    // 保存 log 的目录, 最好单独使用.
    final String SDCARD = Environment.getExternalStorageDirectory().getAbsolutePath();
    final String logPath = SDCARD + "/" + BuildConfig.APPLICATION_ID + "/log";
    // 日志名前缀
    String logFileName = "TEST2";

    // mmap文件会放在这个目录
    final String cachePath = this.getFilesDir() + "/xlog";

    // init xlog
    if (BuildConfig.DEBUG) {
      Xlog.appenderOpen(Xlog.LEVEL_ALL, Xlog.AppednerModeAsync, cachePath, logPath, logFileName, PUB_KEY);
      Xlog.setConsoleLogOpen(true);
    } else {
      Xlog.appenderOpen(Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, cachePath, logPath, logFileName, PUB_KEY);
      Xlog.setConsoleLogOpen(false);
    }

    // 设置 Log 的具体实现
    Log.setLogImp(new Xlog());
  }
 }
--------------------------------------------------------
logcat输出结果：
09-04 22:23:36.457 30863-30863/com.example.me.testxlog I/MainActivity: [, , 0]:debug=true
09-04 22:23:36.457 30863-30863/com.example.me.testxlog I/MainActivity: [, , 0]:yyy

**Comment by larrymeng** [comment]
很奇怪，为什么debug级别的日志没有打出来。

**Comment by garryyan** [comment]
显示的时候加级别过滤了吗？

**Comment by larrymeng** [comment]
加了过滤，级别为Debug.

**Comment by garryyan** [comment]
确实奇怪。不要用ide 直接用logcat命令行 把日志重定向到文件里 仔细看下是否也没有

**Comment by larrymeng** [comment]
我QQ给你源码，有空帮我看看，谢了。

**Comment by garryyan** [comment]
可以 邮箱 1173828173@qq.com

**Comment by garryyan** [comment]
09-05 20:02:30.703 24964-24964/com.example.meng.testxlog D/MainActivity: [, , 0]:haha123
09-05 20:02:30.703 24964-24964/com.example.meng.testxlog I/MainActivity: [, , 0]:debug=true
09-05 20:02:30.703 24964-24964/com.example.meng.testxlog D/MainActivity: [, , 0]:xxx
09-05 20:02:30.703 24964-24964/com.example.meng.testxlog I/MainActivity: [, , 0]:yyy

---------------
上面是我没有修改你的代码，直接在本地跑你的代码跑出来的。所以请检查你查看日志的姿势是不是不对

**Comment by larrymeng** [comment]
的确奇怪，我再检查看看。

**Comment by larrymeng** [comment]
我换了手机测试，结果没问题。
之前用的是华为X2，还是没出来debug日志，我只能呵呵了。

**Comment by garryyan** [comment]
应该和手机有关。 你可以试试你出问题的手机 使用系统的接口打印logcat会不会输出

**Comment by larrymeng** [comment]
一搜，都是华为手机的问题：
http://blog.csdn.net/rflyee/article/details/40714161
http://blog.csdn.net/msn465780/article/details/46117945

**Comment by larrymeng** [comment]
经确认，确实是华为手机默认没有打开日志功能导致的，按照网上指导设置即可正常。
