### ISSUE TITLE
缺失代码

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#295]
仔细读了其中设计的ServiceBase 的实现，目前代码中没有看到有使用的地方，同时对于corepattern\test目录下有使用的测试代码，但是2变代码不同步，例如测试代码中有使用到ServiceUtil.h，这个文件在工程里面没有找到，同样的对于参数ServiceBase测试代码使用的是2个参数，而实际代码则只有一个参数。希望能够提供一份完整的代码，非常感谢。已经送上了我的star。

**Comment by garryyan** [comment]
代码并没有缺失的。
Service这一套当初认为我们可能会用到，恰好有时间，代码作者就封装了一套，所以你能看到测试代码 能看到实现部分，但是看不到调用代码。 测试代码和实现代码不一致，应该是是因为后来改动第二版代码时没有更新测试代码导致的、

**Comment by stevezhou6** [comment]
能否更新一下测试代码。谢谢。

**Comment by garryyan** [comment]
我们这边做的话速度没那么快的，毕竟这一部分代码我们没有使用。 你可以自己修改下。并顺便可以看下实现、

**Comment by stevezhou6** [comment]
恩，我读了下代码，看了几天，终于都弄明白了。
