### ISSUE TITLE
$$$$$$$$$   ^^^^^^^^^^

### ISSUE THREAD

**Issue by liangxianshen** [Tencent/mars#296]
$$$$$$$$$$Jul 14 2017$$$20:13:20$$$$$$$$$$[6810,6810][2017-09-07 +0800 18:01:07]
^^^^^^^^^^Jul 14 2017^^^20:13:20^^^^^^^^^^[12802,12802][2017-09-07 +0800 20:19:04]
这两句log的分别是在什么时机打印的呢？意义是什么啊？虽然我大概清楚，
上面那句对程序有什么影响呢？测试时分析日志发现，上面哪句话打印出来之后application会被重新创建，这很不科学，因为我的app在前台

**Comment by garryyan** [comment]
^^^^^^^^^^  在xlog启动初始化的时候会打印
$$$$ 在xlog退出反初始化的时候会打印
