### ISSUE TITLE
Xlog 多进程是，mmap中的日志未输出到xlog文件中

### ISSUE THREAD

**Issue by TangXun** [Tencent/mars#297]
多进程，主进程使用xlog正常，
其他进程重新初始化了xlog，目录和文件也是独立的，但是
.mmap中的日志并未输出到对应的.xlog中，反解.xlog发现只有mmap的开头和结尾内容并无其他内容，
console中的输出也是正常的，不知道是不是问题

**Comment by garryyan** [comment]
是不是import错了，用了系统的Log?

**Comment by TangXun** [comment]
检查了没有错，而且.mmap中有很多数据,只是没有输出到.xlog文件中

**Comment by garryyan** [comment]
如果开了异步 不会立即输出到文件中的，需要等一段时间，或者调用appenderSync接口。  在程序退出的时候也应该调用appenderClose接口来完成这个操作

**Comment by TangXun** [comment]
刚又看了，好像恢复了，我在检查下是哪里引起的问题...

**Comment by TangXun** [comment]
我大概找到问题了，mmap2的并不是实时输出，只有等到进程退出，下次进入才会输出到xlog文件中，所以应该在进程退出时主动调用日志输出

**Comment by garryyan** [comment]
如果开了异步 不会立即输出到文件中的，需要等一段时间，或者调用 appenderSync 接口。 在程序退出的时候也应该调用 appenderClose 接口来完成这个操作
--------------------------
上面回答已经说了。  而且文档里也有强调，程序退出的时候要调用appenderClose 。 不然就必须等到下次程序启动了。  在程序运行期间可以通过  appenderSync 来把日志刷到文件里，但是不是必要不建议调用这个接口

**Comment by buptlingfeng** [comment]
appenderClose
这个接口调用的时机很不好把握的，一般来说应用在联系两次back键理论上应该杀掉自己的进程，但是很多情况下用户直接点home键，应用本身只知道自己在后台，所以最靠谱的还是每次启动的时候去检查mmap里边有没有数据，这个xlog里边已经实现了
我个人是觉得appendClose这个接口没啥用

在 2017年9月13日 下午4:54，garryyan <notifications@github.com>写道：

**Comment by garryyan** [comment]
在后台不应该调用appenderClose的，真正退出的时候才需要调用。

**Comment by TangXun** [comment]
同步和异步对性能有多大的影响呢 ？

**Comment by garryyan** [comment]
写文件的性能和写内存的性能的差别。    release版本原则上都应该是异步

**Comment by TangXun** [comment]
OK 明白了，那个网络组件如果要使用，是不是需要我们也有自己的后台服务来配套使用呢？

**Comment by garryyan** [comment]
是的。wiki里有说明的
