### ISSUE TITLE
如何只把xlog 编译成 .so 库，在 iOS 和 Android 下面都要

### ISSUE THREAD

**Issue by happyjiahan** [Tencent/mars#298]
在 Android 下面使用 Build_Android 我可以达到 .so,  但是用 Build_apple 只能得到 .framework

**Comment by garryyan** [comment]
ios下面不能使用so吧？没太明白问题的意思。

android使用动态库 所以用so。 ios可以使用动态库dylib和静态库。目前mars只针对ios提供了静态库，如果你想使用dylib的话可以依赖静态库二次编译动态库
