### ISSUE TITLE
飞行模式连接状态切换

### ISSUE THREAD

**Issue by isee15** [Tencent/mars#299]
`bool LongLinkConnectMonitor::NetworkChange() {
    xdebug_function();
#ifdef __APPLE__
    __StopTimer();

    do {
        if (LongLink::kConnected != status_ || (::gettickcount() - last_connect_time_) <= 10 * 1000) break;

        if (kMobile != last_connect_net_type_) break;

        int netifo = getNetInfo();

        if (kNoNet == netifo) break;

        if (__StartTimer()) return false;
    } while (false);

#endif
    longlink_.Disconnect(LongLink::kNetworkChange);
    return 0 == __IntervalConnect(kNetworkChangeConnect);
}
`
在切换到飞行模式的时候，kNoNet 了，但还是去尝试__IntervalConnect，这个操作会导致大概4s的超时失败，连接状态从切换飞行模式之后到真正通知未连接有4s的时间，中间多了一个连接中的状态。怎么能在确定断网的情况下，减少这4s？

**Comment by garryyan** [comment]
这里mars的原则是不相信系统通知。
因为系统告诉没网，并不一定是不能连上的，同样的，系统告诉有网，也并不一定能连上。
所以这4s是无法减少的。
