### ISSUE TITLE
Error:Failed to resolve: com.tencent.mars:mars-xlog:0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by ainide2990** [Tencent/mars#30]
F:\mars\mars\samples\android\xlogSample\app\build.gradle
Error:Failed to resolve: com.tencent.mars:mars-xlog:0.2.0-SNAPSHOT
<a href="openFile:F:/mars/mars/samples/android/xlogSample/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
External Native Build Issues
Build command failed.
Error while executing 'D:\Downloads\ndk\android-ndk-r11c\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk NDK_APPLICATION_MK=F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDEBUG=0 APP_PLATFORM=android-16 NDK_OUT=F:\mars\mars\samples\android\xlogSample\app\.externalNativeBuild\ndkBuild\release\obj NDK_LIBS_OUT=F:\mars\mars\samples\android\xlogSample\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: ERROR:F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk:xlog: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that F:/mars/mars/samples/android/xlogSample/app/src/main/jni/export_include/libmarsxlog.so exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk
Build command failed.
Error while executing 'D:\Downloads\ndk\android-ndk-r11c\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk NDK_APPLICATION_MK=F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDEBUG=1 APP_PLATFORM=android-16 NDK_OUT=F:\mars\mars\samples\android\xlogSample\app\.externalNativeBuild\ndkBuild\debug\obj NDK_LIBS_OUT=F:\mars\mars\samples\android\xlogSample\app\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: ERROR:F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk:xlog: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that F:/mars/mars/samples/android/xlogSample/app/src/main/jni/export_include/libmarsxlog.so exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild F:\mars\mars\samples\android\xlogSample\app\src\main\jni\Android.mk
D:\Downloads\ndk\android-ndk-r11c\build\core\prebuilt-library.mk
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:D:/Downloads/ndk/android-ndk-r11c/build/core/prebuilt-library.mk">Open File</a>
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:D:/Downloads/ndk/android-ndk-r11c/build/core/prebuilt-library.mk">Open File</a>

**Comment by garryyan** [comment]
use the latest code

**Comment by hujiahong0313** [comment]
刚下的代码这个问题没有解决啊

**Comment by garryyan** [comment]
[查看wiki中常见问题](https://github.com/Tencent/mars/wiki/Mars-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%89%93%E5%BC%80-xlog-%E7%9A%84-sample-%E6%8A%A5libmarsxlogso-exists-or-that-its-paths-is-correct)

**Comment by hujiahong0313** [comment]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
wiki中的问题不能解决。还是有这个问题
> Could not find com.tencent.mars:mars-xlog:0.2.0-SNAPSHOT.
     Required by:
         xlogSample:app:unspecified

**Comment by shockcao** [comment]
mars-xlog 的版本是1.0.2   没有SNAPSHOT
如果不是最新代码 可以自己修改一下

**Comment by hujiahong0313** [comment]
我是在master上的damo请问是最新代码么？修改为1.0.2还是报错.
External Native Build Issues
Build command failed.
Error while executing '/Users/hujiahong/Library/Android/sdk/ndk-bundle/ndk-build' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/.externalNativeBuild/ndkBuild/release/obj NDK_LIBS_OUT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: ERROR:/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Android.mk:xlog: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/export_include/libmarsxlog.so exists  or that its path is correct   
Build command failed.
Error while executing '/Users/hujiahong/Library/Android/sdk/ndk-bundle/ndk-build' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/.externalNativeBuild/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: ERROR:/Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/Android.mk:xlog: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/hujiahong/Downloads/mars-master/samples/android/xlogSample/app/src/main/jni/export_include/libmarsxlog.so exists  or that its path is correct   
/Users/hujiahong/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hujiahong/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hujiahong/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
