### ISSUE TITLE
自定义心跳包body

### ISSUE THREAD

**Issue by rorschach** [Tencent/mars#300]
我们产品已有的长连接的心跳包需要携带用户信息，但Mars心跳包中是不包含body的，请问自定义心跳包该如何实现？若需要改动源码的话，要改动哪些部分的代码？

**Comment by garryyan** [comment]
https://github.com/Tencent/mars/blob/master/mars/stn/proto/longlink_packer.cc#L137

**Comment by rorschach** [comment]
若想通过Java接口回调的方式在Android代码中给心跳包body赋值的话，该如何实现？

**Comment by garryyan** [comment]
需要通过jni回调到java
