### ISSUE TITLE
建议：把xlog stn等各个组件拆分开

### ISSUE THREAD

**Issue by 337240552** [Tencent/mars#301]
毕竟不是所有人都需要这几个组件，比如我想用xlog，目前得来个全家桶，虽然我可以在gradle里把不用的so给exclude掉，但是对引用这个组件的工程来说还是很麻烦，要频繁修改

**Comment by garryyan** [comment]
现在已经是拆分开的。项目上是拆分开的，编译的时候也可以选择只编译xlog. 依赖也有mars-core和mars-xlog两个
