### ISSUE TITLE
xlog编译优化选项

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#302]
编译xlog是否可以加编译选项LOCAL_CFLAGS += -03，以达到优化程序的目的呢？

**Comment by garryyan** [comment]
不起作用， ndk默认O2级别，暂时没找到ndk调优化级别的选项。

**Comment by FelixZhang00** [comment]
好的。
再请教一个问题，因为要用[android-ndk-profiler](https://github.com/richq/android-ndk-profiler)做函数调用的耗时记录，需要开启-pg选项，但是发现加了这个选项编译失败了。
报的错是`undefined reference to mcount`
是因为用clang编译器的问题吗？

**Comment by garryyan** [comment]
有可能，我们没有用过这个编译选项和这个工具。

**Comment by FelixZhang00** [comment]
请问下，你们有用其它profiler工具做性能上的分析吗？

**Comment by garryyan** [comment]
目前我们没有使用，native代码目前没看到有性能瓶颈
