### ISSUE TITLE
xcode 9编译失败

### ISSUE THREAD

**Issue by songqi5302855** [Tencent/mars#305]
编译脚本执行时失败，模拟器版本编译有问题
XXX.../getgateway.c:75:10: fatal error: 'net/route.h' file
      not found
#include __ROUTE_HEADER_FILE__
         ^
XXX../getgateway.c:30:31: note: expanded from macro
      '__ROUTE_HEADER_FILE__'
#define __ROUTE_HEADER_FILE__ <net/route.h>
                              ^~~~~~~~~~~~~
1 error generated.

**Comment by garryyan** [comment]
这个问题是因为xcode9 改变了一个头文件的位置，已提交fix.

**Comment by wosshzhb** [comment]
@garryyan  你上面的修改感觉不太好，因为对于mac平台来说，<net/route.h>还是有的，那么就应该用回系统的比较好，只是iOS平台没有了，需要对应于项目自己内部的文件，其实将宏TARGET_OS_SIMULATOR 改为 TARGET_OS_IOS就OK了。
如下：

![default](https://user-images.githubusercontent.com/10632522/31811398-0e3c9f82-b545-11e7-9a8b-b5d94f81f607.png)

**Comment by garryyan** [comment]
@wosshzhb 多谢提醒，我确认下，后续会修改

**Comment by garryyan** [comment]
@wosshzhb ab582b32408f0d15a539f380a81363afff736303 已经修改，后续这类 欢迎提pr

**Comment by wosshzhb** [comment]
ok
