### ISSUE TITLE
android build xlog错误

### ISSUE THREAD

**Issue by 337240552** [Tencent/mars#307]
ndk r14b

armeabi] Compile++ thumb: comm <= mmap_util.cc
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/mmap_util.o] Error 1
make: Leaving directory `/Users/mingchunhu/Documents/github/mars/mars/comm'
build static libs fail!!!

**Comment by garryyan** [comment]
#289

**Comment by garryyan** [comment]
而且目前我们没有支持ndk14，不一定能编过，建议ndk11c

**Comment by 337240552** [comment]
ndk 12b也编不过 mac系统
 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by garryyan** [comment]
#289 看这个issue了吗

**Comment by 337240552** [comment]
把整个mars目录移到更浅层目录，还是不行

**Comment by garryyan** [comment]
1. 换用ndk11c版本
2. 完全更换和现在的无关目录

**Comment by 337240552** [comment]
我再试试 建议各个组件都放到jcenter上面 这种编个包太痛苦了

**Comment by garryyan** [comment]
jcenter上有的。wiki中和reademe中都有提到

**Comment by 337240552** [comment]
我找找，readme中只看到了mars-core 和mars-wrapper

**Comment by 337240552** [comment]
运气比较差 从14b到11c都试了一遍 目录也换了 还是不行。。重启电脑看看管不管用

**Comment by 337240552** [comment]
#289 这个方法管用，再配合r11b编译，刚刚出问题是因为环境变量配好了 但是ndk包没解开。。
