### ISSUE TITLE
请教两个XLog  mmap的问题

### ISSUE THREAD

**Issue by happyjiahan** [Tencent/mars#310]
1.我看过 XLog 的源码，里面兼容了 mmap 不支持时使用内存 Buffer 的方式存储 Log，那么有哪些情况下 mmap 是不支持的呢？或者 mmap 请求失败呢？ 
2.XLog 中把 mmap 回写到硬盘文件时__log2file，使用的是 fwrite ，而不是 msync ，请问是为了兼容 不支持 mmap 的情况吗？还是有特殊的考虑？fwrite 是否比 msync 更耗时呢？

非常感谢。

**Comment by happyjiahan** [comment]
再问一个问题：
3. mmap2 缓存文件 和 .xlog 有哪些区别呢？为什么不直接把Log 写入mmap2文件呢？而是再写到一个.xlog文件里面呢？这样不是多一次文件操作吗？

谢谢，如果有理解不对的地方，请指正。

**Comment by garryyan** [comment]
1. 一些系统api调用会返回失败的情况下
2. fwrite是针对普通文件的，msync是针对mmap文件的。这里之所以是用fwrite是把mmap文件里的东西写到普通文件上，而不是把内存里的写到mmap文件里，这里逻辑你理解有误
3. mmap文件更高效，可以认为和直接写内存一样的效率，但也存在缺点，大小固定比较难扩容，这也是不直接把log直接写到mmap文件中的原因之一。而且系统一般会把mmap文件的大小映射到内存中，如果直接把mmap文件作为日志文件需要比较大的内存损耗，而且也不知道申请多大

**Comment by happyjiahan** [comment]
哇，好快速的回复啊。谢谢，明白了。
还有个疑惑，mmap 的大小固定为 kBufferBlockLength = 150 * 1024 大小，那么把 mmap里面的缓存写到普通文件后，是否会把 mmap reset 呢，好让它继续缓存其他的 Log 内容。我在 __log2file 里面没有找到类似的操作。请问，你是怎么实现的呢？

**Comment by happyjiahan** [comment]
`    if (sg_log_buff->GetData().Length() >= kBufferBlockLength*4/5) {
       int ret = snprintf(temp, sizeof(temp), "[F][ sg_buffer_async.Length() >= BUFFER_BLOCK_LENTH*4/5, len: %d\n", (int)sg_log_buff->GetData().Length());
       log_buff.Length(ret, ret);
    }
`

我又找了一下，是不是上面的代码？

**Comment by garryyan** [comment]
```
static void __async_log_thread() {
    while (true) {

        ScopedLock lock_buffer(sg_mutex_buffer_async);

        if (NULL == sg_log_buff) break;

        AutoBuffer tmp;
        sg_log_buff->Flush(tmp);
        lock_buffer.unlock();

	if (NULL != tmp.Ptr())  __log2file(tmp.Ptr(), tmp.Length());

        if (sg_log_close) break;

        sg_cond_buffer_async.wait(15 * 60 *1000);
    }
}
```
sg_log_buff->Flush(tmp);  这一句代码看内部实现，就是把mmap中的东西copy出来然后reset mmap

**Comment by happyjiahan** [comment]
多谢多谢

**Comment by happyjiahan** [comment]
上面的代码是先在  sg_log_buff->Flush(tmp); 里面把 mmap reset，然后才把 tmp 写入到文件中去，如果这个时候文件写入失败，或者在写入文件之前 Crash 了，是否会导致丢失 Log 呢？
是否应该是先写文件，确认写入成功后才 reset mmap 呢？

**Comment by garryyan** [comment]
是有可能存在你说的这种情况。 但是如果等待写文件 就必须把这个buffer锁死，这个buffer又需要接受其他线程的日志写入，会导致卡顿

**Comment by happyjiahan** [comment]
明白了，Thanks
