### ISSUE TITLE
Android长连接智能心跳使local_port被不断更改，导致onPush方法无法接收到消息

### ISSUE THREAD

**Issue by rorschach** [Tencent/mars#312]
每次向服务器发送心跳包时，都将长连接的local_port修改了，查看[微信终端跨平台组件 Mars 系列（三）连接超时与 IP&Port 排序](https://mp.weixin.qq.com/s?__biz=MzAwNDY1ODY2OQ==&mid=2649286458&idx=1&sn=320f690faa4f97f7a49a291d4de174a9&chksm=8334c3b8b4434aae904b6d590027b100283ef175938610805dd33ca53f004bd3c56040b11fa6#rd)发现这是Mars设计的结果．这样的话长连接不久相当于变成短连接了吗，请问该如何解决这个问题？

日志
[mars.log](https://github.com/Tencent/mars/files/1378898/mars.log)

**Comment by garryyan** [comment]
只有长连接重新建立连接的时候才会更改local_port. 我看你提供的日志，服务器在close socket。 找一下为什么会关闭长连接的原因。

**Comment by rorschach** [comment]
重新上传了一份日志，服务器确认没有关闭连接
 [mars.log](https://github.com/Tencent/mars/files/1379371/mars.log)

这是我封装Mars的代码
[LongLinkClient.txt](https://github.com/Tencent/mars/files/1379374/LongLinkClient.txt)

**Comment by rorschach** [comment]
不好意思，刚后台确认是他的Demo把socket断开了．但是服务器不再断开连接后每次心跳包的本地端口仍然一直在变化
日志 [mars.log](https://github.com/Tencent/mars/files/1379424/mars.log)

**Comment by garryyan** [comment]
自己可以尝试下分析下日志：task socket close sock:45, noop timeout
心跳包超时，问下服务器的是不是没回心跳包

**Comment by rorschach** [comment]
心跳包的回包要遵守什么协议？

**Comment by garryyan** [comment]
wiki中有说这类问题的，麻烦先仔细看wiki:https://github.com/Tencent/mars/wiki/Mars-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95#%E5%B7%B2%E7%BB%8F%E5%9B%BA%E5%AE%9A%E7%9A%84%E5%87%A0%E7%A7%8D%E5%8D%8F%E8%AE%AE

**Comment by rorschach** [comment]
服务器心跳包回包已满足要求，且现象为心跳包每270000ms发送一次，但每次发送心跳包的本地端口号仍然不同。

**Comment by rorschach** [comment]
修改服务器心跳回包已经满足条件，但每次服务器接收到的心跳包的客户端端口仍然不同。且有些心跳包成功，有些仍然抛出异常。
和服务器单独测试心跳包流程的日志文件 [noop.log](https://github.com/Tencent/mars/files/1381240/noop.log)

**Comment by garryyan** [comment]
E/mars::stn: [longlink.cc, __RunReadWrite, 555]:task socket close sock:42, noop timeout,
还是因为服务器没有回心跳包。 你可以自己查日志的。

**Comment by rorschach** [comment]
确实时服务器回包的问题，这个问题已经解决了

**Comment by 20140103** [comment]
请问是怎么解决的  我这边也遇到这个问题
