### ISSUE TITLE
iosDemo工程，发送内容必崩溃

### ISSUE THREAD

**Issue by lsqswl** [Tencent/mars#314]
![2017-10-13 4 49 48](https://user-images.githubusercontent.com/16233756/31537983-a7ca6886-afc9-11e7-9f9c-391416775281.png)
![wechatimg17](https://user-images.githubusercontent.com/16233756/31538081-08689cbc-afca-11e7-801c-580d477e853a.jpeg)

iphone6 
ios8.2

**Comment by garryyan** [comment]
看堆栈是oc层面的异常，应该是sdk兼容性的问题，我手上没有相关机器，你可以跟一下原因

**Comment by lsqswl** [comment]
回复好快啊。刚接触mars，想调研一下是否适合项目使用。我自己跟踪一下看看。

**Comment by lsqswl** [comment]
找到原因了。[UIFont fontWithName:@"PingFangSC-Regular" size:17] 这个“PingFangSC-Regular”不兼容。我暂时改成[UIFont systemFontOfSize:17.0]可以用了。

**Comment by garryyan** [comment]
赞

**Comment by LawrenceHan** [comment]
@lsqswl 不好意思。。。是我写的。。。我当是脑子进水了，没考虑iOS8没有平方这个字体。。。

**Comment by chdzq** [comment]
@lsqswl 自己提交的issue是可以关闭的吧
