### ISSUE TITLE
XLog 如何将map的日志强制写入到文件?

### ISSUE THREAD

**Issue by SheepYoung** [Tencent/mars#315]
hi
  我们有一个需求, 就是上传错误日志, 目前我们使用的是xlog写日志, 但是部分的log还在 map文件中, 好像没有看到一些方法可以将之二写log写入到文件中, 类似于flush 之类的方法。有没有类似的处理方式？

**Comment by garryyan** [comment]
请仔细看wiki中的接口说明：
Android : https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E
iOS: https://github.com/Tencent/mars/wiki/Mars-iOS%EF%BC%8FOS-X-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E

**Comment by dabing1022** [comment]
void appender_flush();
void appender_flush_sync();
