### ISSUE TITLE
xlog模块是否具有JavaAPI用来解压缩和解密

### ISSUE THREAD

**Issue by tianlin95310** [Tencent/mars#317]
现在有这样的需求是让用户自己能看日志，需要解密和解压xlog文件，请问是否有这样的JavaAPI？或者我们不进行压缩和加密，不加密是传一个空的key，那么不压缩该如果处理？

**Comment by garryyan** [comment]
解密脚本设计的初衷是为了保密，所以没考虑在客户端使用。

appender.cc 中 sg_log_buff = new LogBuffe 第三个参数控制是否压缩，目前没有对外暴露。

注意即使不压缩不加密，依旧会给每行日志拼头部信息和尾部信息。
