### ISSUE TITLE
文件管理策略疑问

### ISSUE THREAD

**Issue by JackyAndroid** [Tencent/mars#318]
前提：已查看wiki、相关issue及接口文档
看完之后还是有部分疑问，疑问如下：
1. 每次启动时会删除过期文件，只保留十天内的日志文件（如需修改得修改C层代码，具体位置未知）
2. 单文件最大限制（修改C层源码，具体位置未知）
3. 对储存文件夹没有最大限制，不会自动清理
4. 没有日志滚动

以上是我对疑问的猜测，不知是否正确？如果正确，是否可以提供更多的Java接口，以便开发使用，因为Android开发者大部分还是不熟悉C层代码。

**Comment by garryyan** [comment]
2和4的功能已经有了，不过Android 没提供对外接口 下个版本提供接口，

**Comment by JackyAndroid** [comment]
@garryyan 也就是说1、2、4功能现在已经有了，但是还没有向外提供Java接口？如果是这样，请问下个版本大概是在什么时间发布？

**Comment by garryyan** [comment]
1. 代码其实可以在这里修改  https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L113

接口的话如果你比较急的话可以自己先加上，下个版本时间我们还没确定

**Comment by JackyAndroid** [comment]
@garryyan 好的，多谢
