### ISSUE TITLE
appender_set_maxLogAliveTime

### ISSUE THREAD

**Issue by LuckZXF** [Tencent/mars#320]
appender_set_maxLogAliveTime这个方法是取消了吗，没办法设置保存时间了吗

**Comment by garryyan** [comment]
我们没有加过类似的接口，是否是你们自己扩展的

**Comment by LuckZXF** [comment]
是否有iPhone xlog 相关的源文件，工程提供的是个framework吧。

**Comment by garryyan** [comment]
iOS的framework就是你们根据源文件自己编出来的，我们只提供了源文件
