### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by liangxianshen** [Tencent/mars#322]
java.lang.UnsatisfiedLinkError
Shared library "/data/app/com.duia.cet4-1/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x1003f7; can't open in ClassLoader 0xffb15244
 java.lang.Runtime.loadLibrary0(Runtime.java:989)
java.lang.System.loadLibrary(System.java:1530)

这个crash发生在application初始化时的 System.loadLibrary("stlport_shared");
        System.loadLibrary("marsxlog");  测试过程中从来没出现过，放线上大概出现了有400个crash，怀疑和bugly有关系

**Comment by garryyan** [comment]
看下你依赖的库里是否有多个libstlport_shared.so

**Comment by liangxianshen** [comment]
没有 只有一个，依赖库？我拆包看的

**Comment by garryyan** [comment]
看错误信息是不同的classload load libs导致的，查看你使用的其他第三方库，比如bugly，是否也依赖了libstlport_shared.so

**Comment by ChanJLee** [comment]
检查是否跟热修复有关？jvm是不允许同一个so被多个class loader载入的。解决方案就是在system.load...的地方加try catch

**Comment by liangxianshen** [comment]
嗯嗯 懂了

**Comment by JackyAndroid** [comment]
@garryyan libstlport_shared.so 如果会被其他第三方库加载，什么方式处理比较好？手动load so库，然后加try catch 吗？

**Comment by JackyAndroid** [comment]
@liangxianshen 最后你们是怎么解决的？
