### ISSUE TITLE
samples windows 在vs2013下编不过 

### ISSUE THREAD

**Issue by szmile2008** [Tencent/mars#324]
4>g:\workspace\git-prj\open_source\tencent_mars\mars\stn\stn_logic.cc(329): error C2457: “__FUNCSIG__”:  预定义的宏不能出现在函数体的外部
4>  net_channel_factory.cc
4>g:\workspace\git-prj\open_source\tencent_mars\mars\stn\src\net_channel_factory.cc(36): error C2457: “__FUNCSIG__”:  预定义的宏不能出现在函数体的外部
4>  flow_limit.cc
4>g:\workspace\git-prj\open_source\tencent_mars\mars\stn\src\flow_limit.cc(29): fatal error C1017: 无效的整数常量表达式
4>  正在生成代码...
6>------ 已启动生成:  项目: Sample, 配置: Debug Win32 ------
6>  Sample.cpp
6>g:\workspace\git-prj\open_source\tencent_mars\samples\windows\wrapper\cgitask.h(37): error C2061: 语法错误: 标识符“uint32_t”
6>g:\workspace\git-prj\open_source\tencent_mars\samples\windows\wrapper\cgitask.h(38): error C2061: 语法错误: 标识符“uint32_t”

**Comment by szmile2008** [comment]
Visual Studio 2013 - Windows XP (v120_xp)   编译平台改成了这个 , 是不是一定要安装vs2015?

**Comment by garryyan** [comment]
其他vs版本没试过，建议使用vs2015.有些特性低版本的不支持

**Comment by szmile2008** [comment]
用vs2015编 过了， 但是sample 创建socket 失败了， 请问一下windows现在支持ok了吗？

**Comment by garryyan** [comment]
已经支持ok了， 创建socket失败是因为服务器没有搭建， 查看wiki中的sample使用说明，自己把服务器搭建起来
