### ISSUE TITLE
日志格式 & 刷新日志时机疑问

### ISSUE THREAD

**Issue by JackyAndroid** [Tencent/mars#325]
已通读wiki和相关issue

1. 关于日志格式每条都会有这样[, , 0]的字符，wiki没有解释，请问这个代表什么意思？
2. 目前Android平台大多数应用返回后都是保持在后台运行，微信也是这样，如果被系统杀死是没有任何通知和回调的，那appenderFlush、appenderClose在微信是什么时机回调，如果没办法保证一定会回调这两个接口会出现什么问题？

**Comment by wustwg** [comment]
关于xlog，我也看了wiki和博客，说一下我的理解吧。
1.这个我看了代码，[,,0]表示的是文件名 函数名为空。行号0，官方提供的java日志库不太好用，默认没有类名 方法 行号，所以建议自己将官方的log.java取出来，手动修改支持行号打印。这个不难
2.官方说了是用mmap来实现的缓存，而不是用maap映射整个日志文件。我推测 appenderFlush应该是将mmap映射缓存中的日志刷新到日志文件中去；appenderClose是表示不再写日志到文件了，程序退出时用(我没找到合适的调用时机)。appenderFlush在你程序进入后台的时候调用可能比较合适
假如程序被杀了，没来得及调用这两个接口，也只会导致缓存中存留的有日志，下次程序重新启动时会再将缓存中的日志重新刷新到日志文件中去。不用太担心

以上是我自己的理解，如果有哪里说的不对的还望多指教。

**Comment by garryyan** [comment]
@wustwg 理解是对的。
1. java层面不是不能提供行号等信息，但是考虑到需要每次都要取stack才能取到这些信息，不像C的__FILE__ __LINE__ 有内置宏。 而日志比较频繁使用的功能，所以担心频繁去读取stack会影响性能，所以现在微信也是没有文件名和行号的，是通过tag来区分是哪个文件的日志的
2. 程序退出和捕捉到异常要退出的时候调用appenderClose。  appenderFlush 是把mmap缓存中的内容刷到文件中，在你需要的时候调用就可以。

**Comment by JackyAndroid** [comment]
多谢😊
