### ISSUE TITLE
Android x86 交叉编译后，运行出现signal 6 (SIGABRT), code -6 (SI_TKILL)

### ISSUE THREAD

**Issue by jeffdinglei** [Tencent/mars#327]
请问该如何处理？具体log如下
Build fingerprint: 'google/sdk_google_phone_x86/generic_x86:7.1.1/NYC/4316688:user/release-keys'
11-22 13:58:45.043 17552-17552/? A/DEBUG: Revision: '0'
11-22 13:58:45.043 17552-17552/? A/DEBUG: ABI: 'x86'
11-22 13:58:45.043 17552-17552/? A/DEBUG: pid: 17537, tid: 17537, name:  >>> <<<
11-22 13:58:45.043 17552-17552/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-22 13:58:45.043 17552-17552/? A/DEBUG:     eax 00000000  ebx 00004481  ecx 00004481  edx 00000006
11-22 13:58:45.043 17552-17552/? A/DEBUG:     esi b1be558c  edi b1be5534
11-22 13:58:45.043 17552-17552/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
11-22 13:58:45.043 17552-17552/? A/DEBUG:     eip b1b11424  ebp bfb4d598  esp bfb4d53c  flags 00200296
11-22 13:58:45.044 17552-17552/? A/DEBUG: backtrace:
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #00 pc ffffe424  [vdso:b1b11000] (__kernel_vsyscall+16)
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #01 pc 0007a03c  /system/lib/libc.so (tgkill+28)
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #02 pc 00075885  /system/lib/libc.so (pthread_kill+85)
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #03 pc 0002785a  /system/lib/libc.so (raise+42)
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #04 pc 0001ee36  /system/lib/libc.so (abort+86)
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #05 pc 00022a5b  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #06 pc 0002167b  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #07 pc 00024482  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #08 pc 000226d2  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #09 pc 0001a70e  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #10 pc 00014806  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #11 pc 00014a33  /data/app/-1/lib/x86/libmarsxlog.so
11-22 13:58:45.044 17552-17552/? A/DEBUG:     #12 pc 000109a9  /data/app/-1/lib/x86/libmarsxlog.so (_Z13appender_open13TAppenderModePKcS1_+185)
11-22 13:58:45.045 17552-17552/? A/DEBUG:     #13 pc 00011b7d  /data/app/-1/lib/x86/libmarsxlog.so (_Z24appender_open_with_cache13TAppenderModeRKSsS1_PKc+2381)
11-22 13:58:45.045 17552-17552/? A/DEBUG:     #14 pc 0000654a  /data/app/-1/lib/x86/libmarsxlog.so (Java_com_tencent_mars_xlog_Xlog_appenderOpen+442)
11-22 13:58:45.045 17552-17552/? A/DEBUG:     #15 pc 031b19c6  /data/app/-1/oat/x86/base.odex (offset 0x2d50000)

**Comment by garryyan** [comment]
必现吗？  还有 使用ndk-stack或者addr2line 对应出来代码行号

**Comment by obliviosn** [comment]
需要支持cmake工具构建（android)，直接使用android studio调试c++代码，方便自定义协议用户。
有需要的可以参考: https://github.com/obliviosn/Mars
