### ISSUE TITLE
iOS集成xlog，报错：'micro-ecc-master/uECC.h' file not found, 'limits' file not found

### ISSUE THREAD

**Issue by xiaobt** [Tencent/mars#330]
Mac OS Sierra， 版本10.12.6
XCode Version 9.1 (9B55)

**Comment by garryyan** [comment]
mars/log/crypt/micro-ecc-master/uECC.h  查看下这个文件在你项目里是否存在

**Comment by xiaobt** [comment]
谢谢了，我找到了这个文件；
还有一个问题请教一下哈，如果要在OC的.m文件中使用xlog相关的接口（如xdebug2，xinfo2等），必须得将.m文件重命名.mm文件，请问一下有没有可以直接调用的OC接口，而不用改成.mm？
