### ISSUE TITLE
python build_android.py 出错

### ISSUE THREAD

**Issue by lhb05hust** [Tencent/mars#331]
ndk mac r14 

make: Entering directory `/Users/uc/work/xlog/mars/mars/comm'
[armeabi] Compile++ thumb: comm <= http.cc
[armeabi] Compile thumb  : comm <= md5.c
[armeabi] Compile++ thumb: comm <= memdbg.cc
[armeabi] Compile++ thumb: comm <= mmap_util.cc
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
make: *** Waiting for unfinished jobs....
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'?
      [-Werror,-Wunknown-warning-option]

**Comment by garryyan** [comment]
换 ndk-r11c看是否有问题，如果还有 参考 https://github.com/Tencent/mars/issues/289
