### ISSUE TITLE
iOS 自定义的几个文件不被调用

### ISSUE THREAD

**Issue by MickeyHub** [Tencent/mars#332]
iOS自定义了 longlink_packer stn_callback文件没有被mars库调用，这是为什么

**Comment by garryyan** [comment]
1. longlink_packer  mars不会自带实现，如果没有实现的话，会链接不过。所以加点日志或者调试看下吧
2. 自定义了stn_callback之后 是否通过 mars::stn::SetCallback 设置进去

**Comment by MickeyHub** [comment]
查看了一下，是在+load方法里调用了createMars方法
