### ISSUE TITLE
何种情况下Mars长链会主动断掉

### ISSUE THREAD

**Issue by cloderW** [Tencent/mars#336]
根据抓包观察当服务器某一次seq请求长时间没有返回时，mars发起 FIN包 主动断开长链，然后进行重连，当发生4次以后就不主动发起连接了，如何保证这种情况不断掉连接。

**Comment by garryyan** [comment]
当请求服务器长时间不回的话，mars会认为这个连接有问题，会断开重连，但是考虑到耗电和流量的问题，并不会频繁的连接，会有自动重连的逻辑控制。

这里的问题应该查一下，为什么长时间不返回？

**Comment by SheepYang1993** [comment]
请问下，mars发给服务端的每次请求，服务端都必须响应吗？

**Comment by medusar** [comment]
@SheepYang1993 问下这个问题怎么解决的呢？
