### ISSUE TITLE
iOS XLog是否有bitcode支持?

### ISSUE THREAD

**Issue by vitosubXX** [Tencent/mars#337]

**Comment by vitosubXX** [comment]
mars.framework/mars(Reachability.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)

**Comment by garryyan** [comment]
编译脚本中
```
iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "")
```
改为
```
iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "-fembed-bitcode")
```

**Comment by vitosubXX** [comment]
谢谢解答!

**Comment by momoliyao** [comment]
> 编译脚本中
> 
> ```
> iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "")
> ```
> 
> 改为
> 
> ```
> iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "-fembed-bitcode")
> ```
请问这个应该在那个文件中修改，我在Mars全局搜索了一下，没有搜到这行相关代码；
我在使用最新的framework，依然需要关掉bitcode

**Comment by vitosubXX** [comment]
> > 编译脚本中
> > ```
> > iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "")
> > ```
> > 
> > 
> > 改为
> > ```
> > iphone_xlog_project = Project(RELATIVE_PATH + "mars-log-iphone.xcodeproj", "iphone", set(["Release-iphoneos", "Release-iphonesimulator"]), "mars", "mars.framework", "-fembed-bitcode")
> > ```
> 
> 请问这个应该在那个文件中修改，我在Mars全局搜索了一下，没有搜到这行相关代码；
> 我在使用最新的framework，依然需要关掉bitcode

mars/build_ios.py
line 15:
`IOS_BUILD_OS_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DIOS_PLATFORM=OS -DIOS_ARCH="armv7;arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 && make -j8 && make install'`
改为：
`IOS_BUILD_OS_CMD = 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DIOS_PLATFORM=OS -DIOS_ARCH="armv7;arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=1 -DENABLE_VISIBILITY=1 && make -j8 && make install'`

**Comment by tanpengsccd** [comment]
请问如何编译同时含有arm64 x86_64的库呢？
