### ISSUE TITLE
iOS 工程编译不过啊

### ISSUE THREAD

**Issue by tianyouhui** [Tencent/mars#34]
mars/mars/log/src/appender.cc:68:10: 'mars/comm/verinfo.h' file not found

#include "mars/comm/verinfo.h"
找不到该文件啊，搜了一下，只在sample/win32 里有。。。

**Comment by tianyouhui** [comment]
是我错了。我直接打开的xcode工程，没有生成verinfo.h，用脚本编译了就好了。我错了

**Comment by garryyan** [comment]
@tianyouhui 我们疏忽了，已经加上了verinfo.h  即使不用脚本 自己xcode项目文件也能编译成功 932ada900e9213cb254984d808b516a69544e447
