### ISSUE TITLE
python crypt decompressor.decompress error -3

### ISSUE THREAD

**Issue by baiiu** [Tencent/mars#341]
when crypt *.xlog, here is the crash info.

Traceback (most recent call last):
  File "/Users/baiiu/Desktop/mars-master/mars/log/crypt/decode_mars_nocrypt_log_file.py", line 113, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(decompress_data))
error: Error -3 while decompressing: invalid distance too far back
Traceback (most recent call last):
  File "/Users/baiiu/Desktop/mars-master/mars/log/crypt/decode_mars_nocrypt_log_file.py", line 113, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(decompress_data))
error: Error -3 while decompressing: invalid distance too far back

**Comment by garryyan** [comment]
Is it a problem by chance or inevitable ?

**Comment by baiiu** [comment]
在华为Honor Magic机器(Honor NTS-AL00, 6.0)上发现的，我们在排查问题时发的特殊包在代码中打的日志，两台机器都是这样。

**Comment by garryyan** [comment]
全部日志都解不出来？还只是一部分日志解不出来

**Comment by baiiu** [comment]
全部日志，解出来的文件就一句话：error: Error -3 while decompressing: invalid distance too far back，好像是这个

**Comment by garryyan** [comment]
能重现？一般这种是文件内容已经坏了，或者用的解密脚本不对。

**Comment by baiiu** [comment]
恩，这个机器感觉有点与众不同。应该是文件损坏了。
