### ISSUE TITLE
targetSdkVersion >=23 xlog 踩坑

### ISSUE THREAD

**Issue by kamaelyoung** [Tencent/mars#344]
如果在 Application 中初始化xlog 又没有授权， 程序会停在 启动页 
logcat 打印：
 I/MultiDex: VM with version 2.1.0 has multidex support
 I/MultiDex: install
 I/MultiDex: VM has multidex support, MultiDex support library is disabled.

临时解决方案：

application oncreate 的时候 
 if (EasyPermissions.hasPermissions(getBaseContext(), permissions)) {
      initLogger();
  }
检查权限 如果又存储权限 初始化 xlog

如果没有的话  申请权限 在申请权限结果中 如果有存储权限  去执行 初始化权限 

大家有没有更好的思路

**Comment by garryyan** [comment]
能看下logcat 卡在什么位置了吗。即使没权限会创建文件失败，不会卡才对

**Comment by alwaystest** [comment]
直接放到 `/sdcard/Android/data/your.package/files/xlog` 不行的吗？
Log这种东西，程序卸载了的话，也不应该留在系统中的。
写Log这种操作就没必要申请权限了吧。

**Comment by garryyan** [comment]
sample只是范例下怎么使用xlog，至于路径你可以随意传的
