### ISSUE TITLE
xlog日志文件解析失败

### ISSUE THREAD

**Issue by xtxh** [Tencent/mars#349]
执行 python ~/xlog/decode_mars_log_file.py ~/xlog/Test_20171227.xlog 之后，没有显示任何错误，也没有生成对应的文件

**Comment by garryyan** [comment]
日志是否用了加密？ 用了加密的话，key和解密脚本是否对应

**Comment by xtxh** [comment]
是直接对mars里面提供的sample项目的日志文件进行操作的，并没有做任何更改

**Comment by garryyan** [comment]
wiki里有提到 不设置key的情况下使用另外一个脚本解密

**Comment by xtxh** [comment]
是copy_log_export.py文件吗？这个我也试过了，也不行

**Comment by garryyan** [comment]
decode_mars_nocrypt_log_file.py

仔细读wiki哦  亲

**Comment by xtxh** [comment]
好的，感谢！

**Comment by xtxh** [comment]
感谢耐心回复，问题已解决！👍🏻
