### ISSUE TITLE
auth首次认证失败，20s超时后，立即success，求解答？

### ISSUE THREAD

**Issue by ronindong** [Tencent/mars#350]

**Comment by ronindong** [comment]
登录之前，首次启动app，使用默认账号auth成功后，如何快速的切换到别的账号进行连接？？？？

**Comment by garryyan** [comment]
提问issue的时候请详细描述问题出现的场景，平台。表现，以及自己的分析，附上xlog日志更好。

**Comment by ronindong** [comment]
android平台，首次登录时，使用默认账号连接成功后，开始登录，使用新的账号进行连接，就需要20s超时之后，才能auth成功

**Comment by garryyan** [comment]
如果输入账号密码的话，应该和网络无关。 能看出来在哪里等了20s吗  看下xlog日志你的cgi为什么会等20s

**Comment by ronindong** [comment]
这个问题解决了，是因为mars task ID是从0开始计数引起的。

**Comment by VectorWen** [comment]
@ronindong 如何鉴权的呀？
