### ISSUE TITLE
Mars server 启动失败, 报这个错误：plugin with id 'retty' not found

### ISSUE THREAD

**Issue by tyl210110** [Tencent/mars#355]
Mars server 启动失败, 报这个错误：plugin with id 'retty' not found，要怎么解决？

**Comment by garryyan** [comment]
是Plugin with id 'jetty' not found.吧 。看下你的gradle版本
* 使用gradle 4.0 以下版本
* 使用 Gretty插件

**Comment by tyl210110** [comment]
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.7.3'
    }
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'jetty'
apply plugin: 'com.google.protobuf'

import org.apache.tools.ant.taskdefs.condition.Os
import groovy.transform.Field

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
        proto {
            // In addition to the default 'src/main/proto'
            srcDir 'src/main/proto'
        }
    }
}

jettyRun {
    contextPath = '/'
    httpPort = 8080    // Port for test
    stopPort = 9090
    stopKey = 'stopKey'
}

jettyStop {
    stopPort = 9090
    stopKey = 'stopKey'
}


protobuf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:2.6.1'
    }
    generatedFilesBaseDir = "$projectDir/src"
}

dependencies {
    testCompile 'junit:junit:4.11'
    testCompile 'org.glassfish.jersey.core:jersey-client:2.14'
    testCompile 'commons-codec:commons-codec:1.9'
    compile 'org.glassfish.jersey.containers:jersey-container-servlet:2.14'
    compile 'com.google.protobuf:protobuf-java:2.6.1'
    compile 'commons-codec:commons-codec:1.9'
    compile 'org.apache.commons:commons-lang3:3.1'
    compile 'org.apache.commons:commons-io:1.3.2'
    compile 'io.netty:netty-all:4.0.4.Final'
    compile 'org.xerial:sqlite-jdbc:3.7.2'
    compile 'apache-log4j:log4j:1.2.15'
}

task nettyRun(type: JavaExec, dependsOn: ['classes']) {
    main = 'com.tencent.mars.proxy.ProxyServer'
    classpath = sourceSets.main.runtimeClasspath
}

@Field
def WEBSERVER = 1;

@Field
def PROXYSERVER = 2;

def createStartScript(int serverType) {

    def reversePort = serverType == WEBSERVER ? 8081 : 8080;
    def fileName = serverType == WEBSERVER ? "start-web-server" : "start-proxy-server";
    def runtty = serverType == WEBSERVER ? "jettyRun" : "nettyRun";

    def cmdFile;
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        cmdFile = "${buildDir}/tmp/" + fileName + ".bat" as File
    }
    else if (Os.isFamily(Os.FAMILY_MAC)) {
        cmdFile = "${buildDir}/tmp/" + fileName + ".command" as File
    }
    else {
        cmdFile = "${buildDir}/tmp/" + fileName + ".sh" as File
    }

    cmdFile.delete();
    cmdFile.createNewFile();

    cmdFile.append("adb reverse --remove tcp:" + reversePort + "\n")
    cmdFile.append("adb reverse tcp:" + reversePort + " tcp:" + reversePort + "\n")
    cmdFile.append("cd ${rootDir}\n")

    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        cmdFile.append(rootDir.getAbsolutePath().substring(0, rootDir.getAbsolutePath().indexOf(":") + 1) + "\n")
        cmdFile.append("gradlew.bat " + runtty)
    }
    else if(Os.isFamily(Os.FAMILY_MAC)) {
        cmdFile.append("./gradlew " + runtty)
        print "chmod a+x ${cmdFile}".execute().text
        print "open ${cmdFile}".execute().text
    }
    else if(Os.isFamily(Os.FAMILY_UNIX)) {
        cmdFile.append("./gradlew " + runtty)
    }


}

task startWebServer(dependsOn: ['compileJava', 'jettyStop']) {
    doLast {
        createStartScript(WEBSERVER)

    }
}

task startProxyServer(dependsOn: 'startWebServer') {
    doLast {
        createStartScript(PROXYSERVER)

        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            def cmdFile = "${buildDir}/tmp/start.bat" as File
            cmdFile.delete()
            cmdFile.createNewFile()

            cmdFile.append("cd ${buildDir}/tmp/\n")
            cmdFile.append("start start-proxy-server.bat\n")
            cmdFile.append("start start-web-server.bat\n")
            print "${cmdFile}".execute().text
        }
        else if (Os.isFamily(Os.FAMILY_MAC)) {

        }
        else if (Os.isFamily(Os.FAMILY_UNIX)) {
            def cmdFile = "${buildDir}/tmp/start.sh" as File
            cmdFile.delete()
            cmdFile.createNewFile()

            cmdFile.append("cd ${buildDir}/tmp/\n")

            cmdFile.append("chmod a+x start-proxy-server.sh && nohup ./start-proxy-server.sh > proxyRun.log&\n")
            cmdFile.append("chmod a+x start-web-server.sh && nohup ./start-web-server.sh > webRun.log&\n")
            print "chmod a+x ${cmdFile}".execute().text
            print "${cmdFile}".execute().text
        }
    }
}

task clean(dependsOn: 'jettyStop') << {

}
![20180104142307](https://user-images.githubusercontent.com/5423204/34552162-d35b3bc4-f15a-11e7-987c-7a9f4a4445ab.png)

**Comment by tyl210110** [comment]
![1](https://user-images.githubusercontent.com/5423204/34552289-88398fc8-f15b-11e7-8086-3806a0b8b975.png)
![2](https://user-images.githubusercontent.com/5423204/34552290-88e303f0-f15b-11e7-9ac6-399ac2918023.png)
![3](https://user-images.githubusercontent.com/5423204/34552291-895b3b72-f15b-11e7-8181-b6f1b572328c.png)
![4](https://user-images.githubusercontent.com/5423204/34552292-8a7d5b2a-f15b-11e7-9396-d6fd455d5f30.png)
![20180104142307](https://user-images.githubusercontent.com/5423204/34552293-8b4c03a8-f15b-11e7-876a-a03eae4afd07.png)

**Comment by garryyan** [comment]
echo %PATH%  看看你命令行用的gradle来自哪里

**Comment by tyl210110** [comment]
![tim 20180104161851](https://user-images.githubusercontent.com/5423204/34555090-fac58a9c-f16a-11e7-874f-8ec50ac6e7c5.png)

**Comment by garryyan** [comment]
挂代理了吗？可能需要访问墙外下载

**Comment by tyl210110** [comment]
没挂代理，用AndroidStudio导入的，在编辑器里面 同步gradle 是已经成功的了，没有报错信息，但是jettyrun的时候就报错了

**Comment by garryyan** [comment]
我这边没能重现这个问题，你试着改成Gretty试试
