### ISSUE TITLE
(iOS)客户端定制的心跳时间间隔为1分钟,把网断掉之后,通过控制台打印的日志看到一秒发两次网络请求,这个在断网的情况下能手动把socket重连关掉,有网了再打开吗?

### ISSUE THREAD

**Issue by pwf2006** [Tencent/mars#359]
<img width="923" alt="bf732709-3cf0-4ca2-9c4c-d51006bee3fb" src="https://user-images.githubusercontent.com/7309976/34663832-c6fdce46-f493-11e7-8060-fbcf5c09416a.png">

**Comment by garryyan** [comment]
心跳间隔和重连间隔无关。而且重连不会频繁到一秒钟重连两次的。确定是在重连吗

**Comment by pwf2006** [comment]
Mars重连的间隔是怎么样的一个策略呢?

**Comment by garryyan** [comment]
https://github.com/Tencent/mars/blob/master/mars/stn/src/longlink_connect_monitor.cc#L65
