### ISSUE TITLE
XLog,程序退出后反初始化，再次打开后log失效。

### ISSUE THREAD

**Issue by 328629033** [Tencent/mars#365]
如题。

**Comment by JaySX** [comment]
您好，请问解决了吗

**Comment by garryyan** [comment]
什么平台？再次打开失效是什么样的表现

**Comment by 328629033** [comment]
Android, console没有输出，日志文件不会更新。

**Comment by garryyan** [comment]
是否是多进程应用？ 确认appenderopen和setConsoleLogOpen了吗？

**Comment by 328629033** [comment]
@garryyan 只在主进程进行了调用，appenderopen 和 setColsoleLogOpen都已打开，第 一次是正常的，并且不调用appenderclose退出也是正常的，但调用后再打开log就没作用了。

**Comment by garryyan** [comment]
只在主进程调用，只对主进程生效。除非你调用了appenderclose之后，你自己的进程没有退出

**Comment by 328629033** [comment]
多谢，是进程没有退出的原因。
