### ISSUE TITLE
The connected rtt time in log is negative

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#37]
The log of connected rtt time is negative.
So I found the src code and change the place of log print.
See the pull request.  #36 

![2016-12-29 10 27 14](https://cloud.githubusercontent.com/assets/10632522/21546267/a7d20dfe-ce18-11e6-8ab5-0060bd5a816a.png)

![2016-12-29 10 30 46](https://cloud.githubusercontent.com/assets/10632522/21546290/d2c99ce8-ce18-11e6-946b-01291bb34128.png)

**Comment by garryyan** [comment]
thanks, good job.
#36
