### ISSUE TITLE
关于CommFrequencyLimit的问题

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#372]
// true pass, false limit
bool CommFrequencyLimit::Check() {
    uint64_t now = ::gettickcount();
    if (!touch_times_.empty() && (now<touch_times_.front()) ) { //if user modify the time, amend it
    	xwarn2(TSF"Must be modified time.now=%_", now);
    	size_t size = touch_times_.size();
    	touch_times_.clear();
    	for (size_t i=0; i<size; ++i) {
    		touch_times_.push_back(now-1);
    	}
    }

    if (touch_times_.size() <= count_) {
        touch_times_.push_back(now);
        return true;
    }

此类的功能我想的话是在一段时间间隔内，能够触发的次数，但是不理解上面的判断语句为什么是<= 而不是<

**Comment by garryyan** [comment]
小于和小于等于都行, 边界的衡量不同
