### ISSUE TITLE
xlog的解压，除了python脚本可用，有c或者java版的解压方法吗？

### ISSUE THREAD

**Issue by chwnFlyPig** [Tencent/mars#375]
如题：xlog的解压，除了python脚本可用，有c或者java版的解压方法吗？
我们想在APP上查看xlog文件。目前生成的xlog文件只是进行了压缩。求给一个java版的解压方法。

**Comment by garryyan** [comment]
没有的，需要牵扯到比较多的第三方库，所以没提供
