### ISSUE TITLE
编译android版本编译出来的libcryptowrapper.a库没有包含libcrypto.a

### ISSUE THREAD

**Issue by zhangjgbupt** [Tencent/mars#376]
使用mars/libraries目录下的脚本build_android.py编译armeabi-v7a类型的静态库，编译结果在mars/libraries/mars_android_sdk/mars_libs/armeabi-v7a/目录下，libcryptowrapper.a库文件不包含libcrypto.a， 使用的时候总是连接错误

**Comment by garryyan** [comment]
.a库不相互包含的，必须还要链接一个libcrypto.a。 mars中现在应该是没用这两个库的，后面会移除掉，你是用到了自己代码中了吗？

可以自己通过openssl 1.02k编译一个armeabi-v7a的.a来链接。 mars/openssl/openssl_lib_android/目录下有个armeabi的库，你可以先用来调试试试，但不确认用到v7a上是否可以用

**Comment by Yensan** [comment]
我下载了 Win32OpenSSL-1_1_0h.exe， 然后这个算出来，和你们的结果完全不一样。
难道我用错了吗

**Comment by garryyan** [comment]
算的什么？

**Comment by Yensan** [comment]
@garryyan  Ecdh。排查出来了，是 openssl 版本不对。我用的是 1.1X，你上面提到了 1.0X，我后来改为 1.0.2o，就对了
不过， 还是很难找到 Windows VC++ 64 编译的 libeay.dll，目前只能在 win32 跑。你们提供的是 libeay32.lib

**Comment by Billchen28** [comment]
> .a库不相互包含的，必须还要链接一个libcrypto.a。 mars中现在应该是没用这两个库的，后面会移除掉，你是用到了自己代码中了吗？
> 
> 可以自己通过openssl 1.02k编译一个armeabi-v7a的.a来链接。 mars/openssl/openssl_lib_android/目录下有个armeabi的库，你可以先用来调试试试，但不确认用到v7a上是否可以用

最近修改longlink.cc使用pay_openssl_crypto_util里面提供的ecdh函数进行密钥交换，使用MacDemo进行调试，并且通过。但现在卡在了android的编译和ios的编译里面。安卓方面，已经修改了Android.mk，打开了openssl_crypto和crypto_wrapper在marsstn里面LOCAL_STATIC_LIBRARIES增加了这两个静态库的依赖，并且nm了crypto_wrapper存在类似`00000000 T _ZN12mmpaycertlib17OpenSslCryptoUtil14GenEcdhKeyPairERSsS1_`的符号，但是最终还是报错：
`error: undefined reference to 'mmpaycertlib::OpenSslCryptoUtil::GenEcdhKeyPair(std::string&, std::string&)'`等相关函数没有链接进去的错误，ios的链接还没研究，是不是arm的openssl库没有预置进去？请指点。

**Comment by garryyan** [comment]
网上有很多文章都有写怎么编译 win64的。
