### ISSUE TITLE
怎么保存群聊中各个用户信息

### ISSUE THREAD

**Issue by harleyxt** [Tencent/mars#378]
根据mars心跳包机制，没有body，无法向服务端传用户信息。
我目前实现的逻辑是，用户进入聊天室主动向服务端发送消息，保存ChannelHandlerContext信息。但是如果网络不好的情况下，客户端的可能进行重新连接，netty服务器中的ChannelHandlerContext的id发生变化，和用户关联不上。

**Comment by garryyan** [comment]
看下这个接口的说明[getLongLinkIdentifyCheckBuffer](https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

**Comment by harleyxt** [comment]
@garryyan android客户端里怎么调用getLongLinkIdentifyCheckBuffer这个接口?demo里没有，我不知道调用的时机。

**Comment by garryyan** [comment]
实现 StnLogic.ICallBack 中的接口

**Comment by harleyxt** [comment]
@garryyan StnLogic.ICallBack中的接口已经实现了。但是getLongLinkIdentifyCheckBuffer这个接口的调用是在StnLogic中的私有静态方法getLongLinkIdentifyCheckBuffer中，最后面提到的方法，无任何地方调用。

**Comment by garryyan** [comment]
C++会调用的，看jni接口

**Comment by garryyan** [comment]
这个接口重连后会必调用的，你在这里把用户信息带给服务器，服务器把用户和socket对应起来不就行了

**Comment by harleyxt** [comment]
@garryyan
我在上面的接口实现里，再向服务器发送请求吗？

**Comment by garryyan** [comment]
重连的时候，mars会自动调用这个接口的。然后服务器收到解析就行了

**Comment by harleyxt** [comment]
@garryyan 
    @Override
    public int getLongLinkIdentifyCheckBuffer(ByteArrayOutputStream identifyReqBuf, ByteArrayOutputStream hashCodeBuffer, int[] reqRespCmdID) {
        // Send identify request buf to server
       //identifyReqBuf.write();
        return StnLogic.ECHECK_NOW;
    }
上面是实现，方法里面我应该写什么逻辑。
我实在是迷糊了。。。

**Comment by garryyan** [comment]
identifyReqBuf  写你需要写的数据进去，比如用户的信息。
hashCodeBuffer 一个hash值 可以填md5之类的用于回包校验用的， 如果不校验可以不填
reqCmdID 数据校验的 cmd id，是用户自定义的值，需要上层设置,该数组长度为1，填reqCmdID。

wiki的接口说明里有说的。

**Comment by harleyxt** [comment]
@garryyan 非常感谢，我用identifyReqBuf对象，写了相应数据，服务端接收到了。包括心跳也带我写的信息过来。

**Comment by medusar** [comment]
这逻辑很奇怪，为什么身份校验是通过固定taskId来区分，而心跳是通过cmdid来区分呢?
