### ISSUE TITLE
针对闹钟对齐使用了什么策略优化？

### ISSUE THREAD

**Issue by zengjingfang** [Tencent/mars#383]
你好，我在这边文章[微信终端跨平台组件 Mars 系列 - 我们如约而至](https://github.com/WeMobileDev/article/blob/master/%E5%BE%AE%E4%BF%A1%E7%BB%88%E7%AB%AF%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BB%84%E4%BB%B6%20Mars%20%E7%B3%BB%E5%88%97%20-%20%E6%88%91%E4%BB%AC%E5%A6%82%E7%BA%A6%E8%80%8C%E8%87%B3.md)中有如下叙述：

平台特性优化。虽然 Mars 是跨平台的基础组件，但在很多设计上是需要结合各平台的特性的。例如为了尽量减少频繁的唤醒手机，引入了智能心跳，并且在智能心跳中考虑了 Android 的 alarm 对齐特性(具体实现见smart_heartbeat.cc)。再如在网络切换时，为了平滑切换的过程，使用了 iOS 中网络的特性，在 iOS 中做了延迟处理等。

[smart_heartbeat.cc](https://github.com/Tencent/mars/blob/9bccd66a7204965fa74c7b39383481889419988f/mars/stn/src/smart_heartbeat.cc)

没能明白其中的玄机，还请赐教指点。

**Comment by garryyan** [comment]
会判断是否有 alarm 对齐行为，如果有 alarm 对齐行为，就尽量按照 alarm 的对齐时间来做心跳

**Comment by zengjingfang** [comment]
谢谢回复，alarm 的对齐时间是怎么得知的？是经过闹钟的几次延迟时间做判断去探测？

**Comment by garryyan** [comment]
看函数JudgeMIUIStyle
