### ISSUE TITLE
iOS打包framework中包含mars.framework的问题

### ISSUE THREAD

**Issue by 7General** [Tencent/mars#388]
你好：
     iOS中我们基于mars做了自己公司的app了。现在想要基于mars搞一套SDK出来，现在遇见问题如下。
我们新建了一个framework工程（longlink.framewokr），把mars.framework放到longlink.framework中，这该工程里所有的配置和所需要的资源文件都已经添加上，并且编译通过。可以打包framework。
  当我把打包好的longlink.framework放进新工程里时，同时也把mars.framework一块放进新工程中。我们查看了路劲信息配置都是没问题的，但是就是报的是mars的log和std::的一些问题，，，，

   为了验证framework中包含其他第三方的framework使用和打包流程问题，我特异创建了一个demo，按照现有方式没问题的

  还有mars.framework打包出来的时候支持bitcode吗？

**Comment by shockcao** [comment]
apple  build脚本里支持build with bitcode

**Comment by 7General** [comment]
iOS中我们基于mars做了自己公司的app了。现在想要基于mars搞一套SDK出来，现在遇见问题如下。
我们新建了一个framework工程（longlink.framewokr），把mars.framework放到longlink.framework中，这该工程里所有的配置和所需要的资源文件都已经添加上，并且编译通过。可以打包framework。
当我把打包好的longlink.framework放进新工程里时，同时也把mars.framework一块放进新工程中。我们查看了路劲信息配置都是没问题的，但是就是报的是mars的log和std::的一些问题，，，，

为了验证framework中包含其他第三方的framework使用和打包流程问题，我特异创建了一个demo，按照现有方式没问题的

**Comment by garryyan** [comment]
> 报的是mars的log和std::的一些问题。。。

具体是什么问题？

**Comment by garryyan** [comment]
加好依赖了吗？  这应该是没把mars加进： Link Binary With Libraries

**Comment by captain-black** [comment]
> iOS中我们基于mars做了自己公司的app了。现在想要基于mars搞一套SDK出来，现在遇见问题如下。 我们新建了一个framework工程（longlink.framewokr），把mars.framework放到longlink.framework中，这该工程里所有的配置和所需要的资源文件都已经添加上，并且编译通过。可以打包framework。 当我把打包好的longlink.framework放进新工程里时，同时也把mars.framework一块放进新工程中。我们查看了路劲信息配置都是没问题的，但是就是报的是mars的log和std::的一些问题，，，，
> 
> 为了验证framework中包含其他第三方的framework使用和打包流程问题，我特异创建了一个demo，按照现有方式没问题的

我也遇到一样的问题，主工程引入mars.framework没问题，但是改为在framework子工程里引用就报未定义符号，不解。。。
