### ISSUE TITLE
xlog 日志文件乱码问题，utf8 打开，不使用压缩

### ISSUE THREAD

**Issue by junpengwang** [Tencent/mars#391]
由于项目需求，需要对本地日志文件进行解析，分批上传。遂改了 xlog 源码，默认不压缩日志文件：
 
```
  LogBuffer(void* _pbuffer, size_t _len, bool _is_compress, const char* _pubkey);
```
将调用这个 API 的地方 _is_compress 设置了 false。API 确实生效了，但是确出现了如下图问题。开头与结尾都有乱码，导致在端上无法使用 UTF-8 解析出字符串。

如图：
![1522732474703](https://user-images.githubusercontent.com/13132361/38230587-38341968-3741-11e8-8049-5b74aa365fef.jpg)

**Comment by junpengwang** [comment]
发现直接将 _is_compress 设置为 false，只有中间打印的文本没做压缩。前面的乱码是压缩过的。

**Comment by junpengwang** [comment]
关掉吧，不压缩还需要仔细看代码。

**Comment by garryyan** [comment]
是因为还有日志头部，不压缩 可能还会加密，所以还保留了日志头部

**Comment by junpengwang** [comment]
下午看了一下，看到有 setLogHeader、以及尾部，已经在改，打算把加密部分去掉，改动地方不少。

**Comment by qianxinyi** [comment]
@junpengwang ，Xlog清除文件规则是清除10天后的，有没有针对文件大小加以清除的逻辑啊？

**Comment by junpengwang** [comment]
@qianxinyi 我记得有接口设置缓存文件大小。

**Comment by brady2037** [comment]
> 午看了一下，看到有 setLogHeader、以及尾部，已经在改，打算把加密部分去掉，改动地方不

请问是修改哪里可以把日志头部的乱码删除呢

**Comment by cxMax** [comment]
> > 午看了一下，看到有 setLogHeader、以及尾部，已经在改，打算把加密部分去掉，改动地方不
> 
> 请问是修改哪里可以把日志头部的乱码删除呢

fork了官方的最新版本，进行了修改，解决了不加密，header出现乱码的问题。https://github.com/cxMax/Xlog
可以参考看看，修改方式可以看最近提交的commit记录，写的有问题还请多包涵，问题的话，我在进行修改。

**Comment by iamdennisme** [comment]
> 

master代码是不行的

**Comment by 1iuyan** [comment]
> 下午看了一下，看到有 setLogHeader、以及尾部，已经在改，打算把加密部分去掉，改动地方不少。

遇到同样的问题,请教下都改了哪里?
