### ISSUE TITLE
build static libs fail!!!

### ISSUE THREAD

**Issue by qiangqiang681** [Tencent/mars#392]
编译选择如下：
root@ubuntu:/home/mars/mars/libraries# python build_android.py 
Enter menu:
1. build mars shared libs.
2. build mars static libs.
3. build xlog shared lib with crypt.
4. exit.
3
Enter the architecture which would like to build:
1. armeabi.
2. x86.
3. mips.
4. armeabi-v7a.
5. arm64-v8a.
6. x86_64.
7. mips64.
8. exit.
1
build armeabi
最后会报出以下错误：
arm-linux-androideabi-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
/home/ndk/android-ndk-r11c/build/core/build-binary.mk:462: recipe for target 'obj/local/armeabi/objs/comm/__/anr.o' failed
make: *** [obj/local/armeabi/objs/comm/__/anr.o] Error 4
make: *** Waiting for unfinished jobs....
arm-linux-androideabi-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
/home/ndk/android-ndk-r11c/build/core/build-binary.mk:462: recipe for target 'obj/local/armeabi/objs/comm/__/coroutine/coro_socket.o' failed
make: *** [obj/local/armeabi/objs/comm/__/coroutine/coro_socket.o] Error 4
make: Leaving directory '/home/mars/mars/comm'
build static libs fail!!!

**Comment by SuperXmx** [comment]
@qiangqiang681 这个问题你怎么解决的？

**Comment by SuperXmx** [comment]
我这边也遇到了，我升级g++ 到8版本也不信，麻烦请问下怎么解决的？

**Comment by SuperXmx** [comment]
@qiangqiang681 我这边也遇到了，我升级g++ 到8版本也不信，麻烦请问下怎么解决的？
