### ISSUE TITLE
(Android)动态修改端口号和ip如何处理呢？

### ISSUE THREAD

**Issue by luoyou592** [Tencent/mars#396]

**Comment by garryyan** [comment]
短连直接改就行了。
长连，先改，再重连长连。

**Comment by luoyou592** [comment]
重连就直接MarsServiceProxy.init(...)就ok了是吧

**Comment by garryyan** [comment]
调用 redotasks接口

**Comment by luoyou592** [comment]
调用了，好像并没有修改啊，退出app重新初始化才会修改，我把MarsServiceProxy.init(this, getMainLooper(), null)放在MainActivity,每次退出重新登录进主界面跑init方法好像行不通，是需要在退出时把MarsServiceNative服务干掉吗
