### ISSUE TITLE
(Android)app如何监听wrapper里面的长连接状态呢，需要自己搞多进程通讯吗，还是可以使用现成？

### ISSUE THREAD

**Issue by luoyou592** [Tencent/mars#398]

**Comment by garryyan** [comment]
看wiki中的接口说明，有个回调接口会告诉你状态的

**Comment by luoyou592** [comment]
找到那个接口监听了，现在有个问题就是，我连接上然后断开网络，继续发消息，等触发onTaskEnd后再连接网络，继续发，服务端就解析我的包体异常，cmdid也都停留最后一次发的cmdid，这个是服务端问题，还是客户端哪里要做处理

**Comment by garryyan** [comment]
这个难说，要综合日志分析。实在不行就tcpdump分析
