### ISSUE TITLE
Can I use xlog alone?

### ISSUE THREAD

**Issue by urmyfaith** [Tencent/mars#4]
Can I use `xlog` alone ?

From the architecture in the README,  `xlog` is build on top of the `Com` components.

Or will you separate `xlog` or `STN` into different repo ?

**Comment by shockcao** [comment]
yes xlog and STN are separated
for Android, u can use it by add gradle dependencies   'com.tencent.mars:xlog-1.0.0'
for iOS, u can build it by yourself, use 'python build_apple.py myxloglib'  and select 'build xlog for iphone'
