### ISSUE TITLE
minSdkVersion 冲突, Xlog 里的uses-sdk 能否调低minSdkVersion?

### ISSUE THREAD

**Issue by liveei** [Tencent/mars#40]
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.tencent.mars:mars-xlog:1.0.1] F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\intermediates\exploded-aar\com.tencent.mars\mars-xlog\1.0.1\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.tencent.mars" to force usage

**Comment by shockcao** [comment]
可以将xlog源码和so引入  不使用aar包 自己调低minSdk

**Comment by liveei** [comment]
@shockcao  我想在gradle依赖 :latest.release  放在本地的话, 升级感觉不太方便

**Comment by garryyan** [comment]
@liveei  据我们的统计 16 以下的用户已经极少了，为什么一定要用这么低的 sdkversion呢

**Comment by shockcao** [comment]
@liveei    尝试在自己的代码中建submodule  引入mars，随时关注最新修改？  尝试一下吧？
其实我们发版本肯定是有节奏的，升级的话只需要在发版本的时间节点注意就可以了
