### ISSUE TITLE
能否最后详细帮下我这一个问题，这个问题搞定就任务完成了，拜托了

### ISSUE THREAD

**Issue by luoyou592** [Tencent/mars#400]
在不退出app情况动态修改ip端口的问题, redotasks接口调用了，好像并没有修改啊，退出app重新初始化才会修改，我把MarsServiceProxy.init(this, getMainLooper(), null)放在MainActivity,每次退出重新登录进主界面跑init方法好像行不通，是需要在退出时把MarsServiceNative服务干掉吗。mars有没有详细解决方案呢

**Comment by garryyan** [comment]
#396 不要重复提issue。
先设置 ip， 再调用redotasks。  如果没生效看下日志时序是否有问题。实在不行 也可以先设置ip再调用reset。

为什么行不通 有什么错误，详细描述下

**Comment by luoyou592** [comment]
StnLogic.redoTask();执行这个方法，没看到监听连接的日志打印

**Comment by garryyan** [comment]
看下mars打的日志

**Comment by luoyou592** [comment]
marsservice D/HwCust: Create obj success use class android.telephony.HwCustSignalStrengthImpl
04-26 11:28:05.951 9819-9833/com.tuoling.allchat:marsservice D/HwCust: Create obj success use class android.telephony.HwCustSignalStrengthImpl
04-26 11:28:10.950 9819-10087/com.tuoling.allchat:marsservice D/luoyou: SERVER_FAILED
04-26 11:28:11.013 9819-10152/com.tuoling.allchat:marsservice D/luoyou: onNewsDns
04-26 11:28:11.015 9819-10150/com.tuoling.allchat:marsservice D/luoyou: CONNECTTING
不停打印这鞋东西

**Comment by garryyan** [comment]
应该有网络底层 mars的日志，如果你打开了xlog的话。要学着分析日志，不然这种出问题不容易排查的

**Comment by luoyou592** [comment]
我在application是有打开的，但是这种日志文件打不开啊

**Comment by garryyan** [comment]
看wiki说明，有说日志怎么解密的

**Comment by luoyou592** [comment]
谢了，还真是进程的问题，我在那独立进程注册了个广播，然后执行redoTask方法生效了
