### ISSUE TITLE
python build_android.py 发生异常

### ISSUE THREAD

**Issue by dotingcode** [Tencent/mars#402]
[armeabi] Compile++ thumb: comm <= http.cc
[armeabi] Compile thumb  : comm <= md5.c
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
make: *** Waiting for unfinished jobs....
[armeabi] Compile++ thumb: comm <= memdbg.cc
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
make: Leaving directory `C:/Users/Administrator/Desktop/mars-1.2.1/mars/comm'
build static libs fail!!!

**Comment by dotingcode** [comment]
是我的编译环境问题造成的吗

**Comment by garryyan** [comment]
使用ndk-r11c

**Comment by dotingcode** [comment]
使用 ndkr11c 编译 依旧发生了这个错误 
D:\ProgramFiles\android-ndk-r11c-windows-x86_64\android-ndk-r11c

**Comment by garryyan** [comment]
你电脑上是不是有多个ndk？

**Comment by dotingcode** [comment]
windows 环境变量 只指向一个ndk

**Comment by garryyan** [comment]
如果是新配置的环境变量，应该是环境变量没生效。
建议 echo %PATH%看下里面配置的是ndk的哪个目录

**Comment by dotingcode** [comment]
客户端环境问题 已经编译通过 多谢
