### ISSUE TITLE
ios xlog 'limits' file not found

### ISSUE THREAD

**Issue by idewindy** [Tencent/mars#403]
xcode版本: 9.1

在string_cast.h文件报错'limits' file not found

**Comment by idewindy** [comment]
c++头文件找不到，我把Compile Sources As 修改为 Objective-C++就好了。我看iOSDemo里面也没有设置它，用的也是默认值，但是偏偏他可以编译通过，不太明白为啥？求解

**Comment by idewindy** [comment]
已解决

**Comment by pamierdt** [comment]
@idewindy 请教一下 您是怎么解决这个问题的

**Comment by boyXiong** [comment]
能说一下 是怎么解决的吗
