### ISSUE TITLE
不回调 reportConnectInfo(int status, int longlinkstatus)

### ISSUE THREAD

**Issue by 1649900265** [Tencent/mars#404]
在网络变化的时候不回调 reportConnectInfo(int status, int longlinkstatus)，是c/c++库还是java里面检测的网络变化呢

**Comment by romchik1617** [comment]
Java.C++.C

**Comment by garryyan** [comment]
看下日志为什么没回调？ 是卡在哪里了吗？还是说没发现网络变化
