### ISSUE TITLE
出现大量的异常

### ISSUE THREAD

**Issue by languangheng** [Tencent/mars#405]
1:30:57.472 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so 0x94fb2bf0
05-22 11:30:57.512 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Added shared lib /data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so 0x94fb2bf0
05-22 11:30:57.622 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libstlport_shared.so 0x94fb2bf0
05-22 11:30:57.622 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Shared lib '/data/app-lib/com.sf.sdk.mars3-1/libstlport_shared.so' already loaded in same CL 0x94fb2bf0
05-22 11:30:57.622 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so 0x94fb2bf0
05-22 11:30:57.622 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Shared lib '/data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so' already loaded in same CL 0x94fb2bf0
05-22 11:30:57.622 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libmarsstn.so 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Added shared lib /data/app-lib/com.sf.sdk.mars3-1/libmarsstn.so 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libstlport_shared.so 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Shared lib '/data/app-lib/com.sf.sdk.mars3-1/libstlport_shared.so' already loaded in same CL 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Shared lib '/data/app-lib/com.sf.sdk.mars3-1/libsfpushxlog.so' already loaded in same CL 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Trying to load lib /data/app-lib/com.sf.sdk.mars3-1/libmarsstn.so 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService D/dalvikvm: Shared lib '/data/app-lib/com.sf.sdk.mars3-1/libmarsstn.so' already loaded in same CL 0x94fb2bf0
05-22 11:30:57.642 2959-2959/com.sf.sdk.mars3:SfPushService I/dalvikvm: threadid=1: recursive native library load attempt (/data/app-lib/com.sf.sdk.mars3-1/libmarsstn.so)
05-22 11:30:57.752 2959-2995/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=15: thread exiting, not yet detached (count=0)
05-22 11:30:57.762 2959-2996/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=15: thread exiting, not yet detached (count=0)
05-22 11:30:57.802 2959-2990/com.sf.sdk.mars3:SfPushService D/dalvikvm: JIT code cache reset in 0 ms (0 bytes 1/0)
05-22 11:30:57.812 2959-2990/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 250K, 9% free 3209K/3512K, paused 2ms, total 9ms
05-22 11:30:57.942 2959-2990/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 361K, 12% free 3347K/3776K, paused 25ms, total 28ms
05-22 11:30:58.052 2959-2990/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 404K, 13% free 3440K/3912K, paused 1ms, total 2ms
05-22 11:30:58.202 2959-2992/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 11:30:58.222 2959-3002/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=15: thread exiting, not yet detached (count=0)
05-22 11:30:58.222 2959-3003/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=15: thread exiting, not yet detached (count=0)
05-22 11:31:02.262 2959-3004/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 480K, 15% free 3436K/3996K, paused 3ms, total 5ms
05-22 11:31:02.262 2959-3004/com.sf.sdk.mars3:SfPushService I/dalvikvm-heap: Grow heap (frag case) to 3.421MB for 16396-byte allocation
05-22 11:31:02.262 2959-2969/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed <1K, 15% free 3451K/4016K, paused 4ms, total 4ms
05-22 11:31:02.312 2959-2994/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 318K, 21% free 3200K/4016K, paused 5ms, total 5ms
05-22 11:31:02.352 2959-2994/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 312K, 16% free 3400K/4016K, paused 2ms, total 3ms
05-22 11:31:02.392 2959-2994/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 432K, 14% free 3479K/4016K, paused 2ms, total 3ms
05-22 11:49:32.502 2959-3001/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 11:49:32.992 2959-3164/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 11:49:32.992 2959-3165/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:08:07.072 2959-3163/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 12:08:07.572 2959-3216/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:08:07.572 2959-3217/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:41.742 2959-3215/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 12:26:42.242 2959-3328/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:42.242 2959-3329/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:50.262 2959-3331/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:50.262 2959-3332/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:50.262 2959-3335/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:26:50.272 2959-2994/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 644K, 18% free 3333K/4044K, paused 4ms, total 4ms
05-22 12:26:50.282 2959-3336/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:27:55.592 2959-3334/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:28:27.732 2959-3347/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:30:57.722 2959-3360/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:33:27.722 2959-3377/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:35:57.732 2959-3393/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:38:27.732 2959-3398/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:40:57.732 2959-3404/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:43:27.732 2959-3409/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:45:20.412 2959-3327/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 12:45:20.912 2959-3446/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:45:20.912 2959-3447/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:45:57.722 2959-3456/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:48:27.732 2959-3495/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:50:57.732 2959-3505/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:53:27.732 2959-3518/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:55:57.732 2959-3523/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 12:58:27.742 2959-3532/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:00:57.732 2959-3548/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:03:27.732 2959-3551/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:03:59.072 2959-3445/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 13:03:59.582 2959-3554/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:03:59.582 2959-3555/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:05:57.732 2959-3558/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:08:27.732 2959-3574/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:10:57.732 2959-3577/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:13:27.732 2959-3580/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:15:57.732 2959-3596/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:18:27.732 2959-3634/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:20:57.732 2959-3641/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:22:37.732 2959-3553/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 13:22:38.232 2959-3676/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:22:38.232 2959-3677/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:23:27.732 2959-3681/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:25:57.732 2959-3688/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:28:27.732 2959-3700/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:30:57.732 2959-3708/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:33:27.732 2959-3716/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:35:57.732 2959-3740/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:38:27.732 2959-3754/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:40:57.742 2959-3759/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:41:16.282 2959-3675/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 13:41:16.282 2959-2990/com.sf.sdk.mars3:SfPushService D/dalvikvm: GC_FOR_ALLOC freed 526K, 18% free 3318K/4044K, paused 2ms, total 4ms
05-22 13:41:16.792 2959-3763/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:41:16.792 2959-3764/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:43:27.742 2959-3771/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:45:57.742 2959-3791/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:48:27.742 2959-3829/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:50:57.742 2959-4230/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:53:27.732 2959-6455/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:55:57.742 2959-8640/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:58:27.732 2959-10827/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:59:54.892 2959-3762/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
05-22 13:59:55.402 2959-12124/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
05-22 13:59:55.402 2959-12125/com.sf.sdk.mars3:SfPushService D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)

**Comment by garryyan** [comment]
如果程序没crash，这里不是异常，是正常日志。 参考 #304
