### ISSUE TITLE
Mars 可以通过 Boost.Python 在 Python 里面直接调用吗？

### ISSUE THREAD

**Issue by lapsule** [Tencent/mars#413]
请问下，Mars 是否可以通过 Boost.Python 的方式直接在 Python 里面调用？多谢。

**Comment by garryyan** [comment]
没有尝试过

**Comment by lapsule** [comment]
有个思路是这样，如果可以通过 Boost.Python 或者其他某种方式在 Py 里面直接调用 mars，是否就有可能比较方便的做 UT？ 我们尝试下，有结果了分享
