### ISSUE TITLE
xlog打印本地日志少一行？？？

### ISSUE THREAD

**Issue by qianxinyi** [Tencent/mars#414]
程序未调用appender_close，为什么查看日志文件始终少一行？如果是缓存在系统中，为什么每次都是差一条？

**Comment by garryyan** [comment]
appender_open传的同步模式还是异步模式？

**Comment by qianxinyi** [comment]
同步模式，也调用了appender_flush()

**Comment by garryyan** [comment]
同步模式xlog不会做缓存的，很可能是缓存在系统中的丢失了，至于你问的为什么每次都差一行，就不太清楚了。

**Comment by qianxinyi** [comment]
好的，我知道了。多谢耐心解答
