### ISSUE TITLE
ios ipv6有问题吗？

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#415]
dns.cc

**Comment by garryyan** [comment]
是有点问题的，没有解析ipv6，只解析了ipv4的ip

**Comment by yuangu** [comment]
我有一个小问题，
这个地方为啥不用hints.ai_family = AF_UNSPEC;替代hints.ai_family = PF_INET;
这样子，__local_ipstack_detect这块代码就不用写了？

**Comment by yuangu** [comment]
memset(&hints, 0, sizeof(hints));
hints.ai_family = AF_UNSPEC;
hints.ai_socktype = SOCK_STREAM;

error = getaddrinfo(host_name.c_str(), NULL, &hints, &result);

**Comment by garryyan** [comment]
因为 我们被运营商找过。 运营商表示，微信这么大的用户量，又没配置ipv6的ip,为什么要去dns ipv6类型的。直接导致dns请求量增加了一倍。

所以这里判断下 当前网络不是ipv6的，就不要去试图请求ipv6了

**Comment by yuangu** [comment]
我刚刚在win10上试了很多遍，并没有请求ipv6的地址。不知道移动平台上会不会也是这样子的？代码贴上，见丑了。
`struct addrinfo hints;
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC; /* v4 or v6 is fine. */
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_protocol = IPPROTO_TCP; /* We want a TCP socket */
  hints.ai_flags = AI_PASSIVE;    /* For wildcard IP address */

								  /* Look up the hostname. */
  struct addrinfo* answer = nullptr;
  int err = getaddrinfo("ipv6.baidu.com", nullptr, &hints, &answer);
 
	  for (struct addrinfo* rp = answer; rp != nullptr; rp = rp->ai_next) {
		  char buff[512] = { 0 };
		  void *ptr;
		  switch (rp->ai_family) {
		  case AF_INET:
			  ptr = &((struct sockaddr_in *) rp->ai_addr)->sin_addr;
			  break;
		  case AF_INET6:
			  ptr = &((struct sockaddr_in6 *) rp->ai_addr)->sin6_addr;
			  break;
		  }
		  inet_ntop(rp->ai_family, ptr, buff, rp->ai_addrlen);
		  printf("%s\n", buff);	
  }
`

**Comment by garryyan** [comment]
因为case没走到AF_INET6吗， 没走到AF_INET6 也只是说明 没解析到ipv6。 可以通过tcpdump一下。 这个事情是很久之前的事情了。

**Comment by yuangu** [comment]
是的，我的网络是ipv4的网络，没有走AF_INET6。我大概明白你的意思，我抓包看一下。
