### ISSUE TITLE
ipv6-复合链接

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#416]
对于IPV6 我使用了你们的 复合链接代码
目前对于IOS手机通过IMAC设置成ipv6的wifi后，
连接时会在函数
TcpClientFSM::PreConnectSelect

int ret = connect(sock_, &(addr_.address()), addr_.address_length());
, PreConnectSelect, 216][close connect err:(51, Network is unreachable), localip:0.0.0.0
tcpclient_fsm.cc 

 , PreConnectSelect, 231][status_:3
[complexconnect.cc 

 , ConnectImpatient, 222][index:0, @0x16FE016C8, addr:(119.90.49.107:8035 

 ), socket:24, close connect err:(51, Network is unreachable), localip:0.0.0.0

**Comment by garryyan** [comment]
complexconnect不会转换ip的，需要传转换之后的ip，所以在使用之前如果是ipv6的网络就传递ipv6的ip
