### ISSUE TITLE
日志文件解压失败

### ISSUE THREAD

**Issue by lixiangkai1987** [Tencent/mars#418]
[F]decode_log_file.py decompress err, unpack_from requires a buffer of at least 2 bytes
~~~~~ end of mmap ~~~~~[7992,7992][2018-06-22 +0800 18:02:07]
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid block type
[F]decode_log_file.py decode error len=20866, result:_buffer[476207]:0 != MAGIC_NUM_START 
[F]decode_log_file.py log seq:2-676 is missing
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid distance too far back

**Comment by xinheqiang** [comment]
我也一直出现 日志文件解压失败的问题：
E:\temp\mars-master\mars\log\crypt>python decode_mars_nocrypt_log_file.py
Traceback (most recent call last):
  File "decode_mars_nocrypt_log_file.py", line 108, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid stored block lengths

模式设置为：Xlog.AppednerModeSync 是正常的； 但设置为Xlog.AppednerModeAsync 就出现上面的错误；使用的是：compile 'com.tencent.mars:mars-xlog:1.0.6' 版本；

**Comment by garryyan** [comment]
是否多进程写了同一个文件

**Comment by xinheqiang** [comment]
没有，就是单进程 写 log

**Comment by garryyan** [comment]
是否必现？

**Comment by zhuxiaogit** [comment]
也出现了，单进程。多线程可以不？

**Comment by garryyan** [comment]
多线程不会存在问题，这个找到原因了吗

**Comment by jiaozebo** [comment]
这个问题依然是存在的,

^^^^^^^^^^Oct 23 2018^^^16:23:04^^^^^^^^^^[8160,8160][2019-03-19 +0800 17:29:40]
del time out files time: 0
get mmap time: 2
MARS_URL: 
MARS_PATH: 
MARS_REVISION: 
MARS_BUILD_TIME: 2018-10-23 16:21:19
MARS_BUILD_JOB: default
log appender mode:0, use mmap:1
[F]decode_log_file.py decode error len=1801, result:log length:2841, buffer[10982]:51 != MAGIC_END 
[F]decode_log_file.py log seq:2-32084 is missing
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid code lengths set

**Comment by quntion** [comment]
我也遇到了相同问题

**Comment by xiaoqi010205** [comment]
我也是，这个要怎么解决呀？
提示：👉[F]decode_log_file.py decode error len=1253
