### ISSUE TITLE
XLog依赖问题

### ISSUE THREAD

**Issue by xuyisheng** [Tencent/mars#42]
请问下，XLog按道理来说应该是一个比较独立的模块，为什么会和其它两个通信模块存在非常严重的耦合关系？

**Comment by garryyan** [comment]
其他两个通信模块依赖Xlog ， Xlog并没有依赖他们两个。  不知道你是什么场景下使用的发现他们的耦合关系，可以详细描述下吗

**Comment by xuyisheng** [comment]
多谢回复 我的意思是  能否将xlog单独抽出来 我想单独编译xlog 但是ndk build一直失败

**Comment by dodola** [comment]
是这样，我在抽的时候发现 openssl 模块和 xlog 也是有依赖

**Comment by dodola** [comment]
但是有脚本可以只编译 xlog 的，虽然它也会编译其他依赖，你用的 ndk 是什么版本 的？

**Comment by garryyan** [comment]
@dodola 应该openssl 依赖xlog吧  xlog不会依赖openssl 目前xlog只依赖comm

**Comment by dodola** [comment]
@garryyan 对的

**Comment by garryyan** [comment]
@dodola 那没关系的，你如果只需要xlog的话  不用看谁依赖了xlog 只看xlog依赖了谁就可以了

**Comment by xuyisheng** [comment]
我编译好了，但是生成的mmap2文件如何打开呢

**Comment by garryyan** [comment]
@xuyisheng mmap文件不需要打开 真正的日志内容在xlog文件里

**Comment by xuyisheng** [comment]
了解 非常感谢 编译相关的东西在Wiki里面，已经集成成功！

**Comment by xuyisheng** [comment]
.xlog文件是二进制文件，需要如何解密打开呢？

**Comment by garryyan** [comment]
@xuyisheng 请阅读 wiki 中的常见问题
