### ISSUE TITLE
你好，请问一下，req2buf()， buf2resp(byte[] buf)这两个回调的意思。

### ISSUE THREAD

**Issue by shaohui93** [Tencent/mars#421]
startTask的时候 会回调回调 req2Buf 进行打包，就是在req2buf()把protobuf模型转换成byte，然后发送,不知道到我的这个理解是否正确。 那么buf2resp(byte[] buf)这个回调是干什么的呢？是否是收到数据之后的回调，然后解析成bean？ 但是我看了Samplek看到收到消息应该是走onPush(int cmdid, byte[] data)呀。

**Comment by garryyan** [comment]
buf2resp  是你先有请求，服务器的回包要走这里，和req2buf对应

onpush是服务器直接通过长连给推消息，客户端并没有请求包与之相对应

**Comment by shaohui93** [comment]
了解，感谢。
