### ISSUE TITLE
Xlog日志文件输出错误

### ISSUE THREAD

**Issue by W2L** [Tencent/mars#422]
Android4.4 模拟器。
日志文件创建正常，输出内容仅如下：

^^^^^^^^^^Oct 12 2017^^^18:38:10^^^^^^^^^^[2491,2491][2018-07-10 +0800 10:47:50]
del time out files time: 0
get mmap time: 1
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f685e74
MARS_BUILD_TIME: 2017-10-12 18:37:49
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1

appender has already been opened. _dir:/storage/sdcard//xxx/xlog 
_nameprefix:xxx_log

write file error:1

**Comment by garryyan** [comment]
重复open了。
