### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/xlog/Xlog

### ISSUE THREAD

**Issue by andyken** [Tencent/mars#425]
System.loadLibrary("marsxlog");这行Debug版本报错：JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/xlog/Xlog。
因为是Debug，所以并不是混淆问题。
由于minSdkversion为15，我是导入Log.java和Xlog.java以及对应的libmarsxlog.so和libstlport_shared.so。

**Comment by andyken** [comment]
怀疑是其他第三方组件引入了xlog，把这行System.loadLibrary("marsxlog");去掉，报错找不到appenderOpen方法

**Comment by andyken** [comment]
已解决，是我引入方式不对

**Comment by liuyongyi0110** [comment]
我也遇到了相同的问题，请问你怎么解决的？

**Comment by Jack-Xiao** [comment]
我也遇到了同样的问题，写下解决方法：不要修改包名和类名
https://github.com/Tencent/mars/issues/620
