### ISSUE TITLE
xlog debug包下文件正常，feature包下文件会乱码问题

### ISSUE THREAD

**Issue by wuzhenmin** [Tencent/mars#428]

**Comment by wuzhenmin** [comment]
没有加密，相同的方式在debug下是正常的，feature包下一直是乱码，feature包有混淆，代码里也加了防混淆。

**Comment by garryyan** [comment]
没加密也有压缩的。 看wiki中说的有两个解密脚本，用那个不加密的解密脚本解一下就行了

**Comment by wuzhenmin** [comment]
试过了，也是不行，跑了脚本后没反应，没有wiki上说的会生成.log文件

**Comment by garryyan** [comment]
怎么跑的脚本？有什么错误信息输出吗

**Comment by wuzhenmin** [comment]
终端，pycharm都跑了，没有错误信息

**Comment by garryyan** [comment]
把日志文件发我邮箱  1173828173@qq.com

**Comment by wuzhenmin** [comment]
发送啦

**Comment by garryyan** [comment]
我这边也解不出来，检查下，你release版本appenderopen的方式，传了什么参数。还有退出程序的时候要调用 close
