### ISSUE TITLE
win32编译不成功

### ISSUE THREAD

**Issue by elliyu** [Tencent/mars#43]
error MSB8020: The build tools for v140 (Platform Toolset = 'v140')
我看编译脚本检查的是vs2013可以编译，但是打开mars.sln会失败。
是还有什么注意事项吗？

**Comment by garryyan** [comment]
#16  1.2将会加上支持

**Comment by kyojre** [comment]
把脚本中VS120COMNTOOLS改成V140COMNTOOLS就可以支持vs2015.
可是，语法检测就有很多错误，win32根本编不出来。
xlog可不可以写一个win32的文章。我是想利用他跨平台的特性。

**Comment by garryyan** [comment]
最新代码已支持win平台
