### ISSUE TITLE
__async_log_thread在写的过程中还是有可能丢日志吧？还是没理解逻辑？

### ISSUE THREAD

**Issue by CodeLife2012** [Tencent/mars#430]
[__async_log_thread](https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L604)
中如果在`sg_log_buff->Flush(tmp); `后崩了，还是会出现丢日志的情况下，只是可能性比较小。
理想是`__log2file`才clear掉原来的buffer。

**Comment by CodeLife2012** [comment]
这样也是为了尽快重用`sg_log_buff`，所以要重用是因为[OpenMmapFile](https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L799)中会 [Pre-allocate the file's backing store](https://github.com/Tencent/mars/blob/master/mars/comm/mmap_util.cc#L72l) 导致新申请一个`mmap`相对耗时。`Pre-allocate backing store` 似乎也是文件系统空间紧张做的优化。但这个优化对整体来说影响挺大的。

**Comment by garryyan** [comment]
> __async_log_thread
中如果在sg_log_buff->Flush(tmp);后崩了，还是会出现丢日志的情况下，只是可能性比较小。
理想是__log2file才clear掉原来的buffer。

是存在这个问题的， 不过出现的概率应该比较小，所以这里就没管
