### ISSUE TITLE
关于大size数据的问题

### ISSUE THREAD

**Issue by kongchen** [Tencent/mars#437]
FAQ中提到：
>**使用了Mars发现接收比较大的数据比较容易失败，是什么原因？**
Mars 主要针对信令数据而设计的，如果一个数据需要接收时间比较长，会被认为超时，建议单个数据包不要超过 64 k

如果业务场景就是希望有一些大size数据的传输，比如一个文件的传输，需要从哪些点入手？
如果简单地调大默认的`DEFAULT_TCP_RECV_TIMEOUT`会有什么影响？

**Comment by garryyan** [comment]
需要调各种超时，不建议使用。比如首包超时 包包超时 总超时
