### ISSUE TITLE
关于日志格式，和Console，File分离

### ISSUE THREAD

**Issue by CityHunterDHY** [Tencent/mars#438]
请问一下，是否能在Java层自定义格式的内容，比如我想记录ThreadName而非tid，此处也想请教一下为什么默认是记录tid而非ThreadName，在检查日志的时候应该是ThreadName应该更加见名知意，官方是如何使用tid的，[,,0]这个内容对我来说也没有什么意义，想去掉这个数据在Java层可行吗。
能否只答应console而不写到file里呢，在debug的时候。虽然写到File也没影响，但是想知道能否只输出到console

**Comment by garryyan** [comment]
可行的，这些java层的日志目前参数都是java传递的

**Comment by CityHunterDHY** [comment]
Java层的tid应该是long，我不能不传这个参数，虽然我可以格式化msg，自己写入想要的消息，但是却不能去除[,,0] [tid] [pid]的显示，想再问一下怎样定义日志文件全局信息，比如appversion，model，osversion等，这些东西写入每一条日志的话冗余太多

**Comment by garryyan** [comment]
你如果自己编so的话，看[appender.cc](https://github.com/Tencent/mars/blob/master/mars/log/src/appender.cc#L872)中有类似的，每次启动写一次

**Comment by CityHunterDHY** [comment]
暂时有些超出能力范围了，感谢。

**Comment by momoliyao** [comment]
你好，我看不太懂appender.cc中的代码，想简单问一下，下面分别是iOS和Android打印出来的日志；想请问时间跟后面跟着的[0, 105553152497856]   和 [7274, 1498]是什么数值
iOS： [I][2019-05-11 +8.0 16:39:54.763][0, 105553152497856][][FMXXlog.mm, -[FMXXlog log:::::], 221][234
Android： [D][2019-05-14 +8.0 16:34:05.550][7274, 1498][FXLog][, , 0][葫芦娃之父

**Comment by garryyan** [comment]
进程号和线程号

**Comment by momoliyao** [comment]
> 进程号和线程号
你好，我修改了formater.cc中的代码，当我删除 `fileneme` 的时候，运行 ` python build_android.py `选择 3 之后，会报错
```
[ 95%] Built target comm
make[1]: *** [CMakeFiles/marsxlog.dir/rule] Error 2
make: *** [marsxlog] Error 2
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!
```
但是只删除 ` strFuncName, _info->line` 不会报错

就是下面这快代码，一删除 filename 字段即报错
```
// _log.AllocWrite(30*1024, false);
        int ret = snprintf((char*)_log.PosPtr(), 1024, "[%s][%s][%s][%s][",  // **CPPLINT SKIP**
                           _logbody ? levelStrings[_info->level] : levelStrings[kLevelFatal], temp_time,
                           _info->tag ? _info->tag : "",
                           filename);
```

**Comment by garryyan** [comment]
前面的%s 格式化的是否也相应的去掉了？

**Comment by momoliyao** [comment]
> 前面的%s 格式化的是否也相应的去掉了？
谢谢你
不好意思，找到原因了，说定义了filename，但是没有用到，然后就编译报错了，报错信息里编译结果比较远，一直没有看到，请别人帮忙看，才看到这个报错信息🤣
