### ISSUE TITLE
执行 python build_android.py 编译错误，麻烦帮忙看下，多谢

### ISSUE THREAD

**Issue by smile-beta** [Tencent/mars#439]
具体编译信息如下：
Enter menu:
1. build mars shared libs.
2. build mars static libs.
3. build xlog shared lib with crypt.
4. exit.
1
Enter the architecture which would like to build:
1. armeabi.
2. x86.
3. mips.
4. armeabi-v7a.
5. arm64-v8a.
6. x86_64.
7. mips64.
8. exit.
2
build x86
D:\Github\mars-master\mars\libraries
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&n
bsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="tex
t/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collap
se;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-si
ze: 11px;    line-height: 16px;    color: #737373;    background-color: white;
  margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padd
ing: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0
069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.descript
ion h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent<
/h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr><
/thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align=
"left">BuildTag</td><td align="left">default</td></tr><tr><td align="left">Build
Time</td><td align="left">2018-08-10 11:23:22</td></tr><tr><td align="left">Revi
sion</td><td align="left"></td></tr></table></div>
process_begin: CreateProcess(NULL, `D:/Tools/android-ndk-r11c/build//../ndk-whic
h gcc` -dumpversion, ...) failed.
'info MY_USED_GCC_VERSION_CODE = '
process_begin: CreateProcess(NULL, `D:/Tools/android-ndk-r11c/build//../ndk-whic
h gcc` -dumpversion, ...) failed.
'info LOCAL_SRC_FILES= ../export/aes_crypt.c ../export/ecdh_crypt.c ../export/ec
dsa_verify.c ../export/md5_digest.c ../export/rsa_private_decrypt.c ../export/cr
ypto/ecdh_util.cpp ../export/crypto/gen_rsa_key_pair.cpp ../export/crypto/openss
l_multi_thread_support.cpp ../export/crypto/pay_openssl_crypto_util.cpp ../expor
t/crypto/rsa_crypt.cpp ../export/crypto/rsa_pss_sha256.cpp ../export/crypto/test
_rsa_pss_sha256.cpp '
'info SCR end----------------------------------'
Android NDK: WARNING:jni/Android.mk:cryptowrapper: LOCAL_LDFLAGS is always ignor
ed for static libraries
make: Entering directory `D:/Github/mars-master/mars/openssl'
[x86] "Compile        ": "cryptowrapper <= aes_crypt.c"
[x86] "Compile        ": "cryptowrapper <= ecdh_crypt.c"
process_begin: CreateProcess(NULL, D:/Tools/android-ndk-r11c/build//../toolchain
s/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc -MMD -MP -MF ./obj/
local/x86/objs/cryptowrapper/__/export/aes_crypt.o.d -ffunction-sections -funwin
d-tables -no-canonical-prefixes -fstack-protector-strong -O2 -g -DNDEBUG -fomit-
frame-pointer -fstrict-aliasing -funswitch-loops[x86] "Compile        ": "crypto
wrapper <= ecdsa_verify.c"
 -finline-limit=300 -Ijni/../../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../..
/../ -Ijni/../ -Ijni/../export_include -Ijni/../ -Ijni/../include -Ijni/../inclu
de/openssl -ID:/Tools/android-ndk-r11c/build//../sources/cxx-stl/stlport/stlport
 -ID:/Tools/android-ndk-r11c/build//../sources/cxx-stl//gabi++/include -Ijni -DA
NDROID -DXLOGGER_TAG=\"mars::cryptowrapper\" -Wall -Wsign-compare -Wtype-limits
-Wuninitialized -Wclobbered -Wunused-but-set-parameter -Wempty-body -Wno-error=c
onversion -Wno-error=sign-conversion -Werror=sign-compare -Wno-error=format -Wno
-error=pointer-to-int-cast -Wno-unused-parameter -Wno-missing-field-initializers
 -fdata-sections -Wno-unused-local-typedefs -fvisibility=hidden -Wa,--noexecstac
k -Wformat -Werror=format-security -isystem D:/Tools/android-ndk-r11c/build//..p
latforms/android-9/arch-x86/usr/include -c jni/../export/aes_crypt.c -o ./obj/lo
cal/x86/objs/cryptowrapper/__/export/aes_crypt.o, ...) failed.
make (e=2):
make: *** [obj/local/x86/objs/cryptowrapper/__/export/aes_crypt.o] Error 2
[x86] "Compile        ": "cryptowrapper <= md5_digest.c"
make: *** Waiting for unfinished jobs....
process_begin: CreateProcess(NULL, D:/Tools/android-ndk-r11c/build//../toolchain
s/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc -MMD -MP -MF ./obj/
local/x86/objs/cryptowrapper/__/export/ecdh_crypt.o.d -ffunction-sections -funwi
nd-tables -no-canonical-prefixes -fstack-protector-strong -O2 -g -DNDEBUG -fomit
-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -Ijni/../..
/comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../export_
include -Ijni/../ -Ijni/../include -Ijni/../include/openssl -ID:/Tools/android-n
dk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/Tools/android-ndk-r11c/bu
ild//../sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG=\"mars::cr
yptowrapper\" -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wu
nused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conve
rsion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno
-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-lo
cal-typedefs -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-secur
ity -isystem D:/Tools/android-ndk-r11c/build//../platforms/android-9/arch-x86/us
r/include -c jni/../export/ecdh_crypt.c -o ./obj/local/x86/objs/cryptowrapper/__
/export/ecdh_crypt.o, ...) failed.
make (e=2):
make: *** [obj/local/x86/objs/cryptowrapper/__/export/ecdh_crypt.o] Error 2
process_begin: CreateProcess(NULL, D:/Tools/android-ndk-r11c/build//../toolchain
s/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc -MMD -MP -MF ./obj/
local/x86/objs/cryptowrapper/__/export/ecdsa_verify.o.d -ffunction-sections -fun
wind-tables -no-canonical-prefixes -fstack-protector-strong -O2 -g -DNDEBUG -fom
it-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -Ijni/../
../comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../expor
t_include -Ijni/../ -Ijni/../include -Ijni/../include/openssl -ID:/Tools/android
-ndk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/Tools/android-ndk-r11c/
build//../sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG=\"mars::
cryptowrapper\" -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -
Wunused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-con
version -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -W
no-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-
local-typedefs -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-sec
urity -isystem D:/Tools/android-ndk-r11c/build//../platforms/android-9/arch-x86/
usr/include -c jni/../export/ecdsa_verify.c -o ./obj/local/x86/objs/cryptowrappe
r/__/export/ecdsa_verify.o, ...) failed.
make (e=2):
make: *** [obj/local/x86/objs/cryptowrapper/__/export/ecdsa_verify.o] Error 2
process_begin: CreateProcess(NULL, D:/Tools/android-ndk-r11c/build//../toolchain
s/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc -MMD -MP -MF ./obj/
local/x86/objs/cryptowrapper/__/export/md5_digest.o.d -ffunction-sections -funwi
nd-tables -no-canonical-prefixes -fstack-protector-strong -O2 -g -DNDEBUG -fomit
-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -Ijni/../..
/comm -Ijni/../../ -Ijni/../../../ -Ijni/../../../../ -Ijni/../ -Ijni/../export_
include -Ijni/../ -Ijni/../include -Ijni/../include/openssl -ID:/Tools/android-n
dk-r11c/build//../sources/cxx-stl/stlport/stlport -ID:/Tools/android-ndk-r11c/bu
ild//../sources/cxx-stl//gabi++/include -Ijni -DANDROID -DXLOGGER_TAG=\"mars::cr
yptowrapper\" -Wall -Wsign-compare -Wtype-limits -Wuninitialized -Wclobbered -Wu
nused-but-set-parameter -Wempty-body -Wno-error=conversion -Wno-error=sign-conve
rsion -Werror=sign-compare -Wno-error=format -Wno-error=pointer-to-int-cast -Wno
-unused-parameter -Wno-missing-field-initializers -fdata-sections -Wno-unused-lo
cal-typedefs -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-secur
ity -isystem D:/Tools/android-ndk-r11c/build//../platforms/android-9/arch-x86/us
r/include -c jni/../export/md5_digest.c -o ./obj/local/x86/objs/cryptowrapper/__
/export/md5_digest.o, ...) failed.
make (e=2):
make: *** [obj/local/x86/objs/cryptowrapper/__/export/md5_digest.o] Error 2
make: Leaving directory `D:/Github/mars-master/mars/openssl'
build static libs fail!!!

**Comment by MaYinjian** [comment]
你好，我单独编译xlog也编译失败
clone最新代码   master  
我查看了我的ndk 目录下面的 source.properties :
Pkg.Desc = Android NDK
Pkg.Revision = 16.1.4479499

下面是编译的过程：
myj:libraries mayinjian$ python build_android.py
Enter menu:
1. build mars shared libs.
2. build mars static libs.
3. build xlog shared lib with crypt.
4. exit.
3
Enter the architecture which would like to build:
1. armeabi.
2. x86.
3. mips.
4. armeabi-v7a.
5. arm64-v8a.
6. x86_64.
7. mips64.
8. exit.
5
build arm64-v8a
/Users/mayinjian/Downloads/mars-master/mars/libraries
svn: E155007: '/Users/mayinjian/Downloads/mars-master/mars/libraries' is not a working copy
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left">mars_xlog_sdk/mars_libs</td></tr><tr><td align="left">BuildTime</td><td align="left">2018-08-13 17:48:11</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
'info APP_MODULES = comm'
Android NDK: android-9 is unsupported. Using minimum supported version android-14.    
'info MY_USED_GCC_VERSION_CODE = 4.9.x'
'LOCAL_C_INCLUDES = ./jni . .. ../..'
'SELF_BUILD_CMD = BUILD_STATIC_LIBRARY'
'LOCAL_EXPORT_STATIC_LIBRARIES = '
'LOCAL_EXPORT_SHARED_LIBRARIES = '
'LOCAL_STATIC_LIBRARIES =  '
'LOCAL_SHARED_LIBRARIES =  '
'LOCAL_LDLIBS = -latomic '
'LOCAL_EXPORT_SRC_FILES =  '
'LOCAL_SRC_FILES=/Users/mayinjian/Downloads/mars-master/mars/boost/libs/atomic/src/lockpool.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/context/src/asm/jump_arm64_aapcs_elf_gas.S /Users/mayinjian/Downloads/mars-master/mars/boost/libs/context/src/asm/make_arm64_aapcs_elf_gas.S /Users/mayinjian/Downloads/mars-master/mars/boost/libs/context/src/execution_context.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/context/src/posix/stack_traits.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/coroutine/src/detail/coroutine_context.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/coroutine/src/exceptions.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/coroutine/src/posix/stack_traits.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/date_time/src/gregorian/date_generators.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/date_time/src/gregorian/greg_month.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/date_time/src/gregorian/greg_weekday.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/date_time/src/gregorian/gregorian_types.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/date_time/src/posix_time/posix_time_types.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/exception/src/clone_current_exception_non_intrusive.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/codecvt_error_category.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/operations.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/path.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/path_traits.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/portability.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/unique_path.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/utf8_codecvt_facet.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/filesystem/src/windows_file_codecvt.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/iostreams/src/file_descriptor.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/iostreams/src/mapped_file.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/smart_ptr/src/sp_collector.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/smart_ptr/src/sp_debug_hooks.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/system/src/error_code.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/thread/src/future.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/thread/src/pthread/once.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/thread/src/pthread/once_atomic.cpp /Users/mayinjian/Downloads/mars-master/mars/boost/libs/thread/src/tss_null.cpp /Users/mayinjian/Downloads/mars-master/mars/comm/adler32.c /Users/mayinjian/Downloads/mars-master/mars/comm/alarm.cc /Users/mayinjian/Downloads/mars-master/mars/comm/android/callstack.cc /Users/mayinjian/Downloads/mars-master/mars/comm/android/dumpcrash_stack.cc /Users/mayinjian/Downloads/mars-master/mars/comm/android/getprocessname.c /Users/mayinjian/Downloads/mars-master/mars/comm/android/wakeuplock.cc /Users/mayinjian/Downloads/mars-master/mars/comm/anr.cc /Users/mayinjian/Downloads/mars-master/mars/comm/assert/__assert.c /Users/mayinjian/Downloads/mars-master/mars/comm/autobuffer.cc /Users/mayinjian/Downloads/mars-master/mars/comm/basepacker.cc /Users/mayinjian/Downloads/mars-master/mars/comm/boost_exception.cc /Users/mayinjian/Downloads/mars-master/mars/comm/comm_frequency_limit.cc /Users/mayinjian/Downloads/mars-master/mars/comm/corepattern/coreservice_base.cc /Users/mayinjian/Downloads/mars-master/mars/comm/coroutine/coro_socket.cc /Users/mayinjian/Downloads/mars-master/mars/comm/coroutine/dns.cc /Users/mayinjian/Downloads/mars-master/mars/comm/crypt/ibase64.cc /Users/mayinjian/Downloads/mars-master/mars/comm/crypt/pkcs7_padding.c /Users/mayinjian/Downloads/mars-master/mars/comm/debugger/test_spy_sample.cc /Users/mayinjian/Downloads/mars-master/mars/comm/debugger/testspy.cc /Users/mayinjian/Downloads/mars-master/mars/comm/dns/dns.cc /Users/mayinjian/Downloads/mars-master/mars/comm/http.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/build.conf /Users/mayinjian/Downloads/mars-master/mars/comm/jni/ifaddrs.c /Users/mayinjian/Downloads/mars-master/mars/comm/jni/platform_comm.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/util/comm_function.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/util/scope_jenv.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/util/scoped_jstring.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/util/var_cache.cc /Users/mayinjian/Downloads/mars-master/mars/comm/jni/xlogger_threadinfo.cc /Users/mayinjian/Downloads/mars-master/mars/comm/md5.c /Users/mayinjian/Downloads/mars-master/mars/comm/memdbg.cc /Users/mayinjian/Downloads/mars-master/mars/comm/messagequeue/message_queue.cc /Users/mayinjian/Downloads/mars-master/mars/comm/mmap_util.cc /Users/mayinjian/Downloads/mars-master/mars/comm/network/getdnssvraddrs.cc /Users/mayinjian/Downloads/mars-master/mars/comm/network/getgateway.c /Users/mayinjian/Downloads/mars-master/mars/comm/network/getifaddrs.cc /Users/mayinjian/Downloads/mars-master/mars/comm/network/netinfo_util.cc /Users/mayinjian/Downloads/mars-master/mars/comm/ptrbuffer.cc /Users/mayinjian/Downloads/mars-master/mars/comm/singleton.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/block_socket.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/complexconnect.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/getsocktcpinfo.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/local_ipstack.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/nat64_prefix_util.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/socket_address.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/tcpclient.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/tcpclient_fsm.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/tcpserver.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/tcpserver_fsm.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/udpclient.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/udpserver.cc /Users/mayinjian/Downloads/mars-master/mars/comm/socket/unix_socket.cc /Users/mayinjian/Downloads/mars-master/mars/comm/strutil.cc /Users/mayinjian/Downloads/mars-master/mars/comm/tickcount.cc /Users/mayinjian/Downloads/mars-master/mars/comm/time_utils.c /Users/mayinjian/Downloads/mars-master/mars/comm/tinyxml2.cc /Users/mayinjian/Downloads/mars-master/mars/comm/unix/socket/socketbreaker.cc /Users/mayinjian/Downloads/mars-master/mars/comm/unix/socket/socketpoll.cc /Users/mayinjian/Downloads/mars-master/mars/comm/unix/socket/socketselect.cc /Users/mayinjian/Downloads/mars-master/mars/comm/xlogger/loginfo_extract.c /Users/mayinjian/Downloads/mars-master/mars/comm/xlogger/xloggerbase.c'
Android NDK: WARNING:jni/Android.mk:comm: LOCAL_LDFLAGS is always ignored for static libraries    
Android NDK: WARNING:jni/Android.mk:comm: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module comm    
Android NDK:   ../jni/build.conf    
make: Entering directory `/Users/mayinjian/Downloads/mars-master/mars/comm'
[arm64-v8a] Compile++      : comm <= autobuffer.cc
[arm64-v8a] Compile++      : comm <= basepacker.cc
[arm64-v8a] Compile++      : comm <= boost_exception.cc
[arm64-v8a] Compile++      : comm <= comm_frequency_limit.cc
**error**: error: unknown unknownwarning  warningoption  option'-Wclobbered';  '-Wclobbered';did  didyou  youmean  mean'-Wconsumed'?error : 
'-Wconsumed'?      
[-Werror,-Wunknown-warning-option]      unknown[-Werror,-Wunknown-warning-option] 
warning
 option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; errordid:  you meanunknown
       warning'-Wunused-parameter'?  option[-Werror,-Wunknown-warning-option] '-Wclobbered';
 did erroryou:  meanunknown  '-Wconsumed'?warning
**error**       : option[-Werror,-Wunknown-warning-option] unknown'-Wunused-but-set-parameter';
  didwarning  youoption  mean'-Wunused-but-set-parameter';
       did'-Wunused-parameter'?  you[-Werror,-Wunknown-warning-option] mean

      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
**error**: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/arm64-v8a/objs/comm/__/boost_exception.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/arm64-v8a/objs/comm/__/comm_frequency_limit.o] Error 1
make: *** [obj/local/arm64-v8a/objs/comm/__/autobuffer.o] Error 1
make: *** [obj/local/arm64-v8a/objs/comm/__/basepacker.o] Error 1
make: Leaving directory `/Users/mayinjian/Downloads/mars-master/mars/comm'
build static libs fail!!!

**Comment by MaYinjian** [comment]
必须是 11版本的ndk才能用么？   高的不能支持？

**Comment by garryyan** [comment]
目前高的不支持， 必须r11c 和Python2.7
