### ISSUE TITLE
日志解压java的脚本

### ISSUE THREAD

**Issue by binayabin** [Tencent/mars#440]
目前xlog每次要查看日志都要使用
python decode_mars_nocrypt_log_file.py  xlog_debug_20180810.xlog 进行解压

这个decode_mars_nocrypt_log_file.py 脚本，能否用java实现。或者sdk中有没有解压接口

**Comment by garryyan** [comment]
暂时没计划哦，sdk 中也不大可能提供接口，因为这样加密就没意义了
