### ISSUE TITLE
iOS的Demo不友好啊，都运行不起来

### ISSUE THREAD

**Issue by harddog** [Tencent/mars#445]
![image](https://user-images.githubusercontent.com/13884744/44638617-77136000-a9ea-11e8-8f7a-41a430bb4dbe.png)

仅仅 build for xlog的话，会有以上问题， 必须将全部功能build，然后还有多加一个文件，这些在README里面都没有体现出来

**Comment by garryyan** [comment]
最新代码已经修复了
