### ISSUE TITLE
use Xcode10 build build_apple.py  has problem

### ISSUE THREAD

**Issue by GeekerHuang** [Tencent/mars#446]
OSError: [Errno 2] No such file or directory: '/Users/huangshuai/Desktop/mars\xe7\x9a\x84\xe5\x89\xaf\xe6\x9c\xac/mars/libraries/../app/build/app.build/Release-iphoneos/app.build/Objects-normal'

**Comment by garryyan** [comment]
路径是不是有中文或者空格或者特殊符号，全英文没空格的路径试试

**Comment by lujiayi1228** [comment]
hi ~ did you fix the problem?
