### ISSUE TITLE
appenderClose 调用时机问题

### ISSUE THREAD

**Issue by xinghun92** [Tencent/mars#449]
看说明上说每次应用退出时都需要调用 appenderClose 方法，但有的时候找不到合适的时机调用。比如对于 Android，Demo 是在 OnTerminate 时调用的 appenderClose，但看官方文档说明这个函数仅会在模拟上被调用。现在出现了日志不能解压缩的情况，看了源码实现，如果异步线程正在写文件，而这时候程序退出了，而 appenderClose 方法又没有被调用，日志就会损坏。请问微信的 Android 和 iOS 客户端分别是在什么时机调用的这个方法呢？

**Comment by dd20071** [comment]
我是在onDestroy中调用，但是发现闪退是不会走这里

**Comment by agoodcoolman** [comment]
直接关闭，也没给个解释哇。
