### ISSUE TITLE
关于修改过期自动清理的时间

### ISSUE THREAD

**Issue by dd20071** [Tencent/mars#450]
大家好，想修改过期自动清理的时间参数，在代码里改了kMaxLogAliveTime，然后用python build_android.py编译后，验证新的库，还是会删除10天前的日子，修改没有效果，请问是哪里步骤不对导致的？

**Comment by garryyan** [comment]
自动删除文件只受这个影响，你可以在__del_timeout_file 函数中增加 __android_log_print或者NSLog来具体看下为什么

**Comment by dd20071** [comment]
多谢已解决
