### ISSUE TITLE
长连重建连接后，LonglinkIdentify如何确保在未完成task前做？

### ISSUE THREAD

**Issue by earthskin** [Tencent/mars#451]
我现在用mars的长链方式做客户端和服务器的连接，客户端会间断的断开连接？ 当客户端重连上服务器，使用LonglinkIdentify来维持同一个session，但是现在有个问题： 客户端未完成的task会优先LonglinkIdentify发送到服务器（就是没有确保重连后先发LonglinkIdentify）？   这个问题需要怎么来解决？

**Comment by garryyan** [comment]
你这个设计本身就有问题，为什么不是每需要登陆的包都带有session信息呢。
