### ISSUE TITLE
如果程序运行中异常退出，如断电或奔溃而没有调用appenderClose，日志是否会丢失？

### ISSUE THREAD

**Issue by dd20071** [Tencent/mars#452]
如果程序运行中异常退出，如断电或奔溃而没有调用appenderClose，日志是否会丢失？

**Comment by garryyan** [comment]
断电是有可能丢失的，崩溃一般不会

**Comment by weizhizhanghao** [comment]
com.tencent.mars:mars-xlog:1.2.3 版本，设置每天只存放一个文件，但是文件内容大小压缩后都超过10M了，想问下，mars-xlog 本地设置的可最大存放内容为多少呀？同一天存放多个文件可设置单个文件的最大大小，那只存放同一个文件，内容大小限制为多少呢？
