### ISSUE TITLE
Xlog 多线程的问题

### ISSUE THREAD

**Issue by hackjie** [Tencent/mars#453]
作者你好，使用中遇到个问题就是主线程初始化 xlog 之后，在另一个线程直接调用写入 或者 回到主线程调用写入方法都不能写入，一定要在当前线程重新初始化才可以

**Comment by garryyan** [comment]
不会有这个问题的，确认是同一个进程吗？或者是使用的Log.java 是mars的而不是系统的？

**Comment by hackjie** [comment]
确认是同一个进程，在 iOS 里用的

**Comment by garryyan** [comment]
调试跟一下
