### ISSUE TITLE
解密异常

### ISSUE THREAD

**Issue by m5314** [Tencent/mars#454]
我用脚本解密xlog文件时得到如下报错：
Traceback (most recent call last):
  File "E:\mars-master\mars\log\crypt\decode_mars_nocrypt_log_file.py", line 105
, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid stored block lengths

请问怎么解决？

**Comment by garryyan** [comment]
常见文件有损坏。 是必现的吗

**Comment by m5314** [comment]
> 常见文件有损坏。 是必现的吗

我检查后发现是多进程同时写的问题，区分后没报错了
