### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by applejian** [Tencent/mars#455]
snprintf(log, sizeof(log), "[%s][%s][%s, %s, %d][%s", levelStrings[_info->level], NULL == _info->tag ? "" : _info->tag, file_name, strFuncName, _info->line, _log);

上面这句中 为啥 %d][%s 这里 感觉多了个[ 

还有freopen这种方式跟现在的差距有多少

**Comment by garryyan** [comment]
故意多[的，用来分割日志的。
freopen 是指什么？
