### ISSUE TITLE
Xcode 10 执行python build_apple.py时报错

### ISSUE THREAD

**Issue by lujiayi1228** [Tencent/mars#458]
OSError: [Errno 2] No such file or directory: '/Users/huangshuai/Desktop/mars\xe7\x9a\x84\xe5\x89\xaf\xe6\x9c\xac/mars/libraries/../app/build/app.build/Release-iphoneos/app.build/Objects-normal'

**Comment by lujiayi1228** [comment]
我的路径是全英文的,不含空格，报同样错误。。。观察脚本运行过程，发现会在app/build/app.build文件夹中生产文件，但是脚本会将它删除，并生产新的文件Release-iphonesimulator，最终无法找到Release-iphoneos下的objects-normal.当我试着在生产应有的objects-normal时，将其保存下来，并在最终脚本执行到merging sdt时，将objects-normal所在目录重新生产，此时merging app可以通过，但是会在rming tmp files之后又开始重新编译 - -，最终导致objects-normal仍然不存在。

**Comment by garryyan** [comment]
我正在试图重现这个问题

**Comment by lujiayi1228** [comment]
暂时解决了
