### ISSUE TITLE
xcode10 ， swift 导入mars.framework报错 No such module 'mars'

### ISSUE THREAD

**Issue by lujiayi1228** [Tencent/mars#460]
![image](https://user-images.githubusercontent.com/26211081/45735423-6be2d700-bc1a-11e8-9a0b-a089ed1e514c.png)
framework正确导入
![image](https://user-images.githubusercontent.com/26211081/45735588-f3c8e100-bc1a-11e8-9bc2-107b9c78ffec.png)

如果使用bridge文件导入会报新的错误
![image](https://user-images.githubusercontent.com/26211081/45735761-8ff2e800-bc1b-11e8-8e38-db0baa22aa10.png)
![image](https://user-images.githubusercontent.com/26211081/45735652-34285f00-bc1b-11e8-8256-869e0cef2e7a.png)

**Comment by lujiayi1228** [comment]
![image](https://user-images.githubusercontent.com/26211081/45735588-f3c8e100-bc1a-11e8-9bc2-107b9c78ffec.png)
如果使用bridge文件导入会报新的错误
![image](https://user-images.githubusercontent.com/26211081/45735652-34285f00-bc1b-11e8-8256-869e0cef2e7a.png)

**Comment by lujiayi1228** [comment]
![image](https://user-images.githubusercontent.com/26211081/45735761-8ff2e800-bc1b-11e8-8e38-db0baa22aa10.png)

**Comment by NicolasKim** [comment]
您好 大佬   你这个问题解决了吗？  我遇到了个问题  我在自己做的pod库里依赖了mars  但是import时找不到这个mars    可能他不识别为一个module 导致 ，你知道要怎么解决吗？
