### ISSUE TITLE
ExtractFunctionName 函数可能有bug

### ISSUE THREAD

**Issue by linxiaoyuan** [Tencent/mars#461]
![image](https://user-images.githubusercontent.com/41985804/45742800-5b882780-bc2d-11e8-997e-6e0f68deaa6a.png)

这段逻辑的目的是什么呢？看函数名，猜测是去掉类名，提取出函数名，但遇到 Category 的情况下会失效（类名中有'('）

**Comment by garryyan** [comment]
对  遇到一些函数是会有问题，还有lambda表达式匿名函数这里也可能有问题
