### ISSUE TITLE
关于Xlog使用的一些问题

### ISSUE THREAD

**Issue by kobewylb** [Tencent/mars#462]
1.我想使用XLog来作为客户端的高性能日志采集
2.目前的问题Xlog有自己的格式

^^^^^^^^^^Oct 12 2017^^^18:17:54^^^^^^^^^^[15041,15041][2018-09-19 +0800 19:59:06]
del time out files time: 0
get mmap time: 1
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f685e74
MARS_BUILD_TIME: 2017-10-12 18:17:33
MARS_BUILD_JOB: default
log appender mode:0, use mmap:0
[I][2018-09-19 +8.0 19:59:06.901][15041, 1*][MainActivity][, , 0][===================debug=false
[I][2018-09-19 +8.0 19:59:06.901][15041, 1*][MainActivity][, , 0][===================yyy
$$$$$$$$$$Oct 12 2017$$$18:17:54$$$$$$$$$$[15041,15041][2018-09-19 +0800 19:59:07]

我怎么做到把这些格式的部分去掉，我大概想要的是以下这种格式，我一定要自己修改源码吗？
++++++++++++++++++++++++++
sessionid=duosaidsai || log=727392879 ||.......
++++++++++++++++++++++++++

3.上面的日志我是用mars自带的python解析出来的，请问如果想在服务端解析，我怎么解析一直没找到相关的资料？？

4.还是我使用Xlog来做客户端日志采集打点的出发点就是错的？

**Comment by garryyan** [comment]
2. 这种一般来说作为版本信息的，不建议删掉，如果要删只能改源码
3. 用 python 解析就行，服务端也可以执行 pytho
