### ISSUE TITLE
xlog如何才能支持日志分类同时写入不同的多个日志文件

### ISSUE THREAD

**Issue by wswenyue** [Tencent/mars#467]
日志有不同的分类，需要写入不同的日志文件。
如何能同时写入不同的日志文件？
现在好像只能打开一个mmap文件。

**Comment by garryyan** [comment]
目前不支持的。

最初设计的时候是希望使用不同的tag来划分，看日志的时候也用tag来区分

**Comment by wswenyue** [comment]
目前的需求是，有部分优先级较高的日志需要定时上传，全部日志仅在需要的时候拉取。
xlog目前是只有一个日志文件。

我可以打开关闭不同的日志文件，来实现吗？这样会不会对性能有影响。
比如A、B两种类型的日志。我先打开A日志文件，写完后关闭，再打开B日志文件写

**Comment by garryyan** [comment]
不建议这么做，这样做的话会导致性能会降低很多。
目前xlog 无法满足你描述的这部分需求。
