### ISSUE TITLE
请教下关于xlog的NDK_DEBUG=1 之后不能调试问题

### ISSUE THREAD

**Issue by greatcy** [Tencent/mars#468]
RT,请问下修改脚本build_android.py NDK_DEBUG=1 之后依然不能生成可调试的so库(查看没有.debug相关的段).平时mars xlog模块开发是如何调试的?

**Comment by garryyan** [comment]
NDK_DEBUG=1 是加在python脚本中的ndk-build命令行中了吧？
平时mars都是用xcode和windows进行调试的，安卓主要是看日志

**Comment by greatcy** [comment]
> NDK_DEBUG=1 是加在python脚本中的ndk-build命令行中了吧？
> 平时mars都是用xcode和windows进行调试的，安卓主要是看日志

是的,感觉有点像android-ndk-r11c 的问题

**Comment by greatcy** [comment]
> > NDK_DEBUG=1 是加在python脚本中的ndk-build命令行中了吧？
> > 平时mars都是用xcode和windows进行调试的，安卓主要是看日志
> 
> 是的,感觉有点像android-ndk-r11c 的问题

忘记回复了,我的解决方式是在 mars/libraries/mars_xlog_sdk/jni/Android.mk 文件加上
cmd-strip =
取消压缩丢弃debug信息就可以调试了(因为是在ubuntu下开发,调整了一下)
