### ISSUE TITLE
vs2015 community编译mars\win32proj\mars.sln错误

### ISSUE THREAD

**Issue by gamert** [Tencent/mars#47]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2027	use of undefined type 'mars_boost::detail::shared_state_base'	boost	c:\dev\tc_im_mars\mars\boost\libs\thread\src\win32\thread.cpp	66	
Error	C2039	'make_ready': is not a member of 'mars_boost::shared_ptr<mars_boost::detail::shared_state_base>'	boost	c:\dev\tc_im_mars\mars\boost\libs\thread\src\win32\thread.cpp	66

**Comment by garryyan** [comment]
#43 #16

**Comment by garryyan** [comment]
最新代码已支持win平台
