### ISSUE TITLE
xlog能在程序崩溃的时候把崩溃日志写入文件吗

### ISSUE THREAD

**Issue by js-xiaocaiya** [Tencent/mars#473]
目前没发现有写入相关的崩溃日志

**Comment by garryyan** [comment]
xlog只是日志组件，并不包含crash捕捉的功能。
日志组件： 开发者主动调用相关日志接口写日志，你可以简单理解为文件
crash捕捉模块：绝大部分时间潜伏，程序crash的时候捕捉crash，回溯相关堆栈

**Comment by js-xiaocaiya** [comment]
> xlog只是日志组件，并不包含crash捕捉的功能。
> 日志组件： 开发者主动调用相关日志接口写日志，你可以简单理解为文件
> crash捕捉模块：绝大部分时间潜伏，程序crash的时候捕捉crash，回溯相关堆栈

能更改日志文件的格式吗？添加日志打印的行号跟文件名

**Comment by garryyan** [comment]
C++会自动打印行号。java 的话，注意看Log.java 中的内部实现，也能传递行号和文件名的，但是不建议，因为 java 取行号和文件名没那么方便

**Comment by js-xiaocaiya** [comment]
> C++会自动打印行号。java 的话，注意看Log.java 中的内部实现，也能传递行号和文件名的，但是不建议，因为 java 取行号和文件名没那么方便

日志输出的内容：
[log_level][time][pid, ""][TAG]["", "", ""][content] 双引号里面的内容是什么呀
@garryyan

**Comment by garryyan** [comment]
第一个是线程id，后面三个分别是文件名，函数名，行号。  这四个参数在java层都没使用的，但是mars的Log.java 的内部实现中调用xlog的接口，是可以传这几个参数的

**Comment by js-xiaocaiya** [comment]
设置了Xlog.setConsoleLogOpen(true)，但是没看到有把日志输出到控制台？ @garryyan

**Comment by garryyan** [comment]
日志在文件中是否找到了，Android studio 如果不加 tag 有时候显示会有点问题，tag 不要给空串。

**Comment by daixiansen** [comment]
应用程序崩溃时，xlog好像写入不进去
