### ISSUE TITLE
windows 下面编译xlog出错

### ISSUE THREAD

**Issue by jiaozebo** [Tencent/mars#474]
E:\github\mars-master\mars\libraries>python build_android.py
  File "build_android.py", line 135
    print "c1"
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by jiaozebo** [comment]
E:\github\mars-master\mars\libraries>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by garryyan** [comment]
请使用python2.7版本
