### ISSUE TITLE
shortlink_packer.cc编译问题

### ISSUE THREAD

**Issue by LazyChops** [Tencent/mars#477]
在xcode10下编译和使用没有问题，但是在在xcode9下编译，shortlink_packer.cc文件出现如下问题：
<img width="742" alt="image" src="https://user-images.githubusercontent.com/30312264/47472574-c5ee4200-d841-11e8-83d9-d5dc29646a5c.png">
c++编译选项如下：
<img width="470" alt="image" src="https://user-images.githubusercontent.com/30312264/47472629-f209c300-d841-11e8-91be-f1ffce91a243.png">

**Comment by garryyan** [comment]
请参考 sample/iOS/iOSDemo中的设置。 这里需要C++11的标准的

**Comment by LazyChops** [comment]
直接入XLog功能的话，longlink和shortlink文件是不是都可以不引入项目。 @garryyan

**Comment by garryyan** [comment]
可以
