### ISSUE TITLE
域名解析错误ip问题

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#479]
国行手机在国外用当地的电话卡上网，登入无法与服务器链接。用个人热点共享网络给国外手机也无法。用国外的手机上网登入就可以。用国外手机个人热点共享国行手机在就可以。
其中
"localDNS":"2405:9800:a:2::26,2405:9800:a:1::10,115.178.58.26","connectIP":"64:ff9b::9db9:b993:443"

使用了mars中的DNS的域名解析代码DNS::GetHostByName
"osv":"11.4.1","mod":"iPhone 7 Plus (A1661\/A1784)","os":"iOS"
	host:xx.com ip:.229 i:0
	host:xx.com ip:.229 i:1
	host:xx.com ip:06.20 i:2
	host:xx.com ip:06.20 i:3
	host:xx.com ip:06.19 i:4
	host:xx.com ip:06.19 i:5
	host:xx.com ip:115.231.106.19 i:6
	host:xx.com ip:115.231.106.19 i:7
	host:xx.com ip:47.74.216.229 i:8
	host:xx.com ip:47.74.216.229 i:9
	host:xx.com ip:115.231.106.20 i:10
	host:xx.com ip:115.231.106.20 i:11

使用代码是这样的：
	DNS new_dns_;
	std::vector<std::string> ip_vec;
	new_dns_.GetHostByName(ipports[0].str_host, ip_vec);

奇怪的是通过查看代码：dns.cc中的__GetIP函数
static void __GetIP()

    	       const char* ip = socket_address(single->ai_addr).ip();

                if (!socket_address(ip, 0).valid_server_address(false, true)) {
                    xerror2(TSF"ip is invalid, ip:%0", ip);
                    continue;
                }

                iter->result.push_back(ip);
在这个地方明明对无效ip进行过滤，但是为什么还是会存储到result中。

**Comment by garryyan** [comment]
有什么进展吗？

**Comment by stevezhou6** [comment]
目前打算的做法则是在最终使用ip的地方再做一次合法性过滤

**Comment by garryyan** [comment]
如果是自己的手机，并且可重现的话，可以考虑在 dns.cc 中加更详细的日志定位

**Comment by stevezhou6** [comment]
不是自己的，是用户的，国行手机在国外用当地的电话卡上网

**Comment by stevezhou6** [comment]
目前发现都是一些国外的用户，尤其是泰国的

**Comment by garryyan** [comment]
fixed 0c8171b67849de297c62bebe125e0eb9ad199a25
