### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by jingtai5** [Tencent/mars#481]
请教一个问题，我在mars/log/src/下面添加了一个.cc的jni文件，为什么里面的方法，java访问不到啊？

而如果直接放到mars/libraries/mars_android_sdk/jni 就是正常的。

**Comment by jingtai5** [comment]
嗯，知道原因了，不得不说，腾讯的开发，处理问题的思路很妙啊~~~

**Comment by rancpine** [comment]
这是啥原因啊？ 我也遇到这个问题了
