### ISSUE TITLE
openssl版本不一致

### ISSUE THREAD

**Issue by tangxiangpi** [Tencent/mars#483]
我们的app本身是需要openssl支持的，并且版本用的是1.1，现在打算引入xlog，但是我们不需要日志加密的功能，所以在代码里我只调用了System.loadLibrary("marsxlog");但是报错，uncaughtException:dlopen failed: library "libstlport_shared.so" not found。怎么能够只加载marsxlog就可以正常使用？
xlog用的openssl是1.0.2版本，和我们自身的app使用的1.1版本不一致，担心会有问题

**Comment by garryyan** [comment]
和 openssl 版本并没有什么关系，因为 xlog 要依赖 stl。所以需要在
System.loadLibrary("marsxlog"); 之前System.loadLibrary("stlport_shared");

**Comment by tangxiangpi** [comment]
> 和 openssl 版本并没有什么关系，因为 xlog 要依赖 stl。所以需要在
> System.loadLibrary("marsxlog"); 之前System.loadLibrary("stlport_shared");

谢谢，我理解错了,openssl用来通讯加密的，用的是crypto,ssl这两个库。xlog的加密用的是对称加密算法？

**Comment by garryyan** [comment]
密钥交换用的 ecdh，加密用的 tea。加密的安全性取决于私钥的保存。  xlog 是没有使用 openssl 的

**Comment by tangxiangpi** [comment]
> 密钥交换用的 ecdh，加密用的 tea。加密的安全性取决于私钥的保存。 xlog 是没有使用 openssl 的

ok，感谢
