### ISSUE TITLE
xlog  头文件 放在哪里?

### ISSUE THREAD

**Issue by Guang1234567** [Tencent/mars#487]
请问xlog  头文件 放在哪里?  还是说要自己根据 java 文件生成?

**Comment by garryyan** [comment]
如果直接通过 java 调用的话，不需要 C++的头文件，如果在 C++调用的话，参照 xlog 的sample，把相应文件放到任意你想放的位置

**Comment by Guang1234567** [comment]
@garryyan  找到了谢谢!   另外我需要在 native 链接 xlog, 故需要头文件.

src_code/mars/mars/log/export_include

**Comment by Guang1234567** [comment]
@garryyan 

https://mvnrepository.com/artifact/com.tencent.mars/mars-xlog-armv7a

我发现 maven 仓库上有个 armv7a 版本 xlog,  可以使用它吗?   因为使用它就不用源码编译(针对纯 java 代码的 android 项目), 谢谢
