### ISSUE TITLE
问个关于mmap的问题。

### ISSUE THREAD

**Issue by wobuaihuangjun** [Tencent/mars#491]
请问，在pc端，有什么办法将 .mmap2 文件转换成 .xlog 文件？线上拿回来的日志，经常是最后一段 mmap文件里的日志比较有价值。

**Comment by wobuaihuangjun** [comment]
@garryyan

**Comment by garryyan** [comment]
正常退出会自动把mmap日志刷到文件中，异常退出会在下次启动的时候把mmap文件中的日志写到日志文件中的，不需要你自己来操作

**Comment by wobuaihuangjun** [comment]
异常退出后，有些情况会出现无法启动，走不到初始化日志的业务

**Comment by wobuaihuangjun** [comment]
当前拿到的日志里面。mmap2里的数据是不可用的

**Comment by OurPerfectWorld** [comment]
@wobuaihuangjun 我这边是修改源码，把mmap2作为最终日志文件，而不做为一个缓存中转，仅供参考
