### ISSUE TITLE
关于xlog在win上的运用问题

### ISSUE THREAD

**Issue by OurPerfectWorld** [Tencent/mars#492]
通过调试xlog的win版本，发现有个问题
使用createFileMapping创建map2文件后，此时的map2处于open状态
同时会对该文件上调用fopen操作（在mmap_util.cc中）
在ios上map2进行fopen是正常，并进行初始化文件内容
而win上会fopen失败，导致把map2文件删除，导致后面整个log的写入，和map2文件是毫无关系
这个是就这样设计还是bug来着？

**Comment by OurPerfectWorld** [comment]
@garryyan

**Comment by garryyan** [comment]
已知问题 稍后我 fix 下

**Comment by OurPerfectWorld** [comment]
nice
另外请教下，我方打算把map2改成最终的log生成文件，而不像xlog一样，当成一个中转文件，这个方案有什么弊端么

**Comment by garryyan** [comment]
占用内存会变大，而且你无法预知你的 log 文件将会是多大，除非你不停的去映射文件。当无法预知被映射的文件大小时，操作 mmap 将会是个麻烦的事情

**Comment by OurPerfectWorld** [comment]
嗯嗯了解了，多谢。
