### ISSUE TITLE
makebuild错误

### ISSUE THREAD

**Issue by zuowenpin** [Tencent/mars#497]
unique = $(if $1,$(firstword $1) $(call uniq,$(filter-out $(firstword $1),$1)))
递归调用，第二个应该是unique吧

**Comment by garryyan** [comment]
应该是有问题的，但是暂时就不修复了，因为后续会移除 mk 换用 cmake 编译。

**Comment by garryyan** [comment]
已用 cmake 构建替代 Android.mk
