### ISSUE TITLE
I want to be a part of tencent

### ISSUE THREAD

**Issue by LondonYoungWriterOfCountry** [Tencent/mars#5]
I just graduated this year，but I was hoping to join the big family team.I want to do Meaningful things, not mediocrity spend every day。

**Comment by Luolc** [comment]
hhh nice strategy

**Comment by shwenzhang** [comment]
send a resume to my email: shwenzhang@tencent.com

**Comment by Hell0wor1d** [comment]
good job,  小伙砸

**Comment by pinguo-sunjianfei** [comment]
nice~

**Comment by azhansy** [comment]
666，小伙子

**Comment by dotcool** [comment]
good boy.good company

**Comment by howardjin** [comment]
666

**Comment by DeepMissea** [comment]
厉害了，我的哥。
