### ISSUE TITLE
希望能有一个stn协议文档

### ISSUE THREAD

**Issue by nightsailer** [Tencent/mars#50]
常见问题 “ 如果我已经有现有服务器端了，客户端想使用 Mars，需要服务器做什么工作？” 提到：
“ 需要先理解长短连协议和加解包的区别。”

请问能否方便提供一个这个长短连协议的具体文档，便于实现和适配自己的服务端接口？

**Comment by garryyan** [comment]
关于长短连协议的理解和 req2Buf buf2Resp 的理解可以看一个例子：就像你用 HTTP 发一个 json 数据 HTTP 就类似 Mars 的长短连协议， json 的组装和解析就是 req2Buf 和 buf2Resp 来做的。

长短连协议的自定义可以看一下 wiki 里的自定义扩展。 加解包是在req2Buf和buf2Resp来完成的，也是回调到上层来做的。

**Comment by nightsailer** [comment]
> 关于长短连协议的理解和 req2Buf buf2Resp 的理解可以看一个例子：就像你用 HTTP 发一个 json 数据 HTTP 就类似 Mars 的长短连协议， json 的组装和解析就是 req2Buf 和 buf2Resp 来做的。

其实我想了解的正是你上面所提的 HTTP 的参考实现的文档。
或者我是否可以这样理解，使用stn相当于普通的 TCP 协议，而并不是在 TCP 之上有个封装的特殊的私有协议（ 类似HTTP ）？

**Comment by garryyan** [comment]
长连是基于tcp 的，但是在tcp 上确实还有私有协议，私有协议的实现一般是一个协议头，紧跟要发送的数据。协议头存头长，数据长，版本号等。 这里你可以参看longlink_packer.cc wiki 中也有提，自定义扩展可以改这里。至于短连你可以当做一个简单的http 协议。
