### ISSUE TITLE
arm64-v8a 编译成功但是：recipe for target 'libmarsxlog.so' failed

### ISSUE THREAD

**Issue by zhanlan123** [Tencent/mars#502]
[100%] Linking CXX shared library libmarsxlog.so
D:/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: anonymous version tag cannot be combined with other version tags
collect2.exe: error: ld returned 1 exit status
CMakeFiles/marsxlog.dir/build.make:102: recipe for target 'libmarsxlog.so' failed
make.exe[3]: *** [libmarsxlog.so] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/marsxlog.dir/all' failed
make.exe[2]: *** [CMakeFiles/marsxlog.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/marsxlog.dir/rule' failed
make.exe[1]: *** [CMakeFiles/marsxlog.dir/rule] Error 2
Makefile:164: recipe for target 'marsxlog' failed
make.exe: *** [marsxlog] Error 2
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by garryyan** [comment]
用的哪个版本的ndk？

**Comment by zhanlan123** [comment]
NDK是：最新版的r16b。但就是会有：anonymous version tag cannot be combined with other version tags

**Comment by zhanlan123** [comment]
编译的是你们这两天更新的版本。

**Comment by garryyan** [comment]
最新代码已修复

**Comment by zhanlan123** [comment]
非常感谢
