### ISSUE TITLE
调试模式下无法找到mars的头文件

### ISSUE THREAD

**Issue by zhgw01** [Tencent/mars#504]
这篇wiki中描述的iOS使用cmake_build生成的mars proejct，运行的时候会报找不到头文件
https://github.com/Tencent/mars/wiki/Mars-iOS%EF%BC%8FOS-X-%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#%E8%B0%83%E8%AF%95

**Comment by zhgw01** [comment]
是按照上面的步骤， 先执行`python build_ios.py `,编译结果在 mars/mars/cmake_build/iOS/Darwin.out， 然后头文件只在mars/mars/cmake_build/iOS/Darwin.out/mars.framework/Headers下面

因为要调试源码，所以不能直接使用mars.framework(用子project）， 把search path直接指向mars/mars/cmake_build/iOS/Darwin.out/mars.framework/Headers, 也会造成 `#import <mars/xlog/appender.h>
`找不到？

对照新的wiki还是没找到对头文件查找的处理？

**Comment by garryyan** [comment]
链接的时候要把生成的 framework 移到别的位置再链接，不要直接用mars/mars/cmake_build/iOS/Darwin.out 目录。

因为你下一步生成项目文件的时候会进行一次 clean，会删除之前生成的
