### ISSUE TITLE
Android sample编译通过，但加载so库失败、运行失败

### ISSUE THREAD

**Issue by zhuozp** [Tencent/mars#509]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.mars.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.mars.sample-1/lib/arm, /system/fake-libs, /data/app/com.tencent.mars.sample-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libc++_shared.so"

如上错误。原始工程，没有做改动，ndk版本为r16b。编译出来的包没有这个so。

**Comment by 1031900805** [comment]
请问怎么解决的
