### ISSUE TITLE
长连接建立好后，请求数据需要加密，发送请求前，需要做密钥协商，可以在哪个地方做协商？

### ISSUE THREAD

**Issue by njdragonfly** [Tencent/mars#511]
如题。

**Comment by garryyan** [comment]
密钥协商是在你登陆的时候协商的，为什么是长连建立后协商？

如果你必然想这么做，可以借用getLongLinkIdentifyCheckBuffer 这个接口去做密钥协商，每次长连建立之后会先调用这个接口的。
