### ISSUE TITLE
start server failed

### ISSUE THREAD

**Issue by ishall1** [Tencent/mars#515]
/mars/samples/Server/server/build/tmp/start-proxy-server.command: line 2: adb: command not found
Defining custom 'clean' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:server:extractIncludeProto

FAILURE: Build failed with an exception.

* What went wrong:
java.io.FileNotFoundException: mars/samples/Server/.gradle/2.14.1/taskArtifacts/cache.properties.lock (Permission denied)
> mars/samples/Server/.gradle/2.14.1/taskArtifacts/cache.properties.lock (Permission denied)

**Comment by garryyan** [comment]
sudo 执行下试试

**Comment by ishall1** [comment]
> sudo 执行下试试

进入..//mars/samples/Server/server/build/tmp目录手动sudo执行后成功了
