### ISSUE TITLE
有没有兼容armeabi-v7a的？

### ISSUE THREAD

**Issue by mochengsheng** [Tencent/mars#517]
有没有兼容armeabi-v7a的？

**Comment by garryyan** [comment]
1. armeabi 可以直接放到 armeabi-v7a目录下是可以用的
2. 如果要使用 armeabi-v7a的 lib, 可以通过脚本自己编译，打开编译脚本你能看到可以直接改成你想编的 cpu 架构的，或者可以传参的

**Comment by mochengsheng** [comment]
好的，谢谢

**Comment by mochengsheng** [comment]
在哪里可以下载的到armeabi的库呢？

**Comment by garryyan** [comment]
看 readme 或者 wiki
