### ISSUE TITLE
编译XLog so 报错

### ISSUE THREAD

**Issue by 123yangu** [Tencent/mars#518]
ndk path:D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-c
ollapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th
{ border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style>
<div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td>
<td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-01-15 16:31:47</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
build cmd:cmake C:\git_project\xlog\mars-master\mars -G "Unix Makefiles" -DANDROID_ABI="armeabi" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b/build
/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=gcc -DANDROID_NDK=D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b -DANDROID_PLATFORM=android-14 -DANDROID_STL="c++_shared" && cmake --build . --targe
t marsxlog --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=C:/git_project/xlog/mars-master/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=C:/git_project/xlog/mars-master/mars/cmake_build/Android
CMake Warning at D:/android_tools/adt-bundle-windows-x86_64-20140702/sdk/android-ndk-r16b/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94 (include)
  comm/CMakeLists.txt:6 (project)

CMake Warning at D:/android_tools/adt-bundle-windows-x86_64-20140702/sdk/android-ndk-r16b/build/cmake/android.toolchain.cmake:243 (message):
  armeabi is deprecated and will be removed in a future NDK release.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94 (include)
  comm/CMakeLists.txt:6 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "C:/git_project/xlog/mars-master/mars/cmake_build/Android/CMakeFiles/CMakeOutput.log".
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by garryyan** [comment]
目前我也发现在某些机器上会出现这个问题，我也会继续排查这个问题

**Comment by garryyan** [comment]
@123yangu 更新最新代码，然后同时安装官方最新的 cmake-3.13.3 再试试

**Comment by garryyan** [comment]
1. 安装 cygwin，并务必要安装其中的 make, gcc gdb
2. 把 cygwin 的 bin 目录配置到环境变量中的 PATH 中

**Comment by 123yangu** [comment]
ndk path:D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16
b
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&n
bsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="tex
t/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collap
se;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-si
ze: 11px;    line-height: 16px;    color: #737373;    background-color: white;
  margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padd
ing: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0
069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.descript
ion h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent<
/h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr><
/thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align=
"left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</t
d><td align="left">2019-03-11 14:19:26</td></tr><tr><td align="left">Revision</t
d><td align="left"></td></tr></table></div>
build cmd:cmake "C:\xlog\mars-master\mars" -G "Unix Makefiles" -DANDROID_ABI="ar
meabi" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=D:\android_tools\adt-bu
ndle-windows-x86_64-20140702\sdk\android-ndk-r16b/build/cmake/android.toolchain.
cmake -DANDROID_TOOLCHAIN=gcc -DANDROID_NDK=D:\android_tools\adt-bundle-windows-
x86_64-20140702\sdk\android-ndk-r16b -DANDROID_PLATFORM=android-14 -DANDROID_STL
="c++_shared" && cmake --build .  --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=C:/xlog/mars-master/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=C:/xlog/mars-master/mars/cmake_build/Android
CMake Warning at D:/android_tools/adt-bundle-windows-x86_64-20140702/sdk/android
-ndk-r16b/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94
(include)
  comm/CMakeLists.txt:6 (project)


CMake Warning at D:/android_tools/adt-bundle-windows-x86_64-20140702/sdk/android
-ndk-r16b/build/cmake/android.toolchain.cmake:243 (message):
  armeabi is deprecated and will be removed in a future NDK release.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94
(include)
  comm/CMakeLists.txt:6 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Mak
efiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a differen
t build tool.
-- Configuring incomplete, errors occurred!
See also "C:/xlog/mars-master/mars/cmake_build/Android/CMakeFiles/CMakeOutput.lo
g".
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

环境都已经安装了，但是还是编译错误，我用你们项目的历史版本编译是没有什么问题的

**Comment by garryyan** [comment]
cygwin 有问题。 看 [wiki](https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#%E7%8E%AF%E5%A2%83)
1. 安装 cygwin，并务必要安装其中的 make, gcc gdb
2. 把 cygwin 的 bin 目录配置到环境变量中的 PATH 中

**Comment by 123yangu** [comment]
C:\xlog\mars-master\mars>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Program\ Files\ (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt
_v6-rev0/mingw32/bin/../libexec/gcc/i686-w64-mingw32/8.1.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-8.1.0/configure --host=i686-w64-mingw32 --buil
d=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c
/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32 --enable-shared --enable-stati
c --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-tim
e=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --
enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable
-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable
-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --di
sable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu
-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-sy
stem-zlib --with-gmp=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mp
fr=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw810/prer
equisites/i686-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/i686-w64-
mingw32-static --with-pkgversion='i686-posix-dwarf-rev0, Built by MinGW-W64 proj
ect' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe
-fno-ident -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/
c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i6
86-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/i686
-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686


这个代表已经安装了gcc了，环境没有问题

**Comment by garryyan** [comment]
make 呢

**Comment by 123yangu** [comment]
C:\xlog\mars-master\mars>cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

**Comment by garryyan** [comment]
不仅需要 cmake 还需要 make. 执行下 make 试试

**Comment by 123yangu** [comment]
C:\xlog\mars-master\mars>echo %NDK_ROOt%
D:\android_tools\adt-bundle-windows-x86_64-20140702\sdk\android-ndk-r16b
这个是ndk的配置

**Comment by garryyan** [comment]
> 不仅需要 cmake 还需要 make. 执行下 make 试试

这个呢

**Comment by 123yangu** [comment]
make 不行，这个windows怎么安装，Google了好像没有找到安装教程，有个mingw-get-setup的但是下载下来这个安装不了

**Comment by garryyan** [comment]
和你在 cygwin 中安装 gcc 同样的方式去安装

**Comment by 123yangu** [comment]
mingw-get: *** ERROR *** http://prdownloads.sourceforge.net/mingw/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar.xz?download:cannot open URL
mingw-get: *** ERROR *** Get package: http://prdownloads.sourceforge.net/mingw/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar.xz?download: download failed

这个是现在的错误信息，Google了没有找到解决办法，（也尝试连接vpn翻墙也无法解决）

**Comment by garryyan** [comment]
谷歌： cygwin 国内源

**Comment by 123yangu** [comment]
已确认是make环境问题，已成功编译出so文件，感谢！！！
