### ISSUE TITLE
发送任务失败，errtype=9，errcode=-4

### ISSUE THREAD

**Issue by alpha1918** [Tencent/mars#520]
一直发送自定义业务协议的心跳包，但是在发了50几个包之后就再也发不出去了，每次都是任务失败errtype=9，errcode=-4
中间没有发送其他包，但是在发送这种心跳包失败后，其他包还能正常发送
请问这是什么原因？errtype跟errcode去看过常量的命名了，看不懂

**Comment by garryyan** [comment]
中了流量限制，一般是因为你每次发的包都一样，而且短时间发太多。
解决办法选择其中一个：
1. 每次的请求包一样
2. 降低发送频率
3. Task中的limit_flow 和 limit_frequency 设为 false

**Comment by alpha1918** [comment]
好的，谢谢，我试试
