### ISSUE TITLE
关于信令包的疑问

### ISSUE THREAD

**Issue by alpha1918** [Tencent/mars#521]
关于信令包的疑问，就是cmdid=6的那个nooping包
服务端的同事反映这个包跟正常的包，头4个字节代表的意义不同，导致处理粘包出错
信令包头4个字节（header_len）代表的是包头的长度（20字节）+body_len，即20，因为信令包的body是空的
正常业务包头4个字节代表的事包头(header_len)代表的是包头除了header_len的长度（16字节）+body_len

由于这两种包的组包时头4个字节代表的长度意义不同，处理粘包的时候无所适从，请问如何解决？

**Comment by garryyan** [comment]
header_len 代表的都是单纯包头的长度，应该都是20字节。
body_length 代表的是 body 的长度。
具体代码在longlink_packer.cc中，你应该有自定义过加解包逻辑的，检查下代码逻辑是否有问题

**Comment by alpha1918** [comment]
我明白你说的意思，但是我们没有改这部分的逻辑
我可以修改这里包头的header_len，改的跟信令包一样，问题是ios可以改，但是在android里这部分并没有暴露给我们修改

**Comment by garryyan** [comment]
即使是默认的，看代码：
st.head_length = htonl(sizeof(__STNetMsgXpHeader));
st.body_length = htonl(_body.Length());

你们大概有什么误解吧

**Comment by alpha1918** [comment]
好的，谢谢
