### ISSUE TITLE
为什么这里用==而不是.equals来判断字符串是否相等

### ISSUE THREAD

**Issue by kuangthree** [Tencent/mars#528]
[https://github.com/Tencent/mars/blob/master/samples/Server/server/src/main/java/com/tencent/mars/webserver/HelloCgi.java](url)

`            if(request.getText() == "64KB")
                size = 64*1024;
            if(request.getText() == "128KB")
size = 128*1024;`

**Comment by liushengqiang** [comment]
这个项目你可以编译通过生成.so文件吗？
