### ISSUE TITLE
关于demo的疑问

### ISSUE THREAD

**Issue by liuxupiaoxue** [Tencent/mars#53]
因为好奇就下载了源码看看，结果发现demo的聊天界面怎么似曾相识，这个http://blog.csdn.net/easyer2012/article/details/8045242是网上的一个2012年的例子（因为毕设的关系曾借鉴过），聊天界面布局有很多相似之处哦。

是因为以前人反编译过微信所以抄袭了微信？还是因为是demo的关系，随便找了网上的例子照抄的呢？

**Comment by garryyan** [comment]
在 demo 中确实借鉴了 [Android 之高仿微信聊天的界面](http://blog.csdn.net/way_ping_li/article/details/8008435)  谢谢指出，我已经在 demo 的下面添加 reademe 说明了这个事：7070ba0494e89e61ed3a4fa571364a683c0b00da

对没有及时联系原博主表示歉意，并对他的分享表示感谢，现也已经通过私信的方式联系了原博主。
