### ISSUE TITLE
缓存文件和日志文件生成错误

### ISSUE THREAD

**Issue by Xiao1209** [Tencent/mars#536]
代码如下：
```gradle
implementation 'com.tencent.mars:mars-xlog:1.0.7'
```

```java
public final class Logger {
private static final Xlog temp = new Xlog();
static {
        System.loadLibrary("c++_shared");
        System.loadLibrary("marsxlog");
        final String key = ""; 
        final int cacheDay = 3; //缓存3天
        final String SDCARD = Environment.getExternalStorageDirectory().getAbsolutePath();
//        String dir = Base64.encodeToString(BuildConfig.APPLICATION_ID.getBytes(),Base64.NO_WRAP);
        String dir = BuildConfig.APPLICATION_ID;
        final String logPath = SDCARD + "/"+dir+"/log";
//创建缓存路径方式1
        final String cachePath = SDCARD + "/"+dir + "/cache";
//创建缓存路径方式2       
        //final String cachePath = context.getFilesDir().getPath() + "/cache";
        if (BuildConfig.DEBUG){
            Xlog.appenderOpen(Xlog.LEVEL_DEBUG,Xlog.AppednerModeAsync,cachePath,logPath,"simple",cacheDay,key);
            Xlog.setConsoleLogOpen(true);
        }else {
            Xlog.appenderOpen(Xlog.LEVEL_DEBUG,Xlog.AppednerModeAsync,cachePath,logPath,"simple",cacheDay,key);
            Xlog.setConsoleLogOpen(false);
        }
        Log.setLogImp(temp);
    }
}
```
当我用`创建缓存路径方式1`时，会出现这样的目录结构
```
-sdcard
 --com.demo.kit
   --cache
     --simple.mmap3
     --simple_20190215.xlog
   --log
```

当我用`创建缓存路径方式2`时，甚至无法生成日志文件.
当然，使用方式2时，代码也会有相应改变。
```java
public static void init(Context context){
  System.loadLibrary("c++_shared");
  System.loadLibrary("marsxlog");
 //...
}
```
在`Application#onCreate`中调用
```java
   @Override
    public void onCreate() {
        super.onCreate();
        Logger.init(this);
    }
```
测试机型：
HUAWEI TIT-AL00 (Android 5.1,API 22)

**Comment by techtickcn** [comment]
我这里也一样，如果设置了缓存路径，那么日志只会生成在缓存里，而不会写到logDir

**Comment by garryyan** [comment]
[wiki](https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E) 中有提到cacheDays : 一般情况下填0即可。非0表示会在 _cachedir 目录下存放几天的日志。

**Comment by techtickcn** [comment]
> [wiki](https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E) 中有提到cacheDays : 一般情况下填0即可。非0表示会在 _cachedir 目录下存放几天的日志。

试了下用0就好了，原来缓存日期的意思是几天后从缓存目录移到日志目录。。
那么怎么设置日志目录的日志保留多少天呢？比如只保存10天的

**Comment by garryyan** [comment]
[Xlog.setMaxAliveTime](https://github.com/Tencent/mars/blob/master/mars/libraries/mars_xlog_sdk/src/main/java/com/tencent/mars/xlog/Xlog.java#L95)

**Comment by qingguoguo** [comment]
啊，浏览了这么多issue终于找到问题了，感觉没理解对文档的意思！
我也同时设置了logdir，cachedir，cacheDays 。

文档描述的是
【1.当logDir不可写时，会写到cachedir，】
【2.cacheDays : 一般情况下填0即可。非0表示会在 _cachedir 目录下存放几天的日志。】

我理所当然的想成了**cacheDays 为logDir不可写时cachedir保存的日志天数**，
但实际情况是同时设置了三个参数后，日志先保存在cachedir，保存到cacheDays 的天数后，
再转移到logDir目录。。。。。

  一直奇怪为啥logdir里面没有日志。。。。@garryyan 是不是应该更新一下文档呀
