### ISSUE TITLE
Could it be used in linux/unix , like centos, ubuntu ?

### ISSUE THREAD

**Issue by tidatida** [Tencent/mars#54]
It looks so great with a clear and  beautiful architecture.  Since it's so powerful in building a network application, could it be used  on  common unix/linux platform ?  I known nothing about xcode,  so I don't  known how to start my experience of such an open source, no auto-make / cmake / configure  . Is there a roadmap to show yours' plan?

**Comment by tidatida** [comment]
Can I use it to build an IM server and a client  to use on linux ?   Thanks for any help.

**Comment by tidatida** [comment]
难道只欢迎汉字提问？

**Comment by garryyan** [comment]
Sorry, we have no plan supporting unix/linux yet.

**Comment by tidatida** [comment]
Thx,  maybe I will do it  when I have time.

**Comment by wangyoucao577** [comment]
Hope can support Linux.
