### ISSUE TITLE
编译-Android-脚本：不能编译marsxlog.so

### ISSUE THREAD

**Issue by GeorgeBin** [Tencent/mars#540]
1. 编译-Android-Xlog ，使用build_android.py脚本编译，结果

		Enter menu:
		1. Clean && build mars.
		2. Build incrementally mars.
		3. Clean && build xlog.
		4. Exit

	在选择1、2选项时，编译出文件为单独的 libc++_shared.so 。
	在/mars/libraries/mars_android_sdk/libs/armeabi 目录下。

	在选择3选项时，编译出文件为单独的 libc++_shared.so 。
	在/mars/libraries/mars_xlog_sdk/libs/armeabi 目录下。

	编译出来的文件都是libc++_shared.so，没有生成marsxlog.so文件
2. wiki文档中“Mars-Android-接入指南-->本地编译-->编译” 相关描述，需要同步更新。
	具体内容：

		“如需要自定义日志加密算法或者长短连协议加解包，请选择static libs选项，即 2 和 3。选项 1 和 2 输出结果全部在 mars_android_sdk 目录中，3 和 4 输出结果全部在 mars_xlog_sdk 目录中。”

	https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97

**Comment by garryyan** [comment]
编译过程是否有其他报错？

**Comment by GeorgeBin** [comment]
没有报错，看日志是正常的
>上述情况是在 Mac OS上编译时出现

**Comment by garryyan** [comment]
看下 cmake_build/Android/ 目录下是否有libmarsxlog.so

**Comment by GeorgeBin** [comment]
问题原因找到，因为运行脚本的时候，是直接拖拽 build_android.py 脚本到命令行内，导致
cmake_build 文件夹创建在用户文件路径下： /Users/XXX用户名/cmake_build/Android，从而导致编译出错。
按照文档，cd到mars所在文件夹下，再执行编译脚本，就可以正常运行了
