### ISSUE TITLE
iOS xlogger_Level_impl 引起崩溃，附上bugly日志

### ISSUE THREAD

**Issue by lilong7676** [Tencent/mars#541]
libobjc.A.dylib | objc_msgSend + 28
-- | --
1 ManagePlus | 0x0000000100b44000 + 4139648
2 ManagePlus | 0x0000000100b44000 + 5262428
3 ManagePlus | 0x0000000100b44000 + 9001656
4 ManagePlus | __xlogger_Level_impl + 764868
5 ManagePlus | __xlogger_Level_impl + 358124
6 ManagePlus | __xlogger_Level_impl + 338944
7 ManagePlus | __xlogger_Level_impl + 285656
8 ManagePlus | __xlogger_Level_impl + 31832
9 ManagePlus | __xlogger_Level_impl + 27516
10 ManagePlus | __xlogger_Level_impl + 32244
11 ManagePlus | __xlogger_Level_impl + 93644
12 libsystem_pthread.dylib | __pthread_body + 128
13 libsystem_pthread.dylib | _pthread_start + 48

在每次 applicationWillEnterForeground 中 手动reportEvent_OnForeground:YES,
然后重新初始化了[NetworkService sharedInstance]  会不会和重新初始化有关？

**Comment by garryyan** [comment]
日志和网络的初始化没太大关系。
能贴符号化后的堆栈吗？这里看不到具体的代码行号，最好把所有线程的堆栈都贴上

**Comment by lilong7676** [comment]
libobjc.A.dylib | objc_retain + 16
-- | --
1 ManagePlus | 0x0000000100b08000 + 4139648
2 ManagePlus | 0x0000000100b08000 + 5262428
3 ManagePlus | 0x0000000100b08000 + 9001656
4 ManagePlus | __xlogger_Level_impl + 764868
5 ManagePlus | __xlogger_Level_impl + 358124
6 ManagePlus | __xlogger_Level_impl + 338944
7 ManagePlus | __xlogger_Level_impl + 285656
8 ManagePlus | __xlogger_Level_impl + 31832
9 ManagePlus | __xlogger_Level_impl + 27516
10 ManagePlus | __xlogger_Level_impl + 32244
11 ManagePlus | __xlogger_Level_impl + 93644
12 libsystem_pthread.dylib | __pthread_body + 128
13 libsystem_pthread.dylib | _pthread_start + 48



libsystem_kernel.dylib | 0x00000001e7065ed0 mach_msg_trap
-- | --
1 libsystem_kernel.dylib | 0x00000001e70653a8 mach_msg
2 CoreFoundation | 0x00000001e7469fb0 ___CFRunLoopServiceMachPort
3 CoreFoundation | 0x00000001e7464e4c ___CFRunLoopRun
4 CoreFoundation | 0x00000001e74645b8 CFRunLoopRunSpecific
5 GraphicsServices | 0x00000001e96d8584 GSEventRunModal
6 UIKitCore | 0x0000000213d8f558 UIApplicationMain
7 ManagePlus | 0x00000001013d8d70 0x0000000100b08000
8 libdyld.dylib | 0x00000001e6f24b94 _start


0 libsystem_kernel.dylib | 0x00000001e7070f0c __psynch_cvwait
-- | --
1 libsystem_pthread.dylib | 0x00000001e70f24c8 __pthread_cond_wait$VARIANT$armv81
2 ManagePlus | 0x0000000101e0c3ac __xlogger_Level_impl
3 ManagePlus | 0x0000000101dd1a6c base::internal::Invoker<0, base::internal::BindState<base::internal::RunnableAdapter<void (*)(asl::network::HttpResponse const&)>, void (asl::network::HttpResponse const&), void ()>, void (asl::network::HttpResponse const&)>::Run(base::internal::BindStateBase*, asl::network::HttpResponse const&)
4 ManagePlus | 0x0000000101e0d1c0 __xlogger_Level_impl
5 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
6 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


libsystem_kernel.dylib | 0x00000001e7070f0c __psynch_cvwait
-- | --
1 libsystem_pthread.dylib | 0x00000001e70f24c8 __pthread_cond_wait$VARIANT$armv81
2 ManagePlus | 0x0000000101e0c3ac __xlogger_Level_impl
3 ManagePlus | 0x0000000101e091e8 __xlogger_Level_impl
4 ManagePlus | 0x0000000101e0d1c0 __xlogger_Level_impl
5 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
6 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


libsystem_kernel.dylib | 0x00000001e7065ed0 mach_msg_trap
-- | --
1 libsystem_kernel.dylib | 0x00000001e70653a8 mach_msg
2 CoreFoundation | 0x00000001e7469fb0 ___CFRunLoopServiceMachPort
3 CoreFoundation | 0x00000001e7464e4c ___CFRunLoopRun
4 CoreFoundation | 0x00000001e74645b8 CFRunLoopRunSpecific
5 Foundation | 0x00000001e7e586a4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6 Foundation | 0x00000001e7e58550 -[NSRunLoop(NSRunLoop) runUntilDate:]
7 UIKitCore | 0x0000000213cecac0 -[UIEventFetcher threadMain]
8 Foundation | 0x00000001e7f8b3b0 ___NSThread__start__
9 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
10 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


0 libsystem_kernel.dylib | 0x00000001e7070f0c __psynch_cvwait
-- | --
1 libsystem_pthread.dylib | 0x00000001e70f24c8 __pthread_cond_wait$VARIANT$armv81
2 libc++.1.dylib | 0x00000001e663c568 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)
3 JavaScriptCore | 0x00000001ee7d939c _ZNSt3__118condition_variable10wait_untilINS_6chrono12steady_clockENS2_8durationIxNS_5ratioILl1ELl1000000000EEEEEEENS_9cv_statusERNS_11unique_lockINS_5mutexEEERKNS2_10time_pointIT with unmangled suffix "_T0_EE"
4 JavaScriptCore | 0x00000001ee7d924c std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
5 JavaScriptCore | 0x00000001ee7d7ee8 bmalloc::Scavenger::threadRunLoop()
6 JavaScriptCore | 0x00000001ee7d75a4 bmalloc::Scavenger::Scavenger(std::__1::lock_guard<bmalloc::Mutex>&)
7 JavaScriptCore | 0x00000001ee7d9050 std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*)
8 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
9 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


libsystem_kernel.dylib | 0x00000001e7065ed0 mach_msg_trap
-- | --
1 libsystem_kernel.dylib | 0x00000001e70653a8 mach_msg
2 CoreFoundation | 0x00000001e7469fb0 ___CFRunLoopServiceMachPort
3 CoreFoundation | 0x00000001e7464e4c ___CFRunLoopRun
4 CoreFoundation | 0x00000001e74645b8 CFRunLoopRunSpecific
5 CFNetwork | 0x00000001e7a84e18 -[__CoreSchedulingSetRunnable runForever]
6 Foundation | 0x00000001e7f8b3b0 ___NSThread__start__
7 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
8 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


0 libsystem_kernel.dylib | 0x00000001e7071350 __select
-- | --
1 CoreFoundation | 0x00000001e7472e00 ___CFSocketManager
2 libsystem_pthread.dylib | 0x00000001e70f52fc __pthread_body
3 libsystem_pthread.dylib | 0x00000001e70f525c _pthread_start


0 libobjc.A.dylib | objc_retain + 16
-- | --
1 ManagePlus | 0x0000000100b08000 + 4139648
2 ManagePlus | 0x0000000100b08000 + 5262428
3 ManagePlus | 0x0000000100b08000 + 9001656
4 ManagePlus | __xlogger_Level_impl + 764868
5 ManagePlus | __xlogger_Level_impl + 358124
6 ManagePlus | __xlogger_Level_impl + 338944
7 ManagePlus | __xlogger_Level_impl + 285656
8 ManagePlus | __xlogger_Level_impl + 31832
9 ManagePlus | __xlogger_Level_impl + 27516
10 ManagePlus | __xlogger_Level_impl + 32244
11 ManagePlus | __xlogger_Level_impl + 93644
12 libsystem_pthread.dylib | __pthread_body + 128
13 libsystem_pthread.dylib | _pthread_start + 48

**Comment by garryyan** [comment]
```
TLogLevel   __xlogger_Level_impl() {return gs_level;}
```
__xlogger_Level_impl 的实现只有一行代码，返回一个变量，而且看堆栈是连续调用这个函数，怀疑堆栈已经被破坏了，是有可能其他模块的 crash 导致堆栈被破坏了

**Comment by lilong7676** [comment]
多谢，我再确认下。

**Comment by lilong7676** [comment]
iOS crash 

#17 Thread

SIGSEGV

SEGV_ACCERR



0 libobjc.A.dylib | objc_retain + 16
-- | --
1 ManagePlus | -[NetworkEvent Request2BufferWithTaskID:task:] (NetworkEvent.m:69)
2 ManagePlus | -[NetworkService Request2BufferWithTaskID:userContext:] (NetworkService.mm:0)
3 ManagePlus | mars::stn::StnCallBack::Req2Buf(unsigned int, void*, AutoBuffer&, AutoBuffer&, int&, int) (stn_callback.mm:0)
4 ManagePlus | __invoke (stn_logic.cc:301)
5 ManagePlus | __RunOnStartTask (longlink_task_manager.cc:348)
6 ManagePlus | __RunLoop (list:590)
7 ManagePlus | operator() (optional.hpp:468)
8 ManagePlus | __AsyncInvokeHandler (shared_count.hpp:473)
9 ManagePlus | Run (message_queue.cc:859)
10 ManagePlus | __ThreadRunloop (function_template.hpp:878)
11 ManagePlus | start_routine (thread.h:412)
12 libsystem_pthread.dylib | __pthread_body + 128
13 libsystem_pthread.dylib | _pthread_start + 48

麻烦能看下吗。。

**Comment by garryyan** [comment]
#539  看看是否这个原因导致的

**Comment by lilong7676** [comment]
OK 我关注下崩溃率

**Comment by bravegogo** [comment]
我们的app 也频繁的报这个 __xlogger_Level_impl 崩溃：


libsystem_platform.dylib            0x000000018cb87404 0320875C-0D4B-33CE-8C06-EA3F1AF3F596 + 25604
libsystem_pthread.dylib             0x000000018cb8d1e4 63C12439-CFEC-383D-8B28-8CA6461FC408 + 20964
Xxxxxxxxxx                          0x0000000106650078 __xlogger_Level_impl + 49736
Xxxxxxxxxx                          0x000000010664d084 __xlogger_Level_impl + 37460
Xxxxxxxxxx                          0x0000000106650e8c __xlogger_Level_impl + 53340
libsystem_pthread.dylib             0x000000018cb898fc _pthread_start + 168
libsystem_pthread.dylib             0x000000018cb919d4 thread_start + 8

**Comment by bravegogo** [comment]
> libobjc.A.dylib	objc_msgSend + 28
> 1 ManagePlus	0x0000000100b44000 + 4139648
> 2 ManagePlus	0x0000000100b44000 + 5262428
> 3 ManagePlus	0x0000000100b44000 + 9001656
> 4 ManagePlus	__xlogger_Level_impl + 764868
> 5 ManagePlus	__xlogger_Level_impl + 358124
> 6 ManagePlus	__xlogger_Level_impl + 338944
> 7 ManagePlus	__xlogger_Level_impl + 285656
> 8 ManagePlus	__xlogger_Level_impl + 31832
> 9 ManagePlus	__xlogger_Level_impl + 27516
> 10 ManagePlus	__xlogger_Level_impl + 32244
> 11 ManagePlus	__xlogger_Level_impl + 93644
> 12 libsystem_pthread.dylib	__pthread_body + 128
> 13 libsystem_pthread.dylib	_pthread_start + 48
> 在每次 applicationWillEnterForeground 中 手动reportEvent_OnForeground:YES,
> 然后重新初始化了[NetworkService sharedInstance] 会不会和重新初始化有关？

你这崩溃 是怎么 解决的？？？

**Comment by lilong7676** [comment]
并没有解决，目前还没找到具体原因。。。

**Comment by chikang** [comment]
没有解决吗
