### ISSUE TITLE
长链接登录后，过段时间会断掉登录，自动重连

### ISSUE THREAD

**Issue by justyour** [Tencent/mars#543]
长链接登录后，过段时间会断掉登录，自动重连，这是怎么回事？

**Comment by garryyan** [comment]
查下断掉上下文的日志，一般是因为请求包没有回包或者回包不正确导致的。

**Comment by justyour** [comment]
IOS 如果要做重新登录应该要监听那个方法呢？怎么做登录状态的判断
看文档上 Task.need_authed = true，会有 回调接口询问是否是登录状态，但看这个方法，一直返回的是`true`， 不明白怎么判断
```
bool StnCallBack::MakesureAuthed() {
    return true;
}
```

**Comment by garryyan** [comment]
我不知道你说的登录态和MakesureAuthed是否是同一个。
1. auth 登录态是指用户使用账号密码或者本地保存的 session 登陆上去的。
2. 长连登录态是指要告诉后台你这个长连是属于哪个用户的。
1的状态回调就是MakesureAuthed，sample 中之所以全部返回 true 是偷懒了。你真实使用中要根据用户的真实状态去返回，如果没有登陆，返回 false，并且异步登陆。
2 的回调是在GetLonglinkIdentifyCheckBuffer， 你返回和后台协商好的 buffer.

**Comment by justyour** [comment]
好的，谢谢

**Comment by maoyaxiong** [comment]
MakesureAuthed的注意事项：
看到很多人问登录后长连接为啥会被服务器断开，以及MakesureAuthed相关的问题，我在这里分享一个点：
![image](https://user-images.githubusercontent.com/100395972/155647865-19ea37e4-41a5-4ab8-a773-00546e7c4115.png)
通过源码可知，长连接在建立后，会立马启动任务传送。
此时，需要认证的任务，会根据MakesureAuthed的返回值，决定是否直接发送。而mars官方示例MakesureAuthed返回的是true。导致长连接一直处于已认证状态。所以会导致任务先于登录请求，或者跟登录请求同时到达服务器。服务器对于未认证的连接，要么返回错误，要么断开连接；
以上，供大家参考！
