### ISSUE TITLE
iOS crash [NetworkEvent Request2BufferWithTaskID:task:] 

### ISSUE THREAD

**Issue by lilong7676** [Tencent/mars#546]
iOS crash 

#17 Thread

SIGSEGV

SEGV_ACCERR

0 libobjc.A.dylib | objc_retain + 16
-- | --
1 ManagePlus | -[NetworkEvent Request2BufferWithTaskID:task:] (NetworkEvent.m:69)
2 ManagePlus | -[NetworkService Request2BufferWithTaskID:userContext:] (NetworkService.mm:0)
3 ManagePlus | mars::stn::StnCallBack::Req2Buf(unsigned int, void*, AutoBuffer&, AutoBuffer&, int&, int) (stn_callback.mm:0)
4 ManagePlus | __invoke (stn_logic.cc:301)
5 ManagePlus | __RunOnStartTask (longlink_task_manager.cc:348)
6 ManagePlus | __RunLoop (list:590)
7 ManagePlus | operator() (optional.hpp:468)
8 ManagePlus | __AsyncInvokeHandler (shared_count.hpp:473)
9 ManagePlus | Run (message_queue.cc:859)
10 ManagePlus | __ThreadRunloop (function_template.hpp:878)
11 ManagePlus | start_routine (thread.h:412)
12 libsystem_pthread.dylib | __pthread_body + 128
13 libsystem_pthread.dylib | _pthread_start + 48

麻烦能看下吗。。

_Originally posted by @lilong7676 in https://github.com/Tencent/mars/issues/541#issuecomment-469476449_

**Comment by chikang** [comment]
这个你有解决吗

**Comment by lilong7676** [comment]
> 这个你有解决吗

haha，已经离职了，不清楚有没有解决呢

**Comment by chikang** [comment]
老铁，你尽然可以秒回，哈哈哈，

**Comment by chikang** [comment]
我通过bugly观察到Request2BufferWithTaskID这一行，报错：EXC_BAD_ACCESS，访问错误内存地址，

**Comment by chikang** [comment]
同时也有__xlogger_Level_impl这个错误，跟你以前反馈的两个问题一模一样😂
