### ISSUE TITLE
python build_ios.py 打包, Warning, 导致mars.framework 丢失头文件

### ISSUE THREAD

**Issue by wusijun** [Tencent/mars#548]
Warning: ../../mars/mars/comm/string_cast.h not exist
Warning: ../../mars/mars/comm/strutil.h not exist
Warning: ../../mars/mars/comm/objc/ThreadOperationQueue.h not exist
Warning: ../../mars/mars/comm/time_utils.h not exist
Warning: ../../mars/mars/baseevent/base_logic.h not exist
Warning: ../../mars/mars/comm/objc/scope_autoreleasepool.h not exist
Warning: ../../mars/mars/comm/socket/nat64_prefix_util.h not exist
Warning: ../../mars/mars/comm/verinfo.h not exist
Warning: ../../mars/mars/sdt/sdt.h not exist
Warning: ../../mars/mars/sdt/constants.h not exist
Warning: ../../mars/mars/comm/xlogger/xloggerbase.h not exist
Warning: ../../mars/mars/comm/xlogger/preprocessor.h not exist
Warning: ../../mars/mars/stn/proto/stnproto_logic.h not exist
Warning: ../../mars/mars/app/app_logic.h not exist
Warning: ../../mars/mars/log/appender.h not exist
Warning: ../../mars/mars/comm/autobuffer.h not exist
Warning: ../../mars/mars/sdt/sdt_logic.h not exist
Warning: ../../mars/mars/comm/comm_data.h not exist
Warning: ../../mars/mars/comm/socket/local_ipstack.h not exist
Warning: ../../mars/mars/stn/stn.h not exist
Warning: ../../mars/mars/app/app.h not exist
Warning: ../../mars/mars/stn/stn_logic.h not exist
Warning: ../../mars/mars/sdt/netchecker_profile.h not exist
Warning: ../../mars/mars/comm/projdef.h not exist
Warning: ../../mars/mars/comm/has_member.h not exist
Warning: ../../mars/mars/comm/http.h not exist
Warning: ../../mars/mars/comm/xlogger/xlogger.h not exist
==================Output========================
cmake_build/iOS/Darwin.out/mars.framework

**Comment by wusijun** [comment]
➜  mars git:(master) ✗ python --version
Python 2.7.16

**Comment by garryyan** [comment]
是在 build_ios.py 这个文件所在的目录执行的吗？

**Comment by WuKongCoo1** [comment]
我也遇到了这个问题，有没有解决办法啊

**Comment by garryyan** [comment]
@WuKongCoo1 是在 build_ios.py 这个文件所在的目录执行的吗？  代码所放的目录有空格吗？

**Comment by WuKongCoo1** [comment]
这个看起来就很清晰了吧
Warning: ../../mars/mars/comm/xlogger/xlogger.h not exist
==================Output========================
cmake_build/OSX/Darwin.out/mars.framework
➜  mars pwd
/Users/lineworks/Downloads/mars-master/mars

**Comment by garryyan** [comment]
明白这里的问题了，你先把mars-master目录名字改成 mars 。
之前只考虑了直接 clone 下来的编译，没考虑到直接下载 zip 包的问题，我看怎么修复下。

**Comment by WuKongCoo1** [comment]
可以了，thks

**Comment by momoliyao** [comment]
你好，这个问题在我的电脑上依然存在
Mars代码是最新的，master分支2019.04.15 16：40分又重新git clone下载的（之前git clone和zip包两种方式都试过，均不可以）
macOS Mojave 10.14.3 (18D109)
Python 2.7.10
cd /Users/yanyin/Desktop/mars/mars 
python build_ios.py
Xcode Version 10.1 (10B61)

......
Warning: ../../mars/comm/time_utils.h not exist
Warning: ../../mars/comm/http.h not exist
Warning: ../../mars/comm/socket/nat64_prefix_util.h not exist
Warning: ../../mars/comm/xlogger/xloggerbase.h not exist
Warning: ../../mars/comm/comm_data.h not exist
Warning: ../../mars/comm/has_member.h not exist
Warning: ../../mars/comm/verinfo.h not exist
Warning: ../../mars/comm/objc/scope_autoreleasepool.h not exist
Warning: ../../mars/comm/objc/ThreadOperationQueue.h not exist
Warning: ../../mars/comm/xlogger/xlogger.h not exist
Warning: ../../mars/log/appender.h not exist
Warning: ../../mars/comm/xlogger/preprocessor.h not exist
Warning: ../../mars/comm/strutil.h not exist
Warning: ../../mars/comm/socket/local_ipstack.h not exist
Warning: ../../mars/comm/projdef.h not exist
Warning: ../../mars/comm/string_cast.h not exist
Warning: ../../mars/comm/autobuffer.h not exist
==================Output========================
cmake_build/iOS/Darwin.out/mars.framework

**Comment by garryyan** [comment]
@momoliyao 更新下代码， b7aa5707a16e6a052fe667500043b5eece802be5 修复了

**Comment by momoliyao** [comment]
> @momoliyao 更新下代码， [b7aa570](https://github.com/Tencent/mars/commit/b7aa5707a16e6a052fe667500043b5eece802be5) 修复了

谢谢你，刚试了下，可以了
