### ISSUE TITLE
Android本地编译报错

### ISSUE THREAD

**Issue by MissBundle** [Tencent/mars#55]
步骤：
1，执行python build_android.py
2，选择1 编译静态库
3，选择1 armeabi架构
4，build失败。
错误日志：
Android NDK:   ../jni/build.conf    
[arm64-v8a] Compile++      : comm <= http.cc
[arm64-v8a] Compile        : comm <= md5.c
[arm64-v8a] Compile++      : comm <= memdbg.cc
[arm64-v8a] Compile++      : comm <= mmap_util.cc
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/arm64-v8a/objs/comm/__/http.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/arm64-v8a/objs/comm/__/memdbg.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/arm64-v8a/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/arm64-v8a/objs/comm/__/mmap_util.o] Error 1

**Comment by garryyan** [comment]
@MissBundle 试下最新的代码，刚修改了编译脚本，之前的编译脚本选择armeabi会编译所有的CPU架构，很容易出错，现在改成了只编一个CPU架构。

**Comment by MissBundle** [comment]
还是编译不过，我的是最新的ndk环境，好像是mmap_util.cc出错了，错误日志：
Android NDK:   ../jni/build.conf    
[armeabi] Compile++ thumb: comm <= http.cc
[armeabi] Compile thumb  : comm <= md5.c
[armeabi] Compile++ thumb: comm <= memdbg.cc
[armeabi] Compile++ thumb: comm <= mmap_util.cc
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/memdbg.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs/comm/__/http.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/md5.o] Error 1
error: unknown warning option '-Wclobbered'; did you mean '-Wconsumed'?
      [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-parameter'; did you mean
      '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
make: *** [obj/local/armeabi/objs/comm/__/mmap_util.o] Error 1

**Comment by garryyan** [comment]
ndk的具体版本是多少？r13b？r14? 在什么操作系统上编译的？

**Comment by MissBundle** [comment]
版本是r13b，在mac上编译的。
你们每次编译都会clean吗，我怎么没看到clean操作。

**Comment by garryyan** [comment]
每次都会clean 是通过删除生成的目录clean的 而且编译的时候也会加上 -B选项
你ndk-build --version   输出的信息帖一下。还有打开 ndk目录下 source.properties 里的内容也贴一下看看

**Comment by MissBundle** [comment]
ndk-build --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0


source.properties内容：
Pkg.Desc = Android NDK
Pkg.Revision = 13.1.3345770

**Comment by garryyan** [comment]
暂时看不出来，ndk13b确实在有些电脑上会编不过，我们这边没重现，也暂时没发现原因。 你换用r11c版本试试

**Comment by MissBundle** [comment]
多谢啦，换成11C之后就没有问题了。应该是13B的版本有问题，具体什么问题就不知道了。

**Comment by garryyan** [comment]
这个问题我们也会关注下，主要是现在在身边的环境没出现这个问题，不好看是什么问题。

**Comment by MissBundle** [comment]
android的编译脚本应该还有问题，我编译动态库，结果出来的还是静态库。

**Comment by garryyan** [comment]
如果选择 mars  动态库存放路径在 mars_android_sdk/libs 目录
如果选择 xlog  动态库存放路径在 mars_xlog_sdk/libs 目录

**Comment by MissBundle** [comment]
你们最新的编译脚本还是有问题，没有创建libs目录。
build succeed!
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/Users/zhuqian/Desktop/java/android-ndk-r11c/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.
build fail!!!
Traceback (most recent call last):
  File "build_android.py", line 297, in <module>
    main()
  File "build_android.py", line 286, in main
    shutil.rmtree(SO_DES_DIR)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: 'mars_android_sdk/libs/'

**Comment by garryyan** [comment]
@MissBundle  libs目录会自己创建的。你贴更靠上的日志，我看为什么编译错误，这里是因为上面执行错误 libs目录不存在导致的。这里我也会加个保护

**Comment by MissBundle** [comment]
能不能留一个联系方式啊，我把整个build的日志发给你，这样遇到问题我们交流起来也会更方便。

**Comment by garryyan** [comment]
1173828173@qq.com

**Comment by hgang** [comment]
同样的环境，同样的问题

**Comment by LiHanGuang** [comment]
@garryyan 

遇到跟 @MissBundle 同样的编译环境一样的问题, 不知道你们私下找出是什么原因了吗? 谢谢

另外, 我的编译环境 :   
mac osx 10.12    
ndk 13b  (下载地址: https://developer.android.com/ndk/downloads/revision_history.html)

**Comment by garryyan** [comment]
用r11c试试

**Comment by LiHanGuang** [comment]
ndk r11c 官网没有下载地址了...(https://developer.android.com/ndk/downloads/revision_history.html)

能否给个下载地址?

**Comment by garryyan** [comment]
@LiHanGuang 你下载你相应平台的ndk的那个url后面仔细看有个字符串代表ndk的版本 改成 你想下的版本

**Comment by lucky-chen** [comment]
这个问题解决了吗，r11c好像不能调试，这就蛋疼了

**Comment by garryyan** [comment]
调试和用哪个ndk版本无关吧？

**Comment by lucky-chen** [comment]
r11c 在AS上进不去断点，r14可以

**Comment by garryyan** [comment]
我们会尽快把新版本的ndk兼容了。。。

**Comment by helingwenkai** [comment]
Windows ndkr14b报同样的错误，换到ndkr11c后也报错，然后将目录切换后成功。要更深或者更浅的目录。 比如 之前是 a/b/c 现在可以改成 d/e 。供其他人参考
