### ISSUE TITLE
mac集成mars framework，报错'mars/stn/stn.h' file not found

### ISSUE THREAD

**Issue by WuKongCoo1** [Tencent/mars#551]
如图，按照文档https://github.com/Tencent/mars#mars_cn的流程来做的，出现如下错误，framework里是看到有这个头文件的
![image](https://user-images.githubusercontent.com/10512456/54013483-4475cb80-41b4-11e9-958a-a88fd785e533.png)

**Comment by sandy105** [comment]
@WuKongCoo1  遇到了相同的问题, 请问下怎么解决的
