### ISSUE TITLE
'micro-ecc-master/uECC.h' file not found

### ISSUE THREAD

**Issue by justyour** [Tencent/mars#558]
执行python build_ios.py 脚本编译出来的文件，导入到项目报`'micro-ecc-master/uECC.h' file not found` 文件未找到
<img width="816" alt="图片" src="https://user-images.githubusercontent.com/9986693/54531781-161c9b00-49c1-11e9-9748-3c4b2004174e.png">

**Comment by garryyan** [comment]
这个文件不需要导入你的项目中，会自动编译到静态库中的，为什么要导入到项目中呢

**Comment by garryyan** [comment]
> 这个文件不需要导入你的项目中，会自动编译到静态库中的，为什么要导入到项目中呢

刚更新了 wiki，这个文件不需要加到你项目中的。

**Comment by justyour** [comment]
好的，我用还是老版本了
