### ISSUE TITLE
iOS生成framework后，放进项目编译时间好久啊

### ISSUE THREAD

**Issue by CrazyGitter** [Tencent/mars#56]

**Comment by garryyan** [comment]
你是说的demo编译要好久？还是说单独编译 mars.framework 编译要好久？

**Comment by CrazyGitter** [comment]
@garryyan 是demo编译要好久，机器呼呼响

**Comment by garryyan** [comment]
为什么编译 demo 时 xcode 的进度条一直没进度，感觉被卡住了？

为了保证使用的 Mars 代码是最新代码，每次编译 demo 都会通过 Run Script 编译 Mars。 如果已经编译过一次，可以把 Run Script 移除，防止重复编译。

常见问题中有提到这个

**Comment by CrazyGitter** [comment]
@garryyan 恩，现在删除不会了。有个问题：生成了framework，不是已经包含头文件和静态库吗。怎么还要重新编译

**Comment by garryyan** [comment]
demo是为了保证每次使用的代码是最新代码 所以每次都会重新去编译。如果你自己的项目是没这个的。后面想个好办法自动检测 有更新才编译
