### ISSUE TITLE
想问关于 cacheDir 和 logDir

### ISSUE THREAD

**Issue by NoahNyy** [Tencent/mars#562]
设置 cacheDir 之后, log 多久会被放到 logDir 中?

有没有主动方法调用将 cacheDir 中的日志放到 logDir 中

**Comment by garryyan** [comment]
[看 wiki 中有说明](https://github.com/Tencent/mars/wiki/Mars-Android-%E6%8E%A5%E5%8F%A3%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

**Comment by NoahNyy** [comment]
之前看错了, 谢谢

**Comment by wangduanqing5945** [comment]
我用v1.3.0版本，初始化一个cacheDir，一个logDir，但无论如何日志都不会同步到logDir里，cacheDir里拆分了很多文件了，请问可能是什么原因？
logDir目录已经创建好了，有写权限。 @garryyan @NoahNyy

**Comment by NoahNyy** [comment]
cacheDir 给 `''` 试试，太久了，忘记我当时是什么原因了

**Comment by chenfuxu920** [comment]
cacheDir和logDir都可以填，cachedays 得填0，不然会一直放cacheDir而不会放logDir
