### ISSUE TITLE
腾讯视频报错

### ISSUE THREAD

**Issue by whswhs1128** [Tencent/mars#563]
ActivityManager: Start proc 18951:com.tencent.qqlive/u0a97 for activity com.tencent.qqlive/.ona.activity.WelcomeActivity
01-01 01:06:42.813  1298 15172 W ActivityManager: Slow operation: 52ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
01-01 01:06:42.870 18951 18951 I load_dex_tag: QQLiveApplication init
01-01 01:06:42.871 18951 18951 I Statistics: appStartUp()
01-01 01:06:42.871 18951 18951 I load_dex_tag: application attachBaseContext
01-01 01:06:42.872 18951 18951 I MultiDex: VM with version 2.1.0 has multidex support
01-01 01:06:42.872 18951 18951 I MultiDex: install
01-01 01:06:42.872 18951 18951 I MultiDex: VM has multidex support, MultiDex support library is disabled.
01-01 01:06:42.913  1298  1330 I ActivityManager: Start proc 18966:com.tencent.qqlive:pmservice/u0a97 for content provider com.tencent.qqlive/com.ave.rogers.vplugit
01-01 01:06:42.991 18966 18966 I load_dex_tag: QQLiveApplication init
01-01 01:06:42.992 18966 18966 I Statistics: appStartUp()
01-01 01:06:42.993 18966 18966 I load_dex_tag: application attachBaseContext
01-01 01:06:42.994 18966 18966 I MultiDex: VM with version 2.1.0 has multidex support
01-01 01:06:42.994 18966 18966 I MultiDex: install
01-01 01:06:42.994 18966 18966 I MultiDex: VM has multidex support, MultiDex support library is disabled.
01-01 01:06:43.005 18966 18966 W System  : ClassLoader referenced unknown path: 
01-01 01:06:43.009 18966 18966 E a       : ApplicationWrapper:attachBaseContext: process = com.tencent.qqlive:pmservice, processType = 18
01-01 01:06:43.023 18966 18966 I MMKV    : <MMKV.cpp:192::initialize> page size:4096
01-01 01:06:43.023 18966 18966 I MMKV    : <MMKV.cpp:204::initializeMMKV> root dir: /data/user/0/com.tencent.qqlive/files/mmkv
01-01 01:06:43.025 18966 18966 D AppConfig: traverseSharedPreferencesKey: start
01-01 01:06:43.029 18966 18966 D AppConfig: fs length is :451
01-01 01:06:43.032 18966 18966 I MMKV    : <MMKV.cpp:328::loadFromFile> loading [com.tencent.qqlive_preferences] with 0 size in total, file size is 4096
01-01 01:06:43.033 18966 18966 I MMKV    : <MMKV.cpp:372::loadFromFile> loaded [com.tencent.qqlive_preferences] with 0 values
01-01 01:06:43.038 18966 18966 I MMKV    : <MMKV.cpp:328::loadFromFile> loading [mmkv_inner_prefs_migrate_finish] with 34 size in total, file size is 4096
01-01 01:06:43.038 18966 18966 I MMKV    : <MMKV.cpp:351::loadFromFile> loading [mmkv_inner_prefs_migrate_finish] with crc 1849806459 sequence 6
01-01 01:06:43.038 18966 18966 I MMKV    : <MMKV.cpp:372::loadFromFile> loaded [mmkv_inner_prefs_migrate_finish] with 1 values
01-01 01:06:43.064 18966 18984 E SQLiteLog: (1) no such table: OnePrefs_UpdatePrefsFile
--------- beginning of crash
01-01 01:06:43.081 18966 18966 F libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xcfe9c3f4 in tid 18966 (qlive:pmservice), pid 18966 (qlive:pmservice)
01-01 01:06:43.176 18987 18987 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-01 01:06:43.177  1296  1296 I /system/bin/tombstoned: received crash request for pid 18966
01-01 01:06:43.178 18987 18987 I crash_dump32: performing dump of process 18966 (target tid = 18966)
01-01 01:06:43.178 18987 18987 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 01:06:43.178 18987 18987 F DEBUG   : Build fingerprint: 'Phytium/phytium/phytium:8.1.0/OPM8.181205.001/wanghs03210753:userdebug/test-keys'
01-01 01:06:43.178 18987 18987 F DEBUG   : Revision: '0'
01-01 01:06:43.178 18987 18987 F DEBUG   : ABI: 'arm'
01-01 01:06:43.178 18987 18987 F DEBUG   : pid: 18966, tid: 18966, name: qlive:pmservice  >>> com.tencent.qqlive:pmservice <<<
01-01 01:06:43.178 18987 18987 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xcfe9c3f4
01-01 01:06:43.179 18987 18987 F DEBUG   :     r0 ff9fc960  r1 666a55a4  r2 00000001  r3 e167f15a
01-01 01:06:43.179 18987 18987 F DEBUG   :     r4 e167f170  r5 ee9ab1b8  r6 0000001a  r7 cfeba1f0
01-01 01:06:43.179 18987 18987 F DEBUG   :     r8 ff9fc960  r9 ff9fcad4  sl cfeba258  fp ff9fcc8c
01-01 01:06:43.179 18987 18987 F DEBUG   :     ip fffe8818  sp ff9fc918  lr cfeaa239  pc cfe9c3f4  cpsr a00e0010
01-01 01:06:43.183 18987 18987 F DEBUG   : 
01-01 01:06:43.183 18987 18987 F DEBUG   : backtrace:
01-01 01:06:43.183 18987 18987 F DEBUG   :     #00 pc 000083f4  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so
01-01 01:06:43.183 18987 18987 F DEBUG   :     #01 pc 00016235  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so
01-01 01:06:43.183 18987 18987 F DEBUG   :     #02 pc 00016f8b  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so
01-01 01:06:43.183 18987 18987 F DEBUG   :     #03 pc 0001717b  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so
01-01 01:06:43.184 18987 18987 F DEBUG   :     #04 pc 0000b7b8  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so
01-01 01:06:43.184 18987 18987 F DEBUG   :     #05 pc 0001070c  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so (appender_open_with_ca)
01-01 01:06:43.184 18987 18987 F DEBUG   :     #06 pc 000051cc  /data/app/com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==/lib/arm/libmarsxlog.so (Java_com_tencent_mars)
01-01 01:06:43.184 18987 18987 F DEBUG   :     #07 pc 000aa1d3  /data/dalvik-cache/arm/data@app@com.tencent.qqlive-WzqsePAqghxZ7z8wVCRgUg==@base.apk@classes.dex (o)
01-01 01:06:43.528  1298  3168 D vndksupport: Loading /vendor/lib64/hw/gralloc.drm.so from current namespace instead of sphal namespace.
01-01 01:06:43.540  1298  3168 I EGL-MAIN: found extension DRI_Core version 2
01-01 01:06:43.541  1298  3168 I EGL-MAIN: found extension DRI_DRI2 version 4
01-01 01:06:43.562  1298  3168 I EGL-MAIN: found extension DRI_TexBuffer version 2
01-01 01:06:43.563  1298  3168 I EGL-MAIN: found extension DRI2_Flush version 4
01-01 01:06:43.563  1298  3168 I EGL-MAIN: found extension DRI_IMAGE version 17
01-01 01:06:43.564  1298  3168 I EGL-MAIN: found extension DRI_IMAGE version 17
01-01 01:06:43.564  1298  3168 I EGL-MAIN: found extension DRI_RENDERER_QUERY version 1
01-01 01:06:43.565  1298  3168 I EGL-MAIN: found extension DRI_CONFIG_QUERY version 1
01-01 01:06:43.565  1298  3168 I EGL-MAIN: found extension DRI2_Fence version 2
01-01 01:06:43.565  1298  3168 I EGL-MAIN: found extension DRI2_Interop version 1
01-01 01:06:43.566  1298  3168 I EGL-MAIN: found extension DRI_Robustness version 1
01-01 01:06:43.566  1298  3168 I EGL-MAIN: found extension DRI_NoError version 1
01-01 01:06:43.572  1298  3168 I system_server: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-01 01:06:43.572  1298  3168 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 01:06:43.573  1298  3168 D OpenGLRenderer: Swap behavior 2
01-01 01:06:43.573  1298  3168 E OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
01-01 01:06:44.083  1296  1296 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_26
01-01 01:06:44.088  1298  1364 I BootReceiver: Copying /data/tombstones/tombstone_26 to DropBox (SYSTEM_TOMBSTONE)
01-01 01:06:44.137  1298  1628 I ActivityManager: Process com.tencent.qqlive:pmservice (pid 18966) has died: fore TOP 
01-01 01:06:44.137  1298  1357 W system_server: kill(-18966, 9) failed: No such process
01-01 01:06:44.138  1298  1357 I system_server: Successfully killed process cgroup uid 10097 pid 18966 in 0ms
01-01 01:06:44.139  1230  1230 I Zygote  : Process 18966 exited due to signal (4)
01-01 01:06:44.159  1298  1628 I ActivityManager: Start proc 18995:com.tencent.qqlive:pmservice/u0a97 for restart com.tencent.qqlive:pmservice

在最新版本的腾讯视频中报错，此硬件平台为android-x86移植到arm64。老版本无问题。其他应用无问题。
能帮忙看看吗？有什么思路？

**Comment by garryyan** [comment]
必现吗？必现的话应该是架构兼容性问题

**Comment by whswhs1128** [comment]
> 必现吗？必现的话应该是架构兼容性问题

不是架构相关，有源码内核上必现，有个其他的二进制源码无此问题

**Comment by garryyan** [comment]
试试在必现的内核上，用 github 上的库测试下是否有问题。

**Comment by whswhs1128** [comment]
> 试试在必现的内核上，用 github 上的库测试下是否有问题。

01-01 00:01:07.613  1280  1280 I /system/bin/tombstoned: received crash request for pid 3080
01-01 00:01:07.615  3101  3101 I crash_dump32: performing dump of process 3080 (target tid = 3080)
01-01 00:01:07.616  3101  3101 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 00:01:07.616  3101  3101 F DEBUG   : Build fingerprint: 'Phytium/phytium/phytium:8.1.0/OPM8.181205.001/wanghs03210753:userdebug/test-keys'
01-01 00:01:07.616  3101  3101 F DEBUG   : Revision: '0'
01-01 00:01:07.617  3101  3101 F DEBUG   : ABI: 'arm'
01-01 00:01:07.617  3101  3101 F DEBUG   : pid: 3080, tid: 3080, name: qlive:pmservice  >>> com.tencent.qqlive:pmservice <<<
01-01 00:01:07.617  3101  3101 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xd334d3f4
01-01 00:01:07.617  3101  3101 F DEBUG   :     r0 ffa5da10  r1 60aa99d4  r2 00000001  r3 e576ed53
01-01 00:01:07.618  3101  3101 F DEBUG   :     r4 e576ed60  r5 f0c6e1b8  r6 00000011  r7 d336b1f0
01-01 00:01:07.618  3101  3101 F DEBUG   :     r8 ffa5da10  r9 ffa5db84  sl d336b234  fp ffa5dd3c
01-01 00:01:07.618  3101  3101 F DEBUG   :     ip fffe8818  sp ffa5d9c8  lr d335b239  pc d334d3f4  cpsr a00e0010
01-01 00:01:07.672  1284  1489 I WifiService: getWifiEnabledState uid=10065
01-01 00:01:07.675  1284  1489 I WifiService: getDhcpInfo uid=10065
01-01 00:01:07.675  1284  1489 I WifiService: getSupportedFeatures uid=10065
01-01 00:01:07.715  3101  3101 F DEBUG   : 
01-01 00:01:07.715  3101  3101 F DEBUG   : backtrace:
01-01 00:01:07.715  3101  3101 F DEBUG   :     #00 pc 000083f4  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so
01-01 00:01:07.715  3101  3101 F DEBUG   :     #01 pc 00016235  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so
01-01 00:01:07.715  3101  3101 F DEBUG   :     #02 pc 00016f8b  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so
01-01 00:01:07.715  3101  3101 F DEBUG   :     #03 pc 0001717b  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so
01-01 00:01:07.715  3101  3101 F DEBUG   :     #04 pc 0000b7b8  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so
01-01 00:01:07.715  3101  3101 F DEBUG   :     #05 pc 0001070c  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so (appender_open_with_cache)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #06 pc 000051cc  /data/app/com.tencent.qqlive-1/lib/arm/libmarsxlog.so (Java_com_tencent_mars_xl)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #07 pc 00405c79  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #08 pc 00401775  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #09 pc 004069eb  /system/lib/libart.so (art_quick_invoke_static_stub+226)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #10 pc 000afedf  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsi)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #11 pc 00200de7  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art)
01-01 00:01:07.715  3101  3101 F DEBUG   :     #12 pc 001fcfcd  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #13 pc 003edaef  /system/lib/libart.so (MterpInvokeStaticRange+122)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #14 pc 003f4014  /system/lib/libart.so (ExecuteMterpImpl+15380)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #15 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #16 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #17 pc 001fcfb5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #18 pc 003edaef  /system/lib/libart.so (MterpInvokeStaticRange+122)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #19 pc 003f4014  /system/lib/libart.so (ExecuteMterpImpl+15380)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #20 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #21 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #22 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #23 pc 003ec77f  /system/lib/libart.so (MterpInvokeDirect+250)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #24 pc 003f3c94  /system/lib/libart.so (ExecuteMterpImpl+14484)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #25 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #26 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.716  3101  3101 F DEBUG   :     #27 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #28 pc 003ec77f  /system/lib/libart.so (MterpInvokeDirect+250)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #29 pc 003f3c94  /system/lib/libart.so (ExecuteMterpImpl+14484)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #30 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #31 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #32 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #33 pc 003ec77f  /system/lib/libart.so (MterpInvokeDirect+250)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #34 pc 003f3c94  /system/lib/libart.so (ExecuteMterpImpl+14484)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #35 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #36 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #37 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #38 pc 003eb8d3  /system/lib/libart.so (MterpInvokeVirtual+482)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #39 pc 003f3b94  /system/lib/libart.so (ExecuteMterpImpl+14228)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #40 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #41 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #42 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #43 pc 003ec8ed  /system/lib/libart.so (MterpInvokeStatic+184)
01-01 00:01:07.717  3101  3101 F DEBUG   :     #44 pc 003f3d14  /system/lib/libart.so (ExecuteMterpImpl+14612)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #45 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #46 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #47 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #48 pc 003ec8ed  /system/lib/libart.so (MterpInvokeStatic+184)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #49 pc 003f3d14  /system/lib/libart.so (ExecuteMterpImpl+14612)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #50 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #51 pc 001e7481  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art:)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #52 pc 001fc351  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #53 pc 003ec8ed  /system/lib/libart.so (MterpInvokeStatic+184)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #54 pc 003f3d14  /system/lib/libart.so (ExecuteMterpImpl+14612)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #55 pc 001e2dbd  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::Co)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #56 pc 001e73c9  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Th)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #57 pc 003e11c1  /system/lib/libart.so (artQuickToInterpreterBridge+924)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #58 pc 00405cf1  /system/lib/libart.so (art_quick_to_interpreter_bridge+32)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #59 pc 00401775  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #60 pc 004069eb  /system/lib/libart.so (art_quick_invoke_static_stub+226)
01-01 00:01:07.718  3101  3101 F DEBUG   :     #61 pc 000afedf  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsi)
01-01 00:01:07.719  3101  3101 F DEBUG   :     #62 pc 00200de7  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art)
01-01 00:01:07.719  3101  3101 F DEBUG   :     #63 pc 001fc369  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPN)
01-01 00:01:08.523  1280  1280 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_04
01-01 00:01:08.527  1284  1362 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
01-01 00:01:08.570  1284  1321 I ActivityManager: Process com.tencent.qqlive:pmservice (pid 3080) has died: fore TOP 
01-01 00:01:08.570  1284  1352 W system_server: kill(-3080, 9) failed: No such process

新编了一个so，同样会闪退，有办法知道具体是内核哪块的问题吗？

**Comment by garryyan** [comment]
自己编的库是有符号信息的，ndk-stack一下看行号死在了哪一行代码上

**Comment by whswhs1128** [comment]
> 试试在必现的内核上，用 github 上的库测试下是否有问题。

用新编译的so，apk可以正常使用了，so之前拷错了目录。感谢！
但是想请问之前同样的apk 为何在不同内核上会有差异？

**Comment by garryyan** [comment]
可能和编译使用的 ndk 版本有关系，也可能和 cpu 架构有关系。

**Comment by steven-ma** [comment]
我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128

**Comment by whswhs1128** [comment]
自己去github下mars的库 下载完adb push到apk目录替换可以解决，没有深入研究了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/mars"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 上午10:04
收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;;
抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563)





 
我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128

**Comment by steven-ma** [comment]
> 自己去github下mars的库 下载完adb push到apk目录替换可以解决，没有深入研究了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/mars" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:04 收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;; 抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563) 我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，这个方案确实可行，就是每次重新安装都得来一次

**Comment by whswhs1128** [comment]
你是用的什么开发板？自己编译的内核吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/mars"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 上午10:16
收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;;
抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563)





  
自己去github下mars的库 下载完adb push到apk目录替换可以解决，没有深入研究了。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/mars" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:04 收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;; 抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563) 我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
嗯，这个方案确实可行，就是每次重新安装都得来一次

**Comment by steven-ma** [comment]
> 你是用的什么开发板？自己编译的内核吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/mars" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:16 收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;; 抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563) 自己去github下mars的库 下载完adb push到apk目录替换可以解决，没有深入研究了。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/mars" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:04 收件人:&nbsp;"Tencent/mars"<mars@noreply.github.com&gt;; 抄送:&nbsp;"王翰生"<972120951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/mars] 腾讯视频报错 (#563) 我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 嗯，这个方案确实可行，就是每次重新安装都得来一次 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

用的是rk3399 编译的是AOSP8.1 内核应该是4.9  

http://wiki.t-firefly.com/zh_CN/Firefly-RK3399/compile_android8.1_firmware.html

你是什么版本？

**Comment by ipfgao** [comment]
一样的问题，原因到底在哪里？

**Comment by ipfgao** [comment]
> 我遇到了相同的问题，而且堆栈也是一模一样的，都是挂在PC 000083f4 这个地方，自己编译一个版本，V1.2.2没有问题，楼主后来解决了吗？是否跟内核编译的某个参数有影响 @whswhs1128

同000083f4

**Comment by ipfgao** [comment]
> > 必现吗？必现的话应该是架构兼容性问题
> 
> 不是架构相关，有源码内核上必现，有个其他的二进制源码无此问题

能否用scripts/extract-ikconfig分别提取两个内核的config对比一下？
