### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Beautifulskin** [Tencent/mars#564]
你好，情况是这样的，我们想在原本的xlog上添加一些自己的so库，但是xlog好像用的stlport_shared,而我们自己的so库用的则是c++_shared,因为用的xlog的脚本进行编译（当然我们也进行了修改）所以就想着直接把xlog的stdport_shared换成c++_shared,但是有很多问题爆出，我想问下这类情况有什么建议可以给我吗？或者说我这种做法本来就有问题 非常感谢（大四学生在公司实习，很多不懂，还望大佬给点意见）

**Comment by garryyan** [comment]
最新代码xlog 使用的库也已经换成了c++_share

**Comment by Beautifulskin** [comment]
> 最新代码xlog 使用的库也已经换成了c++_shared

好滴 感谢
