### ISSUE TITLE
android Logcat 输出tag不明确

### ISSUE THREAD

**Issue by caoanqi** [Tencent/mars#572]
![image](https://user-images.githubusercontent.com/3326826/55468933-06df5380-5637-11e9-9f44-c3fdea222ccd.png)

android logcat 输出的信息为什么会有中括号，里面的信息是什么？  应该怎么设置

**Comment by garryyan** [comment]
文件，函数，行号

但是 java 获取这三个信息担心有效率问题，所以留空了，在 cpp 中可以通过宏来获取

**Comment by caoanqi** [comment]
@garryyan 好的，谢谢
