### ISSUE TITLE
自定义长链接文件后,根据wiki ndk-build -B -j没法编译

### ISSUE THREAD

**Issue by SmallerRui** [Tencent/mars#577]
自定义长链接文件后,根据wiki ndk-build -B -j没法编译
 ndk-build -B -j
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
/Users/***/Library/Android/sdk/android-ndk-r16b/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.
请问修改longlink.cc后如何打包成最终包

**Comment by garryyan** [comment]
自定义后直接使用 python build_android.py进行编译即可

**Comment by SmallerRui** [comment]
谢谢,已经解决

**Comment by rishli** [comment]
请问是怎么解决的?
