### ISSUE TITLE
ios上传文件解压失败（[F][ last log...）

### ISSUE THREAD

**Issue by haizhiyun** [Tencent/mars#579]
错误信息：
[F][ last log file:/var/mobile/Containers/Data/Application/1819204D-1FD7-4D49-B8DA-7E6B2B6795B1/Documents/xmlog/XM_20190409.xlog from 2019-04-09 +0800 07:05:42 to 2019-04-09 +0800 10:24:12, time_diff:11910, tick_diff:9855603

---
请问这个信息是什么错误导致的呢

**Comment by garryyan** [comment]
忽略即可，一般是因为手机休眠导致时间计算有误，这是个提示信息。
