### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by dianyuyue** [Tencent/mars#583]
/home/a/Downloads/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open /home/a/Downloads/mars-master/mars/libraries/mars_android_sdk/jni/export.exp: No such file or directory/home/a/Downloads/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: unable to parse version script file /home/a/Downloads/mars-master/mars/libraries/mars_android_sdk/jni/export.expcollect2: error: ld returned 1 exit statusCMakeFiles/marsstn.dir/build.make:81: recipe for target 'libmarsstn.so' failedmake[2]: *** [libmarsstn.so] Error 1CMakeFiles/Makefile2:113: recipe for target 'CMakeFiles/marsstn.dir/all' failedmake[1]: *** [CMakeFiles/marsstn.dir/all] Error 2Makefile:129: recipe for target 'all' failedmake: *** [all] Error 2!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by garryyan** [comment]
没有修改 build_android.py 直接编译的吧？

**Comment by dianyuyue** [comment]
对的 没做任何修改

**Comment by garryyan** [comment]
看是否 存在 /home/a/Downloads/mars-master/mars/libraries/mars_android_sdk/jni/export.exp 这个文件

**Comment by dianyuyue** [comment]
已经没问题了 可能环境问题
