### ISSUE TITLE
单件类使用crash

### ISSUE THREAD

**Issue by stevezhou6** [Tencent/mars#587]
在我代码中和mars一样也使用了单件类
NetCore::NetCore(){
ActiveLogic::Singleton::Instance()->SignalActive......
}
    
NetCore::Singleton::Release();
    SINGLETON_RELEASE_ALL();
    // others use activelogic may crash after activelogic release. eg: LongLinkConnectMonitor

mars的单件类是全局静态对象，程序关闭的时候，对象会进行析够，并且析构是有顺序的，这种单件类很容易造成程序crash，如果是new出来的对象，则不会析够则没有上述问题。
再者就是其他单件类互相访问必须使用STN_WEAK_CALL这种方式。本人使用遇到好几个这种肯。

**Comment by garryyan** [comment]
对的，现在使用 SINGLETON 比较容易出问题，需要特别注意，有的时候在程序退出的时候可以不释放。

**Comment by stevezhou6** [comment]
单件类你是静态对象，怎么不释放，改成指针吗？

**Comment by garryyan** [comment]
是在哪个平台下使用的？

**Comment by stevezhou6** [comment]
android ios

**Comment by garryyan** [comment]
程序退出的时候是否调用了 onDestroy? 自己主动释放

**Comment by stevezhou6** [comment]
我只是使用了mars的部分组件代码，没有调用onDestroy.
现在打算自己来利用全局对象关系来卓个释放。全局静态对象释放顺序来释放。
