### ISSUE TITLE
netsource_timercheck中select出错为什么不退出

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#589]
在netsource_timercheck文件的__TryConnnect函数中，有while(true)循环，但是看select返回小于0的值时，只是打error级别日志，没有break，是忘了写还是有其它特殊原因？
![20190422162218](https://user-images.githubusercontent.com/10632522/56491583-a3509380-651b-11e9-87d1-8831d80afdff.jpg)

**Comment by garryyan** [comment]
看了下代码，是忘了写了，你有遇到死循环的场景？
