### ISSUE TITLE
What does "probe bigger heart on Wednesday" mean?

### ISSUE THREAD

**Issue by ddinn** [Tencent/mars#59]
Hi,

I found some confusing codes in "smart_hearbeat.cc", 
quotes:
"               // heart info changed recently,Don't need probe
                // probe bigger heart on Wednesday
                if ((cur_time - current_net_heart_info_.last_modify_time_) >= ONE_DAY_SECONEDS && cur_TM.tm_wday == 2) {
                    xinfo2(TSF"__TryProbeBiggerHeart. curHeart=%0  ", current_net_heart_info_.cur_heart_);
                    current_net_heart_info_.cur_heart_ += SuccessStep;
                    current_net_heart_info_.success_curr_heart_count_ = 0;
                    current_net_heart_info_.is_stable_ = false;
                    current_net_heart_info_.fail_heart_count_ = 0;
                    __SaveINI();
                }
"

What would happen on Wednesday? And What's differences between |SuccessStep| and |HeartStep|?

**Comment by dodola** [comment]
mark , interesting

**Comment by garryyan** [comment]
haha... it can be any day of the week.
