### ISSUE TITLE
xlogger中xexitmsg_function宏定义问题

### ISSUE THREAD

**Issue by wosshzhb** [Tencent/mars#590]
在xlogger.h文件中xexitmsg_function及xexitmsg_function_if宏定义里面____xloger_anonymous_function_scope_20151022____这个是未定义的变量。

xexitmsg_function是一定要和xinfo_function这个对称着出现吗？

![image](https://user-images.githubusercontent.com/10632522/56502461-f2f78500-6544-11e9-91e6-a4764897f319.png)

**Comment by garryyan** [comment]
一定要对着出现的
