### ISSUE TITLE
iOS编译问题

### ISSUE THREAD

**Issue by yuxiaoyick** [Tencent/mars#591]
下载zip解压后，用终端cd到build_ios.py文件下，然后执行python build_ios.py，报错：

`Enter menu:
1. Clean && build mars.
2. Clean && build xlog.
3. Gen iOS mars Project.
4. Exit
3
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-04-23 15:14:48</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
sh: cmake: command not found
!!!!!!!!!!!gen fail!!!!!!!!!!!!!!!`

这是什么情况？有点懵

**Comment by wakacoon** [comment]
安装cmake

**Comment by wakacoon** [comment]
安装后也不行
Enter menu:
1. Clean && build mars.
2. Clean && build xlog.
3. Gen iOS mars Project.
4. Exit
3
[[==BUILD_DESCRIPTION==]]Revision: b7aa570 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left">master</td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-04-24 13:57:39</td></tr><tr><td align="left">Revision</td><td align="left">b7aa570</td></tr></table></div>
-- CMAKE_INSTALL_PREFIX=/Users/hwy-ytj-025/mars/mars/cmake_build/iOS
-- CMAKE_INSTALL_PREFIX=/Users/hwy-ytj-025/mars/mars/cmake_build/iOS
-- Building with Xcode version: 
-- Configuring iOS build for platform: OS, architecture(s): armv7;arm64
-- Using SDK:  for platform: OS
CMake Error at ios.toolchain.cmake:193 (message):
  Please make sure that Xcode is installed and that the toolchainis pointing
  to the correct path.  Please run:sudo xcode-select -s
  /Applications/Xcode.app/Contents/Developerand see if that fixes the problem
  for you.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:90 (include)
  comm/CMakeLists.txt:6 (project)


CMake Error at ios.toolchain.cmake:197 (message):
  Invalid CMAKE_OSX_SYSROOT: does not exist.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:90 (include)
  comm/CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
!!!!!!!!!!!gen fail!!!!!!!!!!!!!!!

**Comment by zyfu0000** [comment]
sudo Xcode-select -s /Applications/Xcode.app 一下

**Comment by garryyan** [comment]
> sudo Xcode-select -s /Applications/Xcode.app 一下

@wakacoon

**Comment by yuxiaoyick** [comment]
ok了，解决方法：
下载zip解压后，用终端cd到build_ios.py文件下，
然后去 [下载cmake](https://cmake.org/download/)  ，
执行`sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install`
最后执行python build_ios.py
