### ISSUE TITLE
xlog日志文件疑问

### ISSUE THREAD

**Issue by momoliyao** [Tencent/mars#596]
我已经看了wiki还有和日志相关的issue单，没有找到相似问题的解答
os: mac ios
首先，问题是：项目初次启动时，打印logpath，直接复制文件路径，前往文件夹，看到只有Test.mmap3文件，没有.xlog文件，第二次运行时才会有；
然后我把Test.mmap3文件和.xlog文件手动删除，运行项目，还是只生成Test.mmap3文件，然后再一次，才会有.xlog文件，就是感觉初次运行时是不是不会生成.xlog文件？？
其次，我想要每次项目启动时，都删除日志文件和缓存文件mmap3，然后我去修改了appender.cc文件中，static const long kMaxLogAliveTime = 0;    但是这样并没与效果，启动时，上次的日志文件和缓存文件依然存在，请问是我修改的不对吗？

**Comment by qingkouwei** [comment]
日志有个最大保存时间,启动了以后要达到一定条件,比如mmap写到一定程度才会往文件写.

**Comment by momoliyao** [comment]
> 日志有个最大保存时间,启动了以后要达到一定条件,比如mmap写到一定程度才会往文件写.

你好，我看到文档中写到，日志文件最大保存10天之前的文件static const long kMaxLogAliveTime=10*24*60*60；我想要在项目启动的时候就清除之前的文件，然后我将kMaxLogAliveTime=0改成了这样，我以为这样是可以的，实际上我这边并没生效，我不知道是不是改错了哪里

**Comment by qingkouwei** [comment]
它这个清除过期文件实在启动后2分钟后执行

**Comment by momoliyao** [comment]
> 它这个清除过期文件实在启动后2分钟后执行

好的，谢谢你，我修改了我项目中的业务逻辑，暂时还不是非必要这么做，我想有时间在验证一下

**Comment by xiaoqi010205** [comment]
> 日志有个最大保存时间,启动了以后要达到一定条件,比如mmap写到一定程度才会往文件写.



> 
这个mmap的设置在哪里改呀？我也出现这个问题了，每次都要第二次运行才会出现.xlog文件
