### ISSUE TITLE
xlog 单进程多文件隔离支持

### ISSUE THREAD

**Issue by haizhiyun** [Tencent/mars#597]
你好，想请教下，如果我自己修改多文件支持的话，修改思路如下，不知道还有哪些没有考虑周全的：
appender.cc 里面的静态的东西 改成类属性所属的东西

**Comment by garryyan** [comment]
修改思路可参考：feature/xlog_multi_file_from_master 分支

**Comment by haizhiyun** [comment]
@garryyan 多谢，试了下，上面那种修改问题很多，会参考下你的思路。
不过还是希望官方能推动这个实现，感觉很多场景还是需要这个的

**Comment by haizhiyun** [comment]
feature/xlog_multi_file_from_maste分支的源码编译xlog库太大：是哪里有问题吗
 677472  5 15 13:47 libc++_shared.so （600K以上）
3289600  5 15 13:47 libmarsxlog.so  （3M 以上）

编译选项：
python build_android.py 
1. Clean && build mars.
2. Build incrementally mars.
3. Clean && build xlog.
4. Exit
3

**Comment by garryyan** [comment]
> @garryyan 多谢，试了下，上面那种修改问题很多，会参考下你的思路。
> 不过还是希望官方能推动这个实现，感觉很多场景还是需要这个的

后续会支持，最近有其他优先级比较高的工作要做，所以暂时搁置了

>==================Output========================
libs(release): libraries/mars_xlog_sdk/libs/armeabi
symbols(must store permanently): libraries/mars_xlog_sdk/obj/local/armeabi

注意编译结束后的提示信息，真正用来发布的库在libraries/mars_xlog_sdk/libs/armeabi，你看到的 3M 的是符号信息，位置在libraries/mars_xlog_sdk/obj/local/armeabi，符号信息也需要永久保存，方便后面 ndk-stack

**Comment by wangli135** [comment]
这个分支的代码还是半成品吧？能说下当前完成的工作和未完成的工作吗？有这个需求，想就着你这个分支后面继续开发

**Comment by garryyan** [comment]
@wangli135  java 那边的接口还没改过来，不能直接通过 Log.i去打印了，需要有日志实例。
最重要的，代码需要灰度，这个流程也没走。

**Comment by wangli135** [comment]
大佬回复速度好及时。我试着改了下java接口，确实可以多文件了，不过好像有点不太稳定，会有SIGSEGV崩溃

**Comment by garryyan** [comment]
所以其实也缺少了测试，因为代码都不算完成呢，🤣

**Comment by wangli135** [comment]
期待更新

**Comment by xabad** [comment]
期待更新

**Comment by haizhiyun** [comment]
有进展吗，可以参与测试

**Comment by milkywayriver** [comment]
期待更新

**Comment by xabad** [comment]
期待后续

**Comment by brady2037** [comment]
期待更新

**Comment by EthanCo** [comment]
期待更新

**Comment by 0x1306a94** [comment]
我的项目用 `pod` 集成了 `A(静态库)` `B(动态库)` 两个库, `A` `B` 两个库都有使用`xlog`记录日志.
我自己又编译了一份`xlog`,然后集成到项目中,并在`main`中初始化了`xlog`
其中`B`库的日志是加密的, 但是由于我的是在`main`中初始化的,最后就好导致`B`库中的日志和我的日志写到一起了
但是`A`库的日志又完全不受影响,还是写到他自己的日志目录下的

**Comment by zyfu0000** [comment]
https://github.com/zyfu0000/mars

可以试试我们的 fork，feature/xlog_multi_file_from_maste 分支上修改而来，已经上线

**Comment by haizhiyun** [comment]
看到最新提交日志支持多文件，是支持不同的日志写入不同的文件吗？有使用说明没

**Comment by zyfu0000** [comment]
@haizhiyun  是的，可以看看代码实现。很容易理解

**Comment by haizhiyun** [comment]
Ok,辛苦了，感谢维护的大佬们提供&维护这个强大的开源库 hang lu 邮箱：luhanghaizhiyun@gmail.com 签名由 网易邮箱大师 定制 在2021年01月29日 09:46，zyfu0000 写道： @haizhiyun 是的，可以看看代码实现。很容易理解 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by haizhiyun** [comment]
> @haizhiyun 是的，可以看看代码实现。很容易理解

ok ！辛苦，感谢提供一个强大的开源库

**Comment by adffice** [comment]
在arm64-v8a上```public native int getLogLevel(long logInstancePtr);```总是返回6
经过对比发现：
armeabi-v7a

![armeabi-v7a](https://files.catbox.moe/q4n3fx.png)

arm64-v8a

![arm64-v8a](https://files.catbox.moe/uun9oq.png)

```c
JNIEXPORT jint JNICALL Java_com_tencent_mars_xlog_Xlog_getLogLevel
  (JNIEnv *, jobject, jlong _log_instance_ptr) {
	// 这里不能判断小于0，因为指针有可能为负数
    // if (_log_instance_ptr < 0) return kLevelNone;
    if (_log_instance_ptr != -1) return kLevelNone;
    return mars::xlog::GetLevel(_log_instance_ptr);
}
```

**Comment by mhp699379** [comment]
> https://github.com/zyfu0000/mars
> 
> 可以试试我们的 fork，feature/xlog_multi_file_from_maste 分支上修改而来，已经线上验证

大佬，请问如何开启多文件隔离的功能呢，我在iOS 上创建了两个打印日志的单例，分别是两个文件夹路径，可是还是会打印到第一个文件上面， 日志输出“appender has already been opened.”

**Comment by a8453770** [comment]
期待更新

**Comment by WhityLL** [comment]
期待支持多文件写日志

**Comment by xiaoqi010205** [comment]
> https://github.com/zyfu0000/mars
> 
> 可以试试我们的 fork，feature/xlog_multi_file_from_maste 分支上修改而来，已经线上验证

我用了这个还是不行，没有办法打多个文件，引进去都会出错。

**Comment by 0x1306a94** [comment]
不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)

**Comment by xiaoqi010205** [comment]
> 文件

就是不用appender.h 直接用xlogger_interface.h来初始化是嘛？
谢谢，我再试一下，自己写有时候看不明白

**Comment by xiaoqi010205** [comment]
> 不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)

可是文件的config不是始终都是同一个吗？

**Comment by 0x1306a94** [comment]
> > 不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)
> 
> 可是文件的config不是始终都是同一个吗？


```C++
// init
do {
    mars::xlog::XLogConfig config;
    config.logdir_ = logPath;
    config.nameprefix_ = "A";

    mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
} while (0);

do {
   mars::xlog::XLogConfig config;
   config.logdir_ = logPath;
   config.nameprefix_ = "B";

   mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
} while (0);

// write
do {
    mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("A");
    if (logger == nullptr) {
        return;
    }
    mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
} while (0);

do {
    mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("B");
    if (logger == nullptr) {
        return;
    }
    mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
} while (0);
```

**Comment by xiaoqi010205** [comment]
> > > 不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)
> > 
> > 
> > 可是文件的config不是始终都是同一个吗？
> 
> ```c++
> // init
> do {
>     mars::xlog::XLogConfig config;
>     config.logdir_ = logPath;
>     config.nameprefix_ = "A";
> 
>     mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> do {
>    mars::xlog::XLogConfig config;
>    config.logdir_ = logPath;
>    config.nameprefix_ = "B";
> 
>    mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> // write
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("A");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> 
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("B");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> ```

谢谢你！🙏🙏，我昨晚弄了好久都不行，我现在就去试试，爱你。

**Comment by xiaoqi010205** [comment]
> > > 不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)
> > 
> > 
> > 可是文件的config不是始终都是同一个吗？
> 
> ```c++
> // init
> do {
>     mars::xlog::XLogConfig config;
>     config.logdir_ = logPath;
>     config.nameprefix_ = "A";
> 
>     mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> do {
>    mars::xlog::XLogConfig config;
>    config.logdir_ = logPath;
>    config.nameprefix_ = "B";
> 
>    mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> // write
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("A");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> 
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("B");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> ```

太谢谢你啦！我自己弄了好久都没弄明白，现在可以啦，谢谢🙏，感恩有你🌹🌹🌹__

**Comment by xiaoqi010205** [comment]
[F]decode_log_file.py decode error len=1253 多个文件解密的时候出现这个是为什么呀？

**Comment by xiaoqi010205** [comment]
> > > 不是已经提供了多文件支持吗 [xlogger_interface.h](https://github.com/Tencent/mars/blob/master/mars/log/xlogger_interface.h)
> > 
> > 
> > 可是文件的config不是始终都是同一个吗？
> 
> ```c++
> // init
> do {
>     mars::xlog::XLogConfig config;
>     config.logdir_ = logPath;
>     config.nameprefix_ = "A";
> 
>     mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> do {
>    mars::xlog::XLogConfig config;
>    config.logdir_ = logPath;
>    config.nameprefix_ = "B";
> 
>    mars::comm::XloggerCategory *logger = mars::xlog::NewXloggerInstance(config, level);
> } while (0);
> 
> // write
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("A");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> 
> do {
>     mars::comm::XloggerCategory *logger = mars::xlog::GetXloggerInstance("B");
>     if (logger == nullptr) {
>         return;
>     }
>     mars::xlog::XloggerWrite(uintptr_t(logger), NULL, "log message");
> } while (0);
> ```

可以问问这个有时候为什么初始化出来只有.mmap文件但是却没有生成.xlog文件，要第二次运行有了.mmap文件才会生成.xlog文件吗？

**Comment by agoodcoolman** [comment]
几年了，也不知道更新没。

**Comment by EtherealYi** [comment]
请问多文件的事情有后续了么
