### ISSUE TITLE
WeakNetworkLogic的疑问

### ISSUE THREAD

**Issue by xiazhouquan** [Tencent/mars#598]
在看WeakNetworkLogic类的逻辑时候，发现在长链接/短链接任务响应以及接收到数据的时候调用OnConnectEvent OnPkgEvent OnPkgEvent函数更新并计算is_curr_weak_以及tickcount（是否是弱网络)，但是怎么使用IsCurrentNetworkWeak呢，一般该在哪里使用，怎么用？谢谢开源

**Comment by garryyan** [comment]
这个模块现在我们只是用做统计，并不会影响现行逻辑。 你之所以没看到别处在调用IsCurrentNetworkWeak，是因为统计代码，是基于 mars 做的扩展，不在开源的范围内。
