### ISSUE TITLE
iOSDemo crash 

### ISSUE THREAD

**Issue by LemonGui** [Tencent/mars#6]
iOSDemo crash  -- TopicViewController.m  --  line79  [_recvContentField setText:recvtext]; 
'NSInternalInconsistencyException', reason: '-[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.'

**Comment by shockcao** [comment]
thanks for your issue, UI for iOSDemo has not been completed, we should fix it as soon as possible.
the network & log util work well in demo, u can comment out the crash code

**Comment by zxedker** [comment]
#0ca674f
