### ISSUE TITLE
只用xlog的话似乎不兼容

### ISSUE THREAD

**Issue by liangxiwei** [Tencent/mars#600]
看了下只有x86和armeabi才有对应的marxxlog.so,并不是全平台编译，目前市面上很多项目都只保留一个armeabi-v7a的目录，这样子就没法直接引用只能自己编译了。。。能否编译一个全平台的让用户自己选择？

**Comment by liangxiwei** [comment]
ps:如果项目里面有armeabi-v7a目录，是会不到so的。

**Comment by netgb** [comment]
couldn't find "libmarsxlog.so"

**Comment by liangxiwei** [comment]
I compile myself
