### ISSUE TITLE
Android 端首次登录，发现登录不成功，报错如下，请问怎么解决

### ISSUE THREAD

**Issue by liuyongyi0110** [Tencent/mars#603]
Android 端首次登录，发现登录不成功，报错如下，请问怎么解决
cmdid = BaseConstants.IM_CMD_LOGIN), errCode=-10087,errType=4,code=0

**Comment by zzyycobra1234** [comment]
兄弟你的编译环境是多少我是Android studio   com.android.tools.build:gradle:3.4.0 都不能运行起来啊，你是怎么做的？

**Comment by zzyycobra1234** [comment]
我把as 退到2.3.3就可以编译了

**Comment by liuyongyi0110** [comment]
是protof的版本不一样

**Comment by zzyycobra1234** [comment]
你那个问题我之前在没有换As版本的时候也遇到了，对protof不熟，就放弃啊

**Comment by garryyan** [comment]
@liuyongyi0110 -10087是连不上服务器的错误，看你的服务器是否正常

**Comment by liuyongyi0110** [comment]
已经找到了原因，是因为长链接没有建立成功
