### ISSUE TITLE
mars xlog undefined symbols for architecture i386

### ISSUE THREAD

**Issue by liuliangju** [Tencent/mars#605]
编译出来的framework不包含i386 架构

环境 xcode 10.2.1 

lipo -info mars.framework/mars
Architectures in the fat file: mars.framework/mars are: armv7 x86_64 arm64

**Comment by dustturtle** [comment]
@liuliangju 你好，这个问题是如何解决的？

**Comment by liuliangju** [comment]
@dustturtle  我找了一个老版本，将老版本的framework与新版本的framework合成了

**Comment by BoySimonHu** [comment]
您好，请问用的老版本具体是哪个版本？

**Comment by liuliangju** [comment]
@BoySimonHu 你可以在你的项目  Valid Architectures 不选择i386这种架构试试，毕竟 i386架构很老了（iphone5,iphone5s以下的模拟器）。

**Comment by mqlsq** [comment]
> @BoySimonHu 你可以在你的项目 Valid Architectures 不选择i386这种架构试试，毕竟 i386架构很老了（iphone5,iphone5s以下的模拟器）。

但是在用cocoapods做私有库的时候,验证是默认还包含i386的

**Comment by NicolasKim** [comment]
@mqlsq 
可以把 build_ios.py 中IOS_BUILD_SIMULATOR_CMD 和 IOS_BUILD_SIMULATOR_CMD 中的  -DIOS_ARCH="x86_64" 去掉
OPEN_SSL_ARCHS = ['x86_64','i386','armv7','armv7s','arm64']
就可以吧所有架构都打出来了

**Comment by BoySimonHu** [comment]
> > @BoySimonHu 你可以在你的项目 Valid Architectures 不选择i386这种架构试试，毕竟 i386架构很老了（iphone5,iphone5s以下的模拟器）。
> 
> 但是在用cocoapods做私有库的时候,验证是默认还包含i386的

我是自己重新打了一个i386的包。。
