### ISSUE TITLE
task socket close sock:17, user disconnect:10007,    在收到消息后会断开连接？

### ISSUE THREAD

**Issue by justyour** [Tencent/mars#608]
<img width="1007" alt="图片" src="https://user-images.githubusercontent.com/9986693/57456235-98c62600-729f-11e9-9667-7abc8041f4b5.png">

**Comment by garryyan** [comment]
客户端主动断开连接的，结合日志的上下文看为什么会断开连接

**Comment by justyour** [comment]
看了上下文，发现是一个服务器回应的一个消息出错，所以就出现这个问题

**Comment by garryyan** [comment]
那解决掉服务器回应错误消息的问题应该就 fix 你提的这个 issue 了

**Comment by justyour** [comment]
是的
