### ISSUE TITLE
编译出来的xlog大小是直接引用的2倍？

### ISSUE THREAD

**Issue by liangxiwei** [Tencent/mars#610]
我直接编译出来大小是90多k，直接引用的话是50多k，请问你们编译发布的时候还有做额外的操作吗？

**Comment by liangxiwei** [comment]
如果不主动调用close的话是没法得到xlog的，都在缓存里面，这意味着不能全局监听打log，只能用到的时候打开一下，不用的时候就要关掉？

**Comment by garryyan** [comment]
> 我直接编译出来大小是90多k，直接引用的话是50多k，请问你们编译发布的时候还有做额外的操作吗？


libmarsxlog.so 的正常大小是 90 多 k， 如果你引用的 50 多 k，是有问题的。看是否压缩后的大小？





> 如果不主动调用close的话是没法得到xlog的，都在缓存里面，这意味着不能全局监听打log，只能用到的时候打开一下，不用的时候就要关掉？

为了性能不得不放到缓存中的。 在缓存中超过 50kb 或者间隔 15min 会刷到文件中。 xlog 不提供全局监听打 log 的功能
