### ISSUE TITLE
我想问一下stn.h里面的errorType枚举有是什么意思呢？

### ISSUE THREAD

**Issue by Mingmingmew** [Tencent/mars#613]
//error type
enum ErrCmdType {
	kEctOK = 0,
	kEctFalse = 1,
	kEctDial = 2,
	kEctDns = 3,
	kEctSocket = 4,
	kEctHttp = 5,
	kEctNetMsgXP = 6,
	kEctEnDecode = 7,
	kEctServer = 8,
	kEctLocal = 9,
    kEctCanceld = 10,
};

**Comment by garryyan** [comment]
是字面的意思，如果不太理解可以在代码中搜索，看什么地方什么场景会用哪个就能理解是什么含义了
