### ISSUE TITLE
压缩失败

### ISSUE THREAD

**Issue by 13272438611** [Tencent/mars#614]
LogBuffer::Flush方法中deflateEnd会返回Z_DATA_ERROR导致解压的时候相对应的出现解压到最后出现Z_DATA_ERROR，是已知问题吗？

**Comment by garryyan** [comment]
这个暂时没遇到过。 描述下机型，什么场景下出现？是否必现？

**Comment by 13272438611** [comment]
非常感谢答复，是在自己定制修改代码的时候发现的，目前是必现的，正常写就会出现，源码这个地方并没有检查是否成功吧？

**Comment by garryyan** [comment]
> 源码这个地方并没有检查是否成功吧？

对 因为即使失败，也没有其他措施。不过你的必现就可能是你其他修改导致的

**Comment by 13272438611** [comment]
我用没有改动过的源码编的库确实不会压缩失败，非常感谢，我再检查下我的代码。
