### ISSUE TITLE
Xlog编译CMake Error

### ISSUE THREAD

**Issue by zedazheng** [Tencent/mars#616]
python gcc gdb make cmake 已安装、并检验，报以下错误：

CMake Warning at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)

CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:68 (file):
  file failed to open for reading (No such file or directory):

    F:/project/mars-master/mars/comm/C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)

CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:72 (message):
  Failed to parse Android NDK revision:
  C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties.

Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)

CMake Warning at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:243 (message):
  armeabi is deprecated and will be removed in a future NDK release.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)

CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:438 (message):
  Invalid Android platform: android-14.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by leihuxi** [comment]
Starting with r11, Android NDK has deprecated gcc and made clang/llvm the default for Android. Also, gcc will not be updated beyond 4.9.

新版本支持已经移除掉gcc支持

**Comment by zedazheng** [comment]
@leihuxi 用的r16b，那要如何操作

**Comment by leihuxi** [comment]
-DANDROID_TOOLCHAIN=gcc 把编译脚本这个参数去掉

**Comment by zedazheng** [comment]
@leihuxi 报错依旧

[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-05-16 14:47:22</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
build cmd:cmake "F:\project\mars-master\mars" -G "Unix Makefiles" -DANDROID_ABI="armeabi" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NDK=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle -DANDROID_PLATFORM=android-14 -DANDROID_STL="c++_shared" && cmake --build . --target marsxlog --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=/cygdrive/f/project/mars-master/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=/cygdrive/f/project/mars-master/mars/cmake_build/Android
CMake Warning at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:68 (file):
  file failed to open for reading (No such file or directory):

    F:/project/mars-master/mars/comm/C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:72 (message):
  Failed to parse Android NDK revision:
  C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties.

Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Warning at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:243 (message):
  armeabi is deprecated and will be removed in a future NDK release.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:438 (message):
  Invalid Android platform: android-14.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by leihuxi** [comment]
DANDROID_ABI="armeabi"  ndk 16已经废弃了吧, 编译下armeabi-v7a试下

**Comment by zedazheng** [comment]
@leihuxi 

ndk path:C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-05-16 15:23:10</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
build cmd:cmake "F:\project\mars-master\mars" -G "Unix Makefiles" -DANDROID_ABI="armeabi-v7a" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NDK=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle -DANDROID_PLATFORM=android-14 -DANDROID_STL="c++_shared" && cmake --build . --target marsxlog --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=/cygdrive/f/project/mars-master/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=/cygdrive/f/project/mars-master/mars/cmake_build/Android
CMake Warning at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:68 (file):
  file failed to open for reading (No such file or directory):

    F:/project/mars-master/mars/comm/C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:72 (message):
  Failed to parse Android NDK revision:
  C;/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/source.properties.

Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error at C:/Users/dell/AppData/Local/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake:438 (message):
  Invalid Android platform: android-14.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:98 (include)
  F:/project/mars-master/mars/comm/CMakeLists.txt:6 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

**Comment by leihuxi** [comment]
cmake "F:\project\mars-master\mars" -G "Unix Makefiles" -DANDROID_ABI="armeabi-v7a" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NDK=C:\Users\dell\AppData\Local\Android\Sdk\ndk-bundle -DANDROID_PLATFORM=android-14 -DANDROID_STL="c++_shared" && cmake --build . --target marsxlog --config Release -- -j8

这是你的编译参数, 你看看你cmake装的对吗

**Comment by zedazheng** [comment]
@leihuxi 这个cmake在as里面是可以正常编译ndk的，我晚点重装试试，对cmake版本有要求吗

**Comment by leihuxi** [comment]
我没在window装过, 我的是linux系统

**Comment by leihuxi** [comment]
你的llvm也检查下装的有没有问题

**Comment by zedazheng** [comment]
好的，windows确实比较多幺蛾子，我一会也用mac试试

**Comment by garryyan** [comment]
这里应该还是环境变量配置问题：
Windows 系统还需要安装 cygwin，并务必要安装cygwin中的 make, gcc gdb。 然后把 cygwin 的 bin 目录配置到环境变量中的 PATH 中

**Comment by wsmn123123** [comment]
请问后面如何解决的,我也遇到这样的问题.Windows 环境,cygwin已安装,并配置到了PATH中,也安装了make,gcc,gdb. 还是不能编译过

**Comment by wsmn123123** [comment]
我注意到,在读取ndk路径下的source.properties文件时,该文件的路径盘符,是个逗号. 跟这有关系吗?

**Comment by wsmn123123** [comment]
知道问题了,我在cygwin里也装了cmake,版本是3.6.x的版本,后面卸载了,在win下单独装了cmake3.14.x的版本.就没出现这个问题了

**Comment by PopFisher** [comment]
> 知道问题了,我在cygwin里也装了cmake,版本是3.6.x的版本,后面卸载了,在win下单独装了cmake3.14.x的版本.就没出现这个问题了

感谢啊，我也遇到这个问题，顺着官网搞也不对，顺着别个大牛搞的也不对，后面想着进issue里面逛逛，找到了你这个回复，然后我卸载了cygwin里面的cmake就好了
