### ISSUE TITLE
后续是否会对C++工程提供CMakeLists的支持？

### ISSUE THREAD

**Issue by xiejianhe** [Tencent/mars#62]
希望能够提供CMakeLists支持，AndroidStudio的ndk使用cmake方便很多。

**Comment by tidatida** [comment]
+1     同样的需求。 或者能更进一步， 能够在LINUX 环境下编译使用。 例如用于开发linux下的IM server and client .  or  something else.

**Comment by garryyan** [comment]
@tidatida  会考虑一下

**Comment by fireflyc** [comment]
cmake_minimum_required(VERSION 3.6)
project(mars)

set(CMAKE_CXX_STANDARD 11)
include_directories(. ./mars ./mars/stn ./mars/stn/src)
aux_source_directory(. SOURCE_FILES)
aux_source_directory(./mars/stn SOURCE_FILES)
aux_source_directory(./mars/stn/src SOURCE_FILES)

add_library(mars-stn ${SOURCE_FILES})

**Comment by obliviosn** [comment]
mars 的android  客户端我已经改为cmake支持了，同时支持最新版本的ndk和studio，便于二次开发和调试，后面有时间我整理然后发上来。
