### ISSUE TITLE
Android Sample 无法运行。

### ISSUE THREAD

**Issue by VectorWen** [Tencent/mars#625]
由于各种工具都更新了，无法运行了旧版本的的代码。

1. javanano 无法使用了，查看[protobuf](https://github.com/protocolbuffers/protobuf)仓库，没有发现相关文档，猜测已经废弃了javanano 的使用，支持包2017年前也是不更新了
2. android tools 现在无法使用2.1.3 版本了，需要升级到3.0.0+(目前最新3.4.1) 才能使用，升级后发现代码无法编译。

**Comment by byron-xie** [comment]
可以运行，多研究下，这种小问题自己就解决了

**Comment by VectorWen** [comment]
@byron-xie 主要因为版本问题，现在工具都更新了。如果能支持到新的版本工具，相信新手进来也能更快体验Sample，更快入手。

**Comment by WhiteorBlack** [comment]
这个问题有什么好的解决方法吗?

**Comment by VectorWen** [comment]
@WhiteorBlack 我到现在都还有能把Android Sample 运行起来，弄好了这里分享一下方案

**Comment by garryyan** [comment]
@VectorWen @WhiteorBlack 试一下 rb/2019-MAY 这个分支上的 sample

**Comment by VectorWen** [comment]
@garryyan nice，android sample 跑起来了，非常感谢，可以开始学习下一步了。
