### ISSUE TITLE
最新版的xlog无法在本地创建新的日志文件，只能在老的文件上写日志

### ISSUE THREAD

**Issue by jipengzheng** [Tencent/mars#628]
上周刚编译的新版本，通过对比发现，无法创建新的日志文件，但是老版本可以创建，新版本只能在已有的日志文件基础上进行写日志的操作

**Comment by garryyan** [comment]
Android平台吧？ 是否cacheDays填了非 0 的值

**Comment by jipengzheng** [comment]
是的，Android平台，这个cacheDays是新增的，我以为是文件的缓存天数，就写的7,

**Comment by garryyan** [comment]
看 wiki 中的接口详细说明。

**Comment by jipengzheng** [comment]
OK，我再试试

**Comment by jipengzheng** [comment]
已经没问题了，谢谢
