### ISSUE TITLE
Exception: Couldn't load OpenSSL lib ...

### ISSUE THREAD

**Issue by aaadaaaada** [Tencent/mars#630]
window环境下接入XLog安装接入流程把所有软件都安装好了,解密日志时一直提示:
Exception: Couldn't load OpenSSL lib ...
后面参考了这个issues(https://github.com/Tencent/mars/issues/286)解决了问题
下载libeay32.dll就好了

**Comment by agoodcoolman** [comment]
我也遇到了这个问题

**Comment by agoodcoolman** [comment]
[libeay32dll.zip](https://github.com/Tencent/mars/files/3316452/libeay32dll.zip)
把附件上传上来吧，某度搜索下载真的是坑多。
