### ISSUE TITLE
xlog异步模式open,每次打日志都会调用appender_flush，最后文件还是缺少日志

### ISSUE THREAD

**Issue by iswangl** [Tencent/mars#631]
为了保证日志是实时的，每次print完都会执行flush，为什么最后还是会少几行，不close就无法看到最后几行

**Comment by kelthuzadx** [comment]
appender_flush唤醒日志线程，好像没有显式fflush，要不你手动加个fflush试试。。。

**Comment by iswangl** [comment]
> appender_flush唤醒日志线程，好像没有显式fflush，要不你手动加个fflush试试。。。

您好~不是很明白fflush加到哪里，能否具体说明一下，感谢
我现在加到这里还是有部分日志不能实时打印到文件
if (sg_cache_logdir.empty()) {
        if (__openlogfile(sg_logdir)) {
            __writefile(_data, _len, sg_logfile);
			fflush(sg_logfile);//****************************add
            if (kAppednerAsync == sg_mode) {
                __closelogfile();
            }
        }
        return;
    }

**Comment by kelthuzadx** [comment]
要不试试这个：
```cpp
static void __async_log_thread() {
    while (true) {

        ScopedLock lock_buffer(sg_mutex_buffer_async);

        if (NULL == sg_log_buff) break;

        AutoBuffer tmp;
        sg_log_buff->Flush(tmp);
        lock_buffer.unlock();

        if (NULL != tmp.Ptr())  {
            __log2file(tmp.Ptr(), tmp.Length(), true);
            fflush(sg_logfile);
        }

        if (sg_log_close) break;

        sg_cond_buffer_async.wait(15 * 60 * 1000);
    }
}
```

**Comment by iswangl** [comment]
> 要不试试这个：
> 
> ```c++
> static void __async_log_thread() {
>     while (true) {
> 
>         ScopedLock lock_buffer(sg_mutex_buffer_async);
> 
>         if (NULL == sg_log_buff) break;
> 
>         AutoBuffer tmp;
>         sg_log_buff->Flush(tmp);
>         lock_buffer.unlock();
> 
>         if (NULL != tmp.Ptr())  {
>             __log2file(tmp.Ptr(), tmp.Length(), true);
>             fflush(sg_logfile);
>         }
> 
>         if (sg_log_close) break;
> 
>         sg_cond_buffer_async.wait(15 * 60 * 1000);
>     }
> }
> ```

您好，还是不行，我是这样测试的
 ```c++
for (int i = 0; i < 1000; i++){
     xlogger_Write(...);
     appender_flush();
}
 ```
是不是和我频繁flush有关？想要做到的是每打印一条日志就能在文件中读到
十分感谢您抽出时间解答

**Comment by iswangl** [comment]
把下面这行代码注释掉就好了，这是什么原因呢
```c++
sg_cond_buffer_async.wait(15 * 60 * 1000);
```

**Comment by kelthuzadx** [comment]
我好像之前看漏了sorry， __log2file里面针对async有closefile，相当于fflush了。

你把那个注释掉，日志线程和写日志的主线程都抢一个锁，相当于同步操作了
```cpp
// 日志线程，缓冲2本地
static void __async_log_thread() {
    while (true) {
        ScopedLock lock_buffer(sg_mutex_buffer_async);
        ...
    }
}
// 写日志的线程，数据2缓冲
static void __appender_async(const XLoggerInfo* _info, const char* _log) {
    ScopedLock lock(sg_mutex_buffer_async);
    ...
}
```
如果不注释，可能是这样：写日志线程做完之后，日志线程抢锁：
```cpp
static void __async_log_thread() {
    while (true) {

        ScopedLock lock_buffer(sg_mutex_buffer_async);

        if (NULL == sg_log_buff) break;

        AutoBuffer tmp;
        sg_log_buff->Flush(tmp);
        lock_buffer.unlock();
       //!!!!!!!!!!!!!!!!!!!!
        if (NULL != tmp.Ptr())
            __log2file(tmp.Ptr(), tmp.Length(), true);

        if (sg_log_close) break;

        sg_cond_buffer_async.wait(15 * 60 * 1000);
    }
}
```
但是在感叹号位置锁已经释放了，写日志线程又可以继续，所以可能造成日志线程还在将第一个日志从缓冲放到本地的时候写日志线程已经写了三条日志到缓冲。

我的理解是这样，不知道您觉得对不对。。。

**Comment by iswangl** [comment]
我好像明白您的意思了，线程执行顺序是不是如下导致没有实时刷新日志到文件：
写日志线程(1)
日志线程->unlock
写日志线程(2)
notifyall
日志线程->log2file
日志线程->wait(15 minutes)
这样2的内容就没有输出到本地，直到下次notifyall唤醒日志线程

我把unlock()移到log2file后面是不是就会解决了这个问题，刚测试了一下是好的
那如果注释掉wait会有什么bug吗，还是只是效率会变慢
感谢大佬答疑解惑

**Comment by kelthuzadx** [comment]
是的，就是那个意思；

bug应该是没，就是效率上很慢了（因为相当于不用buffer）

**Comment by iswangl** [comment]
谢谢大佬！！十分感谢！！（*＾-＾*）

**Comment by garryyan** [comment]
上面分析的基本就是原因。本身把数据刷到文件中是另外一个线程做的，需要竞争锁。但是如果你的日志线程是个循环，而且很大的循环，刷日志的线程可能抢不到锁的。这样就会导致日志线程把缓冲区刷满并且可能溢出丢弃。

**Comment by iswangl** [comment]
原来是这样，谢谢您的耐心解答😀

**Comment by yangjie2** [comment]
应用层什么时候调用 appender_flush() ??  我测试了下，不调用 flush 也能写进文件呀。
