### ISSUE TITLE
Windows10编译出错

### ISSUE THREAD

**Issue by r17171709** [Tencent/mars#654]
CMake Error at /usr/share/cmake-3.14.5/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file:
  D:android-ndk-r16b/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  comm/CMakeLists.txt:6 (project)

环境变量应该都没有问题，该装的都装了，新建NDK空项目也可以正常通过cmake编译

**Comment by garryyan** [comment]
toolchain 文件是通过 NDK_ROOT环境变量来找的。
看你的错误信息是 Could not find toolchain file:
D:android-ndk-r16b/build/cmake/android.toolchain.cmake

看下你配置的 NDK_ROOT是什么

**Comment by r17171709** [comment]
@garryyan 

C:\Users\Administrator>cd %NDK_ROOT%

C:\Users\Administrator>d:

D:\android-ndk-r16b>
