### ISSUE TITLE
编译iOS下使用的mars.framework，红框里的步骤是做什么用？

### ISSUE THREAD

**Issue by xttxqjfg** [Tencent/mars#658]
现在的场景是编译mars.framework用在iOS的项目中，说明步骤里面有涉及到android目录下的操作，如红框中，这个是必须步骤么？在iOSDemoXlog中直接添加编译好的mars.framework，没有做红框里面的操作通过了编译
![](http://www.xttxqjfg.cn/img/201907/17/170001.png)

**Comment by garryyan** [comment]
这个是给开发者自定义协议的。
执行 python build_ios.py只是编出来静态库，应该是链不过的。

**Comment by xttxqjfg** [comment]
> 这个是给开发者自定义协议的。
> 执行 python build_ios.py只是编出来静态库，应该是链不过的。

执行 python build_ios.py编出来的静态库，直接加到xcode工程能编译通过且运行没有问题
