### ISSUE TITLE
Error: make sure ndk's version == r16b

### ISSUE THREAD

**Issue by fanqGithub** [Tencent/mars#661]
在选择完

Enter menu:
1. Clean && build mars.
2. Build incrementally mars.
3. Clean && build xlog.
4. Exit
3   
后，出现的这个

ndk path:/Users/fq/Library/Android/sdk/ndk-bundle
Error: make sure ndk's version == r16b

应该怎么处理

**Comment by garryyan** [comment]
看错误提示信息：
make sure ndk's version == r16b， 你的 ndk 版本对吗？ 不对的话，去下载，然后配置 NDK_ROOT
