### ISSUE TITLE
windows环境下编译Mars报openssl/md5.h错

### ISSUE THREAD

**Issue by HolyCrazy** [Tencent/mars#669]
按着接入方法-本地编译一步一步走的，
环境： ndk版本 android-ndk-r16b
            cmake版本 cmake-3.15.1-win64-x64
            python版本 python27
            cygwin用的阿里的源，make 和 gdb 都下了
但是运行build_android.py脚本,编译23 ，报错
28%报了一个error
In file included from D:/LeeDuoDownload/project/mars/mars/stn/src/longlink.cc:48:
In file included from D:/LeeDuoDownload/project/mars/mars/stn/src/smart_heartbeat.h:30:
D:/LeeDuoDownload/project/mars/mars/stn/src/special_ini.h:25:10: fatal error: 'openssl/md5.h' file not found
#include "openssl/md5.h"
         ^~~~~~~~~~~~~~~
1 error generated.

但是还能继续运行

82%运行停止了
[ 82%] Linking CXX static library libmars-boost.a
In file included from D:/LeeDuoDownload/project/mars/mars/comm/jni/platform_comm.cc:33:
In file included from D:/LeeDuoDownload/project/mars/mars/comm/../..\mars/comm/coroutine/coroutine.h:18:
In file included from D:/LeeDuoDownload/project/mars/mars/comm/..\boost/coroutine/all.hpp:14:
In file included from D:/LeeDuoDownload/project/mars/mars/comm/..\boost/coroutine/protected_stack_allocator.hpp:12:
D:/LeeDuoDownload/project/mars/mars/comm/..\boost/coroutine/posix/protected_stack_allocator.hpp:71:19: warning: unused
      variable 'result' [-Wunused-variable]
        const int result( ::mprotect( limit, traits_type::page_size(), PROT_NONE) );
                  ^
[ 82%] Built target mars-boost
1 warning generated.
[ 82%] Linking CXX static library libcomm.a
[ 82%] Built target comm
make: *** [Makefile:130: all] Error 2
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

求助，有遇到相同问题的大佬吗？

**Comment by HolyCrazy** [comment]
@tencent-adm

**Comment by anenn** [comment]
用 master 分支拉下来的代码编译 Android 是有问题，后面切换成 v1.3.0 就可以
