### ISSUE TITLE
关于DNS那一块是否可以告知更多优化方案

### ISSUE THREAD

**Issue by DrSlark** [Tencent/mars#67]
对hostName进行解析的时候，会先询问上层对该HostName的想法(GetNewDNS)，上层返回空的话就会去真正的进行DNS查询，是否可以把GetNewDNS的细节更多的透露一点，比如DNS缓存的超时时间一般设置多少？

**Comment by garryyan** [comment]
newdns是我们的叫法。 外部的叫法应该是 HTTP DNS (ps：内部没叫 HTTP DNS的原因是，newdns微信大概2102年就开始做了，那个时候 HTTP DNS还没流行开，所以那个时候不知道有这个名词)。 你可以通过这关键词进行谷歌。
依赖于后台对IP质量的把控，一次下发多个域名的IP，服务器给超时时间，我们目前的超时时间是30min。网络切换时记得重新获取。

**Comment by DrSlark** [comment]
多谢回复，知道怎么做了。

**Comment by DrSlark** [comment]
再问一个问题，在代码中并没有看到包分片的逻辑，不知道微信是怎么处理大包的？

**Comment by garryyan** [comment]
mars不对数据做分片处理。所以mars适合大部分场景下是小数据的应用。建议一个请求不要超过64kb大小。如果偶尔发大数据，可以发之前自己分包。

微信的图片视频会走另一套组件：cdn。 这个暂时没开源的打算

**Comment by DrSlark** [comment]
嗯，在连接可靠的基础上做分片逻辑相对好弄，给task加上chunkid这种就可以了。
对于图片视频那种是否走的quic这种协议，后续是否有相关技术文章介绍？

**Comment by garryyan** [comment]
走的也是tcp协议。后续不确定是否会有文章介绍 应该会有

**Comment by DrSlark** [comment]
期待文章，刚看见你们推送了连接方案和连接排序算法的策略，深入浅出，很棒。
