### ISSUE TITLE
适用于electron吗? 如果是, 我该怎么做?

### ISSUE THREAD

**Issue by jackple** [Tencent/mars#670]
https://juejin.im/post/5af58b81f265da0b767d8837

我想能不能不把osx/win构建成各自平台的可调用的模块, 而是如上面链接一样, 使用node-gyp编出通用的node可调用的模块

**Comment by garryyan** [comment]
理论上可以，但是不建议，你可以尝试下。 我这边也没有什么方案，我们没有在electron尝试过

**Comment by lilong7676** [comment]
@jackple electron有没有成功？我试了下，node下可以运行，electron 不行

**Comment by jackple** [comment]
@lilong7676 我最后没用mars

**Comment by lilong7676** [comment]
想问下你们现在用的什么在electron上..

**Comment by lilong7676** [comment]
补充一下，经测试已经可以打包成node插件使用。
