### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xtxh** [Tencent/mars#673]
编译到85%的时候提示!!!!!!!!!!!build os fail!!!!!!!!!!!!!!!

[ 84%] Building CXX object comm/CMakeFiles/comm.dir/objc/xlogger_threadinfo.mm.o
[ 85%] Building C object comm/CMakeFiles/comm.dir/debugger/debugger_utils.c.o
/Users/keping/Downloads/mars-master/mars/comm/messagequeue/message_queue.cc:728:33: warning: 
      format specifies type 'unsigned long long' but the argument has type
      'intmax_t' (aka 'long') [-Wformat]
              _content.timeout, _content.tid, clock_app_monotonic() - _c...
                                ^~~~~~~~~~~~
1 warning generated.
[ 85%] Linking CXX static library libcomm.a
[ 85%] Built target comm
make: *** [all] Error 2
!!!!!!!!!!!build os fail!!!!!!!!!!!!!!!

**Comment by cuiyu8580** [comment]
me too!

**Comment by garryyan** [comment]
编译的是什么平台？
这个是警告信息不会导致编译失败的，你往上找找贴下错误信息。

**Comment by cuiyu8580** [comment]
[ 32%] Building CXX object stn/CMakeFiles/stn.dir/src/longlink_connect_monitor.cc.o
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/longlink.cc:48:
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/smart_heartbeat.h:30:
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/special_ini.h:27:
/Users/eli/Downloads/mars-master/mars/stn/../../mars/openssl/include/openssl/md5.h:13:11: fatal error: 'openssl/opensslconf.h' file
      not found
# include <openssl/opensslconf.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [stn/CMakeFiles/stn.dir/src/longlink.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 33%] Building CXX object sdt/CMakeFiles/sdt.dir/src/activecheck/pingchecker.cc.o
[ 34%] Linking CXX static library libxlog.a
[ 34%] Built target xlog


MacOS Mojave

**Comment by garryyan** [comment]
是最新代码吗？ 最新代码 master 应该已经 fix 了

**Comment by cuiyu8580** [comment]
ElideMacBook-Pro:mars eli$ ls
CMakeLists.txt			build_watch.py			gradlew				mars_utils.pyc
app				build_windows.py		gradlew.bat			openssl
baseevent			cmake_build			ios.toolchain.cmake		sdt
boost				comm				libraries			settings.gradle
build.gradle			cppcheck_project_scan.bat	lint				stn
build_android.py		cpplint_project_scan.bat	log				uwpproj
build_ios.py			gradle				mars-log-mac.xcodeproj
build_osx.py			gradle.properties		mars_utils.py
ElideMacBook-Pro:mars eli$ cd openssl
ElideMacBook-Pro:openssl eli$ ls
UWP			include			openssl_lib_android	openssl_lib_osx		openssl_lib_windows
export_include		objc			openssl_lib_iOS		openssl_lib_watch	uwpproj
ElideMacBook-Pro:openssl eli$ cd include/
ElideMacBook-Pro:include eli$ ls
internal	openssl
ElideMacBook-Pro:include eli$ cd openssl/
ElideMacBook-Pro:openssl eli$ ls
__DECC_INCLUDE_EPILOGUE.H	cryptoerr.h			md5.h				rsaerr.h
__DECC_INCLUDE_PROLOGUE.H	ct.h				mdc2.h				safestack.h
aes.h				cterr.h				modes.h				seed.h
asn1.h				des.h				obj_mac.h			sha.h
asn1_mac.h			dh.h				objects.h			srp.h
asn1err.h			dherr.h				objectserr.h			srtp.h
asn1t.h				dsa.h				ocsp.h				ssl.h
async.h				dsaerr.h			ocsperr.h			ssl2.h
asyncerr.h			dtls1.h				opensslconf.h			ssl3.h
bio.h				e_os2.h				opensslconf.h.in		sslerr.h
bioerr.h			ebcdic.h			opensslv.h			stack.h
blowfish.h			ec.h				ossl_typ.h			store.h
bn.h				ecdh.h				pem.h				storeerr.h
bnerr.h				ecdsa.h				pem2.h				symhacks.h
buffer.h			ecerr.h				pemerr.h			tls1.h
buffererr.h			engine.h			pkcs12.h			ts.h
camellia.h			engineerr.h			pkcs12err.h			tserr.h
cast.h				err.h				pkcs7.h				txt_db.h
cmac.h				evp.h				pkcs7err.h			ui.h
cms.h				evperr.h			rand.h				uierr.h
cmserr.h			hmac.h				rand_drbg.h			whrlpool.h
comp.h				idea.h				randerr.h			x509.h
comperr.h			kdf.h				rc2.h				x509_vfy.h
conf.h				kdferr.h			rc4.h				x509err.h
conf_api.h			lhash.h				rc5.h				x509v3.h
conferr.h			md2.h				ripemd.h			x509v3err.h
crypto.h			md4.h				rsa.h
ElideMacBook-Pro:openssl eli$

**Comment by cuiyu8580** [comment]
是今天早些时候的，我再下载一份新的试试看

**Comment by cuiyu8580** [comment]
@garryyan 还是这样的问题
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/longlink.cc:48:
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/smart_heartbeat.h:30:
In file included from /Users/eli/Downloads/mars-master/mars/stn/src/special_ini.h:27:
/Users/eli/Downloads/mars-master/mars/stn/../../mars/openssl/include/openssl/md5.h:13:11: fatal error: 
      'openssl/opensslconf.h' file not found
# include <openssl/opensslconf.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [stn/CMakeFiles/stn.dir/src/longlink.cc.o] Error 1
make[1]: *** [stn/CMakeFiles/stn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 31%] Building CXX object boost/CMakeFiles/mars-boost.dir/libs/filesystem/src/unique_path.cpp.o
[ 32%] Building CXX object comm/CMakeFiles/comm.dir/memdbg.cc.o
[ 33%] Building CXX object sdt/CMakeFiles/sdt.dir/src/activecheck/pingchecker.cc.o
[ 34%] Linking CXX static library libxlog.a

**Comment by garryyan** [comment]
找到原因了，稍等下
