### ISSUE TITLE
xlog的文件只会在调用close方法后生成吗

### ISSUE THREAD

**Issue by WuKongCoo1** [Tencent/mars#674]
我想获取程序异常退出时的日志文件，有什么办法吗？目前能想到的就是在程序异常退出时，调用close，然后存储path

**Comment by garryyan** [comment]
现在写文件的逻辑：
1. 调用 close或者 flush
2. 缓存区满 50kb 或者间隔 15min
3. 下次启动的时候，把上次还没有写入文件的日志写入文件

**Comment by WuKongCoo1** [comment]
了解了，thks
