### ISSUE TITLE
能否提供xlog Android arm64-v8a so库？

### ISSUE THREAD

**Issue by hufeiya** [Tencent/mars#677]
因为谷歌Play商店现在必须要求应用支持64位，自己电脑刚换了Windows编译起来很麻烦。非常感谢。

**Comment by hufeiya** [comment]
搞了大半天，所有的编译条件都满足了，但是报错

Administrator@和微-20190718FKIF ~/mars/mars-master/mars
$ python build_android.py
Enter menu:
1. Clean && build mars.
2. Build incrementally mars.
3. Clean && build xlog.
4. Exit
3
ndk path:../../../android-ndk-r16b
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[[==BUILD_DESCRIPTION==]]Revision:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left"></td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-08-12 16:14:31</td></tr><tr><td align="left">Revision</td><td align="left"></td></tr></table></div>
build cmd:cmake "/home/Administrator/mars/mars-master/mars"  -DANDROID_ABI="arm64-v8a" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../../android-ndk-r16b/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=../../../android-ndk-r16b -DANDROID_PLATFORM=android-14 -DANDROID_STL="c++_shared" && cmake --build . --target marsxlog --config Release -- -j8
-- CMAKE_INSTALL_PREFIX=/home/Administrator/mars/mars-master/mars/cmake_build/Android
-- CMAKE_INSTALL_PREFIX=/home/Administrator/mars/mars-master/mars/cmake_build/Android
CMake Error at /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:104 (message):
  Could not find toolchain file:
  ../../../android-ndk-r16b/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  comm/CMakeLists.txt:6 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
!!!!!!!!!!!!!!!!!!build fail!!!!!!!!!!!!!!!!!!!!

看到其它两个issue也有此问题，但未解决。NDK_ROOT的配置是对的，换了好几个地方了，echo也打印出来。如果NDK_ROOT路径配错的话会报错：
Error: source.properties does not exist, make sure ndk's version==r16b
所以不是NDK_ROOT路径问题。

**Comment by hufeiya** [comment]
Windows编译无解，换了个Mac才编译成功的

**Comment by garryyan** [comment]
windows 编译失败，是因为你的 cygwin 配置不对。看 wiki 上的编译说明

**Comment by wanqing-123** [comment]
为什么不直接提供呢

**Comment by garryyan** [comment]
1.2.3 已经提供了
