### ISSUE TITLE
iOS平台下的性能优化

### ISSUE THREAD

**Issue by dustturtle** [Tencent/mars#681]
打开appender_set_console_log(true)，往控制台输出NSLog的时候会在当前线程输出（很可能是主线程），这种情况下大量日志打印会导致页面卡顿。 
建议把NSLog的打印也放到线程中执行（我看文件写入就在专门的线程）。

**Comment by JMStack** [comment]
调试时 log 放在当前线程打印的目的是为了保持日志输出时机的执行时机一致，否则就会出现日志代码执行了控制台还没有输出的情况，这对调试来讲是不合理的。

**Comment by dustturtle** [comment]
你说的也有一定的道理。但不是说打开set_console_log(true)就是在debug，一般开发中的run也是这样。 cocoalumberjack是在日志线程处理的

**Comment by dustturtle** [comment]
而且logging和debugging是不同的定位分析问题的手段，看日志的时候大部分情况只要关注日志本身的时序和时间戳
