### ISSUE TITLE
、 

### ISSUE THREAD

**Issue by Dincoln** [Tencent/mars#687]
时间不定，可能连续发生好几次，有时比较长时间才会发生

**Comment by dulcan1988** [comment]
你好，怎么解决的？

**Comment by Dincoln** [comment]
> 你好，怎么解决的？
我发现断开链接是框架主动发起的，暂时的解决方法是修改longlink_task_manager.cc文件里的 __BatchErrorRespHandle函数，不让它主动断开连接。

**Comment by dulcan1988** [comment]
> > 你好，怎么解决的？
> > 我发现断开链接是框架主动发起的，暂时的解决方法是修改longlink_task_manager.cc文件里的 __BatchErrorRespHandle函数，不让它主动断开连接。

好的~谢谢~。我也碰到一样的问题，安卓和ios都会频繁重连。改后代码能分享下嘛，不太懂CPP -。-

**Comment by dulcan1988** [comment]
> > > > 你好，怎么解决的？
> > > > 我发现断开链接是框架主动发起的，暂时的解决方法是修改longlink_task_manager.cc文件里的 __BatchErrorRespHandle函数，不让它主动断开连接。
> > 
> > 
> > 好的~谢谢~。我也碰到一样的问题，安卓和ios都会频繁重连。改后代码能分享下嘛，不太懂CPP -。-
> 
> [longlink_task_manager.txt](https://github.com/Tencent/mars/files/3766610/longlink_task_manager.txt)
非常感谢

**Comment by Dincoln** [comment]
1
