### ISSUE TITLE
bitcode打开问题

### ISSUE THREAD

**Issue by csl56** [Tencent/mars#689]
Hi,编译framework已经打开bitcode 用的时候报下面错误
mars.framework/mars(md5_one.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by justForL** [comment]
@csl56 兄弟，这个报错你还有印象是怎么解决掉的么？我现在报了同样的问题
