### ISSUE TITLE
只是用xlog，对依赖的标准库能减小吗

### ISSUE THREAD

**Issue by haizhiyun** [Tencent/mars#692]
旧版的stl库和新版依赖的标准库都很大，如果只使用xlog 的话，能否缩小，只编译依赖的文件？

**Comment by haizhiyun** [comment]
@garryyan 使用静态链接打的库，c++_shared 应该是打入了marsxlog.so
感觉增加的量并不是很大（总219k），比动态引入如libc++_shared.so 要小很多，请问能不能用这种静态方式打？ 需要修改哪些地方 ，谢谢！

**Comment by haizhiyun** [comment]
通过静态链接标准库编译的结果确实小了不少（235k），去掉了c++_shared.so(667k) 
直接修改了build_android.py 和 build_android.sh 中的 c++_shared 为 c++_static,但是编译生成的结果还是有 c++_shared.so,不知道要去掉哪里

**Comment by garryyan** [comment]
如果你修改了c++_static，编译的结果有 c++_shared.so, 不要用就行

**Comment by lihb** [comment]
> @garryyan 使用静态链接打的库，c++_shared 应该是打入了marsxlog.so 感觉增加的量并不是很大（总219k），比动态引入如libc++_shared.so 要小很多，请问能不能用这种静态方式打？ 需要修改哪些地方 ，谢谢！

我把c++_shared 改成 c++_static打出来的so，loadlibrary的只loadmarsxlog.so ，但是运行起来会crash。请问你那是ok的么？
