### ISSUE TITLE
java.lang.UnsatisfiedLinkError Native method not found: com.tencent.mars.xlog.Xlog.initLogConfig

### ISSUE THREAD

**Issue by amin358** [Tencent/mars#696]
java.lang.UnsatisfiedLinkError  Native method not found: com.tencent.mars.xlog.Xlog.initLogConfig:(II)V

**Comment by amin358** [comment]
com.tencent.mars.xlog.Xlog.initLogConfig(Native Method)
安卓4.4 4.3 4.2 会偶现

**Comment by garryyan** [comment]
xlog 中没有提供过这个接口
