### ISSUE TITLE
xlog支持Linux系统吗？

### ISSUE THREAD

**Issue by qingguoguo** [Tencent/mars#717]
如题

**Comment by garryyan** [comment]
支持的。不过目前没提供编译脚本

**Comment by qingguoguo** [comment]
那能否提供一下编译脚本？

**Comment by Piasy** [comment]
然鹅并不能编译。

不过修改 CMakeLists.txt，把 `mars/comm/jni/xlogger_threadinfo.cc` 和 `mars/log/jni/ConsoleLog.cc` 编进去，并且对这俩文件的代码稍作修改，去掉对 Android 平台函数的引用，就可以了。
