### ISSUE TITLE
setMaxAliveTime() not working

### ISSUE THREAD

**Issue by zyhedwards** [Tencent/mars#731]
`Xlog.setMaxAliveTime(7 * 24 * 60 * 60)`
`Xlog.appenderOpen(Xlog.LEVEL_INFO, Xlog.AppednerModeAsync, cachePath, logPath, namePrefix, 0, "")`
`Xlog.setMaxFileSize(1 * 1024 * 1024)`
`Xlog.setConsoleLogOpen(false)`

我的设置代码是这样的，通过 setMaxAliveTime(7 * 24 * 60 * 60) 设置了最长7天，但发现没有起作用，存在的日志还是超过7天。

**Comment by Smart-shine** [comment]
我也遇到了同样的问题，不知道是不是哪里设置的不对

**Comment by garryyan** [comment]
会每次重启30s 之后进行删除文件。  没有生效，本地日志存了几天？

**Comment by Smart-shine** [comment]
我这边边本地存了30天+,感觉是没有启动过删除，设置的是最大存10天

**Comment by zyhedwards** [comment]
目前发现最多存了103天

**Comment by garryyan** [comment]
是最新代码吗？ 之前的代码有过一次 bug，修复过一次 0c120a5d

**Comment by zyhedwards** [comment]
的确是旧代码，我更新一下

**Comment by Smart-shine** [comment]
改用了最新的xlog1.2.3版本，修复了这个问题。感谢！

**Comment by htyxz8802** [comment]
xlog 1.3.0 的版本 依旧有这个问题，请问解决了吗？，我使用的是打包的里面的1.3.0的代码
