### ISSUE TITLE
Android_xlog编译，找不到x86_64的so库

### ISSUE THREAD

**Issue by yxhh** [Tencent/mars#732]
Android xlog 本地编译后，在x86_64目录下没有libmarsxlog.so的库；
偶尔情况会出现arm架构的so库。
已经添加了x86_64 的相关配置，代码===> archs = set(['x86_64','x86','arm64-v8a','armeabi-v7a'])
这种情况是什么原因？怎么解决呢？谢谢！！！
编译环境：ndk-r16b  python-2.7  Mac OS

**Comment by garryyan** [comment]
默认本来就只编 armeabi-v7a的库，如需其他架构的，根据自己的需求自行修改

**Comment by yxhh** [comment]
> _No description provided._



> 默认本来就只编 armeabi-v7a的库，如需其他架构的，根据自己的需求自行修改

已经添加了x86_64 的相关配置，代码===>  archs = set(['x86_64','x86','arm64-v8a','armeabi-v7a'])

**Comment by garryyan** [comment]
我试了下，没什么问题，输出文件在 libraries/mars_xlog_sdk/libs 目录下

**Comment by yxhh** [comment]
> 我试了下，没什么问题，输出文件在 libraries/mars_xlog_sdk/libs 目录下

**Comment by yxhh** [comment]
> 我试了下，没什么问题，输出文件在 libraries/mars_xlog_sdk/libs 目录下
能简单介绍下配置过程以及注意事项么？

**Comment by garryyan** [comment]
和你一样的改了下archs = set(['x86_64','x86','arm64-v8a','armeabi-v7a']) 直接编就行

**Comment by yxhh** [comment]
> 和你一样的改了下archs = set(['x86_64','x86','arm64-v8a','armeabi-v7a']) 直接编就行

生成不同架构的so之后，你可以在终端使用file命令查看下，不cpu架构下的so库的真实类型，只有x86_64目录下的libmarsxlog.so的cpu架构对不上，其他的都没问题。

**Comment by yxhh** [comment]
问题已经解决，但是具体原因不知道为什么？
**运行环境：**
Mac Os 2015
python 系统自带2.7版本
ndk：r16b(测试中我使用r20也可以，不过还是建议使用文档中)
cmake：3.1

还是这行代码的问题（问题代码）
`archs = set(['x86_64','x86','arm64-v8a','armeabi-v7a','armeabi'])`
只有把『x86_64』放到最后一位，并且里面不能包含『armeabi』和『armeabi-v7a』这两种架构。
例如，（我测试的正确代码）
`archs = set(['x86','arm64-v8a','x86_64'])`
我测试过程中发现，如果包含『armeabi』和『armeabi-v7a』这两种架构，似乎在生的x86_64对应架构的文件夹下的so库会被arm的so库替换（猜测）。可以使用file命令查看so库的架构类型。

以上只是基于我的数据猜测的结论，我没有仔细深入代码研究。如果有人发现真整问题了，如果有时间的话，可以联系我17732836509

**Comment by weirenren** [comment]
借楼问一下：脚本也能顺带build 出带符号的动态库so 么？
