### ISSUE TITLE
bitcode问题

### ISSUE THREAD

**Issue by WeMadeCode** [Tencent/mars#743]
/Users/xxx/Desktop/TestiOS/mars.framework/mars(ThreadOperationQueue.mm.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/xxx/Desktop/TestiOS/mars.framework/mars' for architecture arm64

**Comment by garryyan** [comment]
默认是关闭 bitcode 的，如需打开请自行build_ios.py/build_osx.py 中的 IOS_BUILD_SIMULATOR_CMD和IOS_BUILD_OS_CMD 中的-DENABLE_BITCODE=1
