### ISSUE TITLE
关于关闭长连接

### ISSUE THREAD

**Issue by jacket-code** [Tencent/mars#78]
如果我想关闭连接，我调用cleartask，发现后面又主动连接上了，能不能主动关闭的连接不再连接？
有一个场景：当前我连接到a服务器，然后我想连接到b服务器，是先断开a的连接，再连接b服务器吧？

**Comment by QGB** [comment]
免运费

**Comment by garryyan** [comment]
cleartasks
reset
setlonglinksvraddr
onforeground
makesureconnected

**Comment by gmtalang** [comment]
@jacket-code  你好，你知道Simplechat 案例中,tcp长连接如何设置吗？ 我看到wiki里面只有短连接
