### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: method:startAlarm, sig:(III)Z

### ISSUE THREAD

**Issue by yongfengnice** [Tencent/mars#784]
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: method:startAlarm, sig:(III)Z，这是什么问题呀大佬，android手机，一启动进程就挂了，望解答一下，在线等，谢谢

**Comment by qwc774163019** [comment]
遇到相似的问题了JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: method:logWrite2, sig:(JILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)，有什么解决办法吗

**Comment by yongfengnice** [comment]
java层logWrite2, sig签名不同，需要自己改一下，其他的类似

**Comment by qwc774163019** [comment]
可以解释下什么意思吗，没遇见过这种问题，多谢

**Comment by qwc774163019** [comment]
多谢帮助，找了一些资料了解了这方面

**Comment by 9alsacelost** [comment]
> 多谢帮助，找了一些资料了解了这方面

大佬，请问怎么解决的，我也遇到了这样的问题
