### ISSUE TITLE
How Xlog control file size？

### ISSUE THREAD

**Issue by FelixZhang00** [Tencent/mars#80]
I haven't find any api to control log file size, otherwise the log file will going huge.
How can I adjust the strategy of log file , like Rotating it or rewriting with multi-files？
Does any api exists？
What is the strategy of log file now for Xlog?

**Comment by garryyan** [comment]
[Mars 常见问题](https://github.com/Tencent/mars/wiki/Mars-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
