### ISSUE TITLE
关于ssl支持

### ISSUE THREAD

**Issue by Billchen28** [Tencent/mars#81]
试用了一些，十分强大，很有价值。
看到工程引入了openssl，但似乎目前还没看到关于ssl的支持文档。
请问是否有打算开放ssl支持？还是只能在上层自己做对称加密？

**Comment by garryyan** [comment]
暂时未有打算。
我们期望你在req2buf打包过程中保证安全性。

**Comment by Billchen28** [comment]
好，了解。只是如果都在req2buf这层加解密，那么就需要每个平台都做一套。看来安全方案在框架层并没有很好的支持。如果在c++框架层增加一套支持会更加完美。
