### ISSUE TITLE
网络关闭的时候没有回调reportConnectInfo

### ISSUE THREAD

**Issue by Nextweekends** [Tencent/mars#815]
task error, taskid:0, cmdid:0, error_type:4, error_code:103

**Comment by medusar** [comment]
看源码应该是这样的，disconnect的时候直接return了，没有回调。楼主跟我理解的一致嘛？代码在[这里](https://github.com/Tencent/mars/blob/78d0a0abc77884cd86934f0dffeb26785ca664ed/mars/stn/src/net_core.cc#L671)
