### ISSUE TITLE
master分支 jni代码和Android代码native方法参数对不上是为什么？有哪个分支的是能对上的吗？

### ISSUE THREAD

**Issue by SuperXmx** [Tencent/mars#817]
![image](https://user-images.githubusercontent.com/24268288/87905679-ba21c500-ca93-11ea-9f3a-39981737190b.png)
![image](https://user-images.githubusercontent.com/24268288/87905789-f3f2cb80-ca93-11ea-8f15-938c13c9485c.png)

**Comment by SuperXmx** [comment]
@garryyan

**Comment by flx413** [comment]
我也发现这个问题了。我后来用的 tag1.3.0这个版本是正常的

**Comment by SuperXmx** [comment]
嗯，使用v1.3.0是正常的
