### ISSUE TITLE
发送消息报错

### ISSUE THREAD

**Issue by LawrenceHan** [Tencent/mars#82]
**出现的问题：**
发送消息时没有response直接进这个回调了
**stn_callback.mm Line: 87**
`int  StnCallBack::OnTaskEnd(int32_t _taskid, void* const _user_context, int _error_type, int _error_code)`

**报错信息是**
`error code: 0`, `errtype: 4`

前两天还是好的。

**我的配置:**
自己新建了个项目，打包mars.framework进来。只有发消息这个有问题，`ping`和`getconvlist`都还是正常的。

**我是用你们提供的proto文件，配合官方的protobuf生成的message proto类**
[项目地址](https://github.com/LawrenceHan/LHWInstantMessage/blob/master/LHWInstantMessage/LHWInstantMessage/LHWChatViewController.m)

**Comment by shockcao** [comment]
由于server是我们在腾讯云上部署的demo，所以并不是稳定的server
刚才由于server连接消耗的问题 导致server卡住 已经恢复 请重新尝试

**Comment by LawrenceHan** [comment]
感谢！
