### ISSUE TITLE
xlog清理机制

### ISSUE THREAD

**Issue by 2193531059** [Tencent/mars#826]
1.文档有说是启动清理，请问是调用appenderOpen后才清理的吗？
2.清理是清理多大空间？全部清理还是部分清理？

**Comment by GkvJwa** [comment]
1.你可以查看有关代码
使用cache的情况:
    if (!_config.cachedir_.empty()) {
        sg_cache_logdir = _config.cachedir_;
        boost::filesystem::create_directories(_config.cachedir_);

        Thread(boost::bind(&__del_timeout_file, _config.cachedir_)).start_after(2 * 60 * 1000);
        // "_nameprefix" must explicitly convert to "std::string", or when the thread is ready to run, "_nameprefix" has been released.
        Thread(boost::bind(&__move_old_files, _config.cachedir_, _config.logdir_, std::string(_config.nameprefix_))).start_after(3 * 60 * 1000);
    }
常规:
    Thread(boost::bind(&__del_timeout_file, _config.logdir_.c_str())).start_after(2 * 60 * 1000);
有关时间可以参考
1 * 60 * 1000; // 1min

2.del的单位为文件，清理可查看
boost::filesystem::
有关函数，如boost::filesystem::remove // 删除文件

**Comment by 2193531059** [comment]
就是appenderOpen后，如果使用了cache，则会3min后去清理，常规2min后清理。然后清理的是超过10天的日志文件。

**Comment by GkvJwa** [comment]
> 就是appenderOpen后，如果使用了cache，则会3min后去清理，常规2min后清理。然后清理的是超过10天的日志文件。
差不多 默认是10天
static const long kMaxLogAliveTime = 10 * 24 * 60 * 60;    // 10 days in second
static const long kMinLogAliveTime = 24 * 60 * 60;    // 1 days in second
static long sg_max_alive_time = kMaxLogAliveTime;
if (now_time > file_modify_time && now_time - file_modify_time > sg_max_alive_time) // using
另cache有两个 -->  
1.__del_timeout_file // 2min 
2.__move_old_files // 3min

**Comment by weirenren** [comment]
设置了一天，为啥cache选没有清理文件，奇怪

**Comment by zhx00100** [comment]
可以按缓存目录的大小配置清理规则吗，比如xlog目录超过200MB则清理超出的日志
