### ISSUE TITLE
我创建了个基于mars的demo/ I created a demo based on mars

### ISSUE THREAD

**Issue by LawrenceHan** [Tencent/mars#84]
<img width="320" alt="mars" src="https://cloud.githubusercontent.com/assets/7960810/21770466/60341a2e-d6be-11e6-9a7c-e56a516dee6a.png">

我创建了个基于mars的demo,可以简单的聊天了。方便大家测试。
第一个界面是ping，第二个界面是聊天频道选择，和mars demo是一致的。
每次启动app要求输入nickname，请尽量不要重名哦 ^_^。(马化腾什么的也不要起哦)

https://github.com/LawrenceHan/LHWInstantMessage

**Comment by shockcao** [comment]
可以将你的demo合并到我们mars/samples/iOSDemo中
然后提交PR给我们  合入我们的代码 @LawrenceHan

**Comment by LawrenceHan** [comment]
可以是可以，但是就不能使用actor model + watcher了，只能先使用demo里的delegate了。我要想想。
