### ISSUE TITLE
为什么要自己实现inet_ntop接口？

### ISSUE THREAD

**Issue by imagec** [Tencent/mars#85]
unix_socket.cc中有一个inet_ntop_v4/6的api。
不过为什么不使用标准的inet_ntop接口，android和ios平台应该是都支持这个接口的啊？

**Comment by garryyan** [comment]
再往上看上面的宏， #ifdef _WIN32

**Comment by imagec** [comment]
也支持win平台？

**Comment by garryyan** [comment]
mars本身支持绝大多数平台  只是现在还有点编译问题需要修改 就没提出支持windows

**Comment by wangyoucao577** [comment]
好像是没必要实现这个接口.   
`inet_ntop`接口是跨平台的, `iOS`, `Windows`, `Linux`都可以用的, 且兼容`ipv4`, `ipv6`.

**Comment by garryyan** [comment]
@wangyoucao577 vista以下的版本不支持

**Comment by wangyoucao577** [comment]
@garryyan  了解, vista以下版本我确实没试过. Tkx.
