### ISSUE TITLE
Mars如何动态设置长链接的IP？

### ISSUE THREAD

**Issue by 2193531059** [Tencent/mars#850]
需求的场景是这样的，在长链接建立后，服务端可能会返回一个特定的ip修改数据包，会将需要重新连接的ip发送给客户端，客户端收到新的ip后，将当前的连接断开，并使用新的ip重新建立长链接，请问mars支持这样的需求场景吗？

**Comment by 2193531059** [comment]
调用Mars.onDestroy后重新初始化mars，可以实现以上场景。

**Comment by wosshzhb** [comment]
不用destroy也可以的，用RedoTasks接口就可以了。这个接口内部会断链
