### ISSUE TITLE
关于WIFI强制设置MSS为1400的问题

### ISSUE THREAD

**Issue by wangyoucao577** [Tencent/mars#87]
在`Mars`介绍的帖子([微信终端跨平台组件 Mars 系列 - 我们如约而至](https://github.com/WeMobileDev/article/blob/master/%E5%BE%AE%E4%BF%A1%E7%BB%88%E7%AB%AF%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BB%84%E4%BB%B6%20Mars%20%E7%B3%BB%E5%88%97%20-%20%E6%88%91%E4%BB%AC%E5%A6%82%E7%BA%A6%E8%80%8C%E8%87%B3.md))中, 看到这个问题, 描述如下: 

    基础组件全量上线微信后，以微信的用户量，当然也会遇到各种各样的“妖”。
    例如，写网络程序躲不开运营商。印象比较深刻的某地的用户反馈连接 WiFi 时，微信不可用，
    后来 tcpdump 发现，当包的大小超过一定大小后就发不出去。
    解决方案：在 WiFi 网络下强制把 MSS 改为1400(代码见 unix_socket.cc)。

光看这个描述有点奇怪, 解决方案也有些暴力. 
`MSS`设置为`1400`是为了让`TCP`切包都小于`1400`来发送? 所以运营商的网络限制了`MTU`在约`1440`? 而又是什么原因`TCP`的`MSS`协商没有能够生效? 为何是`WIFI`? `Celluar`没有这样的问题么? 不该是所有的`WIFI`都需要这样做吧?  

不知是否能够回顾一下当时的细节或者重现方法, 希望可以探讨一下. 谢谢!

**Comment by garryyan** [comment]
异地，当时的一次抓包还是联系的当地的同事帮忙抓的包。而且这里我们并不能说是运营商的网络限制了。中间用的设备也有很大嫌疑，如果想定位出来具体原因，就需要找运营商一起来一层层的去定位，我想你知道这个难度。目前没有发现 Celluar 有这样的问题。

当然和你说的一样，直接把所有WIFI都改了 这个解决办法过于暴力，但是要考虑下，如果不这么做，我们如何检测出来WIFI恰好有我们说的这个问题？直接暴力改了呢，WIFI本身延迟就低，把MSS改小一点，对速度影响也并不大。

如果你这边有更好的方案欢迎提出来，探讨一下。

**Comment by wangyoucao577** [comment]
这种问题定位确实很麻烦.  

1400这个值没什么问题, 毕竟有些网络的MTU连1400都没有. 这里相当于固定WIFI的最大MSS为1400, 并不太会影响效率.   

也谈不上什么更好的解决方案, 并不了解问题细节, 纯属好奇. 
谢谢!
