### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0

### ISSUE THREAD

**Issue by IdioticMadman** [Tencent/mars#878]
10-26 16:11:50.873 10319 25255 10521 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 10521 (HttpRequest-90), pid 25255 (main-PAConfig)
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : Build fingerprint: 'vivo/PD1938C/PD1938:9/PPR1.180610.011/compiler07271826:user/release-keys'
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : Revision: '0'
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : ABI: 'arm'
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : pid: 25255, tid: 10521, name: HttpRequest-90  >>> com.pingan.xjl <<<
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-26 16:11:51.040 10319 10585 10585 F DEBUG   : Cause: null pointer dereference
10-26 16:11:51.040 10319 10585 10585 F DEBUG   :     r0  00000000  r1  00000000  r2  00025800  r3  00000049
10-26 16:11:51.040 10319 10585 10585 F DEBUG   :     r4  00000000  r5  a4b19a40  r6  00025800  r7  a38ecd77
10-26 16:11:51.040 10319 10585 10585 F DEBUG   :     r8  00000000  r9  c0e23400  r10 00000000  r11 00000000
10-26 16:11:51.040 10319 10585 10585 F DEBUG   :     ip  d39baf44  sp  a38ecd48  lr  d39ad6a7  pc  d39ad6ae
10-26 16:11:51.048 10319 10585 10585 F DEBUG   : 
10-26 16:11:51.048 10319 10585 10585 F DEBUG   : backtrace:
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #00 pc 0000a6ae  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #01 pc 0000a1d7  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so (LogBuffer::__Fix()+54)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #02 pc 0000a245  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so (LogBuffer::LogBuffer(void*, unsigned int, bool, char const*)+48)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #03 pc 000090cf  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so (appender_open(TAppenderMode, char const*, char const*, char const*)+422)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #04 pc 000097bd  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so (appender_open_with_cache(TAppenderMode, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, char const*, int, char const*)+868)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #05 pc 00004c77  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/lib/arm/libmarsxlog.so (Java_com_tencent_mars_xlog_Xlog_appenderOpen+334)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #06 pc 000bed3b  /data/app/com.pingan.xjl-iQH3NGzVfrYpAw6l44HppQ==/oat/arm/base.odex (offset 0xa9000) (com.tencent.mars.xlog.Xlog.appenderOpen+218)
10-26 16:11:51.048 10319 10585 10585 F DEBUG   :     #07 pc 0009a8a9  /dev/ashmem/dalvik-jit-code-cache (deleted)

mars-log的版本是1.0.7。
请问这地方，是什么情况引发的空指针呢？

**Comment by qwc774163019** [comment]
老哥，问下解决问题了吗

**Comment by qwc774163019** [comment]
使用了1.3.0版本编译成功后，解决了问题

**Comment by IdioticMadman** [comment]
我们的项目版本比较老，都还是armeabi的，1.3.0不支持了呀，编译不出来

**Comment by qwc774163019** [comment]
我是只是用xlog，我编译了armeabi,armeabi-v7a和arm64-v8a三个平台

**Comment by IdioticMadman** [comment]
1.3.0，能编译出armeabi的log模块么？用windows编译的么？

**Comment by qwc774163019** [comment]
我用的Mac，可以编译出armeabi平台的，目前是没出差错

**Comment by IdioticMadman** [comment]
替换新版后，暂未复现

**Comment by qwc774163019** [comment]
是用的master分支的吗，我看master分支多了一些方法，可是我master分支编译不过去

**Comment by IdioticMadman** [comment]
master分支编译不出来。master分支armeabi的构建不成功，其他平台的可以构建出来
