### ISSUE TITLE
是否可以把构建和库实现剥离开

### ISSUE THREAD

**Issue by imagec** [Tencent/mars#89]
mars支持android和ios平台的构建，对android和ios的构建方式不是很清楚，但是能看出来目前的构建脚本文件都是混杂在源码中，是否能够将构建相关的文件从源码中独立出来，这样构建相关的放在一起（android和ios各一个目录），源码放在一起。
这样感觉结构会清晰些，不知道理论上是否可以实现！

**Comment by garryyan** [comment]
理论上可以，现在也是个独立目录
