### ISSUE TITLE
Mac下的mars.framework库参与项目build时出错

### ISSUE THREAD

**Issue by Sunj-Ula** [Tencent/mars#890]
我建立了一个简单项目用来测试osx平台下的xlog组件,我按照指导步骤得到mars.framework,这个库应该包含我所需要的大部分资源（头文件以及二进制文件），并将如下代码写入程序中：
<img width="762" alt="image" src="https://user-images.githubusercontent.com/40747820/100063219-d384b480-2e6b-11eb-9b23-db9b3eb740c2.png">
在build项目时，链接阶段提示符号未定义：<img width="710" alt="image" src="https://user-images.githubusercontent.com/40747820/100062122-1180d900-2e6a-11eb-93b8-0ad3a3818340.png">
如何解决这个问题？🙏

**Comment by sunuslee** [comment]
看起来是没有连接libz , 你在看关于Mac开发的工作机会吗：）可以联系我

**Comment by Sunj-Ula** [comment]
感谢回复，大概率是我本地库环境出问题了（：谢谢你的美意，当下我还是先补充完善自身技能吧

**Comment by Sunj-Ula** [comment]
补充一下：选中project -> Target -> Build Phrase -> Link Binary With Libraries ：添加“libz.tbd”
问题解决✅
