### ISSUE TITLE
iOS 调试时缺少架构，无法调试

### ISSUE THREAD

**Issue by Dugaofeng** [Tencent/mars#898]
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      LogZlibBuffer::Compress(void const*, unsigned long, void*, unsigned long) in mars(log_zlib_buffer.cc.o)
  "_deflateInit2_", referenced from:
      LogZlibBuffer::__Reset() in mars(log_zlib_buffer.cc.o)
  "_deflateEnd", referenced from:
      LogZlibBuffer::~LogZlibBuffer() in mars(log_zlib_buffer.cc.o)
      LogZlibBuffer::~LogZlibBuffer() in mars(log_zlib_buffer.cc.o)
      LogZlibBuffer::~LogZlibBuffer() in mars(log_zlib_buffer.cc.o)
      LogZlibBuffer::Flush(AutoBuffer&) in mars(log_zlib_buffer.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Dugaofeng** [comment]
已解决， 添加 libz.tbd.  （使用文档也没有提示要加，^V^）

**Comment by Dugaofeng** [comment]
11

**Comment by hnny09** [comment]
1

**Comment by ManOld** [comment]
建议加到文档中去，否则封装的组件因为这个问题跑不起来
