### ISSUE TITLE
拜读了一下XLOG

### ISSUE THREAD

**Issue by jacobjiangwei** [Tencent/mars#9]
http://mp.weixin.qq.com/s/cnhuEodJGIbdodh0IxNeXQ

C++里已经有log4cpp了，你们说的，他们都做到了，而且02年就做好了

buffer的概念很多年前就有了

还有crash是crash，与日志有何关系？抓crash是另外的topic, log啥也不需要做什么，正常open, write, close即可。crash工具该保证日志写下去，而不是日志能crash写进去。。。

感觉因果关系倒置了

丢日志。。。就更是耸人听闻。。。那还叫日志工具吗。。。

另外还用了BOOST库，唉呀妈呀，口口声声强调为了mobile,为了性能，这就把boost库引入到手机上了？

**Comment by mllyx** [comment]
2016年才写的代码和经过微信亿万用户验证冲突吗？这都算吹牛？

**Comment by qiukeren** [comment]
只能说：官方人员的态度真好。

**Comment by simpleton** [comment]
> C++里已经有log4cpp了，你们说的，他们都做到了，而且02年就做好了  

开源就是给大家一种选择，你可以用Log4cpp、Log4j，也可以用xlog，多一种选择没什么不好。

> buffer的概念很多年前就有了

函数式的概念1958就提出，到今天依然很fancy。

> 还有crash是crash，与日志有何关系？抓crash是另外的topic, log啥也不需要做什么，正常open, write, close即可。crash工具该保证日志写下去，而不是日志能crash写进去。。。

我个人理解log和crash都是我们查问题的一个渠道，我个人是专精Android的，Android中如果有native crash，在app级别是很难有机会去拿到和写当时的crash上下文的。

> 丢日志。。。就更是耸人听闻。。。那还叫日志工具吗。。。

理想是好的，现实总是残酷的，总是有各种各样的坑在等着我们。

> 另外还用了BOOST库，唉呀妈呀，口口声声强调为了mobile,为了性能，这就把boost库引入到手机上了？

用什么库我个人觉得只是最早的开发者选型的问题，每个人都有自己的技术栈和使用偏好。如果有性能和程序大小都更优，更适合移动端的库，大家可以在社区开branch去替换掉它。

开源了就是给大家一个交流的途径，总比各自闭门造车的好。因为微信里面确实是在用这些库，微信的日活大家也看到了，“微信亿万用户验证”并没有吹什么牛呀。。。

**Comment by jacobjiangwei** [comment]
既然是精简版boost 为什么不直接c++11？boost库导致库变大多少？crash工具我所知道ios的几个工具都可以抓到，与日志没关系，可以反向映射到c++。你们日志性能跟log4cpp比较过吗，性能数据看看？

**Comment by zvving** [comment]
开源喷子多，赞官方态度。

**Comment by garryyan** [comment]
不用 C++11这个就牵涉到跨平台的原因了。iOS 很早就可以使用 C++11,但是 Android ndk 迟迟没有提供 C++11的标准库，直到今年上半年才给了一个，谷歌一给出，我们就尝试使用了，但是提供的库有 Bug，所以做了回退。所以目前 Mars 是使用 C++11编译，用了 C++11的语法糖，没有使用 C++11的标准库。前面提到的Android 平台下那个库的 Bug 我们一直在关注，看到已经解决了，后面应该会再次尝试切到 C++11，但是需要时间来验证稳定性。

iOS 相对来说没有 Android 的生态恶劣，但是iOS 下也存在有些 Crash工具是捕捉不到的，甚至 Crash 捕捉工具也会 Crash，微信收到闪退但是 Crash 捕捉模块捕捉不到 Crash 的案例数不胜数。这种情况 Android 系统下会更严重。

目前没有直接和 Log4CPP 对比过性能，如果不考虑完整性的话，只考虑耗时文章中有一组数据你可以参考：单行日志的平均耗时。 和Log4CPP 的对比我们后续也会做一下给出数据。

**Comment by oncealong** [comment]
赞官方态度。都是技术人员，有问题心平气和的提出来就好。

**Comment by Mornin5** [comment]
这样的项目出来,对于业界来说无疑是百利而无一害.
不同的人群各取所需, 学习, 使用 ,亦或是优化.
赞微信团队这种态度, 中国互联网需要这样的精神.
希望以后越来越多的优秀项目开源出来.

**Comment by agoodcoolman** [comment]
经得住多大的荣耀就要经得住多大的诋毁. 
                                                                  -------------- 尼古拉斯·赵四

**Comment by XYangX** [comment]
你行你上啊！

**Comment by jinsea** [comment]
我是个菜鸟，但是楼主的问题和官方的解答，也让我加深了对xlog的理解。也会去注意这方面的东西。谢谢楼主和官方！！                                        ————还是不要在issues上说些顶撞人的话，我比较乐意看到技术上的交锋！！

**Comment by shwenzhang** [comment]
在这里我说两句吧，大家也不要去做个人攻击。

关于我们的问题，无论好的还是坏的，我们都会虚心改进，这也是我们开源的目的。我们希望微信可以跟社区共同进步，大家都可以影响到自己日常使用过程中的微信。

**Comment by anzyhui** [comment]
喷跟讲理有时只是一念之差

**Comment by hitdavid** [comment]
你们这是逼大家mute thread吗？在issues里玩这个真无聊。

**Comment by xuyisheng** [comment]
确实 做技术先做人，没人欠你什么，开源已经是为技术做贡献了，好与不好，都是交流，拒绝无脑喷

**Comment by jacobjiangwei** [comment]
说no, 并不是否定，而是获取更多信息的方式。

这位仁兄是不是自我感觉站在一个道德高地嗨起来了？

发自我的 iPhone

**Comment by yyz1542685121** [comment]
宝宝，你是想蹭热点吗？我也来蹭一个【害羞】
不管怎么样，人家团队辛辛苦苦研发的代码，贡献出来大家学习探讨~~~
脑子有洞才会有人喷吧！
如果你觉得人家写的不好，你拿出更好的方案来嘛？
一来二去说不定就真的有个完全不丢日志的工具出来啦hhh
我们的目标是----->世界充满爱⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
光说不练假把式嗷嗷嗷==
亲想上头条拿自己的实力说话啦，这种歪门邪道不可取哒~~~
(ps:微信的攻城狮大大们态度好好哦~~~路转粉ing)

**Comment by garryyan** [comment]
之前承诺的 [benchmark](https://github.com/Tencent/mars/wiki/Mars-Benchmark)

另外，我 reopen 的目的是希望大家关注到 这个benchmars， 此 issue 禁止人身攻击。

**Comment by jacobjiangwei** [comment]
谢谢。。性能看起来数据不错

文中提到了xlog是宏，log4cpp是函数，所以比较慢
我没仔细看，那你们的宏的用法是代码中必须这么写么？
    Xlog.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, "", logPath, "MarsSample");
没搜到这个函数。是有其他的简化写法吗？
ios/android以及c++代码分别的调用方式是怎样的？

另你提到是带压缩的，是不是开发人员拿到的日志默认是压缩的，是zip的吗？

编了一下BOOST版本的总共库31M per arch
有计划去boost化吗？或者说XLOG能与common组件解耦吗？

**Comment by garryyan** [comment]
log4cpp 比 xlog 慢并不是因为 xlog 使用了宏。 是因为 log4cpp 同步写了磁盘，xlog没怎么做。具体细节可以谷歌存储方面的原理分析。

Xlog.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, "", logPath,"MarsSample"); 这个只是程序启动时打开xlog的函数。 其他调用接口打日志的时候通过 xverbose  xinfo  xdebug  xwarn xerror xfatal 。当然这只是C++的接口，Objc 可以直接调用，注意传 C/C++ 的数据类型就行了。如果想直接传NSString这种，需要封装一下，demo 里有封装好的接口可以直接用或者自己封装都可以。 Android使用因为是通过JNI 调用到 C，也需要封装， demo里也有相关封装好的接口。

默认拿到的是压缩的，我们有解压的脚本也提供了，是使用的流式压缩，可以认为是zip的一种，后续可能会考虑使用 zstd替换掉，压缩率更高性能也会更高。

目前没有计划去除 boost，除非全部升到 C++11, 因为boost的跨平台封装和一些库，语法糖的封装是别的库不能比的。 全部编确实会很大，但是我们不会全部用，只使用了部分，所以并不会增大库多少。如果必要，我们尽可能不会使用boost里的功能。举个例子：一直想使用正则表达式的一些库，有其他的scanf可以替代，都没引入。

Xlog 不能和 comm 组件解耦，这里涉及到后面会尝试把STN和Xlog解耦，但是接口就需要放在comm里，实现是Xlog。 而且Xlog总需要一些基础库。  无论解耦不解耦对使用者是不可见的。

**Comment by happyjiahan** [comment]
官方的态度真好，👍

**Comment by huangchen0** [comment]
你好，我们发现一个问题，我们上传日志到FTP，发现有时候上传日志是OKB，如果本地文件存储权限没有开的话，就不会上传的，因为文件都没生成，那上传日志是0KB，是什么原因导致的呢

**Comment by kingson09** [comment]
“mmap提高性能防止丢失数据”，其实说白了就是mmap做的一个buffer，优势就是不会丢数据，性能应该还不如普通内存buffer

**Comment by wustwg** [comment]
> “mmap提高性能防止丢失数据”，其实说白了就是mmap做的一个buffer，优势就是不会丢数据，性能应该还不如普通内存buffer

确实如此，毕竟还要将数据同步到文件中，不可能比 内存还快。
