### ISSUE TITLE
setMaxAliveTime(long logInstancePtr, long aliveSeconds) not work

### ISSUE THREAD

**Issue by bawomingtian** [Tencent/mars#921]
Xlog.XLogConfig logConfig = new Xlog.XLogConfig();
        logConfig.mode = Xlog.AppednerModeAsync;
        logConfig.logdir = logPath;
        logConfig.nameprefix = NAMEPREFIX;
        logConfig.pubkey = XLOG_PUBLIC_KEY;
        logConfig.compressmode = Xlog.ZLIB_MODE;
        logConfig.compresslevel = 0;
        logConfig.cachedir = cachePath;
        logConfig.cachedays = 0;
        Xlog xlog = new Xlog();
        xlog.setMaxAliveTime(0,24*60*60);
        Log.setLogImp(xlog);

想设置xlog只保存一天的日志文件，这样设置无效，查看api，对于方法里面的第一个参数不是很理解

**Comment by bawomingtian** [comment]
找到原因了，设置setMaxAliveTime需要在Log.appenderOpen(Xlog.LEVEL_DEBUG, Xlog.AppednerModeAsync, cachePath, logPath, NAMEPREFIX, 0);后面，和先前看到的资料刚好相反

**Comment by weirenren** [comment]
我按照这个方法设置了，为啥两三天日志文件 都没有被删除；我这里是logdir 和cachePath属于同一目录

**Comment by htyxz8802** [comment]
按照这个设置了， 还是不行，依旧没有删除旧版的日志

**Comment by ManOld** [comment]
遇到了同样的问题

**Comment by Sniper001** [comment]
所以，最后都是怎么解决这个问题的呢 ，手动添加代码定期删除？

**Comment by ManOld** [comment]
> 所以，最后都是怎么解决这个问题的呢 ，手动添加代码定期删除？
添加了下面设置 maxSaveDay 为保存天数
 mars::xlog::appender_set_max_alive_duration(maxSaveDay*24*60*60);
