### ISSUE TITLE
Xlog编译Android报错make[1]: *** [CMakeFiles/marsxlog.dir/rule] Error 2

### ISSUE THREAD

**Issue by yingkong1987** [Tencent/mars#934]
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/2038099/113988215-d1068280-9881-11eb-90b4-aa3262502866.png">

NDK 版本是20.0.5594570
编译脚本未修改过

**Comment by singularmedicalQintao** [comment]
都没有人回答，官方也不管了，开源出来是kpi啊
