### ISSUE TITLE
日志如何解密

### ISSUE THREAD

**Issue by chenzhong13** [Tencent/mars#94]
我使用 gradle 添加 compile 'com.tencent.mars:mars-core:1.1.4' 依赖的方式集成 xlog，但是 xxx.xlog 文件中的内容都是乱码，请问应该如何解密呢

**Comment by agoodcoolman** [comment]
wiki里面有 

Xlog 文件怎么查看？

如果没有修改相关逻辑，使用的默认实现的话，解压脚本在log/crypt/decode_mars_log_file.py
