### ISSUE TITLE
这是一个xcode工程？ 使用ubuntu的同学用什么ide来查看工程啊。 望指教!!

### ISSUE THREAD

**Issue by masonTool** [Tencent/mars#95]

**Comment by garryyan** [comment]
目前是 ios和android项目，目前不支持linux平台

**Comment by masonTool** [comment]
支持一下吧。 哥！！！

**Comment by DrSlark** [comment]
代码都有了，自己新建个工程把代码导入也挺快，这代码比较多，我估计花个2小时也能搞定，而且本身代码是由于支持了MAC OSX的，所以是有POSIX的底子，我想移植起来也比较方便。最近把POSIX代码去支持Windows是真要命了。。
