### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by miaomiaozhou** [Tencent/mars#96]
我发现Mars中的smartHeartbeat的策略和文章（http://mp.weixin.qq.com/s?__biz=MzAwNDY1ODY2OQ==&mid=207243549&idx=1&sn=4ebe4beb8123f1b5ab58810ac8bc5994&scene=21#wechat_redirect）中的有些出入，比如文章中是5次失败在代码中没找到相关逻辑，好像只要alarmnooptimeout一响就直接跳出循环了，还有智能心跳中为什么周三要尝试下更大的，NetHeartbeatInfo中的stable的意思是如果心跳连续增加或者连续降低就是true，又突然的变化就是false吗？

**Comment by yuangu** [comment]
我也发现了，8秒后就会触发 nooping && alarmnooptimeout.Status() == Alarm::kOnAlarm 然后 关闭socket。和他的文档写的不是一回事啊？
