### ISSUE TITLE
  Undefined symbols  "mars::stn::LongLinkEncoder::SetEncoderVersion(int)"

### ISSUE THREAD

**Issue by icoder20150719** [Tencent/mars#961]
Undefined symbols for architecture x86_64:
  "mars::stn::LongLinkEncoder::SetEncoderVersion(int)", referenced from:
      mars::stn::onInitConfigBeforeOnCreate(int) in mars(stn_logic.cc.o)
      mars::stn::$_6::__invoke(int) in mars(stn_logic.cc.o)
  "mars::stn::gDefaultLongLinkEncoder", referenced from:
      mars::stn::SignallingKeeper::__SendSignallingBuffer() in mars(signalling_keeper.cc.o)
      mars::stn::LongLinkTaskManager::AddMinorLink(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in mars(longlink_task_manager.cc.o)
      mars::stn::LongLinkChannelFactory::$_2::__invoke(unsigned long long const&, mars::stn::NetSource&, mars::stn::LonglinkConfig const&) in mars(net_channel_factory.cc.o)
      mars::stn::LongLinkSpeedTestItem::LongLinkSpeedTestItem(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short) in mars(longlink_speed_test.cc.o)
      mars::stn::LongLinkSpeedTestItem::__HandleSpeedTestResp() in mars(longlink_speed_test.cc.o)
      mars::sdt::TcpChecker::__NoopReq(AutoBuffer&) in mars(tcpchecker.cc.o)
      mars::sdt::TcpChecker::__NoopResp(AutoBuffer const&, unsigned int&, unsigned int&, unsigned long&, AutoBuffer&) in mars(tcpchecker.cc.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hnny09** [comment]
解决了吗？我也遇到这样的问题

**Comment by hnny09** [comment]
怎么解决的？

**Comment by KongQingYu92** [comment]
Hi~How to solve this problem？

**Comment by blingmanaaaaa** [comment]
有解决方法吗？
