### ISSUE TITLE
Exception: Couldn't load OpenSSL lib , 升级到MACOS 11.5.1后出现

### ISSUE THREAD

**Issue by maoqis** [Tencent/mars#969]
Traceback (most recent call last):
File "/Users/maoqis/Documents/work/logs/bin/decode_mars_crypt_log_file.py", line 9, in
import pyelliptic
File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/init.py", line 43, in
File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 637, in
Exception: Couldn't load OpenSSL lib ...

MACOS 11.5.1
pyelliptic==1.5.10

![image](https://user-images.githubusercontent.com/3467849/132679726-dd53f31d-471c-4aea-b96e-997a003df57f.png)

python2 和3 都有该问题。

**Comment by zhetengxiang** [comment]
亲测可以解决问题。
mac 11.2.1 python 2.7
参考：https://github.com/Tencent/mars/issues/501解决

1、pip install https://github.com/mfranciszkiewicz/pyelliptic/archive/1.5.10.tar.gz#egg=pyelliptic
2、修改openssl.py，例如楼主位置`build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py`
```python
def find_crypto_lib():
    if sys.platform != 'win32':
       # 注释掉下面路径,写绝对路径
       # return ctypes.util.find_library('crypto')
       return '/usr/lib/libcrypto.dylib'
```
3、重新运行就不报错了


> Traceback (most recent call last): File "/Users/maoqis/Documents/work/logs/bin/decode_mars_crypt_log_file.py", line 9, in import pyelliptic File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/init.py", line 43, in File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 637, in Exception: Couldn't load OpenSSL lib ...
> 
> MACOS 11.5.1 pyelliptic==1.5.10
> 
> ![image](https://user-images.githubusercontent.com/3467849/132679726-dd53f31d-471c-4aea-b96e-997a003df57f.png)
> 
> python2 和3 都有该问题。

**Comment by maoqis** [comment]
感谢，我试下

**Comment by maoqis** [comment]
> 亲测可以解决问题。 mac 11.2.1 python 2.7 参考：[https://github.com/Tencent/mars/issues/501解决](https://github.com/Tencent/mars/issues/501%E8%A7%A3%E5%86%B3)
> 
> 1、pip install https://github.com/mfranciszkiewicz/pyelliptic/archive/1.5.10.tar.gz#egg=pyelliptic 2、修改openssl.py，例如楼主位置`build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py`
> 
> ```python
> def find_crypto_lib():
>     if sys.platform != 'win32':
>        # 注释掉下面路径,写绝对路径
>        # return ctypes.util.find_library('crypto')
>        return '/usr/lib/libcrypto.dylib'
> ```
> 
> 3、重新运行就不报错了
> 
> > Traceback (most recent call last): File "/Users/maoqis/Documents/work/logs/bin/decode_mars_crypt_log_file.py", line 9, in import pyelliptic File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/init.py", line 43, in File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 637, in Exception: Couldn't load OpenSSL lib ...
> > MACOS 11.5.1 pyelliptic==1.5.10
> > ![image](https://user-images.githubusercontent.com/3467849/132679726-dd53f31d-471c-4aea-b96e-997a003df57f.png)
> > python2 和3 都有该问题。

**Comment by maoqis** [comment]
解决了，感谢@zhetengxiang。

下载 https://github.com/mfranciszkiewicz/pyelliptic/archive/1.5.10.tar.gz#egg=pyelliptic 解压，进入目录
修改 pyelliptic-1.5.10 编译前的文件，build/lib/pyelliptic/openssl.py

修改内容 如上 zhetengxiang 提供

再安装 sudo python setup.py install

**Comment by z870248707** [comment]
补充一下，libcrypto.dylib 路径不一定是`/usr/lib/libcrypto.dylib`，可能要在OpenSSL安装目录下找找，比如`/usr/local/opt/openssl/lib/libcrypto.dylib`

**Comment by gogi2010** [comment]
> 解决了，感谢@zhetengxiang。
> 
> 下载 https://github.com/mfranciszkiewicz/pyelliptic/archive/1.5.10.tar.gz#egg=pyelliptic 解压，进入目录 修改 pyelliptic-1.5.10 编译前的文件，build/lib/pyelliptic/openssl.py
> 
> 修改内容 如上 zhetengxiang 提供
> 
> 再安装 sudo python setup.py install

1、解压pyelliptic-1.5.10后要修改的文件路径是pyelliptic/openssl.py。
2、如果之前有安装过其他pyelliptic版本需要先卸载
