### ISSUE TITLE
iOSDemoXLog build failed, caused by `mars` does not contain bitcode

### ISSUE THREAD

**Issue by wangyoucao577** [Tencent/mars#97]
Here's the screenshot with details:  
![image](https://cloud.githubusercontent.com/assets/1905370/21897176/c6503736-d923-11e6-9387-373ea0e04b07.png)

**Comment by garryyan** [comment]
暂时把项目的 bitcode关闭  后续我兼容下

**Comment by EngsShi** [comment]
+1
