### ISSUE TITLE
xlog 无法在控制台输出

### ISSUE THREAD

**Issue by zhouxu88** [Tencent/mars#970]
Log.setConsoleLogOpen(true);
调用这个了，但是没有在控制台输出

**Comment by xiaoqi010205** [comment]
> Log.setConsoleLogOpen(true); 调用这个了，但是没有在控制台输出

我也遇到这个问题了，控制台没有输出。请问您解决了吗？

**Comment by zhifeng754** [comment]
> 

我也遇到了这个问题，请问解决了吗
