### ISSUE TITLE
SmartHeartBeat的三个问题

### ISSUE THREAD

**Issue by DrSlark** [Tencent/mars#98]
1.中国移动等的NAT超时时间都在5分钟上下，貌似没有在你们SmartHeartBeat中看到对不同网络类型的策略，如果在移动网络下在把心跳放到10分钟多，失败概率会很大吧？不知道你们是怎么避免这种情况的？
2.心跳历史策略的清空时机；
3. 网络切换对心跳的影响。

**Comment by garryyan** [comment]
1. 为什么要特殊处理？ 如果正好用的中国移动 最后的心跳也会固定在4.5min或者5min就行了。一样的都是从4.5min开始试探，如果NAT超时就不会试探到10min
2. 超过一天，或者是周三
3. 不同网络下是独立的，没什么关联，所以严格说来没太大影响。

最后说一句不是针对你，这些问题的答案在代码中都能找到。  以后这些问题不再回答。

**Comment by DrSlark** [comment]
多谢

**Comment by zs-2014** [comment]
2. 超过一天，或者是周三
这个说法不对吧，在 smart_heartbeat.cc 中是 and 的关系，并非或的关系

```
if ((cur_time - current_net_heart_info_.last_modify_time_) >= ONE_DAY_SECONEDS && cur_TM.tm_wday == 2) {
                    xinfo2(TSF"__TryProbeBiggerHeart. curHeart=%0  ", current_net_heart_info_.cur_heart_);
                    current_net_heart_info_.cur_heart_ += SuccessStep;
                    current_net_heart_info_.success_curr_heart_count_ = 0;
                    current_net_heart_info_.is_stable_ = false;
                    current_net_heart_info_.fail_heart_count_ = 0;
                    __SaveINI();
                }
```

**Comment by garryyan** [comment]
@zs-2014 嗯 你说的对  已经更改。

**Comment by medusar** [comment]
@garryyan  想问下服务端如何对心跳做兼容呢？服务端对于一个连接如何长时间没有收到数据也会做idle断开处理，而智能心跳的时间间隔不固定，服务端如何处理呢？如果设置一个特别大的超时会导致非法连接长期占用可用连接，如果太短则会主动关闭连接导致客户端心跳失去意义。
