### ISSUE TITLE
同时集成mmkv和xlog时,libc++_shared.so重复

### ISSUE THREAD

**Issue by wolongalick** [Tencent/mars#981]
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/arm64-v8a/libc++_shared.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by wolongalick** [comment]
> It looks like a Android developer problem.

libc++_shared.so这个库,在mmkv和xlog的jni中都有,所以冲突了

**Comment by garryyan** [comment]
use pickFirst  or https://github.com/Tencent/MMKV/issues/362

**Comment by wolongalick** [comment]
Thank you very much.

**Comment by wolongalick** [comment]
> use pickFirst or [Tencent/MMKV#362](https://github.com/Tencent/MMKV/issues/362)

Thank you very much
