### ISSUE TITLE
集成 XLog 出错

### ISSUE THREAD

**Issue by CherryLover** [Tencent/mars#989]
编译 xlog 版本：tag v1.3.0
ndk 版本：r16b
引用的 xlog 版本：implementation 'com.tencent.mars:mars-xlog:1.2.5'

System.loadLibrary("c++_shared")
System.loadLibrary("marsxlog")

报错内容
java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.UnsatisfiedLinkError: method:appenderOpen, sig:(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V

**Comment by CherryLover** [comment]
已解决，去除 implementation 'com.tencent.mars:mars-xlog:1.2.5' 这个依赖，使用源码进行依赖。

源码来源见图
![image](https://user-images.githubusercontent.com/18376501/142196894-ea73cd04-0b53-4193-b01c-8ffd5e88bdee.png)

注意，源码复制一定要保持包名

**Comment by AttITuder** [comment]
直接依赖，无法下载依赖库是什么原因？

**Comment by CherryLover** [comment]
因为没有远程包，需要进行源码依赖，你可以看上面相关信息

**Comment by AttITuder** [comment]
好吧，我也是源码编译使用了，谢谢
