### ISSUE TITLE
is a bug in mars/mars/stn/src/dynamic_timeout::DynamicTimeout？？？？？

### ISSUE THREAD

**Issue by zs-2014** [Tencent/mars#99]
int main(int argc, char *argv[]){
        DynamicTimeout *dyn_timeout = new DynamicTimeout();

        // loop(1)
       while(dyn_timeout ->GetStatus() != kBad){
            dyn_timeout ->CgiTaskStatistic("/foo",  kDynTimeTaskFailedPkgLen, 0);
        }

       // loop(2) 能使 kBad 切换到 kEvaluating 状态
       // while(dyn_timeout ->GetStatus() == kBad){
       //      dyn_timeout ->CgiTaskStatistic("/foo", kDynTimeSmallPackageLen-1, kDynTimeSmallPackageWifiCosttime-1);
       // }

      // loop(3) 不能使 kBad 切换到 kEvaluating 状态
      // while(dyn_timeout ->GetStatus() == kBad){
      //    dyn_timeout ->CgiTaskStatistic("/foo", kDynTimeBigPackageLen-1, DynTimeBigPackageWifiCosttime-1);
      //}
    return 0;
}

loop(1) 代表着网络请求不断的失败，达到了一定数量之后， DynamicTimeout 处于 kBad 的状态，
loop(2) 表示不断的有 [small|normal] package 能够请求成功，那么一定数量的成功之后
               kBad 会切换到 kEvaluating 状态
loop(3) 表示不断有 [middle|big|bigger] package 能够快速的请求成功，然而在 5 分钟内，无论成功了
            多少次，依然不能使用 kBad 切换到 kEvaluating 或者 kExcellent 状态。
[small|normal] package 能够使 kBad 切换到 kEvaluating 而 [middle|big|bigger] package 不能够使 kBad 切换到 kEvaluating 这是一个 feature 还是 一个 bug 呢？？？

**Comment by shockcao** [comment]
case kDynTimeTaskBiggerPkgMeetExpectTag:
        {
            if (dyntime_status_ == kEValuating) {
                dyntime_latest_bigpkg_goodtime_ = gettickcount();
            }
        }
        	break;

是一个bug   这里多加了一个break，原有逻辑是向下继续执行下一个case
这里的break是误加

**Comment by zs-2014** [comment]
ok！不过这个策略要是有状态切换图或许更好理解！

**Comment by DrSlark** [comment]
![default](https://cloud.githubusercontent.com/assets/3771584/21927202/071b9476-d9c0-11e6-9a2a-b6fdce182df5.png)
我画了下大概这样

**Comment by shockcao** [comment]
@DrSlark 刚才看到有个状态切换图  可以提交PR给我们  非常感谢

**Comment by DrSlark** [comment]
我那图根据你们现有代码画的你说多了个break，有点问题，所以删了，待会改好重新传一下哈

**Comment by garryyan** [comment]
@DrSlark 从你画的这个图能看出来，你看代码很仔细。 为刚才 #98 对你说的话表示道歉，我已经修改了回答。

**Comment by DrSlark** [comment]
![default](https://cloud.githubusercontent.com/assets/3771584/21928029/7d9dfbe0-d9c3-11e6-8924-2a55a801ba3b.png)
 
很感激你的回答啊，只是代码注释太少，有时候有点懒去演绎下逻辑就问你了。
关于弱网强网时延包括策略我本来在自己项目中做了一部分，当时的想法是把分片，时延包括图片传输等策略等封装到一个FSM中的，后来你们开源了老板让去看Mars策略，于是做了下给老板看的。

**Comment by shockcao** [comment]
@DrSlark mars开源的部分目前不包含图片传输的部分   图片传输是mars的cdn组件 由于一些限制，还在内部整理中，后续有开源计划
所以mars现有开源部分是针对小数据包的传输，做了小数据包在弱网络下的优化，所以并不需要分片的逻辑
并且mars cdn的话也不是分片传输的

**Comment by DrSlark** [comment]
多谢，我们的『Mars』已经跑了好几年了，也很稳定，除了动态时延那一模块，其它基本一致，但由于人实在太少许多策略跟不上调研，所以你们的开源给我们很多启发，多谢！

**Comment by DrSlark** [comment]
@shockcao 那是state machine的意思 ，用astah作图的时候自动生成的没法改，我前面也点了半天才明白的。。
