### ISSUE TITLE
日志的临时文件mmap什么时候会写入.xlog文件中

### ISSUE THREAD

**Issue by qqsheji** [Tencent/mars#996]
我现在log打印后，在指定位置找到了xlog文件，解密后但是log里面没有我打印的内容，过了好一会重新下载xlog文件解密后才有之前打印的内容，请问怎么解决？
还有日志里面的类似于这样的信息，如何关闭：
^^^^^^^^^^Feb 24 2021^^^09:50:49^^^^^^^^^^[10226,10226][2021-12-15 +0800 14:22:50]
get mmap time: 5
MARS_URL: 
MARS_PATH: rb/2021-FEB
MARS_REVISION: 42a9695b
MARS_BUILD_TIME: 2021-02-24 09:50:42
MARS_BUILD_JOB: 
log appender mode:0, use mmap:1
log dir space info, capacity:118539419648 free:117041803264 available:117041803264

**Comment by qqsheji** [comment]
解决了

**Comment by hnny09** [comment]
修改xlog源码吗？删除对应打印？

**Comment by xiaoqi010205** [comment]
> 

怎么解决的呀？

**Comment by qqsheji** [comment]
写入xlog是在下次启动的时候，或者自己调用sync方法写入

xiaoqi ***@***.***> 于2022年7月12日周二 11:42写道：
